// AUTO-GENERATED BARREL — re-exports every sqlite schema module's tables.
// Each module file lives in ./<module>.js and exports its table objects.
// "master" and "report" own no tables and export {} (harmless spread).

module.exports = {
  ...require('./attendance'),
  ...require('./attendanceType'),
  ...require('./auditTrail'),
  ...require('./balanceSheetReport'),
  ...require('./banking'),
  ...require('./company'),
  ...require('./companyCreationSuccess'),
  ...require('./companyFeatureValues'),
  ...require('./companyGstDetails'),
  ...require('./companyPanCinDetails'),
  ...require('./companyTcsDetails'),
  ...require('./companyTdsDetails'),
  ...require('./costCentre'),
  ...require('./currency'),
  ...require('./dayBookReport'),
  ...require('./eInvoice'),
  ...require('./employee'),
  ...require('./employeeCategory'),
  ...require('./employeeGroup'),
  ...require('./featureGroup'),
  ...require('./featureItem'),
  ...require('./financialYear'),
  ...require('./godown'),
  ...require('./group'),
  ...require('./gst'),
  ...require('./gstClassification'),
  ...require('./gstRegistration'),
  ...require('./ledger'),
  ...require('./master'),
  ...require('./payHead'),
  ...require('./payrollUnit'),
  ...require('./physicalStock'),
  ...require('./priceLevels'),
  ...require('./priceList'),
  ...require('./profitLossReport'),
  ...require('./report'),
  ...require('./salaryStructure'),
  ...require('./stockCategory'),
  ...require('./stockGroup'),
  ...require('./stockItem'),
  ...require('./tallyFeatures'),
  ...require('./taxUnits'),
  ...require('./tcsNatureOfGoods'),
  ...require('./tdsNatureOfPayment'),
  ...require('./trialBalanceReport'),
  ...require('./unit'),
  ...require('./voucher'),
  ...require('./voucherEntryActions'),
  ...require('./voucherType'),
  ...require('./whatsapp'),
};
