const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('api', {
    app: {
    getDataPath: () => invoke('app:getDataPath'),
    },
    company: {
        create:         (data) => invoke('company:create', data),
        getAll:         ()     => invoke('company:getAll'),
        getById:        (id)   => invoke('company:getById', id),
        update:         (data) => invoke('company:update', data),
        delete:         (id)   => invoke('company:delete', id),
        verifyPassword: (data) => invoke('company:verifyPassword', data),
    },
    fy: {
        create:    (data)                  => invoke('fy:create', data),
        getAll:    (company_id)            => invoke('fy:getAll', company_id),
        getById:   (id)                    => invoke('fy:getById', id),
        setActive: (fy_id, company_id)     => invoke('fy:setActive', { fy_id, company_id }),
        delete:    (id)                    => invoke('fy:delete', id),
    },
    group: {
        create:  (data)       => invoke('group:create', data),
        getAll:  (company_id) => invoke('group:getAll', company_id),
        getById: (id)         => invoke('group:getById', id),
        update:  (data)       => invoke('group:update', data),
        delete:  (id)         => invoke('group:delete', id),
        getTree: (company_id) => invoke('group:getTree', company_id),
    },
    ledger: {
        create:     (data)               => invoke('ledger:create', data),
        getAll:     (company_id)         => invoke('ledger:getAll', company_id),
        getById:    (id)                 => invoke('ledger:getById', id),
        update:     (data)               => invoke('ledger:update', data),
        delete:     (id)                 => invoke('ledger:delete', id),
        getByGroup: (company_id, groupId) => invoke('ledger:getByGroup', { company_id, group_id: groupId }),
    },
    costCentre: {
        create:  (data)       => invoke('costCentre:create', data),
        getAll:  (company_id) => invoke('costCentre:getAll', company_id),
        getById: (id)         => invoke('costCentre:getById', id),
        update:  (data)       => invoke('costCentre:update', data),
        delete:  (id)         => invoke('costCentre:delete', id),
        getTree: (company_id) => invoke('costCetre:getTree', company_id),
    },
    unit: {
        create:       (data)       => invoke('unit:create', data),
        getAll:       (company_id) => invoke('unit:getAll', company_id),
        getSimpleUnits: (company_id) => invoke('unit:getSimpleUnits', company_id),
        getById:      (id)         => invoke('unit:getById', id),
        update:       (data)       => invoke('unit:update', data),
        delete:       (id)         => invoke('unit:delete', id),
    },
    stockGroup: {
        create:  (data)       => invoke('stockGroup:create', data),
        getAll:  (company_id) => invoke('stockGroup:getAll', company_id),
        getById: (id)         => invoke('stockGroup:getById', id),
        update:  (data)       => invoke('stockGroup:update', data),
        delete:  (id)         => invoke('stockGroup:delete', id),
        getTree: (company_id) => invoke('stockGroup:getTree', company_id),
    },
    stockCategory: {
        create:  (data)       => invoke('stockCategory:create', data),
        getAll:  (company_id) => invoke('stockCategory:getAll', company_id),
        getById: (id)         => invoke('stockCategory:getById', id),
        update:  (data)       => invoke('stockCategory:update', data),
        delete:  (id)         => invoke('stockCategory:delete', id),
    },
    stockItem: {
        create:        (data)                          => invoke('stockItem:create', data),
        getAll:        (company_id)                    => invoke('stockItem:getAll', company_id),
        getById:       (id)                            => invoke('stockItem:getById', id),
        update:        (data)                          => invoke('stockItem:update', data),
        delete:        (id)                            => invoke('stockItem:delete', id),
        getByGroup:    ({ company_id, group_id })      => invoke('stockItem:getByGroup', { company_id, group_id }),
        getByCategory: ({ company_id, category_id })   => invoke('stockItem:getByCategory', { company_id, category_id }),
    },
    godown: {
        create:  (data)       => invoke('godown:create', data),
        getAll:  (company_id) => invoke('godown:getAll', company_id),
        getById: (id)         => invoke('godown:getById', id),
        update:  (data)       => invoke('godown:update', data),
        delete:  (id)         => invoke('godown:delete', id),
        getTree: (company_id) => invoke('godown:getTree', company_id),
    },
    voucher: {
        create:     (data)                                         => invoke('voucher:create', data),
        getAll:     (company_id, fy_id)                            => invoke('voucher:getAll', { company_id, fy_id }),
        getById:    (id)                                           => invoke('voucher:getById', id),
        update:     (data)                                         => invoke('voucher:update', data),
        delete:     (id)                                           => invoke('voucher:delete', id),
        cancel:     (id)                                           => invoke('voucher:cancel', id),
        getDaybook: (company_id, fy_id, from_date, to_date)        => invoke('voucher:getDaybook', { company_id, fy_id, from_date, to_date }),
        getByType:  (company_id, fy_id, type)                      => invoke('voucher:getByType', { company_id, fy_id, voucher_type: type }),
        getByLedger:(company_id, fy_id, ledgerId)                  => invoke('voucher:getByLedger', { company_id, fy_id, ledger_id: ledgerId }),
        getNextNumber: (company_id, fy_id, type)                   => invoke('voucher:getNextNumber', { company_id, fy_id, voucher_type: type }),
        getLedgerBalance: (ledger_id, company_id, fy_id)           => invoke('voucher:getLedgerBalance', { ledger_id, company_id, fy_id }),
        searchLedgers:   (company_id, searchTerm)                  => invoke('voucher:searchLedgers', { company_id, searchTerm }),
        getPendingBills:  (ledger_id, company_id, fy_id)            => invoke('voucher:getPendingBills', { ledger_id, company_id, fy_id }),
    },
    report: {
        trialBalance: (company_id, fy_id)                                        => invoke('report:trialBalance', { company_id, fy_id }),
        balanceSheet: (company_id, fy_id)                                        => invoke('report:balanceSheet', { company_id, fy_id }),
        profitLoss:   (company_id, fy_id)                                        => invoke('report:profitLoss', { company_id, fy_id }),
        ledgerReport: (company_id, fy_id, ledger_id, from_date, to_date)         => invoke('report:ledgerReport', { company_id, fy_id, ledger_id, from_date, to_date }),
        cashBook:     (company_id, fy_id, from_date, to_date)                    => invoke('report:cashBook', { company_id, fy_id, from_date, to_date }),
        bankBook:     (company_id, fy_id, ledger_id, from_date, to_date)         => invoke('report:bankBook', { company_id, fy_id, ledger_id, from_date, to_date }),
        daybook:      (company_id, fy_id, from_date, to_date)                    => invoke('report:daybook', { company_id, fy_id, from_date, to_date }),
    },
    banking: {
        getUnreconciled: (company_id, fy_id, ledger_id)                          => invoke('banking:getUnreconciled', { company_id, fy_id, ledger_id }),
        reconcile:       (data)                                                   => invoke('banking:reconcile', data),
        unreconcile:     (data)                                                   => invoke('banking:unreconcile', data),
        getStatement:    (company_id, fy_id, ledger_id, from_date, to_date)      => invoke('banking:getStatement', { company_id, fy_id, ledger_id, from_date, to_date }),
        getSummary:      (company_id, fy_id, ledger_id)                          => invoke('banking:getSummary', { company_id, fy_id, ledger_id }),
    },
    currency: {
        create:     (data)               => invoke('currency:create', data),
        getAll:     (company_id)         => invoke('currency:getAll', company_id),
        getById:    (id)                 => invoke('currency:getById', id),
        update:     (data)               => invoke('currency:update', data),
        delete:     (id)                 => invoke('currency:delete', id),
        setDefault: (company_id, id)     => invoke('currency:setDefault', { company_id, id }),
    },
    voucherType: {
        create:       (data)       => invoke('voucherType:create', data),
        getAll:       (company_id) => invoke('voucherType:getAll', company_id),
        getById:      (id)         => invoke('voucherType:getById', id),
        update:       (data)       => invoke('voucherType:update', data),
        delete:       (id)         => invoke('voucherType:delete', id),
        getConfig:    (id)         => invoke('voucherType:getConfig', id),
        updateConfig: (data)       => invoke('voucherType:updateConfig', data),
    },
    gstRegistration: {
        create:  (data)       => invoke('gstRegistration:create', data),
        getAll:  (company_id) => invoke('gstRegistration:getAll', company_id),
        getById: (id)         => invoke('gstRegistration:getById', id),
        update:  (data)       => invoke('gstRegistration:update', data),
        delete:  (id)         => invoke('gstRegistration:delete', id),
    },
    gstClassification: {
        create:  (data)       => invoke('gstClassification:create', data),
        getAll:  (company_id) => invoke('gstClassification:getAll', company_id),
        getById: (id)         => invoke('gstClassification:getById', id),
        update:  (data)       => invoke('gstClassification:update', data),
        delete:  (id)         => invoke('gstClassification:delete', id),
    },
    gst: {
        computeTax:    (payload) => invoke('gst:computeTax', payload),
        generateGSTR1: (data)    => invoke('gst:generateGSTR1', data),
        getGSTR1:      (data)    => invoke('gst:getGSTR1', data),
        getHSNRates:   (cid)     => invoke('gst:getHSNRates', cid),
        upsertHSNRate: (data)    => invoke('gst:upsertHSNRate', data),
        deleteHSNRate: (data)    => invoke('gst:deleteHSNRate', data),
    },
    master: {
        getMenu: (company_id) => invoke('master:getMenu', company_id),
    },
    tallyFeatures: {
        get:    (company_id) => invoke('tallyFeatures:get', company_id),
        update: (data)       => invoke('tallyFeatures:update', data),
        reset:  (company_id) => invoke('tallyFeatures:reset', company_id),
    },
    companyCreationSuccess: {
        get:    (company_id) => invoke('companyCreationSuccess:get', company_id),
        update: (data)       => invoke('companyCreationSuccess:update', data),
    },
    featureGroup: {
        getAll:  () => invoke('featureGroup:getAll'),
        getById: (id) => invoke('featureGroup:getById', id),
    },
    featureItem: {
        getAll:     ()         => invoke('featureItem:getAll'),
        getById:    (id)       => invoke('featureItem:getById', id),
        getByGroup: (group_id) => invoke('featureItem:getByGroup', group_id),
    },
    companyFeatureValues: {
        get:        (company_id)          => invoke('companyFeatureValues:get', company_id),
        getByGroup: (company_id, group_id) => invoke('companyFeatureValues:getByGroup', { company_id, group_id }),
        update:     (data)                => invoke('companyFeatureValues:update', data),
        updateBulk: (company_id, values)  => invoke('companyFeatureValues:updateBulk', { company_id, values }),
    },
    attendanceType: {
        create:  (data)       => invoke('attendanceType:create', data),
        getAll:  (company_id) => invoke('attendanceType:getAll', company_id),
        getById: (id)         => invoke('attendanceType:getById', id),
        update:  (data)       => invoke('attendanceType:update', data),
        delete:  (id)         => invoke('attendanceType:delete', id),
    },
    payHead: {
        create:         (data)       => invoke('payHead:create', data),
        getAll:         (company_id) => invoke('payHead:getAll', company_id),
        getById:        (id)         => invoke('payHead:getById', id),
        update:         (data)       => invoke('payHead:update', data),
        delete:         (id)         => invoke('payHead:delete', id),
        getSlabs:       (pay_head_id) => invoke('payHead:getSlabs', pay_head_id),
        createSlab:     (data)       => invoke('payHead:createSlab', data),
        deleteSlab:     (id)         => invoke('payHead:deleteSlab', id),
        getFormulas:    (pay_head_id) => invoke('payHead:getFormulas', pay_head_id),
        createFormula:  (data)       => invoke('payHead:createFormula', data),
        deleteFormula:  (id)         => invoke('payHead:deleteFormula', id),
    },
    salaryStructure: {
        create:        (data)                                    => invoke('salaryStructure:create', data),
        createBulk:    (company_id, employee_id, effective_from, entries) => invoke('salaryStructure:createBulk', { company_id, employee_id, effective_from, entries }),
        getAll:        (company_id)                              => invoke('salaryStructure:getAll', company_id),
        getById:       (id)                                      => invoke('salaryStructure:getById', id),
        getByEmployee: (company_id, employee_id)                 => invoke('salaryStructure:getByEmployee', { company_id, employee_id }),
        update:        (data)                                    => invoke('salaryStructure:update', data),
        delete:        (id)                                      => invoke('salaryStructure:delete', id),
    },
    employee: {
        create:     (data)                     => invoke('employee:create', data),
        getAll:     (company_id)               => invoke('employee:getAll', company_id),
        getById:    (id)                       => invoke('employee:getById', id),
        update:     (data)                     => invoke('employee:update', data),
        delete:     (id)                       => invoke('employee:delete', id),
        getByGroup: (company_id, group_id)     => invoke('employee:getByGroup', { company_id, group_id }),
    },
    employeeCategory: {
        create:  (data)       => invoke('employeeCategory:create', data),
        getAll:  (company_id) => invoke('employeeCategory:getAll', company_id),
        getById: (id)         => invoke('employeeCategory:getById', id),
        update:  (data)       => invoke('employeeCategory:update', data),
        delete:  (id)         => invoke('employeeCategory:delete', id),
    },
    employeeGroup: {
        create:  (data)       => invoke('employeeGroup:create', data),
        getAll:  (company_id) => invoke('employeeGroup:getAll', company_id),
        getById: (id)         => invoke('employeeGroup:getById', id),
        update:  (data)       => invoke('employeeGroup:update', data),
        delete:  (id)         => invoke('employeeGroup:delete', id),
        getTree: (company_id) => invoke('employeeGroup:getTree', company_id),
    },
    payrollUnit: {
        create:  (data)       => invoke('payrollUnit:create', data),
        getAll:  (company_id) => invoke('payrollUnit:getAll', company_id),
        getById: (id)         => invoke('payrollUnit:getById', id),
        update:  (data)       => invoke('payrollUnit:update', data),
        delete:  (id)         => invoke('payrollUnit:delete', id),
    },
});