const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('api', {
    app: {
    getDataPath: () => invoke('app:getDataPath'),
    },
    company: {
        create:         (data) => invoke('company:create', data),
        getAll:         ()     => invoke('company:getAll'),
        getById:        (id)   => invoke('company:getById', id),
        update:         (data) => invoke('company:update', data),
        delete:         (id)   => invoke('company:delete', id),
        verifyPassword: (data) => invoke('company:verifyPassword', data),
    },
    taxUnits:{
        create:         (data)=> invoke('taxUnits:create',data),
        getAll:         (company_id)=> invoke('taxUnits:getAll',company_id),
        getById:         (id) => invoke('taxUnits:getById',id),
        update:           (data) => invoke('taxUnits:update', data),
        delete:           (id) => invoke('taxUnits:delete',id),
    },
    priceList:{
        create:  (data)       => invoke('priceList:create', data),
        getAll:  (company_id) => invoke('priceList:getAll', company_id),
        getById: (id)         => invoke('priceList:getById', id),
        update:  (data)       => invoke('priceList:update', data),
        delete:  (id)         => invoke('priceList:delete', id),
    },
      priceLevels: {
        get:    (company_id) => invoke('priceLevels:get', company_id),
        save:   (data)       => invoke('priceLevels:save', data),
        delete: (company_id) => invoke('priceLevels:delete', company_id),
    },
    fy: {
        create:    (data)                  => invoke('fy:create', data),
        getAll:    (company_id)            => invoke('fy:getAll', company_id),
        getById:   (id)                    => invoke('fy:getById', id),
        setActive: (fy_id, company_id)     => invoke('fy:setActive', { fy_id, company_id }),
        delete:    (id)                    => invoke('fy:delete', id),
    },
    group: {
        create:  (data)       => invoke('group:create', data),
        getAll:  (company_id) => invoke('group:getAll', company_id),
        getById: (id)         => invoke('group:getById', id),
        update:  (data)       => invoke('group:update', data),
        delete:  (id)         => invoke('group:delete', id),
        getTree: (company_id) => invoke('group:getTree', company_id),
    },
    ledger: {
        create:     (data)               => invoke('ledger:create', data),
        getAll:     (company_id)         => invoke('ledger:getAll', company_id),
        getById:    (id)                 => invoke('ledger:getById', id),
        update:     (data)               => invoke('ledger:update', data),
        delete:     (id)                 => invoke('ledger:delete', id),
        getByGroup: (company_id, groupId) => invoke('ledger:getByGroup', { company_id, group_id: groupId }),
        getTotalOpeningBalance: (company_id) => invoke('ledger:getTotalOpeningBalance', company_id),
    },
    costCentre: {
        create:  (data)       => invoke('costCentre:create', data),
        getAll:  (company_id) => invoke('costCentre:getAll', company_id),
        getById: (id)         => invoke('costCentre:getById', id),
        update:  (data)       => invoke('costCentre:update', data),
        delete:  (id)         => invoke('costCentre:delete', id),
        getTree: (company_id) => invoke('costCentre:getTree', company_id),
    },
    unit: {
        create:       (data)       => invoke('unit:create', data),
        getAll:       (company_id) => invoke('unit:getAll', company_id),
        getSimpleUnits: (company_id) => invoke('unit:getSimpleUnits', company_id),
        getById:      (id)         => invoke('unit:getById', id),
        update:       (data)       => invoke('unit:update', data),
        delete:       (id)         => invoke('unit:delete', id),
    },
    stockGroup: {
        create:  (data)       => invoke('stockGroup:create', data),
        getAll:  (company_id) => invoke('stockGroup:getAll', company_id),
        getById: (id)         => invoke('stockGroup:getById', id),
        update:  (data)       => invoke('stockGroup:update', data),
        delete:  (id)         => invoke('stockGroup:delete', id),
        getTree: (company_id) => invoke('stockGroup:getTree', company_id),
    },
    stockCategory: {
        create:  (data)       => invoke('stockCategory:create', data),
        getAll:  (company_id) => invoke('stockCategory:getAll', company_id),
        getById: (id)         => invoke('stockCategory:getById', id),
        update:  (data)       => invoke('stockCategory:update', data),
        delete:  (id)         => invoke('stockCategory:delete', id),
    },
    stockItem: {
        create:        (data)                          => invoke('stockItem:create', data),
        getAll:        (company_id)                    => invoke('stockItem:getAll', company_id),
        getById:       (id)                            => invoke('stockItem:getById', id),
        update:        (data)                          => invoke('stockItem:update', data),
        delete:        (id)                            => invoke('stockItem:delete', id),
        getByGroup:    ({ company_id, group_id })      => invoke('stockItem:getByGroup', { company_id, group_id }),
        getByCategory: ({ company_id, category_id })   => invoke('stockItem:getByCategory', { company_id, category_id }),
        getStockBalances: (company_id)                 => invoke('stockItem:getStockBalances', company_id),
    },
    godown: {
        create:  (data)       => invoke('godown:create', data),
        getAll:  (company_id) => invoke('godown:getAll', company_id),
        getById: (id)         => invoke('godown:getById', id),
        update:  (data)       => invoke('godown:update', data),
        delete:  (id)         => invoke('godown:delete', id),
        getTree: (company_id) => invoke('godown:getTree', company_id),
    },
    voucher: {
        create:     (data)                                         => invoke('voucher:create', data),
        getAll:     (company_id, fy_id)                            => invoke('voucher:getAll', { company_id, fy_id }),
        getById:    (id)                                           => invoke('voucher:getById', id),
        update:     (data)                                         => invoke('voucher:update', data),
        delete:     (id)                                           => invoke('voucher:delete', id),
        cancel:     (id)                                           => invoke('voucher:cancel', id),
        getDaybook: (company_id, fy_id, from_date, to_date)        => invoke('voucher:getDaybook', { company_id, fy_id, from_date, to_date }),
        getByType:  (company_id, fy_id, type)                      => invoke('voucher:getByType', { company_id, fy_id, voucher_type: type }),
        getByLedger:(company_id, fy_id, ledgerId)                  => invoke('voucher:getByLedger', { company_id, fy_id, ledger_id: ledgerId }),
        getNextNumber: (company_id, fy_id, type)                   => invoke('voucher:getNextNumber', { company_id, fy_id, voucher_type: type }),
        getLedgerBalance: (ledger_id, company_id, fy_id)           => invoke('voucher:getLedgerBalance', { ledger_id, company_id, fy_id }),
        searchLedgers:   (company_id, searchTerm)                  => invoke('voucher:searchLedgers', { company_id, searchTerm }),
        getPendingBills:  (ledger_id, company_id, fy_id)            => invoke('voucher:getPendingBills', { ledger_id, company_id, fy_id }),
    },
    report: {
        trialBalance: (company_id, fy_id)                                        => invoke('report:trialBalance', { company_id, fy_id }),
        balanceSheet: (company_id, fy_id)                                        => invoke('report:balanceSheet', { company_id, fy_id }),
        profitLoss:   (company_id, fy_id)                                        => invoke('report:profitLoss', { company_id, fy_id }),
        ledgerReport: (company_id, fy_id, ledger_id, from_date, to_date)         => invoke('report:ledgerReport', { company_id, fy_id, ledger_id, from_date, to_date }),
        cashBook:     (company_id, fy_id, from_date, to_date)                    => invoke('report:cashBook', { company_id, fy_id, from_date, to_date }),
        bankBook:     (company_id, fy_id, ledger_id, from_date, to_date)         => invoke('report:bankBook', { company_id, fy_id, ledger_id, from_date, to_date }),
        daybook:      (company_id, fy_id, from_date, to_date)                    => invoke('report:daybook', { company_id, fy_id, from_date, to_date }),
        billsReceivable: (company_id, fy_id)                                     => invoke('report:billsReceivable', { company_id, fy_id }),
        billsPayable:    (company_id, fy_id)                                     => invoke('report:billsPayable', { company_id, fy_id }),
        cashFlow:        (company_id, fy_id, from_date, to_date)                 => invoke('report:cashFlow', { company_id, fy_id, from_date, to_date }),
        fundsFlow:       (company_id, fy_id, from_date, to_date)                 => invoke('report:fundsFlow', { company_id, fy_id, from_date, to_date }),
        stockSummary:    (company_id, fy_id, as_on_date, method)                 => invoke('report:stockSummary', { company_id, fy_id, as_on_date, method }),
        stockGroupItems:  (company_id, fy_id, group_id)                          => invoke('report:stockGroupItems', { company_id, fy_id, group_id }),
        stockItemMonthly: (company_id, fy_id, item_id)                           => invoke('report:stockItemMonthly', { company_id, fy_id, item_id }),
        ratioAnalysis:   (company_id, fy_id)                                     => invoke('report:ratioAnalysis', { company_id, fy_id }),
        groupSummaryDrilldown: (company_id, fy_id, group_id)                     => invoke('report:groupSummaryDrilldown', { company_id, fy_id, group_id }),
        ledgerMonthlySummary:  (company_id, fy_id, ledger_id)                    => invoke('report:ledgerMonthlySummary', { company_id, fy_id, ledger_id }),
        run:              (reportId, params)                                     => invoke('report:run', { reportId, params }),
        getSavedViews:    (company_id)                                           => invoke('report:getSavedViews', { company_id }),
        saveView:         (payload)                                              => invoke('report:saveView', payload),
        deleteSavedView:  (id)                                                   => invoke('report:deleteSavedView', { id }),
        godownSummary:    (company_id, fy_id, as_on_date)                        => invoke('report:godownSummary', { company_id, fy_id, as_on_date }),
        stockAgeing:      (company_id, fy_id, as_on_date)                        => invoke('report:stockAgeing', { company_id, fy_id, as_on_date }),
        movementAnalysis: (company_id, fy_id, as_on_date)                        => invoke('report:movementAnalysis', { company_id, fy_id, as_on_date }),
        reorderStatus:    (company_id, fy_id)                                    => invoke('report:reorderStatus', { company_id, fy_id }),
        orderOutstanding: (company_id, fy_id, type)                              => invoke('report:orderOutstanding', { company_id, fy_id, type }),
        costCentreReport: (company_id, fy_id, as_on_date)                        => invoke('report:costCentreReport', { company_id, fy_id, as_on_date }),
        budgetVsActual:   (company_id, fy_id)                                    => invoke('report:budgetVsActual', { company_id, fy_id }),
        // Accounting summaries
        groupSummary:        (company_id, fy_id) => invoke('report:groupSummary',        { company_id, fy_id }),
        statistics:          (company_id, fy_id) => invoke('report:statistics',          { company_id, fy_id }),
        costCategorySummary: (company_id, fy_id) => invoke('report:costCategorySummary', { company_id, fy_id }),
        // Inventory summaries
        stockItemSummary:     (company_id, fy_id) => invoke('report:stockItemSummary',     { company_id, fy_id }),
        stockGroupSummary:    (company_id, fy_id) => invoke('report:stockGroupSummary',    { company_id, fy_id }),
        stockCategorySummary: (company_id, fy_id) => invoke('report:stockCategorySummary', { company_id, fy_id }),
        // Payroll reports
        payslipReport:    (company_id, fy_id) => invoke('report:payslipReport',    { company_id, fy_id }),
        salaryStatement:  (company_id, fy_id) => invoke('report:salaryStatement',  { company_id, fy_id }),
        salaryRegister:   (company_id, fy_id) => invoke('report:salaryRegister',   { company_id, fy_id }),
        attendanceReport: (company_id, fy_id) => invoke('report:attendanceReport', { company_id, fy_id }),
        payHeadBreakup:   (company_id, fy_id) => invoke('report:payHeadBreakup',   { company_id, fy_id }),
        pfReport:         (company_id, fy_id) => invoke('report:pfReport',         { company_id, fy_id }),
        esiReport:        (company_id, fy_id) => invoke('report:esiReport',        { company_id, fy_id }),
        professionalTax:  (company_id, fy_id) => invoke('report:professionalTax',  { company_id, fy_id }),
        gratuity:         (company_id, fy_id) => invoke('report:gratuity',         { company_id, fy_id }),
        journalRegister:   (company_id, fy_id) => invoke('report:journalRegister',   { company_id, fy_id }),
        debitNoteRegister:  (company_id, fy_id) => invoke('report:debitNoteRegister',  { company_id, fy_id }),
        creditNoteRegister: (company_id, fy_id) => invoke('report:creditNoteRegister', { company_id, fy_id }),
        purchaseRegister:   (company_id, fy_id) => invoke('report:purchaseRegister',   { company_id, fy_id }),
        salesRegister:      (company_id, fy_id) => invoke('report:salesRegister',      { company_id, fy_id }),
        contraRegister:     (company_id, fy_id) => invoke('report:contraRegister',     { company_id, fy_id }),
       contraRegisterVouchers: (company_id, fy_id, from_date, to_date)   => invoke('report:contraRegisterVouchers', { company_id, fy_id, from_date, to_date }),
    },
    banking: {
        getUnreconciled: (company_id, fy_id, ledger_id)                          => invoke('banking:getUnreconciled', { company_id, fy_id, ledger_id }),
        reconcile:       (data)                                                   => invoke('banking:reconcile', data),
        unreconcile:     (data)                                                   => invoke('banking:unreconcile', data),
        getStatement:    (company_id, fy_id, ledger_id, from_date, to_date)      => invoke('banking:getStatement', { company_id, fy_id, ledger_id, from_date, to_date }),
        getSummary:      (company_id, fy_id, ledger_id)                          => invoke('banking:getSummary', { company_id, fy_id, ledger_id }),
    },
    auditTrail: {
        getAll:      (company_id, limit)                                         => invoke('auditTrail:getAll', { company_id, limit }),
        getByEntity: (company_id, entity_type, entity_id)                       => invoke('auditTrail:getByEntity', { company_id, entity_type, entity_id }),
        verifyChain: (company_id)                                               => invoke('auditTrail:verifyChain', { company_id }),
    },
    currency: {
        create:     (data)               => invoke('currency:create', data),
        getAll:     (company_id)         => invoke('currency:getAll', company_id),
        getById:    (id)                 => invoke('currency:getById', id),
        update:     (data)               => invoke('currency:update', data),
        delete:     (id)                 => invoke('currency:delete', id),
        setDefault: (company_id, id)     => invoke('currency:setDefault', { company_id, id }),
    },
    voucherType: {
        create:       (data)       => invoke('voucherType:create', data),
        getAll:       (company_id) => invoke('voucherType:getAll', company_id),
        getById:      (id)         => invoke('voucherType:getById', id),
        update:       (data)       => invoke('voucherType:update', data),
        delete:       (id)         => invoke('voucherType:delete', id),
        getConfig:    (id)         => invoke('voucherType:getConfig', id),
        updateConfig: (data)       => invoke('voucherType:updateConfig', data),
    },
    gstRegistration: {
        create:  (data)       => invoke('gstRegistration:create', data),
        getAll:  (company_id) => invoke('gstRegistration:getAll', company_id),
        getById: (id)         => invoke('gstRegistration:getById', id),
        update:  (data)       => invoke('gstRegistration:update', data),
        delete:  (id)         => invoke('gstRegistration:delete', id),
    },
    gstClassification: {
        create:  (data)       => invoke('gstClassification:create', data),
        getAll:  (company_id) => invoke('gstClassification:getAll', company_id),
        getById: (id)         => invoke('gstClassification:getById', id),
        update:  (data)       => invoke('gstClassification:update', data),
        delete:  (id)         => invoke('gstClassification:delete', id),
    },
    tcsNatureOfGoods: {
        create:  (data)       => invoke('tcsNatureOfGoods:create', data),
        getAll:  (company_id) => invoke('tcsNatureOfGoods:getAll', company_id),
        getById: (id)         => invoke('tcsNatureOfGoods:getById', id),
        update:  (data)       => invoke('tcsNatureOfGoods:update', data),
        delete:  (id)         => invoke('tcsNatureOfGoods:delete', id),
    },
    tdsNatureOfPayment: {
        create:  (data)       => invoke('tdsNatureOfPayment:create', data),
        getAll:  (company_id) => invoke('tdsNatureOfPayment:getAll', company_id),
        getById: (id)         => invoke('tdsNatureOfPayment:getById', id),
        update:  (data)       => invoke('tdsNatureOfPayment:update', data),
        delete:  (id)         => invoke('tdsNatureOfPayment:delete', id),
    },
    gst: {
        computeTax:           (payload) => invoke('gst:computeTax', payload),
        generateGSTR1:        (data)    => invoke('gst:generateGSTR1', data),
        getGSTR1:             (data)    => invoke('gst:getGSTR1', data),
        generateGSTR3B:       (data)    => invoke('gst:generateGSTR3B', data),
        getGSTR3B:            (data)    => invoke('gst:getGSTR3B', data),
        getHSNRates:          (cid)     => invoke('gst:getHSNRates', cid),
        upsertHSNRate:        (data)    => invoke('gst:upsertHSNRate', data),
        deleteHSNRate:        (data)    => invoke('gst:deleteHSNRate', data),
        getAnnualComputation: (data)    => invoke('gst:getAnnualComputation', data),
        getGSTR1Reconciliation: (data)   => invoke('gst:getGSTR1Reconciliation', data),
        getGSTR2BReconciliation: (data)   => invoke('gst:getGSTR2BReconciliation', data),
        importGSTR2B:         (data)      => invoke('gst:importGSTR2B', data),
        getIMSInwardSupplies: (data)      => invoke('gst:getIMSInwardSupplies', data),
        getChallanReconciliation: (data)  => invoke('gst:getChallanReconciliation', data),
    },
    master: {
        getMenu: (company_id) => invoke('master:getMenu', company_id),
    },
    tallyFeatures: {
        get:    (company_id) => invoke('tallyFeatures:get', company_id),
        update: (data)       => invoke('tallyFeatures:update', data),
        reset:  (company_id) => invoke('tallyFeatures:reset', company_id),
    },
    companyCreationSuccess: {
        get:    (company_id) => invoke('companyCreationSuccess:get', company_id),
        update: (data)       => invoke('companyCreationSuccess:update', data),
    },
    featureGroup: {
        getAll:  () => invoke('featureGroup:getAll'),
        getById: (id) => invoke('featureGroup:getById', id),
    },
    featureItem: {
        getAll:     ()         => invoke('featureItem:getAll'),
        getById:    (id)       => invoke('featureItem:getById', id),
        getByGroup: (group_id) => invoke('featureItem:getByGroup', group_id),
    },
    companyFeatureValues: {
        get:        (company_id)          => invoke('companyFeatureValues:get', company_id),
        getByGroup: (company_id, group_id) => invoke('companyFeatureValues:getByGroup', { company_id, group_id }),
        update:     (data)                => invoke('companyFeatureValues:update', data),
        updateBulk: (company_id, values)  => invoke('companyFeatureValues:updateBulk', { company_id, values }),
    },
    attendanceType: {
        create:  (data)       => invoke('attendanceType:create', data),
        getAll:  (company_id) => invoke('attendanceType:getAll', company_id),
        getById: (id)         => invoke('attendanceType:getById', id),
        update:  (data)       => invoke('attendanceType:update', data),
        delete:  (id)         => invoke('attendanceType:delete', id),
    },
    payHead: {
        create:         (data)       => invoke('payHead:create', data),
        getAll:         (company_id) => invoke('payHead:getAll', company_id),
        getById:        (id)         => invoke('payHead:getById', id),
        update:         (data)       => invoke('payHead:update', data),
        delete:         (id)         => invoke('payHead:delete', id),
        getSlabs:       (pay_head_id) => invoke('payHead:getSlabs', pay_head_id),
        createSlab:     (data)       => invoke('payHead:createSlab', data),
        deleteSlab:     (id)         => invoke('payHead:deleteSlab', id),
        getFormulas:    (pay_head_id) => invoke('payHead:getFormulas', pay_head_id),
        createFormula:  (data)       => invoke('payHead:createFormula', data),
        deleteFormula:  (id)         => invoke('payHead:deleteFormula', id),
    },
    salaryStructure: {
        create:        (data)                                    => invoke('salaryStructure:create', data),
        createBulk:    (company_id, employee_id, effective_from, entries) => invoke('salaryStructure:createBulk', { company_id, employee_id, effective_from, entries }),
        getAll:        (company_id)                              => invoke('salaryStructure:getAll', company_id),
        getById:       (id)                                      => invoke('salaryStructure:getById', id),
        getByEmployee: (company_id, employee_id)                 => invoke('salaryStructure:getByEmployee', { company_id, employee_id }),
        update:        (data)                                    => invoke('salaryStructure:update', data),
        delete:        (id)                                      => invoke('salaryStructure:delete', id),
    },
    employee: {
        create:     (data)                     => invoke('employee:create', data),
        getAll:     (company_id)               => invoke('employee:getAll', company_id),
        getById:    (id)                       => invoke('employee:getById', id),
        update:     (data)                     => invoke('employee:update', data),
        delete:     (id)                       => invoke('employee:delete', id),
        getByGroup: (company_id, group_id)     => invoke('employee:getByGroup', { company_id, group_id }),
    },
    employeeCategory: {
        create:  (data)       => invoke('employeeCategory:create', data),
        getAll:  (company_id) => invoke('employeeCategory:getAll', company_id),
        getById: (id)         => invoke('employeeCategory:getById', id),
        update:  (data)       => invoke('employeeCategory:update', data),
        delete:  (id)         => invoke('employeeCategory:delete', id),
    },
    employeeGroup: {
        create:  (data)       => invoke('employeeGroup:create', data),
        getAll:  (company_id) => invoke('employeeGroup:getAll', company_id),
        getById: (id)         => invoke('employeeGroup:getById', id),
        update:  (data)       => invoke('employeeGroup:update', data),
        delete:  (id)         => invoke('employeeGroup:delete', id),
        getTree: (company_id) => invoke('employeeGroup:getTree', company_id),
    },
    payrollUnit: {
        create:  (data)       => invoke('payrollUnit:create', data),
        getAll:  (company_id) => invoke('payrollUnit:getAll', company_id),
        getById: (id)         => invoke('payrollUnit:getById', id),
        update:  (data)       => invoke('payrollUnit:update', data),
        delete:  (id)         => invoke('payrollUnit:delete', id),
    },
    physicalStock: {
        create:        (data)            => invoke('physicalStock:create', data),
        getAll:        (company_id)      => invoke('physicalStock:getAll', company_id),
        getById:       (id)              => invoke('physicalStock:getById', id),
        delete:        (id)              => invoke('physicalStock:delete', id),
        getNextNumber: (company_id)      => invoke('physicalStock:getNextNumber', { company_id }),
    },
    attendance: {
        create:        (data)            => invoke('attendance:create', data),
        getAll:        (company_id)      => invoke('attendance:getAll', company_id),
        getById:       (id)              => invoke('attendance:getById', id),
        delete:        (id)              => invoke('attendance:delete', id),
        getNextNumber: (company_id)      => invoke('attendance:getNextNumber', { company_id }),
    },
    companyGstDetails: {
        get:  (company_id) => invoke('companyGstDetails:get', company_id),
        save: (data)       => invoke('companyGstDetails:save', data),
    },
    companyTdsDetails: {
        get:  (company_id) => invoke('companyTdsDetails:get', company_id),
        save: (data)       => invoke('companyTdsDetails:save', data),
    },
    companyTcsDetails: {
        get:  (company_id) => invoke('companyTcsDetails:get', company_id),
        save: (data)       => invoke('companyTcsDetails:save', data),
    },
    companyPanCinDetails: {
        get:  (company_id) => invoke('companyPanCinDetails:get', company_id),
        save: (data)       => invoke('companyPanCinDetails:save', data),
    },
    ai: {
        getKeyStatus: ()        => invoke('ai:getKeyStatus'),
        setKey:       (config)  => invoke('ai:setKey', config),
        clearKey:     ()        => invoke('ai:clearKey'),
        testKey:      (config)  => invoke('ai:testKey', config || {}),
        ask:          (payload) => invoke('ai:ask', payload),
    },
    tally: {
        testConnection: (params)  => invoke('tally:testConnection', params),
        preview:        (params)  => invoke('tally:preview', params),
        importMasters:  (params)  => invoke('tally:importMasters', params),
        importVouchers: (params)  => invoke('tally:importVouchers', params),
    },
});
