-- ============================================================================
-- Module: attendance
-- Postgres DDL translated from SQLite source: server/attendance/attendance.js
-- Tables: attendance_vouchers, attendance_voucher_entries
--
-- Type mapping notes:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * datetime TEXT (created_at/updated_at, stored as ISO strings) -> TIMESTAMPTZ
--   * date TEXT (voucher date) -> DATE
--   * REAL holding a quantity/value -> NUMERIC(18,4) (NEVER floating point for
--     money/quantity values in an accounting app)
--   * FK constraints are declared explicitly in the SQLite source where noted;
--     others are INFERRED from *_id columns. See ALTER TABLE block at bottom.
-- ============================================================================

CREATE TABLE attendance_vouchers (
    attendance_voucher_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT      NOT NULL,
    voucher_number         TEXT,
    date                   DATE        NOT NULL,   -- SQLite: TEXT NOT NULL (date-only)
    narration              TEXT,
    created_at             TIMESTAMPTZ DEFAULT now(),  -- SQLite: TEXT DEFAULT (datetime('now')), ISO string
    updated_at             TIMESTAMPTZ DEFAULT now()   -- SQLite: TEXT DEFAULT (datetime('now')); never updated by this module
);

CREATE TABLE attendance_voucher_entries (
    entry_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_voucher_id  BIGINT      NOT NULL,
    employee_id            BIGINT,                 -- nullable in source (no NOT NULL)
    attendance_type_id     BIGINT,                 -- nullable in source (no NOT NULL)
    value                  NUMERIC(18,4) DEFAULT 0 -- SQLite: REAL DEFAULT 0. Quantity/value -> NUMERIC, NOT float.
);

-- Indexes on FK columns -------------------------------------------------------
CREATE INDEX idx_attendance_vouchers_company_id
    ON attendance_vouchers (company_id);
CREATE INDEX idx_attendance_voucher_entries_voucher_id
    ON attendance_voucher_entries (attendance_voucher_id);
CREATE INDEX idx_attendance_voucher_entries_employee_id
    ON attendance_voucher_entries (employee_id);
CREATE INDEX idx_attendance_voucher_entries_attendance_type_id
    ON attendance_voucher_entries (attendance_type_id);

-- Foreign keys (grouped to avoid cross-module ordering problems) --------------
-- EXPLICIT in SQLite source (REFERENCES ... ON DELETE CASCADE):
ALTER TABLE attendance_vouchers
    ADD CONSTRAINT fk_attendance_vouchers_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source (REFERENCES ... ON DELETE CASCADE):
ALTER TABLE attendance_voucher_entries
    ADD CONSTRAINT fk_attendance_voucher_entries_voucher
    FOREIGN KEY (attendance_voucher_id) REFERENCES attendance_vouchers (attendance_voucher_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source (REFERENCES employees(employee_id), no ON DELETE):
ALTER TABLE attendance_voucher_entries
    ADD CONSTRAINT fk_attendance_voucher_entries_employee
    FOREIGN KEY (employee_id) REFERENCES employees (employee_id);

-- EXPLICIT in SQLite source (REFERENCES attendance_types(attendance_type_id)):
ALTER TABLE attendance_voucher_entries
    ADD CONSTRAINT fk_attendance_voucher_entries_attendance_type
    FOREIGN KEY (attendance_type_id) REFERENCES attendance_types (attendance_type_id);
