-- ============================================================================
-- Postgres DDL for backend module: attendanceType
-- Source (read-only): server/attendanceType/attendanceType.js  (SQLite schema)
--
-- Translation notes:
--   * SQLite INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
--   * SQLite 0/1 INTEGER flags -> BOOLEAN (0 -> false, 1 -> true).
--   * SQLite datetime('now') TEXT (ISO-8601 string) -> TIMESTAMPTZ DEFAULT now().
--   * max_days is a quantity (number of days) -> NUMERIC(18,4). It is NOT money,
--     but it is a quantity, so a fixed-point NUMERIC is used (never floating point).
--   * FK constraints are EXPLICIT in the SQLite source for company_id (REFERENCES
--     companies) and unit_id (REFERENCES payroll_units). They are emitted as
--     ALTER TABLE statements at the bottom so cross-module load order does not matter.
-- ============================================================================

CREATE TABLE IF NOT EXISTS attendance_types (
    attendance_type_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT       NOT NULL,
    name                TEXT         NOT NULL,
    alias               TEXT,
    type                TEXT         NOT NULL DEFAULT 'Attendance / Leave with Pay',
    unit_id             BIGINT,
    period              TEXT         NOT NULL DEFAULT 'Per Day',
    carry_forward       BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    encashment          BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    max_days            NUMERIC(18,4) NOT NULL DEFAULT 0,     -- quantity (days), fixed-point not float
    is_active           BOOLEAN      NOT NULL DEFAULT true,   -- SQLite INTEGER 0/1 (soft-delete flag)
    is_predefined       BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1 (system/seeded row)
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),  -- SQLite stores ISO-8601 string
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now()   -- SQLite stores ISO-8601 string
);

-- ----------------------------------------------------------------------------
-- Indexes on FK columns
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_attendance_types_company_id ON attendance_types (company_id);
CREATE INDEX IF NOT EXISTS idx_attendance_types_unit_id    ON attendance_types (unit_id);

-- Application-level uniqueness: name is unique per company among ACTIVE rows
-- (enforced in service code via case-insensitive SELECT, not a DB constraint in
-- the source). Emitted here as a partial unique index to preserve that rule.
CREATE UNIQUE INDEX IF NOT EXISTS uq_attendance_types_company_name_active
    ON attendance_types (company_id, lower(name))
    WHERE is_active = true;

-- ----------------------------------------------------------------------------
-- Foreign keys (grouped at bottom; order-independent across modules)
-- ----------------------------------------------------------------------------

-- EXPLICIT in SQLite source: company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE attendance_types
    ADD CONSTRAINT fk_attendance_types_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source: unit_id INTEGER REFERENCES payroll_units(payroll_unit_id)
ALTER TABLE attendance_types
    ADD CONSTRAINT fk_attendance_types_unit
    FOREIGN KEY (unit_id) REFERENCES payroll_units (payroll_unit_id);
