-- ============================================================================
-- Postgres DDL for backend module: balanceSheetReport
-- Source (SQLite): server/balanceSheetReport/balanceSheetReport.js
-- Tables: balance_sheet_reports, balance_sheet_views
--
-- Type-mapping notes:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * TEXT (datetime strings)           -> TIMESTAMPTZ (app stores ISO-8601 strings)
--   * TEXT (date-only, e.g. report_date)-> DATE
--   * INTEGER flags (0/1, is_*, show_*) -> BOOLEAN (0 -> false, 1 -> true)
--   * REAL holding money (balances/debit/credit) -> NUMERIC(18,2)
--       MONEY IS NEVER stored as floating point. Do not use REAL/DOUBLE for these.
--   * datetime('now') DEFAULT           -> DEFAULT now()
-- FK constraints are grouped at the bottom via ALTER TABLE so cross-module load
-- ordering is irrelevant.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: balance_sheet_reports  (report header / saved configuration)
-- ----------------------------------------------------------------------------
CREATE TABLE balance_sheet_reports (
    report_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                      BIGINT          NOT NULL,
    report_name                     TEXT            DEFAULT 'Balance Sheet',
    report_date                     DATE,                                   -- date-only TEXT -> DATE
    comparison_period_start         DATE,                                   -- date-only TEXT -> DATE
    comparison_period_end           DATE,                                   -- date-only TEXT -> DATE
    format_type                     TEXT            DEFAULT 'Vertical',
    method_of_showing               TEXT            DEFAULT 'Net Balance',
    show_vertical_balance_sheet     BOOLEAN         NOT NULL DEFAULT TRUE,  -- was INTEGER DEFAULT 1 (0/1 -> bool)
    show_working_capital_figures    BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    profit_or_loss_as_liability     BOOLEAN         NOT NULL DEFAULT TRUE,  -- was INTEGER DEFAULT 1
    show_detail_view                BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    show_condensed_view             BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    show_schedule_vi                BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    include_closing_stock           BOOLEAN         NOT NULL DEFAULT TRUE,  -- was INTEGER DEFAULT 1
    compare_quarterly               BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    basis_of_values                 TEXT            DEFAULT 'Default',
    change_view                     TEXT,
    exception_reports_enabled       BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    filter_enabled                  BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    saved_view_name                 TEXT,
    filter_details                  TEXT,                                   -- free-form / serialized JSON
    show_profit                     BOOLEAN         NOT NULL DEFAULT TRUE,  -- was INTEGER DEFAULT 1
    show_columnar                   BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    show_optional                   BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    show_post_dated                 BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    show_stat_adjustment            BOOLEAN         NOT NULL DEFAULT FALSE, -- was INTEGER DEFAULT 0
    created_at                      TIMESTAMPTZ     NOT NULL DEFAULT now(), -- ISO string in SQLite; datetime('now')
    updated_at                      TIMESTAMPTZ     NOT NULL DEFAULT now()  -- ISO string in SQLite; datetime('now')
);

-- ----------------------------------------------------------------------------
-- Table: balance_sheet_views  (individual balance sheet line rows)
-- ----------------------------------------------------------------------------
CREATE TABLE balance_sheet_views (
    view_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id                 BIGINT        NOT NULL,
    company_id                BIGINT        NOT NULL,
    report_date               DATE,                                         -- date-only TEXT -> DATE
    group_name                TEXT,
    parent_group_name         TEXT,
    opening_balance           NUMERIC(18,2) NOT NULL DEFAULT 0,             -- MONEY: never float; was REAL DEFAULT 0
    side                      TEXT          NOT NULL DEFAULT 'Assets',      -- expected: 'Assets' | 'Liabilities'
    current_period_debit      NUMERIC(18,2) NOT NULL DEFAULT 0,             -- MONEY: never float; was REAL DEFAULT 0
    current_period_credit     NUMERIC(18,2) NOT NULL DEFAULT 0,             -- MONEY: never float; was REAL DEFAULT 0
    closing_balance           NUMERIC(18,2) NOT NULL DEFAULT 0,             -- MONEY: never float; was REAL DEFAULT 0
    display_order             INTEGER       NOT NULL DEFAULT 0,
    is_total_row              BOOLEAN       NOT NULL DEFAULT FALSE,         -- was INTEGER DEFAULT 0
    is_drill_down_available   BOOLEAN       NOT NULL DEFAULT TRUE,         -- was INTEGER DEFAULT 1
    created_at                TIMESTAMPTZ   NOT NULL DEFAULT now()          -- ISO string in SQLite; datetime('now')
);

-- ----------------------------------------------------------------------------
-- Indexes on FK columns
-- ----------------------------------------------------------------------------
CREATE INDEX idx_balance_sheet_reports_company_id ON balance_sheet_reports (company_id);
CREATE INDEX idx_balance_sheet_views_report_id    ON balance_sheet_views (report_id);
CREATE INDEX idx_balance_sheet_views_company_id   ON balance_sheet_views (company_id);

-- ============================================================================
-- Foreign keys (grouped to avoid cross-module ordering problems)
-- ============================================================================

-- EXPLICIT in source: balance_sheet_reports.company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE balance_sheet_reports
    ADD CONSTRAINT fk_balance_sheet_reports_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: balance_sheet_views.report_id REFERENCES balance_sheet_reports(report_id) ON DELETE CASCADE
ALTER TABLE balance_sheet_views
    ADD CONSTRAINT fk_balance_sheet_views_report
    FOREIGN KEY (report_id) REFERENCES balance_sheet_reports (report_id) ON DELETE CASCADE;

-- EXPLICIT in source: balance_sheet_views.company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE balance_sheet_views
    ADD CONSTRAINT fk_balance_sheet_views_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
