-- ============================================================================
-- Banking module — Postgres schema
-- Translated from server/banking/banking.js (SQLite source).
-- SQLite source table: reconciliations
-- ============================================================================

CREATE TABLE reconciliations (
    -- SQLite: reconciliation_id INTEGER PRIMARY KEY AUTOINCREMENT
    reconciliation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- SQLite: entry_id INTEGER NOT NULL REFERENCES voucher_entries(entry_id) ON DELETE CASCADE
    entry_id          BIGINT NOT NULL,

    -- SQLite: voucher_id INTEGER NOT NULL REFERENCES vouchers(voucher_id) ON DELETE CASCADE
    voucher_id        BIGINT NOT NULL,

    -- SQLite: ledger_id INTEGER NOT NULL REFERENCES ledgers(ledger_id) ON DELETE CASCADE
    ledger_id         BIGINT NOT NULL,

    -- SQLite TEXT date-only value -> DATE
    reconciled_date   DATE,

    -- SQLite TEXT date-only value -> DATE
    bank_date         DATE,

    -- SQLite TEXT free-form bank reference -> TEXT
    bank_reference    TEXT,

    -- SQLite: reconciled_at TEXT DEFAULT (datetime('now')) -> ISO-8601 timestamp.
    -- App stores ISO strings; mapped to TIMESTAMPTZ with now() default.
    reconciled_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- No money/quantity columns exist in this module's table, so no NUMERIC
-- precision notes are required here. (If amounts are later denormalized onto
-- reconciliations, map currency -> NUMERIC(18,2) and qty/rate -> NUMERIC(18,4),
-- never floating point.)

-- Indexes on FK columns
CREATE INDEX idx_reconciliations_entry_id   ON reconciliations (entry_id);
CREATE INDEX idx_reconciliations_voucher_id ON reconciliations (voucher_id);
CREATE INDEX idx_reconciliations_ledger_id  ON reconciliations (ledger_id);

-- ============================================================================
-- Foreign keys (grouped at bottom for cross-module load ordering safety)
-- These FKs are EXPLICIT in the SQLite source (REFERENCES ... ON DELETE CASCADE).
-- The referenced tables (voucher_entries, vouchers, ledgers) are owned by other
-- modules; ensure they are created before these constraints are applied.
-- ============================================================================

-- EXPLICIT in source: entry_id REFERENCES voucher_entries(entry_id) ON DELETE CASCADE
ALTER TABLE reconciliations
    ADD CONSTRAINT fk_reconciliations_entry_id
    FOREIGN KEY (entry_id) REFERENCES voucher_entries (entry_id) ON DELETE CASCADE;

-- EXPLICIT in source: voucher_id REFERENCES vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE reconciliations
    ADD CONSTRAINT fk_reconciliations_voucher_id
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;

-- EXPLICIT in source: ledger_id REFERENCES ledgers(ledger_id) ON DELETE CASCADE
ALTER TABLE reconciliations
    ADD CONSTRAINT fk_reconciliations_ledger_id
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id) ON DELETE CASCADE;
