-- =============================================================================
-- Module: companyFeatureValues
-- Source: server/companyFeatureValues/companyFeatureValues.js
-- Target: PostgreSQL
-- Per-company feature toggle / setting values, keyed by feature_item_id.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: company_feature_values
-- -----------------------------------------------------------------------------
CREATE TABLE company_feature_values (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- SQLite: company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
    company_id      BIGINT       NOT NULL,
    -- SQLite: feature_item_id INTEGER NOT NULL REFERENCES feature_items(feature_item_id) ON DELETE CASCADE
    feature_item_id BIGINT       NOT NULL,
    -- 0/1 flag in SQLite (INTEGER DEFAULT 0) -> BOOLEAN; 0 => false, 1 => true.
    value_boolean   BOOLEAN      NOT NULL DEFAULT false,
    value_text      TEXT,
    -- Generic numeric "value" slot. Source is REAL with no money/qty semantics
    -- (it is a free-form per-feature number), so DOUBLE PRECISION is used.
    -- If a given feature stores currency or quantity, store it as NUMERIC instead
    -- (NUMERIC(18,2) for currency, NUMERIC(18,4) for qty/rate) — never float for money.
    value_number    DOUBLE PRECISION,
    -- SQLite stores a date-only string in value_date -> DATE.
    value_date      DATE,
    -- 0/1 flag in SQLite (INTEGER DEFAULT 0) -> BOOLEAN; 0 => false, 1 => true.
    is_enabled      BOOLEAN      NOT NULL DEFAULT false,
    -- SQLite: TEXT DEFAULT (datetime('now')) — ISO-8601 string -> TIMESTAMPTZ.
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- SQLite: TEXT DEFAULT (datetime('now')) — ISO-8601 string -> TIMESTAMPTZ.
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- A company should hold at most one value per feature item.
-- (Not declared UNIQUE in the SQLite source, but the service treats
--  (company_id, feature_item_id) as the logical key for SELECT/UPDATE.
--  Inferred constraint — verify before enabling in production.)
ALTER TABLE company_feature_values
    ADD CONSTRAINT uq_company_feature_values_company_item
    UNIQUE (company_id, feature_item_id);

-- Indexes on FK / lookup columns.
CREATE INDEX idx_company_feature_values_company_id
    ON company_feature_values (company_id);
CREATE INDEX idx_company_feature_values_feature_item_id
    ON company_feature_values (feature_item_id);

-- -----------------------------------------------------------------------------
-- Foreign keys (grouped at bottom for cross-module load ordering).
-- Both FKs are EXPLICIT in the SQLite source (REFERENCES ... ON DELETE CASCADE).
-- -----------------------------------------------------------------------------

-- EXPLICIT FK (source: companies(company_id) ON DELETE CASCADE)
ALTER TABLE company_feature_values
    ADD CONSTRAINT fk_company_feature_values_company
    FOREIGN KEY (company_id)
    REFERENCES companies (company_id)
    ON DELETE CASCADE;

-- EXPLICIT FK (source: feature_items(feature_item_id) ON DELETE CASCADE)
ALTER TABLE company_feature_values
    ADD CONSTRAINT fk_company_feature_values_feature_item
    FOREIGN KEY (feature_item_id)
    REFERENCES feature_items (feature_item_id)
    ON DELETE CASCADE;
