-- =====================================================================
-- Module: companyCreationSuccess
-- Postgres DDL translated from SQLite source:
--   server/companyCreationSuccess/companyCreationSuccess.js
--
-- SQLite -> Postgres notes for this module:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
--   * The 0/1 INTEGER flag columns become BOOLEAN (0 -> false, 1 -> true).
--     Their SQLite DEFAULT 1/0 become DEFAULT TRUE/FALSE accordingly.
--   * created_at / updated_at hold ISO-8601 datetime TEXT (datetime('now'))
--     and become TIMESTAMPTZ DEFAULT now().
--   * NOT NULL added where the SQLite column was NOT NULL or has a DEFAULT.
-- FK constraints are grouped at the bottom as ALTER TABLE statements so
-- cross-module load ordering is not a problem.
-- =====================================================================

CREATE TABLE IF NOT EXISTS company_creation_success (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                BIGINT  NOT NULL,
    created_successfully      BOOLEAN NOT NULL DEFAULT TRUE,   -- SQLite INTEGER 0/1, DEFAULT 1
    success_screen_shown      BOOLEAN NOT NULL DEFAULT FALSE,  -- SQLite INTEGER 0/1, DEFAULT 0
    show_more_features        BOOLEAN NOT NULL DEFAULT FALSE,  -- SQLite INTEGER 0/1, DEFAULT 0
    show_all_features         BOOLEAN NOT NULL DEFAULT FALSE,  -- SQLite INTEGER 0/1, DEFAULT 0
    default_features_loaded   BOOLEAN NOT NULL DEFAULT TRUE,   -- SQLite INTEGER 0/1, DEFAULT 1
    feature_setup_completed   BOOLEAN NOT NULL DEFAULT FALSE,  -- SQLite INTEGER 0/1, DEFAULT 0
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),  -- app stores ISO-8601 strings
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()   -- app stores ISO-8601 strings
);

-- A company has at most one creation-success record. The SQLite source does not
-- declare this UNIQUE, but the service treats company_id as the lookup/update key
-- (one row per company). Enforcing it in Postgres is recommended.
ALTER TABLE company_creation_success
    ADD CONSTRAINT uq_company_creation_success_company_id UNIQUE (company_id);  -- inferred (not explicit in source)

CREATE INDEX IF NOT EXISTS idx_company_creation_success_company_id
    ON company_creation_success (company_id);

-- =====================================================================
-- Foreign keys (grouped, run after all module tables exist)
-- =====================================================================

-- EXPLICIT in SQLite source:
--   company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE company_creation_success
    ADD CONSTRAINT fk_company_creation_success_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;  -- explicit in source
