-- =====================================================================
-- Module: company
-- Source: server/company/company.js  (SQLite init)
-- Target: PostgreSQL
--
-- Translation notes:
--   * SQLite "INTEGER PRIMARY KEY AUTOINCREMENT" -> identity column.
--   * All TEXT columns -> TEXT (no length caps in source).
--   * created_at stores ISO datetime strings (SQLite datetime('now'))
--     -> TIMESTAMPTZ DEFAULT now().
--   * financial_year_beginning_from / books_beginning_from are stored as
--     ISO date/datetime TEXT. They are kept as TEXT here because the source
--     does not constrain them and they may carry full ISO timestamps; see
--     comments for the recommended DATE/TIMESTAMPTZ choice.
--   * password holds a bcrypt hash (server strips it before returning rows).
--   * The companies table has NO money/quantity columns.
--   * This is a ROOT/parent table: company_id is referenced by virtually every
--     other module via *_id columns. It has no outgoing foreign keys.
-- =====================================================================

CREATE TABLE companies (
    company_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                          TEXT NOT NULL,
    mailing_name                  TEXT,
    address1                      TEXT,
    address2                      TEXT,
    state                         TEXT,
    country                       TEXT,
    pincode                       TEXT,
    telephone                     TEXT,
    mobile                        TEXT,
    fax                           TEXT,
    email                         TEXT,
    website                       TEXT,
    base_currency_symbol          TEXT,
    formal_name                   TEXT,
    -- ISO date string in source; consider DATE if always date-only.
    financial_year_beginning_from TEXT,
    -- ISO date string in source; consider DATE if always date-only.
    books_beginning_from          TEXT,
    -- bcrypt hash; never returned to the renderer.
    password                      TEXT,
    access_control                TEXT,
    edit_log                      TEXT,
    -- SQLite: TEXT DEFAULT (datetime('now')) storing ISO strings.
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------
-- None. `companies` is the top-level tenant/root table and has no outgoing
-- foreign keys. Its primary key `company_id` is the target of inferred FKs
-- in nearly every other module (groups.company_id, ledgers.company_id,
-- financial_years.company_id, vouchers.company_id, etc.). Those FK
-- constraints belong in the respective module SQL files and should reference:
--
--   ALTER TABLE <child_table>
--     ADD CONSTRAINT fk_<child>_company
--     FOREIGN KEY (company_id) REFERENCES companies (company_id);   -- inferred
-- ---------------------------------------------------------------------
