-- ============================================================================
-- Module: costCentre
-- Source: server/costCentre/costCentre.js  (SQLite -> PostgreSQL translation)
-- Table:  cost_centres
-- ============================================================================
--
-- SQLite source (verbatim):
--   cc_id         INTEGER PRIMARY KEY AUTOINCREMENT
--   company_id    INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
--   name          TEXT NOT NULL
--   alias         TEXT
--   parent_id     INTEGER REFERENCES cost_centres(cc_id)
--   category      TEXT DEFAULT 'Primary'
--   is_active     INTEGER DEFAULT 1
--   is_predefined INTEGER DEFAULT 0
--   created_at    TEXT DEFAULT (datetime('now'))
--   updated_at    TEXT DEFAULT (datetime('now'))
--
-- Notes:
--   * is_active / is_predefined are 0/1 integer flags in SQLite -> BOOLEAN here
--     (0 -> false, 1 -> true). Defaults translated accordingly.
--   * created_at / updated_at store ISO-8601 datetime strings -> TIMESTAMPTZ,
--     datetime('now') default -> now().
--   * company_id FK is EXPLICIT in the SQLite source (with ON DELETE CASCADE).
--   * parent_id self-FK is EXPLICIT in the SQLite source (no ON DELETE action).
--   * No money/quantity columns in this table.
-- ============================================================================

CREATE TABLE cost_centres (
    cc_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    BIGINT      NOT NULL,
    name          TEXT        NOT NULL,
    alias         TEXT,
    parent_id     BIGINT,
    category      TEXT        NOT NULL DEFAULT 'Primary',
    is_active     BOOLEAN     NOT NULL DEFAULT true,   -- SQLite INTEGER 0/1 (DEFAULT 1)
    is_predefined BOOLEAN     NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1 (DEFAULT 0)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),  -- SQLite TEXT ISO-8601, datetime('now')
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()   -- SQLite TEXT ISO-8601, datetime('now')
);

-- The app enforces a case-insensitive unique active name per company in code
-- (service.create). Optional DB-level guard (commented; uncomment if desired):
-- CREATE UNIQUE INDEX uq_cost_centres_company_name_active
--   ON cost_centres (company_id, lower(name))
--   WHERE is_active = true;

-- Indexes on FK columns
CREATE INDEX idx_cost_centres_company_id ON cost_centres (company_id);
CREATE INDEX idx_cost_centres_parent_id  ON cost_centres (parent_id);

-- ============================================================================
-- Foreign keys (grouped at bottom so cross-module load ordering is irrelevant)
-- ============================================================================

-- EXPLICIT in source: REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE cost_centres
    ADD CONSTRAINT fk_cost_centres_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: REFERENCES cost_centres(cc_id) (self-referential parent)
ALTER TABLE cost_centres
    ADD CONSTRAINT fk_cost_centres_parent
    FOREIGN KEY (parent_id) REFERENCES cost_centres (cc_id);
