-- =============================================================================
-- Module: currency
-- Source: server/currency/currency.js  (SQLite schema init)
-- Target: PostgreSQL
--
-- SQLite -> Postgres mapping notes:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * TEXT datetime defaults (datetime('now'))  -> TIMESTAMPTZ DEFAULT now()
--     (the app stores ISO-8601 strings in SQLite).
--   * INTEGER 0/1 flag columns -> BOOLEAN (0 -> false, 1 -> true).
--   * No money/quantity columns exist in this module.
-- Foreign keys are declared as separate ALTER TABLE statements at the bottom so
-- cross-module load order does not matter.
-- =============================================================================

CREATE TABLE currencies (
    currency_id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                             BIGINT  NOT NULL,                         -- FK -> companies.company_id (explicit in source, ON DELETE CASCADE)
    name                                   TEXT    NOT NULL,
    formal_name                            TEXT,
    iso_code                               TEXT    NOT NULL,
    symbol                                 TEXT,
    decimal_places                         INTEGER NOT NULL DEFAULT 2,
    decimal_symbol                         TEXT    NOT NULL DEFAULT '.',
    decimal_places_in_words                TEXT,
    suffix_symbol_to_amount                BOOLEAN NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 -> BOOLEAN
    show_amount_in_millions                BOOLEAN NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 -> BOOLEAN
    word_representing_amount_after_decimal TEXT,
    add_space_between_amount_and_symbol    BOOLEAN NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 -> BOOLEAN
    is_active                              BOOLEAN NOT NULL DEFAULT true,            -- SQLite INTEGER 0/1 -> BOOLEAN; soft-delete sets false
    is_default                             BOOLEAN NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 -> BOOLEAN
    is_predefined                          BOOLEAN NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 -> BOOLEAN; marks seeded base currency
    created_at                             TIMESTAMPTZ NOT NULL DEFAULT now(),       -- SQLite TEXT datetime('now')
    updated_at                             TIMESTAMPTZ NOT NULL DEFAULT now()        -- SQLite TEXT datetime('now')
);

-- The service enforces "one active currency per (company_id, iso_code)" via a
-- case-insensitive lookup before insert. Recommended Postgres equivalent:
CREATE UNIQUE INDEX uq_currencies_company_iso_active
    ON currencies (company_id, LOWER(iso_code))
    WHERE is_active = true;

-- Index on the FK column for join/filter performance.
CREATE INDEX idx_currencies_company_id ON currencies (company_id);

-- -----------------------------------------------------------------------------
-- Foreign key constraints (grouped to avoid cross-module ordering problems).
-- companies(company_id) is owned by the "company" module.
-- This FK is EXPLICIT in the SQLite source
-- (company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE).
-- -----------------------------------------------------------------------------
ALTER TABLE currencies
    ADD CONSTRAINT fk_currencies_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
