-- ============================================================================
-- Module: dayBookReport
-- Source: server/dayBookReport/dayBookReport.js (SQLite schema init)
-- Target: PostgreSQL
--
-- Tables: day_book_reports, day_book_entries, day_book_entry_lines
--
-- Money/quantity columns use NUMERIC, NEVER floating point. The SQLite source
-- declares these as REAL; storing money in REAL/float risks rounding errors.
-- They are mapped to NUMERIC(18,2) (currency) here on purpose.
--
-- SQLite INTEGER 0/1 boolean flags are mapped to BOOLEAN. The application
-- writes 0/1 integers; migrate with: (col <> 0) -> true / (col = 0) -> false.
--
-- SQLite datetime('now') defaults store ISO-8601 strings; mapped to TIMESTAMPTZ
-- with DEFAULT now().
--
-- FK constraints are grouped at the bottom as ALTER TABLE statements so this
-- file can load before/after other modules without ordering problems. FKs that
-- are EXPLICIT in the SQLite source (REFERENCES ...) are marked "explicit"; FKs
-- INFERRED from *_id naming are marked "inferred".
-- ============================================================================

-- ----------------------------------------------------------------------------
-- day_book_reports  (report header)
-- ----------------------------------------------------------------------------
CREATE TABLE day_book_reports (
    report_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                 BIGINT       NOT NULL,
    report_name                TEXT         DEFAULT 'Day Book',
    date_from                  DATE,                       -- date-only ISO text in source
    date_to                    DATE,                       -- date-only ISO text in source
    selected_company_id        BIGINT,
    basis_of_values            TEXT         DEFAULT 'Default',
    change_view                TEXT,
    exception_reports_enabled  BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    saved_view_name            TEXT,
    filter_enabled             BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    filter_details             TEXT,
    show_profit                BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_columnar              BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_optional              BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_post_dated            BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_stat_adjustment       BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_details               BOOLEAN      NOT NULL DEFAULT true,   -- SQLite INTEGER 0/1, default 1
    show_related_reports       BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    created_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),  -- ISO string in source
    updated_at                 TIMESTAMPTZ  NOT NULL DEFAULT now()   -- ISO string in source
);

-- ----------------------------------------------------------------------------
-- day_book_entries  (one row per voucher line in the report)
-- ----------------------------------------------------------------------------
CREATE TABLE day_book_entries (
    entry_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id          BIGINT       NOT NULL,
    company_id         BIGINT       NOT NULL,
    voucher_id         BIGINT,
    voucher_date       DATE,                                -- date-only ISO text in source
    particulars        TEXT,
    voucher_type       TEXT,
    voucher_number     TEXT,
    debit_amount       NUMERIC(18,2) NOT NULL DEFAULT 0,    -- MONEY: never float
    credit_amount      NUMERIC(18,2) NOT NULL DEFAULT 0,    -- MONEY: never float
    narration          TEXT,
    party_ledger_name  TEXT,
    show_profit        BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    is_optional        BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    is_post_dated      BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    is_stat_adjustment BOOLEAN      NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    gross_profit       NUMERIC(18,2) NOT NULL DEFAULT 0,    -- MONEY: never float
    cost               NUMERIC(18,2) NOT NULL DEFAULT 0,    -- MONEY: never float
    display_order      INTEGER      NOT NULL DEFAULT 0,
    is_drillable       BOOLEAN      NOT NULL DEFAULT true,   -- SQLite INTEGER 0/1, default 1
    notes              TEXT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),  -- ISO string in source
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()   -- ISO string in source
);

-- ----------------------------------------------------------------------------
-- day_book_entry_lines  (ledger split lines under an entry)
-- ----------------------------------------------------------------------------
CREATE TABLE day_book_entry_lines (
    line_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id       BIGINT       NOT NULL,
    ledger_id      BIGINT,
    particulars    TEXT,
    debit_amount   NUMERIC(18,2) NOT NULL DEFAULT 0,        -- MONEY: never float
    credit_amount  NUMERIC(18,2) NOT NULL DEFAULT 0,        -- MONEY: never float
    line_order     INTEGER      NOT NULL DEFAULT 0,
    notes          TEXT
);

-- ----------------------------------------------------------------------------
-- Indexes on FK columns
-- ----------------------------------------------------------------------------
CREATE INDEX idx_day_book_reports_company_id        ON day_book_reports (company_id);
CREATE INDEX idx_day_book_reports_selected_company  ON day_book_reports (selected_company_id);
CREATE INDEX idx_day_book_entries_report_id         ON day_book_entries (report_id);
CREATE INDEX idx_day_book_entries_company_id        ON day_book_entries (company_id);
CREATE INDEX idx_day_book_entries_voucher_id        ON day_book_entries (voucher_id);
CREATE INDEX idx_day_book_entry_lines_entry_id      ON day_book_entry_lines (entry_id);
CREATE INDEX idx_day_book_entry_lines_ledger_id     ON day_book_entry_lines (ledger_id);

-- ============================================================================
-- Foreign keys (grouped to avoid cross-module load-order issues).
-- Referenced tables (companies, vouchers, ledgers) belong to other modules.
-- ============================================================================

-- explicit in source: companies(company_id) ON DELETE CASCADE
ALTER TABLE day_book_reports
    ADD CONSTRAINT fk_day_book_reports_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- inferred from selected_company_id naming (no REFERENCES in SQLite source).
-- Nullable; no cascade because it is an optional view selection, not ownership.
ALTER TABLE day_book_reports
    ADD CONSTRAINT fk_day_book_reports_selected_company
    FOREIGN KEY (selected_company_id) REFERENCES companies (company_id);

-- explicit in source: day_book_reports(report_id) ON DELETE CASCADE
ALTER TABLE day_book_entries
    ADD CONSTRAINT fk_day_book_entries_report
    FOREIGN KEY (report_id) REFERENCES day_book_reports (report_id) ON DELETE CASCADE;

-- explicit in source: companies(company_id) ON DELETE CASCADE
ALTER TABLE day_book_entries
    ADD CONSTRAINT fk_day_book_entries_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- explicit in source: vouchers(voucher_id) (no action specified -> NO ACTION)
ALTER TABLE day_book_entries
    ADD CONSTRAINT fk_day_book_entries_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id);

-- explicit in source: day_book_entries(entry_id) ON DELETE CASCADE
ALTER TABLE day_book_entry_lines
    ADD CONSTRAINT fk_day_book_entry_lines_entry
    FOREIGN KEY (entry_id) REFERENCES day_book_entries (entry_id) ON DELETE CASCADE;

-- explicit in source: ledgers(ledger_id) (no action specified -> NO ACTION)
ALTER TABLE day_book_entry_lines
    ADD CONSTRAINT fk_day_book_entry_lines_ledger
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id);
