-- ============================================================================
-- Module: eInvoice
-- Postgres DDL translated from server/eInvoice/eInvoice.js (SQLite source).
-- Tables: einvoice_credentials, einvoice_records
--
-- Conventions applied:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * TEXT -> TEXT
--   * datetime('now') TEXT defaults -> TIMESTAMPTZ DEFAULT now()
--     (NOTE: the app stores ISO-8601 strings in SQLite; in Postgres use TIMESTAMPTZ)
--   * INTEGER 0/1 flags (is_sandbox) -> BOOLEAN (0 -> false, 1 -> true)
--   * No money/quantity columns exist in this module.
--   * FK constraints are grouped at the bottom via ALTER TABLE.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: einvoice_credentials
-- One IRP credential set per company (upserted by company_id).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS einvoice_credentials (
    cred_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT      NOT NULL,
    client_id      TEXT        NOT NULL,
    client_secret  TEXT        NOT NULL,
    username       TEXT        NOT NULL,
    password       TEXT        NOT NULL,
    app_key        TEXT        NOT NULL,
    is_sandbox     BOOLEAN     NOT NULL DEFAULT true,   -- SQLite INTEGER DEFAULT 1 (0/1 -> false/true)
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),  -- SQLite TEXT DEFAULT datetime('now'); app stores ISO strings
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()   -- SQLite TEXT DEFAULT datetime('now'); app stores ISO strings
);

-- The service upserts by company_id (SELECT ... WHERE company_id = ?), so one
-- credential row per company is the intended cardinality. Enforce it explicitly.
ALTER TABLE einvoice_credentials
    ADD CONSTRAINT uq_einvoice_credentials_company UNIQUE (company_id);

-- ----------------------------------------------------------------------------
-- Table: einvoice_records
-- One row per generated/cancelled e-Invoice (IRN).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS einvoice_records (
    irn_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT      NOT NULL,
    voucher_id      BIGINT,                                  -- nullable; voucher_id || null in service
    invoice_number  TEXT        NOT NULL,
    invoice_date    TEXT        NOT NULL,                    -- kept TEXT: IRP DocDtls.Dt format (dd/mm/yyyy), not ISO; do not coerce to DATE
    buyer_gstin     TEXT,
    irn             TEXT,
    ack_no          TEXT,
    ack_dt          TEXT,                                    -- IRP AckDt string (TEXT preserved; IRP format)
    signed_invoice  TEXT,
    signed_qr_code  TEXT,
    ewb_no          TEXT,
    ewb_dt          TEXT,                                    -- IRP EwbDt string (TEXT preserved; IRP format)
    status          TEXT        NOT NULL DEFAULT 'PENDING',  -- PENDING | GENERATED | CANCELLED
    cancel_reason   INTEGER,                                 -- IRP cancellation reason code (stays INTEGER)
    cancel_remarks  TEXT,
    cancelled_at    TIMESTAMPTZ,                             -- set via datetime('now') -> TIMESTAMPTZ
    raw_response    TEXT,                                    -- JSON string of full IRP response (could be JSONB; kept TEXT to match source)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),      -- SQLite TEXT DEFAULT datetime('now'); app stores ISO strings
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()       -- SQLite TEXT DEFAULT datetime('now'); app stores ISO strings
);

-- ----------------------------------------------------------------------------
-- Indexes on FK / lookup columns
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_einvoice_records_company_id ON einvoice_records (company_id);
CREATE INDEX IF NOT EXISTS idx_einvoice_records_voucher_id ON einvoice_records (voucher_id);
-- Records are looked up by IRN (getRecordByIRN, cancel UPDATE ... WHERE irn = ?).
CREATE INDEX IF NOT EXISTS idx_einvoice_records_irn        ON einvoice_records (irn);
-- getRecords orders by created_at DESC per company.
CREATE INDEX IF NOT EXISTS idx_einvoice_records_company_created
    ON einvoice_records (company_id, created_at DESC);

-- ============================================================================
-- Foreign keys (grouped so cross-module table ordering is not a problem).
-- ============================================================================

-- EXPLICIT in SQLite source: company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE einvoice_credentials
    ADD CONSTRAINT fk_einvoice_credentials_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source: company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE einvoice_records
    ADD CONSTRAINT fk_einvoice_records_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- INFERRED FK: voucher_id has no explicit REFERENCES in the SQLite source, but the
-- column name + usage (links a generated IRN to its source sales voucher) implies a
-- relationship to the vouchers table's primary key. Adjust the referenced table/column
-- to match the actual vouchers schema. Kept NULL-able (records may exist without a voucher).
ALTER TABLE einvoice_records
    ADD CONSTRAINT fk_einvoice_records_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE SET NULL;
