-- ============================================================================
-- Module: employeeGroup
-- Source: server/employeeGroup/employeeGroup.js  (SQLite CREATE TABLE)
-- Target: PostgreSQL
--
-- Notes:
--   * SQLite INTEGER 0/1 flags (is_active, is_predefined) -> BOOLEAN.
--   * SQLite datetime('now') TEXT (ISO-8601 string) -> TIMESTAMPTZ DEFAULT now().
--   * FK to companies is EXPLICIT in the SQLite source (REFERENCES ... ON DELETE CASCADE).
--   * FK to employee_categories and the self-FK on parent_group_id are EXPLICIT
--     in the SQLite source (REFERENCES ...), preserved below.
--   * No money/quantity columns exist in this module.
-- ============================================================================

CREATE TABLE employee_groups (
    employee_group_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT  NOT NULL,
    employee_category_id BIGINT,                                   -- nullable; added via ALTER TABLE in source
    name                 TEXT    NOT NULL,
    alias                TEXT,
    parent_group_id      BIGINT,                                   -- self-reference (hierarchy)
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,            -- SQLite INTEGER DEFAULT 1 (0/1 -> false/true)
    is_predefined        BOOLEAN NOT NULL DEFAULT FALSE,           -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),       -- SQLite TEXT DEFAULT (datetime('now')); app stores ISO strings
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()        -- SQLite TEXT DEFAULT (datetime('now')); app stores ISO strings
);

-- Indexes on FK / lookup columns
CREATE INDEX idx_employee_groups_company_id           ON employee_groups (company_id);
CREATE INDEX idx_employee_groups_employee_category_id ON employee_groups (employee_category_id);
CREATE INDEX idx_employee_groups_parent_group_id      ON employee_groups (parent_group_id);

-- Enforce per-company case-insensitive uniqueness of active group names.
-- (The service checks this in application code; this partial index makes it a hard constraint.)
CREATE UNIQUE INDEX uq_employee_groups_company_lower_name_active
    ON employee_groups (company_id, LOWER(name))
    WHERE is_active = TRUE;

-- ============================================================================
-- Foreign keys (grouped at bottom so cross-module load order does not matter)
-- ============================================================================

-- EXPLICIT in SQLite source: company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE employee_groups
    ADD CONSTRAINT fk_employee_groups_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source: employee_category_id INTEGER REFERENCES employee_categories(employee_category_id)
ALTER TABLE employee_groups
    ADD CONSTRAINT fk_employee_groups_employee_category
    FOREIGN KEY (employee_category_id) REFERENCES employee_categories (employee_category_id);

-- EXPLICIT in SQLite source: parent_group_id INTEGER REFERENCES employee_groups(employee_group_id)
ALTER TABLE employee_groups
    ADD CONSTRAINT fk_employee_groups_parent
    FOREIGN KEY (parent_group_id) REFERENCES employee_groups (employee_group_id);
