-- ============================================================================
-- Postgres DDL for module: employeeCategory
-- Source: server/employeeCategory/employeeCategory.js (SQLite schema init)
-- Tables: employee_categories
-- FK constraints are grouped at the bottom (ALTER TABLE) to avoid cross-module
-- ordering problems.
-- ============================================================================

CREATE TABLE IF NOT EXISTS employee_categories (
    employee_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT  NOT NULL,
    name                 TEXT    NOT NULL,
    alias                TEXT,
    -- 0/1 integer flags in SQLite -> BOOLEAN in Postgres (0=false, 1=true).
    allocate_revenue     BOOLEAN NOT NULL DEFAULT false,   -- SQLite: INTEGER DEFAULT 0
    allocate_non_revenue BOOLEAN NOT NULL DEFAULT false,   -- SQLite: INTEGER DEFAULT 0
    is_active            BOOLEAN NOT NULL DEFAULT true,     -- SQLite: INTEGER DEFAULT 1 (soft-delete marker)
    is_predefined        BOOLEAN NOT NULL DEFAULT false,    -- SQLite: INTEGER DEFAULT 0
    -- SQLite stored ISO-8601 strings via datetime('now') -> TIMESTAMPTZ with now().
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Helpful indexes on FK / lookup columns.
CREATE INDEX IF NOT EXISTS idx_employee_categories_company_id
    ON employee_categories (company_id);

-- Supports the case-insensitive active-name lookup used by create()
-- (WHERE company_id = ? AND LOWER(name) = LOWER(?) AND is_active = 1).
CREATE INDEX IF NOT EXISTS idx_employee_categories_company_lower_name
    ON employee_categories (company_id, lower(name));

-- ============================================================================
-- Foreign keys
-- ============================================================================

-- EXPLICIT in source: SQLite declared
--   company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE employee_categories
    ADD CONSTRAINT fk_employee_categories_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;

-- NOTE: employee_categories is also referenced BY other modules' tables
-- (employee_groups.employee_category_id and employees.employee_category_id,
-- observed in employeeCategoryService.delete). Those inbound FK constraints
-- belong to the employeeGroup / employee modules and are intentionally NOT
-- declared here to keep this module self-contained.
