-- ============================================================================
-- Module: employee
-- Source: server/employee/employee.js  (SQLite schema init -> Postgres DDL)
-- Tables: employees
--
-- Type mapping notes:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * created_at/updated_at (ISO datetime TEXT, default datetime('now')) -> TIMESTAMPTZ DEFAULT now()
--   * date_of_* (date-only TEXT) -> DATE
--   * 0/1 flag INTEGER (is_active, define_salary_details) -> BOOLEAN
--   * All other TEXT columns -> TEXT
--   * No money/quantity columns exist in this table.
-- FK notes:
--   * company_id, employee_category_id, employee_group_id are EXPLICIT
--     REFERENCES in the SQLite source. Re-declared below as Postgres FKs.
-- ============================================================================

CREATE TABLE IF NOT EXISTS employees (
    employee_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT  NOT NULL,
    employee_category_id   BIGINT,
    employee_group_id      BIGINT,
    name                   TEXT    NOT NULL,
    alias                  TEXT,
    employee_code          TEXT,
    designation            TEXT,
    department             TEXT,
    function               TEXT,
    location               TEXT,
    date_of_joining        DATE,                          -- date-only ISO string in SQLite
    date_of_leaving        DATE,                          -- date-only ISO string in SQLite
    date_of_birth          DATE,                          -- date-only ISO string in SQLite
    gender                 TEXT,
    blood_group            TEXT,
    father_name            TEXT,
    mother_name            TEXT,
    spouse_name            TEXT,
    address                TEXT,
    city                   TEXT,
    state                  TEXT,
    pincode                TEXT,
    mobile                 TEXT,
    phone                  TEXT,
    email                  TEXT,
    define_salary_details  BOOLEAN NOT NULL DEFAULT FALSE, -- SQLite INTEGER DEFAULT 0; 0->false, 1->true
    bank_account_number    TEXT,
    bank_name              TEXT,
    bank_branch            TEXT,
    ifsc_code              TEXT,
    applicable_tax_regime  TEXT,
    pan                    TEXT,
    aadhaar                TEXT,
    uan                    TEXT,
    pf_account_number      TEXT,
    eps_account_number     TEXT,
    date_of_joining_pf     DATE,                          -- date-only ISO string in SQLite
    pran                   TEXT,
    esi_number             TEXT,
    esi_dispensary_name    TEXT,
    is_active              BOOLEAN NOT NULL DEFAULT TRUE,  -- SQLite INTEGER DEFAULT 1; 0->false, 1->true
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(), -- SQLite TEXT DEFAULT datetime('now')
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()  -- SQLite TEXT DEFAULT datetime('now')
);

-- Indexes on FK columns (recommended for lookups/filtering).
CREATE INDEX IF NOT EXISTS idx_employees_company_id           ON employees (company_id);
CREATE INDEX IF NOT EXISTS idx_employees_employee_category_id ON employees (employee_category_id);
CREATE INDEX IF NOT EXISTS idx_employees_employee_group_id    ON employees (employee_group_id);

-- employee_code uniqueness is enforced in application code only (per active row
-- of a company). A partial unique index models that intent; enable if desired:
-- CREATE UNIQUE INDEX IF NOT EXISTS uq_employees_company_code_active
--     ON employees (company_id, employee_code) WHERE is_active = TRUE;

-- ============================================================================
-- Foreign keys (grouped at bottom so cross-module table order is not an issue).
-- All three FKs are EXPLICIT in the SQLite source (REFERENCES clauses).
-- ============================================================================

ALTER TABLE employees
    ADD CONSTRAINT fk_employees_company_id
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE; -- explicit in source

ALTER TABLE employees
    ADD CONSTRAINT fk_employees_employee_category_id
    FOREIGN KEY (employee_category_id) REFERENCES employee_categories (employee_category_id); -- explicit in source

ALTER TABLE employees
    ADD CONSTRAINT fk_employees_employee_group_id
    FOREIGN KEY (employee_group_id) REFERENCES employee_groups (employee_group_id); -- explicit in source
