-- ============================================================================
-- Postgres DDL for backend module: featureGroup
-- Source: server/featureGroup/featureGroup.js (SQLite schema init)
-- ============================================================================
-- SQLite source table: feature_groups
--   feature_group_id  INTEGER PRIMARY KEY AUTOINCREMENT
--   group_key         TEXT NOT NULL UNIQUE
--   group_name        TEXT NOT NULL
--   online_access     INTEGER DEFAULT 0   -- 0/1 boolean
--   display_order     INTEGER DEFAULT 0
--   is_active         INTEGER DEFAULT 1   -- 0/1 boolean
-- ============================================================================

CREATE TABLE feature_groups (
    feature_group_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_key         TEXT    NOT NULL,
    group_name        TEXT    NOT NULL,
    -- online_access: SQLite INTEGER 0/1 used as a boolean -> BOOLEAN (0->false, 1->true).
    online_access     BOOLEAN NOT NULL DEFAULT FALSE,
    display_order     INTEGER NOT NULL DEFAULT 0,
    -- is_active: SQLite INTEGER 0/1 used as a boolean -> BOOLEAN (0->false, 1->true).
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,

    -- Preserved from SQLite: group_key UNIQUE.
    CONSTRAINT uq_feature_groups_group_key UNIQUE (group_key)
);

-- ----------------------------------------------------------------------------
-- Indexes
-- ----------------------------------------------------------------------------
-- Supports getAll(): WHERE is_active = 1 ORDER BY display_order ASC.
CREATE INDEX idx_feature_groups_active_order
    ON feature_groups (is_active, display_order);

-- ============================================================================
-- Foreign keys (ALTER TABLE, grouped at bottom for cross-module ordering)
-- ============================================================================
-- No foreign keys: the feature_groups table contains no *_id reference columns.
-- (feature_group_id is this table's own primary key, not a reference.)
-- No FK constraints emitted for this module.
