-- ============================================================================
-- Postgres DDL for the `featureItem` backend module
-- Source: server/featureItem/featureItem.js (SQLite schema init)
-- Tables: feature_items
-- ============================================================================
--
-- SQLite -> Postgres type mapping applied:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   TEXT                              -> TEXT
--   INTEGER used as boolean (0/1)     -> BOOLEAN (0->false, 1->true)
-- This table contains NO money/quantity columns.
-- ============================================================================

CREATE TABLE feature_items (
    feature_item_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_group_id      BIGINT  NOT NULL,
    feature_key           TEXT    NOT NULL UNIQUE,
    feature_name          TEXT    NOT NULL,
    description           TEXT,
    -- SQLite: control_type TEXT DEFAULT 'boolean'
    control_type          TEXT    NOT NULL DEFAULT 'boolean',
    -- SQLite: default_value_boolean INTEGER DEFAULT 0 (0/1 boolean flag -> BOOLEAN)
    default_value_boolean BOOLEAN NOT NULL DEFAULT FALSE,
    -- SQLite: display_order INTEGER DEFAULT 0
    display_order         INTEGER NOT NULL DEFAULT 0,
    -- SQLite: is_mandatory INTEGER DEFAULT 0 (0/1 boolean flag -> BOOLEAN)
    is_mandatory          BOOLEAN NOT NULL DEFAULT FALSE,
    -- SQLite: is_active INTEGER DEFAULT 1 (0/1 boolean flag -> BOOLEAN)
    is_active             BOOLEAN NOT NULL DEFAULT TRUE
);

-- Index on the FK column for join/lookup performance (getByGroup filters on it).
CREATE INDEX idx_feature_items_feature_group_id
    ON feature_items (feature_group_id);

-- ============================================================================
-- Foreign key constraints (grouped at bottom to avoid cross-module ordering
-- problems; create feature_groups before applying these).
-- ============================================================================

-- EXPLICIT in source: SQLite declared
--   feature_group_id INTEGER NOT NULL
--     REFERENCES feature_groups(feature_group_id) ON DELETE CASCADE
ALTER TABLE feature_items
    ADD CONSTRAINT fk_feature_items_feature_group
    FOREIGN KEY (feature_group_id)
    REFERENCES feature_groups (feature_group_id)
    ON DELETE CASCADE;
