-- ============================================================================
-- Postgres DDL for backend module: financialYear
-- Source: server/financialYear/financialYear.js (SQLite schema init)
-- ============================================================================
-- Type mapping applied:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   TEXT (date-only)                  -> DATE
--   TEXT (ISO datetime)               -> TIMESTAMPTZ
--   INTEGER (0/1 flag)                -> BOOLEAN (0->false, 1->true)
--   datetime('now') default          -> now()
-- ============================================================================

CREATE TABLE financial_years (
    fy_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- company_id: FK is EXPLICIT in the SQLite source
    --   (REFERENCES companies(company_id) ON DELETE CASCADE).
    --   Constraint emitted at bottom of file.
    company_id   BIGINT      NOT NULL,
    start_date   DATE        NOT NULL,   -- date-only TEXT in SQLite
    end_date     DATE        NOT NULL,   -- date-only TEXT in SQLite
    is_active    BOOLEAN     NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    is_closed    BOOLEAN     NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    closing_date DATE,                                -- nullable date-only TEXT
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()   -- SQLite TEXT DEFAULT datetime('now')
);

-- Indexes on FK columns
CREATE INDEX idx_financial_years_company_id ON financial_years (company_id);

-- Optional but sensible: a company should not have two FYs with the same start date.
-- (The service enforces this in application code via a duplicate check on
--  company_id + start_date; mirror it in the DB as a UNIQUE constraint.)
ALTER TABLE financial_years
    ADD CONSTRAINT uq_financial_years_company_start UNIQUE (company_id, start_date);

-- ============================================================================
-- Foreign keys (grouped at bottom for cross-module load ordering)
-- ============================================================================

-- EXPLICIT FK in source SQLite schema:
--   financial_years.company_id -> companies(company_id) ON DELETE CASCADE
ALTER TABLE financial_years
    ADD CONSTRAINT fk_financial_years_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
