-- ============================================================================
-- Module: godown
-- Source: server/godown/godown.js  (SQLite schema init)
-- Target: PostgreSQL
--
-- SQLite -> Postgres translation notes:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * Boolean-ish INTEGER (0/1) columns -> BOOLEAN (0 -> false, 1 -> true)
--   * created_at / updated_at TEXT (ISO-8601 via datetime('now')) -> TIMESTAMPTZ
--     DEFAULT now()  (app stores ISO strings in SQLite)
--   * TEXT -> TEXT (no length cap in source)
--   * Foreign keys: company_id and parent_godown_id are EXPLICIT REFERENCES in the
--     SQLite source (see ALTER TABLE section below).
-- ============================================================================

CREATE TABLE IF NOT EXISTS godowns (
    godown_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                  BIGINT  NOT NULL,
    name                        TEXT    NOT NULL,
    alias                       TEXT,
    parent_godown_id            BIGINT,
    address                     TEXT,
    city                        TEXT,
    state                       TEXT,
    pincode                     TEXT,
    -- 0/1 SQLite boolean -> BOOLEAN. DEFAULT 0 -> false.
    is_primary                  BOOLEAN NOT NULL DEFAULT false,
    -- 0/1 SQLite boolean -> BOOLEAN. DEFAULT 0 -> false.
    is_main_location            BOOLEAN NOT NULL DEFAULT false,
    -- 0/1 SQLite boolean -> BOOLEAN. DEFAULT 1 -> true.
    allow_storage_of_materials  BOOLEAN NOT NULL DEFAULT true,
    -- 0/1 SQLite boolean -> BOOLEAN. DEFAULT 1 -> true. Soft-delete flag.
    is_active                   BOOLEAN NOT NULL DEFAULT true,
    -- 0/1 SQLite boolean -> BOOLEAN. DEFAULT 0 -> false.
    is_predefined               BOOLEAN NOT NULL DEFAULT false,
    -- ISO-8601 datetime TEXT in SQLite -> TIMESTAMPTZ
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes on FK columns.
CREATE INDEX IF NOT EXISTS idx_godowns_company_id        ON godowns (company_id);
CREATE INDEX IF NOT EXISTS idx_godowns_parent_godown_id  ON godowns (parent_godown_id);

-- Supports the active-name uniqueness checks performed in the service layer.
CREATE INDEX IF NOT EXISTS idx_godowns_company_active    ON godowns (company_id, is_active);

-- ----------------------------------------------------------------------------
-- Foreign key constraints (grouped at bottom for cross-module load ordering).
-- ----------------------------------------------------------------------------

-- EXPLICIT FK in source:
--   company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE godowns
    ADD CONSTRAINT fk_godowns_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;

-- EXPLICIT FK in source (self-referential):
--   parent_godown_id INTEGER REFERENCES godowns(godown_id)
-- No ON DELETE action specified in source; defaulting to NO ACTION.
ALTER TABLE godowns
    ADD CONSTRAINT fk_godowns_parent
    FOREIGN KEY (parent_godown_id) REFERENCES godowns (godown_id);
