-- =============================================================================
-- Module: group
-- Source: server/group/group.js  (SQLite -> PostgreSQL translation)
-- Table:  groups  (chart-of-accounts hierarchy)
-- =============================================================================
-- Notes:
--   * SQLite INTEGER 0/1 flags are translated to BOOLEAN. The application stores
--     0 -> false and 1 -> true. Migrate existing data with (col <> 0).
--   * created_at / updated_at hold SQLite datetime('now') ISO-8601 strings ->
--     TIMESTAMPTZ DEFAULT now().
--   * GST rate columns hold tax percentages (REAL in SQLite). They are mapped to
--     NUMERIC(18,4), NOT floating point, to avoid rounding errors in tax math.
--   * Foreign keys are defined as separate ALTER TABLE statements at the bottom
--     so cross-module load ordering does not matter.
-- =============================================================================

CREATE TABLE IF NOT EXISTS groups (
    group_id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                        BIGINT       NOT NULL,                      -- FK -> companies.company_id (explicit in SQLite source)
    name                              TEXT         NOT NULL,
    alias                             TEXT,
    parent_group_id                   BIGINT,                                     -- FK -> groups.group_id (self ref; explicit in SQLite source)
    is_primary                        BOOLEAN      NOT NULL DEFAULT false,        -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    is_predefined                     BOOLEAN      NOT NULL DEFAULT false,        -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    nature                            TEXT,                                       -- Assets | Liabilities | Income | Expenses
    set_alter_tds_details             BOOLEAN      NOT NULL DEFAULT false,        -- 0/1 -> false/true
    set_alter_tcs_details             BOOLEAN      NOT NULL DEFAULT false,        -- 0/1 -> false/true
    set_alter_other_statutory_details BOOLEAN      NOT NULL DEFAULT false,        -- 0/1 -> false/true
    hsn_sac_source                    TEXT,
    hsn_sac_description               TEXT,
    gst_rate_source                   TEXT,
    taxability_type                   TEXT,
    behaves_like_subledger            BOOLEAN      NOT NULL DEFAULT false,        -- 0/1 -> false/true
    show_net_debit_credit             BOOLEAN      NOT NULL DEFAULT false,        -- 0/1 -> false/true
    used_for_calculation              BOOLEAN      NOT NULL DEFAULT false,        -- 0/1 -> false/true
    allocation_method                 TEXT         NOT NULL DEFAULT 'Average Cost',
    gst_rate                          NUMERIC(18,4),                              -- tax percentage; NOT floating point
    cgst_rate                         NUMERIC(18,4),                              -- tax percentage; NOT floating point
    sgst_rate                         NUMERIC(18,4),                              -- tax percentage; NOT floating point
    igst_rate                         NUMERIC(18,4),                              -- tax percentage; NOT floating point
    hsn_sac_code                      TEXT,
    statutory_details                 TEXT,                                       -- JSON/serialized text blob
    sort_order                        INTEGER      NOT NULL DEFAULT 0,
    group_type                        TEXT,                                       -- 'Primary' | 'Predefined' | 'User'
    display_order                     INTEGER      NOT NULL DEFAULT 0,
    is_active                         BOOLEAN      NOT NULL DEFAULT true,         -- SQLite INTEGER DEFAULT 1 (soft-delete flag)
    created_at                        TIMESTAMPTZ  NOT NULL DEFAULT now(),        -- SQLite TEXT DEFAULT datetime('now')
    updated_at                        TIMESTAMPTZ  NOT NULL DEFAULT now()         -- SQLite TEXT DEFAULT datetime('now')
);

-- -----------------------------------------------------------------------------
-- Indexes (FK columns + common lookup paths)
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_groups_company_id      ON groups (company_id);
CREATE INDEX IF NOT EXISTS idx_groups_parent_group_id ON groups (parent_group_id);
-- Supports the frequent "active groups per company" queries (getAll / getTree).
CREATE INDEX IF NOT EXISTS idx_groups_company_active  ON groups (company_id, is_active);

-- Enforce the service's uniqueness rule: one active group name per company
-- (case-insensitive). The service checks LOWER(name) before insert; this partial
-- unique index makes it a hard constraint.
CREATE UNIQUE INDEX IF NOT EXISTS uq_groups_company_active_name
    ON groups (company_id, LOWER(name))
    WHERE is_active = true;

-- -----------------------------------------------------------------------------
-- Foreign keys (grouped at bottom; safe regardless of cross-module load order)
-- -----------------------------------------------------------------------------

-- EXPLICIT in SQLite source: company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE groups
    ADD CONSTRAINT fk_groups_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source: parent_group_id INTEGER REFERENCES groups(group_id)
-- Self-referential hierarchy. ON DELETE NOT specified in source; ON DELETE RESTRICT
-- chosen to mirror the service's "cannot delete group with subgroups" guard.
ALTER TABLE groups
    ADD CONSTRAINT fk_groups_parent
    FOREIGN KEY (parent_group_id) REFERENCES groups (group_id) ON DELETE RESTRICT;
