-- =============================================================================
-- Postgres DDL — GST module
-- Source: server/gst/gst.js (SQLite schema init)
-- Tables: gst_hsn_rates, gst_voucher_tax_lines, gstr1_exports
--
-- Conventions applied (SQLite -> Postgres):
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * ISO datetime TEXT (created_at, datetime('now')) -> TIMESTAMPTZ DEFAULT now()
--   * date-only TEXT (effective_from/_to, filed_date) -> DATE
--   * INTEGER 0/1 boolean flags (is_inter_state) -> BOOLEAN (0->false, 1->true)
--   * REAL holding rates (gst_rate, cgst_rate, ...) -> NUMERIC(18,4)  [rate]
--   * REAL holding quantity (quantity) -> NUMERIC(18,4)              [qty]
--   * REAL holding money (assessable_value, amount) -> NUMERIC(18,2) [currency]
--     NEVER use floating point for money/quantity — exact NUMERIC only.
--   * Foreign keys: emitted as ALTER TABLE statements grouped at the bottom.
--     Some FKs are EXPLICIT in the SQLite source (REFERENCES ...); others are
--     INFERRED from *_id naming. Each constraint is commented accordingly.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Table: gst_hsn_rates
-- Company-level, effective-dated HSN/SAC GST rate overrides.
-- -----------------------------------------------------------------------------
CREATE TABLE gst_hsn_rates (
    rate_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT      NOT NULL,
    hsn_code        TEXT        NOT NULL,
    effective_from  DATE        NOT NULL,                 -- date-only ISO string
    effective_to    DATE,                                 -- nullable (open-ended)
    taxability      TEXT        NOT NULL DEFAULT 'Taxable',
    gst_rate        NUMERIC(18,4) NOT NULL DEFAULT 0,     -- tax rate (percent)
    cgst_rate       NUMERIC(18,4) NOT NULL DEFAULT 0,     -- tax rate (percent)
    sgst_rate       NUMERIC(18,4) NOT NULL DEFAULT 0,     -- tax rate (percent)
    igst_rate       NUMERIC(18,4) NOT NULL DEFAULT 0,     -- tax rate (percent)
    cess_rate       NUMERIC(18,4) NOT NULL DEFAULT 0,     -- tax rate (percent)
    type_of_supply  TEXT        NOT NULL DEFAULT 'Goods', -- 'Goods' | 'Services'
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()    -- app stores ISO string
);


-- -----------------------------------------------------------------------------
-- Table: gst_voucher_tax_lines
-- Per-voucher GST audit/breakdown lines (CGST/SGST/IGST/CESS).
-- -----------------------------------------------------------------------------
CREATE TABLE gst_voucher_tax_lines (
    tax_line_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id            BIGINT      NOT NULL,
    entry_id              BIGINT,                              -- nullable; ON DELETE SET NULL
    hsn_code              TEXT,
    description           TEXT,
    quantity              NUMERIC(18,4) NOT NULL DEFAULT 0,    -- qty
    unit                  TEXT,
    assessable_value      NUMERIC(18,2) NOT NULL DEFAULT 0,    -- MONEY: exact numeric, never float
    tax_type              TEXT,                                -- 'CGST' | 'SGST' | 'IGST' | 'CESS'
    rate                  NUMERIC(18,4) NOT NULL DEFAULT 0,    -- tax rate (percent)
    amount                NUMERIC(18,2) NOT NULL DEFAULT 0,    -- MONEY: exact numeric, never float
    is_inter_state        BOOLEAN     NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1 -> false/true
    party_gstin           TEXT,
    party_state           TEXT,
    gst_classification_id BIGINT,                              -- inferred FK (see ALTERs)
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()   -- app stores ISO string
);


-- -----------------------------------------------------------------------------
-- Table: gstr1_exports
-- Snapshot of a generated GSTR-1 return for a (company, fy, period).
-- JSON section columns stay as TEXT/JSONB; app stores JSON.stringify output.
-- -----------------------------------------------------------------------------
CREATE TABLE gstr1_exports (
    export_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT      NOT NULL,
    fy_id              BIGINT      NOT NULL,
    return_period      TEXT        NOT NULL,                -- 'MMYYYY' e.g. '052026'
    filed_date         DATE,                                -- nullable until filed
    status             TEXT        NOT NULL DEFAULT 'Draft',-- 'Draft' | 'Filed'
    b2b_json           TEXT,                                -- consider JSONB
    b2cl_json          TEXT,                                -- consider JSONB
    b2cs_json          TEXT,                                -- consider JSONB
    cdnr_json          TEXT,                                -- consider JSONB
    hsn_json           TEXT,                                -- consider JSONB
    errors_json        TEXT,                                -- consider JSONB
    full_payload_json  TEXT,                                -- consider JSONB
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()   -- app stores ISO string
);


-- -----------------------------------------------------------------------------
-- Indexes (FK columns + common lookup patterns)
-- -----------------------------------------------------------------------------
CREATE INDEX idx_gst_hsn_rates_company_id            ON gst_hsn_rates (company_id);
CREATE INDEX idx_gst_hsn_rates_company_hsn_eff       ON gst_hsn_rates (company_id, hsn_code, effective_from);

CREATE INDEX idx_gst_voucher_tax_lines_voucher_id    ON gst_voucher_tax_lines (voucher_id);
CREATE INDEX idx_gst_voucher_tax_lines_entry_id      ON gst_voucher_tax_lines (entry_id);
CREATE INDEX idx_gst_voucher_tax_lines_classif_id    ON gst_voucher_tax_lines (gst_classification_id);

CREATE INDEX idx_gstr1_exports_company_id            ON gstr1_exports (company_id);
CREATE INDEX idx_gstr1_exports_fy_id                 ON gstr1_exports (fy_id);
-- Lookup pattern used by generate/getGSTR1 (company_id, fy_id, return_period).
CREATE INDEX idx_gstr1_exports_lookup                ON gstr1_exports (company_id, fy_id, return_period);


-- =============================================================================
-- Foreign keys (grouped so cross-module table ordering is not a problem).
-- Referenced tables (companies, financial_years, vouchers, voucher_entries,
-- gst_classifications) live in OTHER modules; apply after all CREATE TABLEs.
-- =============================================================================

-- EXPLICIT in source: gst_hsn_rates.company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE gst_hsn_rates
    ADD CONSTRAINT fk_gst_hsn_rates_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: gst_voucher_tax_lines.voucher_id REFERENCES vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE gst_voucher_tax_lines
    ADD CONSTRAINT fk_gst_voucher_tax_lines_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;

-- EXPLICIT in source: gst_voucher_tax_lines.entry_id REFERENCES voucher_entries(entry_id) ON DELETE SET NULL
ALTER TABLE gst_voucher_tax_lines
    ADD CONSTRAINT fk_gst_voucher_tax_lines_entry
    FOREIGN KEY (entry_id) REFERENCES voucher_entries (entry_id) ON DELETE SET NULL;

-- INFERRED (no FK in source): gst_voucher_tax_lines.gst_classification_id -> gst_classifications.
--   Column exists but is never written by the gst module's code; relationship
--   inferred from the *_id naming and the sibling gstClassification module.
--   Verify the referenced table/PK column name before enabling in production.
ALTER TABLE gst_voucher_tax_lines
    ADD CONSTRAINT fk_gst_voucher_tax_lines_classification
    FOREIGN KEY (gst_classification_id) REFERENCES gst_classifications (gst_classification_id);

-- EXPLICIT in source: gstr1_exports.company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE gstr1_exports
    ADD CONSTRAINT fk_gstr1_exports_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: gstr1_exports.fy_id REFERENCES financial_years(fy_id) ON DELETE CASCADE
ALTER TABLE gstr1_exports
    ADD CONSTRAINT fk_gstr1_exports_fy
    FOREIGN KEY (fy_id) REFERENCES financial_years (fy_id) ON DELETE CASCADE;


-- =============================================================================
-- NOTE on stock_groups migrations (server/gst/gst.js lines 63-76)
-- The gst module also runs ALTER TABLE stock_groups ADD COLUMN igst_rate / cess_rate
-- (both REAL DEFAULT 0). stock_groups belongs to the inventory/stock module, so
-- those columns are documented here for provenance but NOT created in this file.
-- Postgres equivalents (apply in the stock_groups owning module):
--   ALTER TABLE stock_groups ADD COLUMN igst_rate NUMERIC(18,4) NOT NULL DEFAULT 0;  -- tax rate
--   ALTER TABLE stock_groups ADD COLUMN cess_rate NUMERIC(18,4) NOT NULL DEFAULT 0;  -- tax rate
-- =============================================================================
