-- ============================================================================
-- Module: gstClassification
-- Postgres DDL translated from SQLite source:
--   server/gstClassification/gstClassification.js
--
-- Source table: gst_classifications
--
-- Translation notes:
--   * SQLite INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT
--     AS IDENTITY PRIMARY KEY.
--   * INTEGER 0/1 flag columns (is_*) -> BOOLEAN. The app stores 0/1; map
--     0 -> false, 1 -> true. DEFAULT 0 -> false, DEFAULT 1 -> true.
--   * created_at / updated_at hold ISO-8601 datetime strings (datetime('now'))
--     -> TIMESTAMPTZ DEFAULT now().
--   * Rate columns (igst_rate, cgst_rate, sgst_rate, cess_rate, gst_rate) hold
--     GST percentages (money-adjacent). Mapped to NUMERIC(18,4) — NEVER float.
--     Using exact NUMERIC avoids rounding error in tax computation.
--   * The FK on company_id IS EXPLICIT in the SQLite source
--     (REFERENCES companies(company_id) ON DELETE CASCADE); preserved below.
-- ============================================================================

CREATE TABLE IF NOT EXISTS gst_classifications (
    gc_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              BIGINT NOT NULL,
    name                    TEXT   NOT NULL,
    description             TEXT,
    hsn_sac_code            TEXT,
    is_non_gst_goods        BOOLEAN        NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    nature_of_transaction   TEXT           NOT NULL DEFAULT 'Not Applicable',
    taxability              TEXT           NOT NULL DEFAULT 'Unknown',
    is_reverse_charge       BOOLEAN        NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    is_ineligible_for_itc   BOOLEAN        NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    rate_type               TEXT           NOT NULL DEFAULT 'Fixed Rate',
    igst_rate               NUMERIC(18,4)  NOT NULL DEFAULT 0,      -- GST rate %, exact numeric (never float)
    igst_valuation_type     TEXT           NOT NULL DEFAULT 'Based on Value',
    cgst_rate               NUMERIC(18,4)  NOT NULL DEFAULT 0,      -- GST rate %, exact numeric (never float)
    cgst_valuation_type     TEXT           NOT NULL DEFAULT 'Based on Value',
    sgst_rate               NUMERIC(18,4)  NOT NULL DEFAULT 0,      -- GST rate %, exact numeric (never float)
    sgst_valuation_type     TEXT           NOT NULL DEFAULT 'Based on Value',
    cess_rate               NUMERIC(18,4)  NOT NULL DEFAULT 0,      -- GST rate %, exact numeric (never float)
    cess_valuation_type     TEXT           NOT NULL DEFAULT 'Based on Value',
    gst_rate                NUMERIC(18,4)  NOT NULL DEFAULT 0,      -- aggregate GST rate %, exact numeric (never float)
    gst_rate_details        TEXT,                                  -- JSON string of slab rows (rate_type = 'Slab Based')
    valuation_type          TEXT           NOT NULL DEFAULT 'Based on Value',
    is_predefined           BOOLEAN        NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0 (0/1 -> false/true)
    is_active               BOOLEAN        NOT NULL DEFAULT true,   -- SQLite INTEGER DEFAULT 1 (0/1 -> false/true); soft-delete sets false
    created_at              TIMESTAMPTZ    NOT NULL DEFAULT now(),  -- SQLite TEXT DEFAULT (datetime('now')) ISO-8601
    updated_at              TIMESTAMPTZ    NOT NULL DEFAULT now()   -- SQLite TEXT DEFAULT (datetime('now')) ISO-8601
);

-- Index on the FK column for join/lookup performance and the common
-- "WHERE company_id = ? AND is_active = 1" query path.
CREATE INDEX IF NOT EXISTS idx_gst_classifications_company_id
    ON gst_classifications (company_id);

-- Note: the service enforces case-insensitive name uniqueness per company only
-- among ACTIVE rows (WHERE company_id = ? AND LOWER(name) = LOWER(?) AND
-- is_active = 1). A plain UNIQUE constraint cannot express the "active only"
-- predicate, so this is modeled as a partial unique index on lower(name).
CREATE UNIQUE INDEX IF NOT EXISTS uq_gst_classifications_company_name_active
    ON gst_classifications (company_id, lower(name))
    WHERE is_active = true;

-- ============================================================================
-- Foreign keys (grouped here so cross-module load ordering is not a concern).
-- ============================================================================

-- EXPLICIT FK in SQLite source: company_id REFERENCES companies(company_id)
-- ON DELETE CASCADE.
ALTER TABLE gst_classifications
    ADD CONSTRAINT fk_gst_classifications_company
    FOREIGN KEY (company_id)
    REFERENCES companies (company_id)
    ON DELETE CASCADE;
