-- ============================================================================
-- Module: gstRegistration
-- Source: server/gstRegistration/gstRegistration.js
-- Postgres DDL translated from the SQLite CREATE TABLE (+ ALTER migrations).
--
-- Type-mapping notes:
--   * gst_id: SQLite INTEGER PRIMARY KEY AUTOINCREMENT
--             -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY.
--   * Integer 0/1 flag columns -> BOOLEAN (SQLite 0/1 converts to false/true).
--   * created_at / updated_at: SQLite TEXT storing ISO-8601 strings
--             -> TIMESTAMPTZ with DEFAULT now() (SQLite default was datetime('now')).
--   * Date-only TEXT columns (registration_date, effective_from, *_applicable_from)
--             -> DATE (app stores ISO date strings).
--   * composition_tax_rate: REAL holding a tax-rate percentage -> NUMERIC(18,4).
--             Rates are NOT mapped to floating point on purpose (precision-critical).
--   * state_id: declared TEXT in source despite the _id suffix -> kept as TEXT (not a numeric FK).
-- ============================================================================

CREATE TABLE gst_registrations (
    gst_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                   BIGINT      NOT NULL,                         -- FK -> companies.company_id (explicit in source, ON DELETE CASCADE)
    registration_type            TEXT        DEFAULT 'Regular',
    registration_status          TEXT        DEFAULT 'Active',
    assessee_of_other_territory  BOOLEAN     NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 (default 0)
    periodicity_of_gstr1         TEXT        DEFAULT 'Monthly',
    gstin                        TEXT,                                         -- 15-char GSTIN, app-validated when present
    gst_username                 TEXT,
    mode_of_filing               TEXT        DEFAULT 'Online',
    e_invoice_details            TEXT,
    e_invoice_application        BOOLEAN     NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 (default 0)
    e_way_bill_applicable        BOOLEAN     NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 (default 0)
    e_way_bill_applicable_from   DATE,                                         -- ISO date string in source
    applicable_for_intrastat     BOOLEAN     NOT NULL DEFAULT false,           -- SQLite INTEGER 0/1 (default 0)
    legal_name                   TEXT,
    trade_name                   TEXT,
    state_id                     TEXT,                                         -- TEXT in source despite _id suffix; NOT a numeric FK
    registration_date            DATE,                                         -- ISO date string in source
    effective_from               DATE,                                         -- ISO date string in source
    address_type                 TEXT        DEFAULT 'Primary',
    goods_dispatched_from        TEXT        DEFAULT 'Primary',
    e_invoice_applicable_from    DATE,                                         -- ISO date string in source
    e_invoice_bill_from_place    TEXT,
    composition_tax_rate         NUMERIC(18,4),                               -- MONEY/RATE: precision-critical, NOT floating point
    composition_tax_calc_basis   TEXT,
    is_active                    BOOLEAN     NOT NULL DEFAULT true,            -- SQLite INTEGER 0/1 (default 1); set false on soft-delete
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),           -- SQLite default datetime('now'); stored as ISO string
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now()            -- SQLite default datetime('now'); refreshed on update
);

-- Index on FK column to support getAll(company_id) lookups.
CREATE INDEX idx_gst_registrations_company_id ON gst_registrations (company_id);

-- The service treats (company_id, gstin) as logically unique among active rows.
-- This is enforced in application code, not in the SQLite schema. Optional partial
-- unique index to enforce it in Postgres (only for active registrations):
-- CREATE UNIQUE INDEX uq_gst_registrations_company_gstin_active
--   ON gst_registrations (company_id, gstin) WHERE is_active = true;

-- ============================================================================
-- Foreign keys (grouped at bottom for cross-module load ordering)
-- ============================================================================

-- EXPLICIT in source: gstRegistration.js declares
--   REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE gst_registrations
    ADD CONSTRAINT fk_gst_registrations_company
    FOREIGN KEY (company_id)
    REFERENCES companies (company_id)
    ON DELETE CASCADE;
