-- ============================================================================
-- Module: ledger
-- Postgres DDL translated from SQLite source (server/ledger/ledger.js).
-- Tables: ledgers, ledger_bank_details, ledger_statutory_details
--
-- Conventions:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
--   * SQLite TEXT datetime defaults (datetime('now')) -> TIMESTAMPTZ DEFAULT now().
--     (App stores ISO-8601 strings in SQLite; modelled as TIMESTAMPTZ here.)
--   * 0/1 flag INTEGER columns -> BOOLEAN. App code coerces values to 0/1;
--     in Postgres treat 0=false, 1=true. DEFAULT 0/1 -> false/true.
--   * MONEY columns -> NUMERIC(18,2). NEVER floating point for money.
--   * RATE / percentage columns -> NUMERIC(18,4).
--   * FK constraints are emitted as ALTER TABLE at the bottom so cross-module
--     table-creation order does not matter. Columns marked [explicit FK in source]
--     had REFERENCES in SQLite; others are [inferred] from *_id naming.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Table: ledgers
-- ----------------------------------------------------------------------------
CREATE TABLE ledgers (
    ledger_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                 BIGINT  NOT NULL,                                  -- FK -> companies (explicit in source, ON DELETE CASCADE)
    group_id                   BIGINT,                                            -- FK -> groups (explicit in source)
    name                       TEXT    NOT NULL,
    alias                      TEXT,
    ledger_type                TEXT    DEFAULT 'General',
    nature                     TEXT,
    opening_balance            NUMERIC(18,2) DEFAULT 0,    -- MONEY: never floating point
    closing_balance            NUMERIC(18,2) DEFAULT 0,    -- MONEY: never floating point
    is_bill_wise               BOOLEAN DEFAULT false,      -- SQLite INTEGER 0/1
    maintain_inventory_values  BOOLEAN DEFAULT false,      -- SQLite INTEGER 0/1
    mailing_name               TEXT,
    address1                   TEXT,
    address2                   TEXT,
    city                       TEXT,
    state                      TEXT,
    country                    TEXT,
    pincode                    TEXT,
    phone                      TEXT,
    email                      TEXT,
    gstin                      TEXT,
    pan                        TEXT,
    registration_type          TEXT    DEFAULT 'Unregistered',
    allow_cost_centres         BOOLEAN DEFAULT false,      -- SQLite INTEGER 0/1
    default_credit_period      INTEGER DEFAULT 0,          -- day count (kept as integer)
    check_credit_days          INTEGER DEFAULT 0,          -- NOTE: app coerces input to 0/1 on write; column is integer
    invoice_rounding           BOOLEAN DEFAULT false,      -- SQLite INTEGER 0/1
    rounding_method            TEXT,
    rounding_limit             NUMERIC(18,4) DEFAULT 0,    -- rounding threshold (rate-like)
    additional_gst_details     BOOLEAN DEFAULT false,      -- SQLite INTEGER 0/1
    service_tax_details        BOOLEAN DEFAULT false,      -- SQLite INTEGER 0/1
    include_assessable_value   TEXT    DEFAULT 'Not Applicable',
    method_of_calculation      TEXT    DEFAULT 'Based on Value',
    other_statutory_details    BOOLEAN DEFAULT false,      -- SQLite INTEGER 0/1
    is_active                  BOOLEAN DEFAULT true,       -- SQLite INTEGER DEFAULT 1
    is_predefined              BOOLEAN DEFAULT false,      -- SQLite INTEGER DEFAULT 0
    created_at                 TIMESTAMPTZ DEFAULT now(),  -- app stores ISO-8601 string
    updated_at                 TIMESTAMPTZ DEFAULT now()   -- app stores ISO-8601 string
);


-- ----------------------------------------------------------------------------
-- Table: ledger_bank_details
-- (transaction_type, cross_using, company_bank added via ALTER in source)
-- ----------------------------------------------------------------------------
CREATE TABLE ledger_bank_details (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id                     BIGINT NOT NULL,         -- FK -> ledgers (explicit in source, ON DELETE CASCADE)
    account_holder_name           TEXT,
    account_number                TEXT,
    ifsc_code                     TEXT,
    swift_code                    TEXT,
    bank_name                     TEXT,
    branch_name                   TEXT,
    bank_configuration            TEXT,
    cheque_book_start_no          TEXT,
    cheque_book_end_no            TEXT,
    enable_cheque_printing        BOOLEAN DEFAULT false,   -- SQLite INTEGER 0/1
    cheque_printing_configuration TEXT,
    od_limit                      NUMERIC(18,2) DEFAULT 0, -- MONEY (overdraft limit): never floating point
    transaction_type              TEXT,
    cross_using                   TEXT DEFAULT 'A/c Payee',
    company_bank                  TEXT
);


-- ----------------------------------------------------------------------------
-- Table: ledger_statutory_details
-- (include_in_assessable_value_calculation, appropriate_to,
--  method_of_calculation added via ALTER in source)
-- ----------------------------------------------------------------------------
CREATE TABLE ledger_statutory_details (
    id                                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id                               BIGINT NOT NULL,  -- FK -> ledgers (explicit in source, ON DELETE CASCADE)
    gst_applicability                       TEXT DEFAULT 'Not Applicable',
    hsn_sac_code                            TEXT,
    hsn_sac_description                     TEXT,
    gst_rate                                NUMERIC(18,4) DEFAULT 0,  -- tax rate %
    cgst_rate                               NUMERIC(18,4) DEFAULT 0,  -- tax rate %
    sgst_rate                               NUMERIC(18,4) DEFAULT 0,  -- tax rate %
    igst_rate                               NUMERIC(18,4) DEFAULT 0,  -- tax rate %
    type_of_duty_tax                        TEXT,
    percentage_of_calculation               NUMERIC(18,4) DEFAULT 0,  -- rate %
    statutory_details                       TEXT,
    include_in_assessable_value_calculation TEXT DEFAULT 'Not Applicable',
    appropriate_to                          TEXT DEFAULT 'Goods',
    method_of_calculation                   TEXT DEFAULT 'Based on Quantity'
);


-- ----------------------------------------------------------------------------
-- Indexes on FK columns
-- ----------------------------------------------------------------------------
CREATE INDEX idx_ledgers_company_id                  ON ledgers (company_id);
CREATE INDEX idx_ledgers_group_id                    ON ledgers (group_id);
CREATE INDEX idx_ledger_bank_details_ledger_id       ON ledger_bank_details (ledger_id);
CREATE INDEX idx_ledger_statutory_details_ledger_id  ON ledger_statutory_details (ledger_id);

-- Supports the duplicate-name check: WHERE company_id = ? AND LOWER(name) = LOWER(?) AND is_active = 1
CREATE INDEX idx_ledgers_company_active_name ON ledgers (company_id, lower(name)) WHERE is_active = true;


-- ============================================================================
-- Foreign key constraints (grouped to avoid cross-module ordering issues)
-- ============================================================================

-- [explicit FK in source] ledgers.company_id -> companies.company_id (ON DELETE CASCADE)
-- companies table is owned by another module; constraint added here for completeness.
ALTER TABLE ledgers
    ADD CONSTRAINT fk_ledgers_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- [explicit FK in source] ledgers.group_id -> groups.group_id
-- groups table is owned by another module.
ALTER TABLE ledgers
    ADD CONSTRAINT fk_ledgers_group
    FOREIGN KEY (group_id) REFERENCES groups (group_id);

-- [explicit FK in source] ledger_bank_details.ledger_id -> ledgers.ledger_id (ON DELETE CASCADE)
ALTER TABLE ledger_bank_details
    ADD CONSTRAINT fk_ledger_bank_details_ledger
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id) ON DELETE CASCADE;

-- [explicit FK in source] ledger_statutory_details.ledger_id -> ledgers.ledger_id (ON DELETE CASCADE)
ALTER TABLE ledger_statutory_details
    ADD CONSTRAINT fk_ledger_statutory_details_ledger
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id) ON DELETE CASCADE;
