-- =============================================================================
-- Postgres DDL for the "payHead" module
-- Source: server/payHead/payHead.js (SQLite schema init)
-- Tables: pay_heads, pay_head_slab_lines, pay_head_formula_lines
--
-- Conventions applied (SQLite -> Postgres):
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * created_at / updated_at (ISO-8601 TEXT, default datetime('now')) -> TIMESTAMPTZ DEFAULT now()
--   * date-only TEXT (effective_from) -> DATE
--   * INTEGER 0/1 flags (affects_net_salary, use_for_gratuity, set_alter_income_tax,
--     is_active, is_predefined) -> BOOLEAN (0 -> false, 1 -> true)
--   * Monetary / quantity REAL columns -> NUMERIC. percentage_or_amount, value,
--     amount_gt, amount_up_to, rounding_limit hold rates/amounts; mapped to
--     NUMERIC(18,4). NEVER use floating point for money — see comments below.
--   * Foreign keys: SQLite source DOES declare explicit REFERENCES here; those are
--     marked "EXPLICIT in source". No inferred-only FKs in this module.
-- =============================================================================

-- ----------------------------------------------------------------------------
-- Table: pay_heads
-- ----------------------------------------------------------------------------
CREATE TABLE pay_heads (
    pay_head_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT        NOT NULL,
    name                   TEXT          NOT NULL,
    alias                  TEXT,
    pay_head_type          TEXT          DEFAULT 'Earnings for Employees',
    income_type            TEXT          DEFAULT 'Fixed',
    under_group            TEXT,
    affects_net_salary     BOOLEAN       DEFAULT TRUE,   -- SQLite INTEGER 0/1 (default 1) -> BOOLEAN
    payslip_display_name   TEXT,
    use_for_gratuity       BOOLEAN       DEFAULT FALSE,  -- SQLite INTEGER 0/1 (default 0) -> BOOLEAN
    set_alter_income_tax   BOOLEAN       DEFAULT FALSE,  -- SQLite INTEGER 0/1 (default 0) -> BOOLEAN
    calculation_type       TEXT          DEFAULT 'As User Defined Value',
    calculation_period     TEXT          DEFAULT 'Months',
    rounding_method        TEXT          DEFAULT 'Not Applicable',
    rounding_limit         NUMERIC(18,4) DEFAULT 0,      -- MONEY/quantity: never float
    statutory_component    TEXT,
    percentage_or_amount   NUMERIC(18,4) DEFAULT 0,      -- MONEY/rate (percent or flat amount): never float
    is_active              BOOLEAN       DEFAULT TRUE,   -- SQLite INTEGER 0/1 (default 1) -> BOOLEAN; soft-delete flag
    is_predefined          BOOLEAN       DEFAULT FALSE,  -- SQLite INTEGER 0/1 (default 0) -> BOOLEAN
    created_at             TIMESTAMPTZ   DEFAULT now(),  -- app stores ISO-8601 strings (datetime('now'))
    updated_at             TIMESTAMPTZ   DEFAULT now()   -- app stores ISO-8601 strings (datetime('now'))
);

-- ----------------------------------------------------------------------------
-- Table: pay_head_slab_lines
-- ----------------------------------------------------------------------------
CREATE TABLE pay_head_slab_lines (
    slab_line_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_head_id     BIGINT        NOT NULL,
    effective_from  DATE,                                -- date-only TEXT -> DATE
    amount_gt       NUMERIC(18,4) DEFAULT 0,             -- MONEY/quantity bound: never float
    amount_up_to    NUMERIC(18,4) DEFAULT 0,             -- MONEY/quantity bound: never float
    slab_type       TEXT,
    value           NUMERIC(18,4) DEFAULT 0,             -- MONEY/rate (slab value): never float
    created_at      TIMESTAMPTZ   DEFAULT now()          -- app stores ISO-8601 strings
);

-- ----------------------------------------------------------------------------
-- Table: pay_head_formula_lines
-- ----------------------------------------------------------------------------
CREATE TABLE pay_head_formula_lines (
    formula_line_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_head_id      BIGINT      NOT NULL,
    sequence         INTEGER     DEFAULT 0,
    function         TEXT,
    pay_head_id_ref  BIGINT,                             -- nullable self-reference to a pay head operand
    operator         TEXT,
    created_at       TIMESTAMPTZ DEFAULT now()           -- app stores ISO-8601 strings
);

-- ----------------------------------------------------------------------------
-- Indexes on foreign-key columns
-- ----------------------------------------------------------------------------
CREATE INDEX idx_pay_heads_company_id            ON pay_heads (company_id);
CREATE INDEX idx_ph_slab_lines_pay_head_id       ON pay_head_slab_lines (pay_head_id);
CREATE INDEX idx_ph_formula_lines_pay_head_id    ON pay_head_formula_lines (pay_head_id);
CREATE INDEX idx_ph_formula_lines_pay_head_ref   ON pay_head_formula_lines (pay_head_id_ref);

-- Recommended uniqueness: one active pay head name per company.
-- The service enforces case-insensitive uniqueness on (company_id, LOWER(name))
-- among active rows only. Modeled as a partial unique index.
CREATE UNIQUE INDEX uq_pay_heads_company_lower_name_active
    ON pay_heads (company_id, lower(name))
    WHERE is_active = TRUE;

-- ----------------------------------------------------------------------------
-- Foreign key constraints (grouped at bottom for cross-module load ordering)
-- ----------------------------------------------------------------------------

-- EXPLICIT in source: pay_heads.company_id REFERENCES companies(company_id) ON DELETE CASCADE
-- (companies table is owned by the "company" module.)
ALTER TABLE pay_heads
    ADD CONSTRAINT fk_pay_heads_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: pay_head_slab_lines.pay_head_id REFERENCES pay_heads(pay_head_id) ON DELETE CASCADE
ALTER TABLE pay_head_slab_lines
    ADD CONSTRAINT fk_ph_slab_lines_pay_head
    FOREIGN KEY (pay_head_id) REFERENCES pay_heads (pay_head_id) ON DELETE CASCADE;

-- EXPLICIT in source: pay_head_formula_lines.pay_head_id REFERENCES pay_heads(pay_head_id) ON DELETE CASCADE
ALTER TABLE pay_head_formula_lines
    ADD CONSTRAINT fk_ph_formula_lines_pay_head
    FOREIGN KEY (pay_head_id) REFERENCES pay_heads (pay_head_id) ON DELETE CASCADE;

-- EXPLICIT in source: pay_head_formula_lines.pay_head_id_ref REFERENCES pay_heads(pay_head_id) (no ON DELETE clause)
-- Nullable operand reference. Using ON DELETE SET NULL so removing a referenced
-- pay head does not orphan formula lines.
ALTER TABLE pay_head_formula_lines
    ADD CONSTRAINT fk_ph_formula_lines_pay_head_ref
    FOREIGN KEY (pay_head_id_ref) REFERENCES pay_heads (pay_head_id) ON DELETE SET NULL;
