-- ============================================================================
-- Module: payrollUnit
-- Source: server/payrollUnit/payrollUnit.js  (table: payroll_units)
-- Target: PostgreSQL
--
-- SQLite -> Postgres translation notes:
--   * payroll_unit_id: INTEGER PRIMARY KEY AUTOINCREMENT
--       -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   * created_at / updated_at: SQLite stores ISO-8601 strings via datetime('now')
--       -> TIMESTAMPTZ DEFAULT now()
--   * is_active / is_predefined: INTEGER 0/1 used as boolean
--       -> BOOLEAN (0 -> false, 1 -> true). DEFAULTs translated accordingly.
--   * conversion: REAL. Interpreted as a unit-conversion FACTOR (a rate/quantity),
--       so mapped to NUMERIC(18,4) to avoid floating-point error. NOT money.
--   * decimal_places: small integer count -> INTEGER.
-- ============================================================================

CREATE TABLE payroll_units (
    payroll_unit_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT          NOT NULL,
    name             TEXT            NOT NULL,
    symbol           TEXT,
    formal_name      TEXT,
    unit_type        TEXT            NOT NULL DEFAULT 'Simple',
    decimal_places   INTEGER         NOT NULL DEFAULT 0,
    first_unit       TEXT,
    -- conversion: NUMERIC(18,4) -- unit conversion factor (quantity/rate), never float
    conversion       NUMERIC(18,4),
    second_unit      TEXT,
    -- is_active: BOOLEAN <- SQLite INTEGER 0/1 (0=>false, 1=>true)
    is_active        BOOLEAN         NOT NULL DEFAULT true,
    -- is_predefined: BOOLEAN <- SQLite INTEGER 0/1 (0=>false, 1=>true)
    is_predefined    BOOLEAN         NOT NULL DEFAULT false,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- Indexes on FK columns -------------------------------------------------------
CREATE INDEX idx_payroll_units_company_id ON payroll_units (company_id);

-- Helpful uniqueness guard (matches the app's case-insensitive duplicate check
-- among active units per company). Optional but recommended.
CREATE UNIQUE INDEX uq_payroll_units_company_name_active
    ON payroll_units (company_id, LOWER(name))
    WHERE is_active = true;

-- ============================================================================
-- Foreign keys (grouped at bottom so cross-module load order does not matter)
-- ============================================================================

-- EXPLICIT in source: SQLite declared
--   company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE payroll_units
    ADD CONSTRAINT fk_payroll_units_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;
