-- =====================================================================
-- Module: physicalStock
-- Source: server/physicalStock/physicalStock.js (SQLite schema init)
-- Target: PostgreSQL
--
-- Tables:
--   physical_stock_entries       (stocktake voucher header)
--   physical_stock_entry_lines   (per-item count lines)
--
-- Notes:
--   * SQLite stores datetimes as ISO strings (datetime('now')) -> TIMESTAMPTZ
--     with DEFAULT now() here.
--   * date-only columns (voucher_date, manufacturing_date, expiry_date) -> DATE.
--   * 0/1 integer flags (is_optional, is_post_dated) -> BOOLEAN
--     (SQLite 0->false, 1->true).
--   * quantity/rate/amount are MONEY/quantity values -> NUMERIC, NOT floating point.
--   * FK constraints are grouped at the bottom as ALTER TABLE statements so
--     cross-module table ordering does not matter.
-- =====================================================================

CREATE TABLE physical_stock_entries (
    physical_stock_entry_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               BIGINT      NOT NULL,
    voucher_no               TEXT,
    voucher_date             DATE        NOT NULL,                 -- date-only TEXT -> DATE
    reference_no             TEXT,
    narration                TEXT,
    is_optional              BOOLEAN     NOT NULL DEFAULT false,   -- SQLite INTEGER 0/1 -> BOOLEAN
    is_post_dated            BOOLEAN     NOT NULL DEFAULT false,   -- SQLite INTEGER 0/1 -> BOOLEAN
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),   -- ISO string -> TIMESTAMPTZ
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()    -- ISO string -> TIMESTAMPTZ
);

CREATE TABLE physical_stock_entry_lines (
    line_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    physical_stock_entry_id  BIGINT      NOT NULL,
    stock_item_id            BIGINT,
    godown_id                BIGINT,
    batch_no                 TEXT,
    lot_no                   TEXT,
    manufacturing_date       DATE,                                 -- date-only TEXT -> DATE
    expiry_date              DATE,                                 -- date-only TEXT -> DATE
    quantity                 NUMERIC(18,4) NOT NULL DEFAULT 0,     -- MONEY/qty: NUMERIC, never float
    rate                     NUMERIC(18,4) NOT NULL DEFAULT 0,     -- unit rate: NUMERIC, never float
    amount                   NUMERIC(18,2) NOT NULL DEFAULT 0,     -- currency amount (qty*rate): NUMERIC, never float
    line_order               INTEGER       NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT now(), -- ISO string -> TIMESTAMPTZ
    updated_at               TIMESTAMPTZ   NOT NULL DEFAULT now()  -- ISO string -> TIMESTAMPTZ
);

-- ---------------------------------------------------------------------
-- Indexes on FK columns
-- ---------------------------------------------------------------------
CREATE INDEX idx_pse_company_id          ON physical_stock_entries (company_id);
CREATE INDEX idx_psel_entry_id           ON physical_stock_entry_lines (physical_stock_entry_id);
CREATE INDEX idx_psel_stock_item_id      ON physical_stock_entry_lines (stock_item_id);
CREATE INDEX idx_psel_godown_id          ON physical_stock_entry_lines (godown_id);

-- ---------------------------------------------------------------------
-- Foreign keys
-- All FKs below are EXPLICIT in the SQLite source (REFERENCES ... clauses),
-- not merely inferred from *_id naming.
-- ---------------------------------------------------------------------

-- EXPLICIT in source: company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE physical_stock_entries
    ADD CONSTRAINT fk_pse_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: physical_stock_entry_id REFERENCES physical_stock_entries(...) ON DELETE CASCADE
ALTER TABLE physical_stock_entry_lines
    ADD CONSTRAINT fk_psel_entry
    FOREIGN KEY (physical_stock_entry_id) REFERENCES physical_stock_entries (physical_stock_entry_id) ON DELETE CASCADE;

-- EXPLICIT in source: stock_item_id REFERENCES stock_items(item_id)  [no ON DELETE -> RESTRICT]
ALTER TABLE physical_stock_entry_lines
    ADD CONSTRAINT fk_psel_stock_item
    FOREIGN KEY (stock_item_id) REFERENCES stock_items (item_id);

-- EXPLICIT in source: godown_id REFERENCES godowns(godown_id)  [no ON DELETE -> RESTRICT]
ALTER TABLE physical_stock_entry_lines
    ADD CONSTRAINT fk_psel_godown
    FOREIGN KEY (godown_id) REFERENCES godowns (godown_id);

-- ---------------------------------------------------------------------
-- Column comments (money / conversion documentation)
-- ---------------------------------------------------------------------
COMMENT ON COLUMN physical_stock_entry_lines.quantity IS 'Counted quantity. NUMERIC(18,4); never floating point.';
COMMENT ON COLUMN physical_stock_entry_lines.rate     IS 'Unit rate. NUMERIC(18,4); never floating point.';
COMMENT ON COLUMN physical_stock_entry_lines.amount   IS 'Currency amount = quantity * rate, computed server-side. NUMERIC(18,2); never floating point.';
COMMENT ON COLUMN physical_stock_entries.is_optional   IS 'SQLite 0/1 flag mapped to BOOLEAN (0->false, 1->true).';
COMMENT ON COLUMN physical_stock_entries.is_post_dated IS 'SQLite 0/1 flag mapped to BOOLEAN (0->false, 1->true).';
