-- ============================================================================
-- Module: priceLevels
-- Source: server/priceLevels/priceLevel.js  (SQLite table: price_levels)
-- Target: PostgreSQL
--
-- SQLite -> Postgres translation notes:
--   * price_level_id  INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT IDENTITY PK
--   * is_active       INTEGER 0/1 flag                  -> BOOLEAN (0->false, 1->true)
--   * created_at / updated_at  ISO-8601 TEXT (datetime('now')) -> TIMESTAMPTZ
--                              (app stores ISO strings; default now())
--   * name            TEXT NOT NULL DEFAULT ''          -> TEXT NOT NULL DEFAULT ''
--   * The source has an EXPLICIT FK on company_id (REFERENCES companies(...)
--     ON DELETE CASCADE). It is reproduced below (see ALTER TABLE section).
-- ============================================================================

CREATE TABLE price_levels (
    price_level_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT      NOT NULL,
    level_index     INTEGER     NOT NULL,
    name            TEXT        NOT NULL DEFAULT '',
    is_active       BOOLEAN     DEFAULT TRUE,   -- SQLite INTEGER 0/1 (default 1) -> BOOLEAN
    created_at      TIMESTAMPTZ DEFAULT now(),  -- SQLite TEXT datetime('now') ISO-8601 string
    updated_at      TIMESTAMPTZ DEFAULT now(),  -- SQLite TEXT datetime('now') ISO-8601 string

    -- One price level per ordinal position per company.
    CONSTRAINT uq_price_levels_company_level UNIQUE (company_id, level_index)
);

-- Index on the FK column for join/lookup performance.
CREATE INDEX idx_price_levels_company_id ON price_levels (company_id);

-- ============================================================================
-- Foreign keys (grouped at bottom so cross-module load ordering is irrelevant).
-- ============================================================================

-- EXPLICIT FK in source (priceLevel.js: REFERENCES companies(company_id) ON DELETE CASCADE).
ALTER TABLE price_levels
    ADD CONSTRAINT fk_price_levels_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;
