-- ============================================================================
-- Module: priceList
-- Source: server/priceList/priceList.js  (SQLite schema init)
-- Target: PostgreSQL
--
-- Tables:
--   price_lists        (price list headers)
--   price_list_lines   (rate/slab lines belonging to a header)
--
-- Conventions applied:
--   * SQLite INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT
--     AS IDENTITY PRIMARY KEY.
--   * created_at / updated_at store ISO-8601 strings via datetime('now') ->
--     TIMESTAMPTZ DEFAULT now().
--   * is_active is an INTEGER used as a 0/1 boolean -> BOOLEAN
--     (0 -> false, 1 -> true). DEFAULT 1 -> DEFAULT true.
--   * Quantity / rate / percentage REAL columns hold accounting numbers and
--     are mapped to NUMERIC (NEVER floating point) to avoid rounding error:
--       qty_from, qty_less_than, rate, disc_percent -> NUMERIC(18,4).
--   * applicable_from is a date stored as TEXT -> DATE.
--   * Foreign keys are EXPLICIT in the SQLite source (REFERENCES clauses);
--     they are reproduced verbatim below (NOT inferred). Cross-module targets
--     (companies, stock_items) live in other modules; FK ALTERs are grouped at
--     the bottom so load order across modules does not matter.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Table: price_lists
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS price_lists (
    price_list_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT       NOT NULL,                       -- FK -> companies.company_id (explicit in source)
    stock_group     TEXT         NOT NULL DEFAULT 'All Items',
    price_level     TEXT         NOT NULL,
    applicable_from DATE         NOT NULL,                       -- TEXT date in SQLite; service stores a date string
    is_active       BOOLEAN      NOT NULL DEFAULT true,          -- SQLite INTEGER 0/1; DEFAULT 1 -> true; soft-delete flag
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),         -- SQLite datetime('now') ISO string
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()          -- SQLite datetime('now') ISO string
);

COMMENT ON COLUMN price_lists.is_active   IS 'Soft-delete flag. SQLite INTEGER 0/1 mapped to BOOLEAN (0=false, 1=true). delete sets false.';
COMMENT ON COLUMN price_lists.company_id  IS 'Explicit FK in SQLite source: REFERENCES companies(company_id) ON DELETE CASCADE.';


-- ----------------------------------------------------------------------------
-- Table: price_list_lines
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS price_list_lines (
    line_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_list_id   BIGINT         NOT NULL,                     -- FK -> price_lists.price_list_id (explicit in source)
    item_id         BIGINT,                                      -- FK -> stock_items.item_id (explicit in source); nullable
    particulars     TEXT           NOT NULL,
    qty_from        NUMERIC(18,4)  NOT NULL DEFAULT 0,           -- quantity; NUMERIC, never float
    qty_less_than   NUMERIC(18,4)  NOT NULL DEFAULT 0,           -- quantity; NUMERIC, never float
    rate            NUMERIC(18,4)  NOT NULL DEFAULT 0,           -- money/rate; NUMERIC, never float
    disc_percent    NUMERIC(18,4)  NOT NULL DEFAULT 0,           -- percentage; NUMERIC, never float
    sort_order      INTEGER        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),       -- SQLite datetime('now') ISO string
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now()        -- SQLite datetime('now') ISO string
);

COMMENT ON COLUMN price_list_lines.qty_from      IS 'Quantity slab lower bound. NUMERIC to preserve accounting precision (never floating point).';
COMMENT ON COLUMN price_list_lines.qty_less_than IS 'Quantity slab upper bound. NUMERIC to preserve accounting precision (never floating point).';
COMMENT ON COLUMN price_list_lines.rate          IS 'Rate / unit price. NUMERIC(18,4) to preserve money precision (never floating point).';
COMMENT ON COLUMN price_list_lines.disc_percent  IS 'Discount percentage. NUMERIC to preserve precision (never floating point).';
COMMENT ON COLUMN price_list_lines.price_list_id IS 'Explicit FK in SQLite source: REFERENCES price_lists(price_list_id) ON DELETE CASCADE.';
COMMENT ON COLUMN price_list_lines.item_id       IS 'Explicit FK in SQLite source: REFERENCES stock_items(item_id) ON DELETE SET NULL.';


-- ----------------------------------------------------------------------------
-- Indexes (on FK columns)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_price_lists_company_id        ON price_lists (company_id);
CREATE INDEX IF NOT EXISTS idx_price_list_lines_price_list_id ON price_list_lines (price_list_id);
CREATE INDEX IF NOT EXISTS idx_price_list_lines_item_id       ON price_list_lines (item_id);


-- ----------------------------------------------------------------------------
-- Foreign keys (grouped; run after all module tables exist)
-- All FKs below are EXPLICIT in the SQLite source (REFERENCES clauses),
-- not inferred.
-- ----------------------------------------------------------------------------

-- price_lists.company_id -> companies.company_id  (cross-module: company)
ALTER TABLE price_lists
    ADD CONSTRAINT fk_price_lists_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;

-- price_list_lines.price_list_id -> price_lists.price_list_id  (intra-module)
ALTER TABLE price_list_lines
    ADD CONSTRAINT fk_price_list_lines_price_list
    FOREIGN KEY (price_list_id) REFERENCES price_lists (price_list_id)
    ON DELETE CASCADE;

-- price_list_lines.item_id -> stock_items.item_id  (cross-module: stockItems)
ALTER TABLE price_list_lines
    ADD CONSTRAINT fk_price_list_lines_item
    FOREIGN KEY (item_id) REFERENCES stock_items (item_id)
    ON DELETE SET NULL;
