-- ============================================================================
-- Module: profitLossReport  (Postgres DDL)
-- Source: server/profitLossReport/profitLossReport.js (SQLite init)
-- ----------------------------------------------------------------------------
-- Tables: profit_loss_reports, profit_loss_views
--
-- Type-mapping conventions applied:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * datetime TEXT (datetime('now')) -> TIMESTAMPTZ DEFAULT now()  (app stores ISO strings)
--   * date-only TEXT (report_date/period_*) -> DATE
--   * INTEGER 0/1 boolean flags -> BOOLEAN (0->false, 1->true)
--   * REAL money columns -> NUMERIC(18,2)  (MONEY — never floating point)
-- FK constraints are grouped at the bottom as ALTER TABLE statements.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: profit_loss_reports  (saved P&L report header)
-- ----------------------------------------------------------------------------
CREATE TABLE profit_loss_reports (
    report_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                    BIGINT NOT NULL,
    report_name                   TEXT DEFAULT 'Profit & Loss A/c',
    report_date                   DATE,                       -- date-only TEXT in SQLite
    period_start                  DATE,                       -- date-only TEXT in SQLite
    period_end                    DATE,                       -- date-only TEXT in SQLite
    format_type                   TEXT DEFAULT 'Vertical',
    compare_with_previous_period  BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    comparison_period_start       DATE,                       -- date-only TEXT in SQLite
    comparison_period_end         DATE,                       -- date-only TEXT in SQLite
    basis_of_values               TEXT DEFAULT 'Default',
    change_view                   TEXT,
    exception_report_enabled      BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    saved_view_name               TEXT,
    filter_enabled                BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    filter_details                TEXT,                       -- free-form / serialized filter payload
    show_detail_view              BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_condensed_view           BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_percentage_of_sales      BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_auto_column              BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_profit                   BOOLEAN NOT NULL DEFAULT true,   -- SQLite INTEGER 0/1, default 1
    show_optional                 BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_post_dated               BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_stat_adjustment          BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    show_schedule_vi              BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),  -- ISO-8601 string in app
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now()   -- ISO-8601 string in app
);

-- ----------------------------------------------------------------------------
-- Table: profit_loss_views  (one section/group line of a saved report)
-- ----------------------------------------------------------------------------
CREATE TABLE profit_loss_views (
    view_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id                 BIGINT NOT NULL,
    company_id                BIGINT NOT NULL,
    report_date               DATE,                           -- date-only TEXT in SQLite
    section                   TEXT DEFAULT 'Income',          -- Income|Expense|GrossProfit|NetProfit
    group_name                TEXT,
    parent_group_name         TEXT,
    opening_balance           NUMERIC(18,2) NOT NULL DEFAULT 0,  -- MONEY — never float
    current_period_amount     NUMERIC(18,2) NOT NULL DEFAULT 0,  -- MONEY — never float
    closing_balance           NUMERIC(18,2) NOT NULL DEFAULT 0,  -- MONEY — never float
    display_order             INTEGER NOT NULL DEFAULT 0,
    is_total_row              BOOLEAN NOT NULL DEFAULT false,    -- SQLite INTEGER 0/1
    is_gross_profit_row       BOOLEAN NOT NULL DEFAULT false,    -- SQLite INTEGER 0/1
    is_drill_down_available   BOOLEAN NOT NULL DEFAULT true,     -- SQLite INTEGER 0/1, default 1
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now() -- ISO-8601 string in app
);

-- ----------------------------------------------------------------------------
-- Indexes on FK columns
-- ----------------------------------------------------------------------------
CREATE INDEX idx_profit_loss_reports_company_id ON profit_loss_reports (company_id);
CREATE INDEX idx_profit_loss_views_report_id    ON profit_loss_views (report_id);
CREATE INDEX idx_profit_loss_views_company_id   ON profit_loss_views (company_id);

-- ============================================================================
-- Foreign keys (grouped here so cross-module table ordering is not a problem)
-- ----------------------------------------------------------------------------
-- All three FKs below are EXPLICIT in the SQLite source (REFERENCES ... ON DELETE CASCADE).
-- `companies` is owned by another module; ensure it is created before applying these.
-- ============================================================================

-- EXPLICIT in source: profit_loss_reports.company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE profit_loss_reports
    ADD CONSTRAINT fk_profit_loss_reports_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: profit_loss_views.report_id REFERENCES profit_loss_reports(report_id) ON DELETE CASCADE
ALTER TABLE profit_loss_views
    ADD CONSTRAINT fk_profit_loss_views_report
    FOREIGN KEY (report_id) REFERENCES profit_loss_reports (report_id) ON DELETE CASCADE;

-- EXPLICIT in source: profit_loss_views.company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE profit_loss_views
    ADD CONSTRAINT fk_profit_loss_views_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
