-- =============================================================================
-- Module: salaryStructure
-- Source: server/salaryStructure/salaryStructure.js  (SQLite schema init)
-- Target: PostgreSQL
--
-- SQLite -> Postgres translation notes:
--   * structure_id INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT IDENTITY PK.
--   * effective_from is a date-only TEXT -> DATE.
--   * amount holds MONEY -> NUMERIC(18,2). Never use floating point for money.
--   * is_active INTEGER 0/1 -> BOOLEAN (0 -> false, 1 -> true); default 1 -> true.
--   * created_at / updated_at store datetime('now') strings -> TIMESTAMPTZ
--     with DEFAULT now().
--   * All three FKs (company_id, employee_id, pay_head_id) are EXPLICIT in the
--     SQLite source (REFERENCES ... ON DELETE CASCADE); they are reproduced
--     faithfully below (not inferred).
-- =============================================================================

CREATE TABLE IF NOT EXISTS salary_structures (
    structure_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        BIGINT          NOT NULL,
    employee_id       BIGINT          NOT NULL,
    effective_from    DATE            NOT NULL,                 -- date-only TEXT in SQLite
    pay_head_id       BIGINT          NOT NULL,
    amount            NUMERIC(18,2)   NOT NULL DEFAULT 0,       -- MONEY: never floating point
    calculation_mode  TEXT            NOT NULL DEFAULT 'Flat Rate',
    is_active         BOOLEAN         NOT NULL DEFAULT TRUE,    -- SQLite INTEGER 0/1 (default 1)
    created_at        TIMESTAMPTZ     NOT NULL DEFAULT now(),   -- SQLite datetime('now') ISO string
    updated_at        TIMESTAMPTZ     NOT NULL DEFAULT now()    -- SQLite datetime('now') ISO string
);

-- Indexes on FK columns (recommended; absent in SQLite source).
CREATE INDEX IF NOT EXISTS idx_salary_structures_company_id  ON salary_structures (company_id);
CREATE INDEX IF NOT EXISTS idx_salary_structures_employee_id ON salary_structures (employee_id);
CREATE INDEX IF NOT EXISTS idx_salary_structures_pay_head_id ON salary_structures (pay_head_id);

-- Application-level uniqueness (NOT enforced by a DB constraint in the source).
-- The service rejects duplicate active rows for
-- (company_id, employee_id, effective_from, pay_head_id) where is_active = 1.
-- Optional partial unique index to enforce it at the DB level:
-- CREATE UNIQUE INDEX IF NOT EXISTS uq_salary_structures_active
--     ON salary_structures (company_id, employee_id, effective_from, pay_head_id)
--     WHERE is_active = TRUE;

-- =============================================================================
-- Foreign key constraints (grouped at bottom for cross-module load ordering).
-- All FKs below are EXPLICIT in the SQLite source (REFERENCES ... ON DELETE CASCADE).
-- =============================================================================

ALTER TABLE salary_structures
    ADD CONSTRAINT fk_salary_structures_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;  -- explicit in source

ALTER TABLE salary_structures
    ADD CONSTRAINT fk_salary_structures_employee
    FOREIGN KEY (employee_id) REFERENCES employees (employee_id)
    ON DELETE CASCADE;  -- explicit in source

ALTER TABLE salary_structures
    ADD CONSTRAINT fk_salary_structures_pay_head
    FOREIGN KEY (pay_head_id) REFERENCES pay_heads (pay_head_id)
    ON DELETE CASCADE;  -- explicit in source
