-- ============================================================================
-- Module: stockItem
-- Source: server/stockItem/stockItem.js (SQLite schema init)
-- Target: PostgreSQL
--
-- Tables:
--   stock_items
--   stock_item_opening_allocations
--
-- Notes:
--  * SQLite stores INTEGER PRIMARY KEY AUTOINCREMENT -> Postgres IDENTITY.
--  * SQLite boolean-like INTEGER 0/1 columns -> Postgres BOOLEAN
--    (0 -> false, 1 -> true). App logic coerces truthy values to 1/0 on write.
--  * MONEY / QUANTITY columns are REAL in SQLite. They are mapped to NUMERIC here.
--    NEVER use floating point for money/quantities in an accounting system.
--  * created_at / updated_at are ISO-8601 strings via datetime('now') in SQLite
--    -> TIMESTAMPTZ with DEFAULT now().
--  * Date-only columns (mfg_date, expiry_date) -> DATE.
--  * The SQLite source declares some FKs explicitly (REFERENCES ...). Cross-module
--    FKs are emitted as ALTER TABLE at the bottom; whether each is explicit in the
--    source or inferred is noted per constraint.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Table: stock_items
-- ----------------------------------------------------------------------------
CREATE TABLE stock_items (
    item_id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id                     BIGINT       NOT NULL,

    name                           TEXT         NOT NULL,
    alias                          TEXT,

    group_id                       BIGINT,                                    -- FK -> stock_groups.sg_id
    category_id                    BIGINT,                                    -- FK -> stock_categories.sc_id
    unit_id                        BIGINT,                                    -- FK -> units.unit_id

    -- GST Applicability
    gst_applicable                 TEXT         NOT NULL DEFAULT 'Not Applicable',

    -- HSN/SAC & related details
    hsn_sac                        TEXT,
    source_of_details              TEXT         NOT NULL DEFAULT 'As per Company/Stock Group',
    hsn_sac_description            TEXT,

    -- legacy split columns kept for backward compat
    hsn_code                       TEXT,
    sac_code                       TEXT,

    -- GST rate & related details
    gst_rate_details               TEXT,
    source_of_gst_rate             TEXT         NOT NULL DEFAULT 'As per Company/Stock Group',
    taxability_type                TEXT,
    gst_rate                       NUMERIC(18,4) NOT NULL DEFAULT 0,          -- tax rate (percentage)
    cgst_rate                      NUMERIC(18,4) NOT NULL DEFAULT 0,          -- tax rate (percentage)
    sgst_rate                      NUMERIC(18,4) NOT NULL DEFAULT 0,          -- tax rate (percentage)
    igst_rate                      NUMERIC(18,4) NOT NULL DEFAULT 0,          -- tax rate (percentage)

    type_of_supply                 TEXT         NOT NULL DEFAULT 'Goods',

    rate_of_duty                   NUMERIC(18,4) NOT NULL DEFAULT 0,          -- rate
    statutory_details              TEXT,

    opening_quantity               NUMERIC(18,4) NOT NULL DEFAULT 0,          -- quantity
    opening_rate                   NUMERIC(18,2) NOT NULL DEFAULT 0,          -- MONEY per unit (do NOT use float)
    opening_value                  NUMERIC(18,2) NOT NULL DEFAULT 0,          -- MONEY = opening_quantity * opening_rate (computed in app)

    reorder_level                  NUMERIC(18,4) NOT NULL DEFAULT 0,          -- quantity
    reorder_quantity               NUMERIC(18,4) NOT NULL DEFAULT 0,          -- quantity

    track_batches                  BOOLEAN      NOT NULL DEFAULT false,       -- SQLite INTEGER 0/1
    track_expiry                   BOOLEAN      NOT NULL DEFAULT false,       -- SQLite INTEGER 0/1
    track_date_of_manufacturing    BOOLEAN      NOT NULL DEFAULT false,       -- SQLite INTEGER 0/1 (migration-added)
    enable_cost_tracking           BOOLEAN      NOT NULL DEFAULT false,       -- SQLite INTEGER 0/1 (migration-added)

    has_bom                        BOOLEAN      NOT NULL DEFAULT false,       -- SQLite INTEGER 0/1
    bom_name                       TEXT,

    excise_applicable              TEXT         NOT NULL DEFAULT 'Not Applicable',
    excise_details                 TEXT,
    excise_tariff_name             TEXT,
    excise_tariff_hsn_code         TEXT,
    excise_tariff_uom              TEXT         NOT NULL DEFAULT 'Undefined',
    excise_tariff_valuation_type   TEXT         NOT NULL DEFAULT 'Undefined',
    excise_tariff_rate             NUMERIC(18,4) NOT NULL DEFAULT 0,          -- rate
    excise_tariff_rate_per_unit    NUMERIC(18,2) NOT NULL DEFAULT 0,          -- MONEY per unit (do NOT use float)

    vat_applicable                 TEXT         NOT NULL DEFAULT 'Applicable',
    vat_details                    TEXT,

    is_active                      BOOLEAN      NOT NULL DEFAULT true,        -- SQLite INTEGER 0/1; soft-delete flag
    created_at                     TIMESTAMPTZ  NOT NULL DEFAULT now(),       -- SQLite stored ISO-8601 string
    updated_at                     TIMESTAMPTZ  NOT NULL DEFAULT now()        -- SQLite stored ISO-8601 string
);

COMMENT ON COLUMN stock_items.opening_rate  IS 'MONEY per unit. Mapped from SQLite REAL to NUMERIC(18,2). Never use floating point for money.';
COMMENT ON COLUMN stock_items.opening_value IS 'MONEY. Computed in app as opening_quantity * opening_rate. NUMERIC(18,2).';
COMMENT ON COLUMN stock_items.excise_tariff_rate_per_unit IS 'MONEY per unit. NUMERIC(18,2). Never use floating point for money.';
COMMENT ON COLUMN stock_items.is_active IS 'Soft-delete flag. SQLite INTEGER 0/1 -> BOOLEAN (1=true=active).';

-- Helpful indexes
CREATE INDEX idx_stock_items_company_id  ON stock_items (company_id);
CREATE INDEX idx_stock_items_group_id    ON stock_items (group_id);
CREATE INDEX idx_stock_items_category_id ON stock_items (category_id);
CREATE INDEX idx_stock_items_unit_id     ON stock_items (unit_id);

-- Application-level uniqueness: active item name is unique per company
-- (enforced in code via case-insensitive check, not by a DB constraint in the source).
-- Optional partial unique index to enforce it at the DB layer:
-- CREATE UNIQUE INDEX uq_stock_items_company_active_name
--   ON stock_items (company_id, lower(name)) WHERE is_active;


-- ----------------------------------------------------------------------------
-- Table: stock_item_opening_allocations
-- ----------------------------------------------------------------------------
CREATE TABLE stock_item_opening_allocations (
    allocation_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    item_id         BIGINT       NOT NULL,                                    -- FK -> stock_items.item_id

    godown_id       BIGINT,                                                   -- FK -> godowns.godown_id (ON DELETE SET NULL)
    batch_number    TEXT,
    mfg_date        DATE,                                                     -- date-only text in SQLite
    expiry_date     DATE,                                                     -- date-only text in SQLite

    quantity        NUMERIC(18,4) NOT NULL DEFAULT 0,                         -- quantity
    rate            NUMERIC(18,2) NOT NULL DEFAULT 0,                         -- MONEY per unit (do NOT use float)
    amount          NUMERIC(18,2) NOT NULL DEFAULT 0                          -- MONEY = quantity * rate (computed in app)
);

COMMENT ON COLUMN stock_item_opening_allocations.rate   IS 'MONEY per unit. Mapped from SQLite REAL to NUMERIC(18,2). Never use floating point for money.';
COMMENT ON COLUMN stock_item_opening_allocations.amount IS 'MONEY. Computed in app as quantity * rate. NUMERIC(18,2).';

CREATE INDEX idx_sioa_item_id   ON stock_item_opening_allocations (item_id);
CREATE INDEX idx_sioa_godown_id ON stock_item_opening_allocations (godown_id);


-- ============================================================================
-- Foreign key constraints (grouped to avoid cross-module ordering issues)
-- ============================================================================

-- stock_items.company_id -> companies.company_id
-- EXPLICIT in source (REFERENCES companies(company_id) ON DELETE CASCADE).
ALTER TABLE stock_items
    ADD CONSTRAINT fk_stock_items_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;

-- stock_items.group_id -> stock_groups.sg_id
-- EXPLICIT in source (REFERENCES stock_groups(sg_id)).
ALTER TABLE stock_items
    ADD CONSTRAINT fk_stock_items_group
    FOREIGN KEY (group_id) REFERENCES stock_groups (sg_id);

-- stock_items.category_id -> stock_categories.sc_id
-- EXPLICIT in source (REFERENCES stock_categories(sc_id)).
ALTER TABLE stock_items
    ADD CONSTRAINT fk_stock_items_category
    FOREIGN KEY (category_id) REFERENCES stock_categories (sc_id);

-- stock_items.unit_id -> units.unit_id
-- EXPLICIT in source (REFERENCES units(unit_id)).
ALTER TABLE stock_items
    ADD CONSTRAINT fk_stock_items_unit
    FOREIGN KEY (unit_id) REFERENCES units (unit_id);

-- stock_item_opening_allocations.item_id -> stock_items.item_id
-- EXPLICIT in source (REFERENCES stock_items(item_id) ON DELETE CASCADE).
ALTER TABLE stock_item_opening_allocations
    ADD CONSTRAINT fk_sioa_item
    FOREIGN KEY (item_id) REFERENCES stock_items (item_id)
    ON DELETE CASCADE;

-- stock_item_opening_allocations.godown_id -> godowns.godown_id
-- EXPLICIT in source (REFERENCES godowns(godown_id) ON DELETE SET NULL).
ALTER TABLE stock_item_opening_allocations
    ADD CONSTRAINT fk_sioa_godown
    FOREIGN KEY (godown_id) REFERENCES godowns (godown_id)
    ON DELETE SET NULL;
