-- ============================================================================
-- Module: stockGroup
-- Postgres DDL translated from server/stockGroup/stockGroup.js (SQLite source).
--
-- Notes:
--   * SQLite 0/1 integer flags are translated to BOOLEAN. The app stores 0/1;
--     map 0 -> false, 1 -> true on migration.
--   * created_at / updated_at are stored as ISO-8601 strings (SQLite
--     datetime('now')) -> TIMESTAMPTZ with now() default.
--   * gst_rate / cgst_rate / sgst_rate are tax percentage rates (quantities,
--     not currency) -> NUMERIC(18,4). NEVER use floating point for these.
--   * FK constraints are grouped at the bottom (ALTER TABLE) to avoid
--     cross-module ordering problems.
-- ============================================================================

CREATE TABLE IF NOT EXISTS stock_groups (
    sg_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                  BIGINT NOT NULL,
    name                        TEXT NOT NULL,
    alias                       TEXT,
    parent_group_id             BIGINT,
    should_quantities_be_added  BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    hsn_sac_code                TEXT,
    hsn_sac_description         TEXT,
    gst_rate                    NUMERIC(18,4) NOT NULL DEFAULT 0,  -- tax rate (percentage); not money, not float
    cgst_rate                   NUMERIC(18,4) NOT NULL DEFAULT 0,  -- tax rate (percentage); not money, not float
    sgst_rate                   NUMERIC(18,4) NOT NULL DEFAULT 0,  -- tax rate (percentage); not money, not float
    taxability_type             TEXT DEFAULT NULL,
    statutory_details           TEXT,
    is_primary                  BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    is_active                   BOOLEAN NOT NULL DEFAULT true,   -- SQLite INTEGER 0/1; soft-delete marker
    is_predefined               BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER 0/1
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),  -- ISO-8601 string in SQLite
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()   -- ISO-8601 string in SQLite
);

-- Indexes on FK columns
CREATE INDEX IF NOT EXISTS idx_stock_groups_company_id      ON stock_groups (company_id);
CREATE INDEX IF NOT EXISTS idx_stock_groups_parent_group_id ON stock_groups (parent_group_id);

-- Uniqueness: the service enforces (company_id, LOWER(name)) for active rows in
-- application code (no DB UNIQUE in source). A partial unique index reproduces it.
CREATE UNIQUE INDEX IF NOT EXISTS uq_stock_groups_company_lower_name_active
    ON stock_groups (company_id, LOWER(name))
    WHERE is_active = true;  -- inferred from service create() duplicate check; not in SQLite source

-- ============================================================================
-- Foreign key constraints
-- ============================================================================

-- EXPLICIT in source: stock_groups.company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE stock_groups
    ADD CONSTRAINT fk_stock_groups_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: stock_groups.parent_group_id REFERENCES stock_groups(sg_id) (self-FK)
ALTER TABLE stock_groups
    ADD CONSTRAINT fk_stock_groups_parent
    FOREIGN KEY (parent_group_id) REFERENCES stock_groups (sg_id);
