-- ============================================================================
-- Postgres DDL for backend module: stockCategory
-- Source: server/stockCategory/stockCategory.js (SQLite schema init)
-- Tables: stock_categories
-- ----------------------------------------------------------------------------
-- SQLite -> Postgres translation notes:
--   * sc_id INTEGER PRIMARY KEY AUTOINCREMENT -> IDENTITY PRIMARY KEY.
--   * is_active is stored as 0/1 in SQLite; mapped to BOOLEAN here
--     (1 -> true = active, 0 -> false = soft-deleted). DEFAULT 1 -> DEFAULT true.
--   * created_at / updated_at hold ISO-8601 strings via SQLite datetime('now');
--     mapped to TIMESTAMPTZ with DEFAULT now().
--   * The SQLite source declares explicit FK REFERENCES for both company_id and
--     parent_category_id; these are EXPLICIT (not inferred). FK constraints are
--     grouped at the bottom as ALTER TABLE statements for cross-module ordering.
--   * No money/quantity columns exist in this module.
-- ============================================================================

CREATE TABLE IF NOT EXISTS stock_categories (
    sc_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT       NOT NULL,
    name               TEXT         NOT NULL,
    alias              TEXT,
    description        TEXT,
    parent_category_id BIGINT,
    is_active          BOOLEAN      NOT NULL DEFAULT true,   -- SQLite INTEGER 0/1 (DEFAULT 1) -> BOOLEAN (false/true)
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),  -- SQLite TEXT datetime('now') ISO-8601 string
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()   -- SQLite TEXT datetime('now') ISO-8601 string
);

COMMENT ON COLUMN stock_categories.is_active IS
    'Soft-delete flag. SQLite stored 0/1; true = active, false = deleted.';
COMMENT ON COLUMN stock_categories.parent_category_id IS
    'Self-referencing parent category (hierarchy).';

-- Index on FK columns for join/lookup performance.
CREATE INDEX IF NOT EXISTS idx_stock_categories_company_id
    ON stock_categories (company_id);
CREATE INDEX IF NOT EXISTS idx_stock_categories_parent_category_id
    ON stock_categories (parent_category_id);

-- Supports the per-company case-insensitive active-name duplicate check
-- (service: WHERE company_id = ? AND LOWER(name) = LOWER(?) AND is_active = 1).
-- NOT declared UNIQUE in source (the app enforces uniqueness in code, and only
-- among is_active = 1 rows), so this is a non-unique helper index.
CREATE INDEX IF NOT EXISTS idx_stock_categories_company_lower_name
    ON stock_categories (company_id, lower(name));

-- ============================================================================
-- Foreign key constraints (grouped to avoid cross-module ordering issues)
-- ============================================================================

-- EXPLICIT in SQLite source:
--   company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE stock_categories
    ADD CONSTRAINT fk_stock_categories_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;

-- EXPLICIT in SQLite source:
--   parent_category_id INTEGER REFERENCES stock_categories(sc_id)
--   (self-reference; no ON DELETE action specified in source -> RESTRICT default)
ALTER TABLE stock_categories
    ADD CONSTRAINT fk_stock_categories_parent
    FOREIGN KEY (parent_category_id) REFERENCES stock_categories (sc_id)
    ON DELETE RESTRICT;
