-- =============================================================================
-- Module: tallyFeatures
-- Postgres DDL translated from SQLite source:
--   server/tallyFeatures/tallyFeatures.js
-- One row per company holding Tally-style "F11" feature toggles.
--
-- Type mapping notes:
--   * tally_feature_id : SQLite INTEGER PRIMARY KEY AUTOINCREMENT
--                        -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   * all *_/maintain_/enable_/use_/mark_ flags : SQLite INTEGER 0/1
--                        -> BOOLEAN (0 -> false, 1 -> true).
--                        SQLite DEFAULT 0/1 -> BOOLEAN DEFAULT false/true.
--   * created_at / updated_at : SQLite TEXT DEFAULT (datetime('now')) storing
--                        ISO-8601 strings -> TIMESTAMPTZ DEFAULT now().
--   * No money/quantity columns exist in this table.
-- =============================================================================

CREATE TABLE IF NOT EXISTS tally_features (
    tally_feature_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                          BIGINT  NOT NULL,                 -- FK -> companies(company_id); explicit in SQLite source, see ALTER below
    maintain_accounts                   BOOLEAN NOT NULL DEFAULT true,    -- SQLite INTEGER DEFAULT 1 (0/1 -> false/true)
    enable_bill_wise_entry              BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_cost_centres                 BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    maintain_inventory                  BOOLEAN NOT NULL DEFAULT true,    -- SQLite INTEGER DEFAULT 1
    integrate_accounts_with_inventory   BOOLEAN NOT NULL DEFAULT true,    -- SQLite INTEGER DEFAULT 1
    enable_multiple_price_levels        BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_batches                      BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    maintain_expiry_date_for_batches    BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    use_discount_column_in_invoices     BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    use_separate_actual_billed_qty      BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_gst                          BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    set_alter_company_gst_details       BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_tds                          BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_tcs                          BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_browser_access_for_reports   BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_tally_net_services           BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_payment_request_qr           BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    enable_multiple_addresses           BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    mark_modified_vouchers              BOOLEAN NOT NULL DEFAULT false,   -- SQLite INTEGER DEFAULT 0
    created_at                          TIMESTAMPTZ NOT NULL DEFAULT now(),  -- SQLite TEXT DEFAULT (datetime('now')); ISO-8601 string
    updated_at                          TIMESTAMPTZ NOT NULL DEFAULT now()   -- SQLite TEXT DEFAULT (datetime('now')); ISO-8601 string
);

-- One feature-set per company (each company has exactly one row).
-- Not present as a UNIQUE constraint in the SQLite source, but strongly implied
-- by access pattern (all queries are WHERE company_id = ?). Recommended:
ALTER TABLE tally_features
    ADD CONSTRAINT uq_tally_features_company_id UNIQUE (company_id);  -- inferred (recommended)

-- Index on FK column.
CREATE INDEX IF NOT EXISTS idx_tally_features_company_id
    ON tally_features (company_id);

-- =============================================================================
-- Foreign keys (grouped at bottom; cross-module ordering-safe).
-- =============================================================================

-- EXPLICIT in SQLite source: company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE tally_features
    ADD CONSTRAINT fk_tally_features_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
