-- ============================================================================
-- Module: taxUnits
-- Postgres DDL translated from SQLite source: server/taxUnits/taxUnit.js
-- Table: tax_units
--
-- Translation notes:
--  * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
--  * TEXT -> TEXT (no length caps present in source).
--  * created_at / updated_at store ISO-8601 datetime strings (SQLite
--    datetime('now')) -> TIMESTAMPTZ DEFAULT now().
--  * INTEGER flags used as booleans (is_active, set_alter_*) -> BOOLEAN.
--    SQLite stored 0/1; map 0 -> false, 1 -> true on migration.
--  * The company_id FK is EXPLICIT in the SQLite source
--    (REFERENCES companies(company_id) ON DELETE CASCADE) -- NOT inferred.
-- ============================================================================

CREATE TABLE tax_units (
    tax_unit_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                BIGINT  NOT NULL,                       -- explicit FK in source -> companies(company_id)
    name                      TEXT    NOT NULL,
    alias                     TEXT,
    address_line1             TEXT,
    address_line2             TEXT,
    address_line3             TEXT,
    address_line4             TEXT,
    state                     TEXT,
    pincode                   TEXT,
    telephone                 TEXT,
    registered_for            TEXT    NOT NULL DEFAULT 'Excise',      -- SQLite DEFAULT 'Excise'
    set_alter_excise_details  BOOLEAN NOT NULL DEFAULT false,         -- SQLite INTEGER DEFAULT 0 (0->false,1->true)
    registration_type         TEXT    NOT NULL DEFAULT 'Importer',    -- SQLite DEFAULT 'Importer'
    ecc_number                TEXT,
    set_alter_excise_tariff   BOOLEAN NOT NULL DEFAULT false,         -- SQLite INTEGER DEFAULT 0 (0->false,1->true)
    set_alter_rule11_book     BOOLEAN NOT NULL DEFAULT false,         -- SQLite INTEGER DEFAULT 0 (0->false,1->true)
    sort_order                INTEGER NOT NULL DEFAULT 0,
    is_active                 BOOLEAN NOT NULL DEFAULT true,          -- SQLite INTEGER DEFAULT 1 (0->false,1->true)
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),     -- SQLite TEXT datetime('now'), ISO-8601
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()      -- SQLite TEXT datetime('now'), ISO-8601
);

-- ----------------------------------------------------------------------------
-- Application-enforced uniqueness (not a constraint in source):
-- create() rejects a duplicate active name per company, case-insensitively.
-- A partial unique index makes this explicit and authoritative in Postgres.
-- ----------------------------------------------------------------------------
CREATE UNIQUE INDEX uq_tax_units_company_active_name
    ON tax_units (company_id, lower(name))
    WHERE is_active = true;

-- Index on FK column for join/lookup performance.
CREATE INDEX idx_tax_units_company_id ON tax_units (company_id);

-- ============================================================================
-- Foreign keys (grouped at bottom so cross-module load order is irrelevant).
-- ============================================================================

-- EXPLICIT in source (SQLite: REFERENCES companies(company_id) ON DELETE CASCADE).
ALTER TABLE tax_units
    ADD CONSTRAINT fk_tax_units_company_id
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
