-- ============================================================================
-- Module: tcsNatureOfGoods
-- Postgres DDL translated from SQLite source:
--   server/tcsNatureOfGoods/tcsNatureOfGoods.js
-- Source table: tcs_nature_of_goods
--
-- Type mapping notes:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * is_* flags (SQLite INTEGER 0/1) -> BOOLEAN (0 -> false, 1 -> true)
--   * rate_* columns hold percentage/money-like values -> NUMERIC(18,4)
--     (NEVER floating point for money/rates)
--   * threshold_level holds a currency amount -> NUMERIC(18,2)
--     (NEVER floating point for money)
--   * created_at / updated_at store ISO-8601 strings -> TIMESTAMPTZ
--     (SQLite datetime('now') default -> now())
-- ============================================================================

CREATE TABLE tcs_nature_of_goods (
    tcs_id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                    BIGINT NOT NULL,
    name                          TEXT NOT NULL,
    section                       TEXT,
    payment_code                  TEXT,
    -- MONEY/RATE: SQLite REAL -> NUMERIC(18,4). Never use floating point for rates.
    rate_individual_with_pan      NUMERIC(18,4) NOT NULL DEFAULT 0,
    rate_individual_without_pan   NUMERIC(18,4) NOT NULL DEFAULT 0,
    rate_other_with_pan           NUMERIC(18,4) NOT NULL DEFAULT 0,
    rate_other_without_pan        NUMERIC(18,4) NOT NULL DEFAULT 0,
    -- BOOLEAN: SQLite INTEGER 0/1 -> BOOLEAN (0 -> false, 1 -> true)
    is_own_status                 BOOLEAN NOT NULL DEFAULT false,
    tax_on_receipt_or_realization TEXT NOT NULL DEFAULT 'Tax Calculated on Receipt',
    -- MONEY: SQLite REAL threshold amount -> NUMERIC(18,2). Never use floating point for money.
    threshold_level               NUMERIC(18,2) NOT NULL DEFAULT 0,
    -- BOOLEAN: SQLite INTEGER 0/1 -> BOOLEAN
    is_zero_rated                 BOOLEAN NOT NULL DEFAULT false,
    is_predefined                 BOOLEAN NOT NULL DEFAULT false,
    is_active                     BOOLEAN NOT NULL DEFAULT true,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index on FK column for join/filter performance.
CREATE INDEX idx_tcs_nature_of_goods_company_id ON tcs_nature_of_goods (company_id);

-- ----------------------------------------------------------------------------
-- Foreign keys (grouped at bottom so cross-module load order does not matter).
-- ----------------------------------------------------------------------------

-- EXPLICIT in source: SQLite column declared
--   "company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE".
ALTER TABLE tcs_nature_of_goods
    ADD CONSTRAINT fk_tcs_nature_of_goods_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
