-- =====================================================================
-- Module: tdsNatureOfPayment
-- Postgres DDL translated from SQLite schema
--   source: server/tdsNatureOfPayment/tdsNatureOfPayment.js
-- Table(s): tds_nature_of_payment
--
-- Conventions:
--   * SQLite INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * SQLite TEXT datetime (datetime('now')) -> TIMESTAMPTZ DEFAULT now()
--     NOTE: app stores ISO-8601 strings; values must be cast on migration.
--   * INTEGER 0/1 flags -> BOOLEAN (0 -> false, 1 -> true on migration)
--   * MONEY columns -> NUMERIC (NEVER floating point). threshold_limit is money.
--   * RATE columns -> NUMERIC(18,4) (percentage rates; high precision, never float).
-- FK handling: FK constraints are emitted as ALTER TABLE statements at the
--   bottom of this file so cross-module load ordering is not a problem.
-- =====================================================================

CREATE TABLE IF NOT EXISTS tds_nature_of_payment (
    tds_id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                  BIGINT       NOT NULL,
    name                        TEXT         NOT NULL,
    section                     TEXT,
    payment_code                TEXT,
    remittance_code             TEXT,
    -- rate columns: TDS percentage rates. NUMERIC(18,4), never floating point.
    rate_individual_with_pan    NUMERIC(18,4) NOT NULL DEFAULT 0,
    rate_other_with_pan         NUMERIC(18,4) NOT NULL DEFAULT 0,
    -- is_zero_rated: SQLite INTEGER 0/1 -> BOOLEAN (0->false, 1->true)
    is_zero_rated               BOOLEAN      NOT NULL DEFAULT false,
    -- threshold_limit: MONEY value. NUMERIC(18,2), never floating point.
    threshold_limit             NUMERIC(18,2) NOT NULL DEFAULT 0,
    -- is_predefined: SQLite INTEGER 0/1 -> BOOLEAN (0->false, 1->true)
    is_predefined               BOOLEAN      NOT NULL DEFAULT false,
    -- is_active: SQLite INTEGER 0/1 -> BOOLEAN soft-delete flag (1->true=active)
    is_active                   BOOLEAN      NOT NULL DEFAULT true,
    -- created_at / updated_at: SQLite TEXT ISO-8601 -> TIMESTAMPTZ
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Indexes on FK columns
CREATE INDEX IF NOT EXISTS idx_tds_nature_of_payment_company_id
    ON tds_nature_of_payment (company_id);

-- Supports the active-records-per-company lookups used by getAll / create dup-check.
CREATE INDEX IF NOT EXISTS idx_tds_nature_of_payment_company_active
    ON tds_nature_of_payment (company_id, is_active);

-- =====================================================================
-- Foreign key constraints (grouped at bottom for load-order safety)
-- =====================================================================

-- EXPLICIT in source: SQLite schema declares
--   company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE tds_nature_of_payment
    ADD CONSTRAINT fk_tds_nature_of_payment_company
    FOREIGN KEY (company_id)
    REFERENCES companies (company_id)
    ON DELETE CASCADE;
