-- ============================================================================
-- Module: trialBalanceReport  (Postgres DDL)
-- Source: server/trialBalanceReport/trialBalanceReport.js (SQLite schema)
-- Translated SQLite -> Postgres. Money columns use NUMERIC, never floating point.
-- FK constraints are grouped at the bottom as ALTER TABLE statements.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: trial_balance_reports  (saved Trial Balance report header)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trial_balance_reports (
    report_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT NOT NULL,
    company_name           TEXT,
    report_date            DATE,                              -- date-only TEXT -> DATE
    period_start           DATE,                              -- date-only TEXT -> DATE
    period_end             DATE,                              -- date-only TEXT -> DATE
    show_closing_balance   BOOLEAN NOT NULL DEFAULT TRUE,     -- SQLite INTEGER 0/1 -> BOOLEAN (1 -> TRUE)
    show_debit_credit      BOOLEAN NOT NULL DEFAULT TRUE,     -- SQLite INTEGER 0/1 -> BOOLEAN (1 -> TRUE)
    show_groups            BOOLEAN NOT NULL DEFAULT TRUE,     -- SQLite INTEGER 0/1 -> BOOLEAN (1 -> TRUE)
    show_grand_total       BOOLEAN NOT NULL DEFAULT TRUE,     -- SQLite INTEGER 0/1 -> BOOLEAN (1 -> TRUE)
    detailed_mode          BOOLEAN NOT NULL DEFAULT FALSE,    -- SQLite INTEGER 0/1 -> BOOLEAN (0 -> FALSE)
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),-- app stores ISO datetime strings; SQLite default datetime('now')
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now() -- app stores ISO datetime strings; SQLite default datetime('now')
);

-- ----------------------------------------------------------------------------
-- Table: trial_balance_rows  (saved Trial Balance report detail line)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trial_balance_rows (
    row_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id         BIGINT NOT NULL,
    parent_row_id     BIGINT,                                 -- self-reference; nullable (top-level rows)
    row_type          TEXT NOT NULL DEFAULT 'Ledger',         -- has DEFAULT -> NOT NULL
    particulars       TEXT,
    group_id          BIGINT,                                 -- inferred FK target (groups)
    ledger_id         BIGINT,                                 -- inferred FK target (ledgers)
    display_order     INTEGER NOT NULL DEFAULT 0,             -- has DEFAULT -> NOT NULL
    opening_debit     NUMERIC(18,2) NOT NULL DEFAULT 0,       -- MONEY: NUMERIC, never float
    opening_credit    NUMERIC(18,2) NOT NULL DEFAULT 0,       -- MONEY: NUMERIC, never float
    period_debit      NUMERIC(18,2) NOT NULL DEFAULT 0,       -- MONEY: NUMERIC, never float
    period_credit     NUMERIC(18,2) NOT NULL DEFAULT 0,       -- MONEY: NUMERIC, never float
    closing_debit     NUMERIC(18,2) NOT NULL DEFAULT 0,       -- MONEY: NUMERIC, never float
    closing_credit    NUMERIC(18,2) NOT NULL DEFAULT 0,       -- MONEY: NUMERIC, never float
    is_drillable      BOOLEAN NOT NULL DEFAULT TRUE,          -- SQLite INTEGER 0/1 -> BOOLEAN (1 -> TRUE)
    is_grand_total    BOOLEAN NOT NULL DEFAULT FALSE,         -- SQLite INTEGER 0/1 -> BOOLEAN (0 -> FALSE)
    notes             TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),     -- app stores ISO datetime strings
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()      -- app stores ISO datetime strings
);

-- ----------------------------------------------------------------------------
-- Indexes on FK columns
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_trial_balance_reports_company_id ON trial_balance_reports (company_id);
CREATE INDEX IF NOT EXISTS idx_trial_balance_rows_report_id     ON trial_balance_rows (report_id);
CREATE INDEX IF NOT EXISTS idx_trial_balance_rows_parent_row_id ON trial_balance_rows (parent_row_id);
CREATE INDEX IF NOT EXISTS idx_trial_balance_rows_group_id      ON trial_balance_rows (group_id);
CREATE INDEX IF NOT EXISTS idx_trial_balance_rows_ledger_id     ON trial_balance_rows (ledger_id);

-- ----------------------------------------------------------------------------
-- Foreign key constraints (grouped; run after all module tables exist)
-- ----------------------------------------------------------------------------

-- EXPLICIT in source: trial_balance_reports.company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE trial_balance_reports
    ADD CONSTRAINT fk_trial_balance_reports_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in source: trial_balance_rows.report_id REFERENCES trial_balance_reports(report_id) ON DELETE CASCADE
ALTER TABLE trial_balance_rows
    ADD CONSTRAINT fk_trial_balance_rows_report
    FOREIGN KEY (report_id) REFERENCES trial_balance_reports (report_id) ON DELETE CASCADE;

-- INFERRED (no FK constraint in SQLite source): self-reference for row hierarchy.
ALTER TABLE trial_balance_rows
    ADD CONSTRAINT fk_trial_balance_rows_parent
    FOREIGN KEY (parent_row_id) REFERENCES trial_balance_rows (row_id) ON DELETE CASCADE;

-- INFERRED (no FK constraint in SQLite source): group_id presumed -> groups(group_id).
-- Adjust target table/column to your actual groups table before applying.
ALTER TABLE trial_balance_rows
    ADD CONSTRAINT fk_trial_balance_rows_group
    FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE SET NULL;

-- INFERRED (no FK constraint in SQLite source): ledger_id presumed -> ledgers(ledger_id).
-- Adjust target table/column to your actual ledgers table before applying.
ALTER TABLE trial_balance_rows
    ADD CONSTRAINT fk_trial_balance_rows_ledger
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id) ON DELETE SET NULL;
