-- ============================================================================
-- Module: unit
-- Source: server/unit/unit.js  (SQLite CREATE TABLE units + migrations)
-- Target: PostgreSQL
--
-- SQLite -> Postgres translation notes:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
--   * is_simple / is_active / is_predefined are SQLite 0/1 INTEGER flags -> BOOLEAN
--     (0 -> false, 1 -> true). DEFAULT values translated accordingly.
--   * created_at / updated_at store ISO-8601 strings via datetime('now') -> TIMESTAMPTZ
--     DEFAULT now().
--   * conversion_factor holds a quantity ratio -> NUMERIC(18,4). It is intentionally
--     NOT floating point (money/quantity precision).
--   * FK constraints: companies(company_id) is EXPLICIT in the SQLite source.
--     The self-references first_unit_id / second_unit_id are also explicit in source.
--     All are emitted as ALTER TABLE statements at the bottom.
-- ============================================================================

CREATE TABLE units (
    unit_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT       NOT NULL,
    name                TEXT         NOT NULL,
    symbol              TEXT         NOT NULL,
    formal_name         TEXT,
    decimal_places      INTEGER      NOT NULL DEFAULT 0,   -- SQLite DEFAULT 0
    unit_quantity_code  TEXT,
    unit_type           TEXT         NOT NULL DEFAULT 'Simple',  -- 'Simple' | 'Compound'
    is_simple           BOOLEAN      NOT NULL DEFAULT TRUE,  -- SQLite INTEGER 0/1, default 1
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,  -- SQLite INTEGER 0/1, default 1; soft-delete flag
    is_predefined       BOOLEAN      NOT NULL DEFAULT FALSE, -- SQLite INTEGER 0/1, default 0
    first_unit_id       BIGINT,      -- compound only; self-reference to units.unit_id
    second_unit_id      BIGINT,      -- compound only; self-reference to units.unit_id
    conversion_factor   NUMERIC(18,4) DEFAULT 1,  -- quantity ratio; NUMERIC (NOT floating point)
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),  -- app stores ISO-8601 strings
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now()   -- app stores ISO-8601 strings
);

-- ----------------------------------------------------------------------------
-- Indexes on FK columns
-- ----------------------------------------------------------------------------
CREATE INDEX idx_units_company_id    ON units (company_id);
CREATE INDEX idx_units_first_unit_id  ON units (first_unit_id);
CREATE INDEX idx_units_second_unit_id ON units (second_unit_id);

-- Supports the dominant lookup pattern: active units per company.
CREATE INDEX idx_units_company_active ON units (company_id, is_active);

-- ----------------------------------------------------------------------------
-- Foreign keys (grouped at bottom for cross-module load ordering)
-- ----------------------------------------------------------------------------

-- EXPLICIT in SQLite source: company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE units
    ADD CONSTRAINT fk_units_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source: first_unit_id REFERENCES units(unit_id) (self-reference)
ALTER TABLE units
    ADD CONSTRAINT fk_units_first_unit
    FOREIGN KEY (first_unit_id) REFERENCES units (unit_id);

-- EXPLICIT in SQLite source: second_unit_id REFERENCES units(unit_id) (self-reference)
ALTER TABLE units
    ADD CONSTRAINT fk_units_second_unit
    FOREIGN KEY (second_unit_id) REFERENCES units (unit_id);

-- ----------------------------------------------------------------------------
-- Column comments
-- ----------------------------------------------------------------------------
COMMENT ON COLUMN units.conversion_factor IS
    'Quantity ratio for compound units (first_unit = conversion_factor x second_unit). NUMERIC(18,4), never floating point.';
COMMENT ON COLUMN units.is_active IS
    'Soft-delete flag. SQLite stored 0/1; delete sets to false instead of removing the row.';
