-- =====================================================================
-- Module: voucherEntryActions
-- Source: server/voucherEntryActions/voucherEntryActions.js (SQLite init)
-- Target: PostgreSQL
--
-- Notes:
--   * SQLite INTEGER PRIMARY KEY AUTOINCREMENT -> IDENTITY column.
--   * action_data / additional_details are JSON-serialized TEXT in SQLite.
--     Mapped to JSONB here (the service JSON.stringify's on write and
--     JSON.parse's on read). Use TEXT instead if you need to preserve
--     non-JSON string fallbacks the service tolerates on read.
--   * Money/quantity columns are NEVER mapped to floating point.
--   * is_optional is stored 0/1 in SQLite -> BOOLEAN (0=false, 1=true).
--   * performed_at / created_at hold ISO-8601 strings -> TIMESTAMPTZ.
-- =====================================================================

CREATE TABLE voucher_entry_actions (
    action_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT NOT NULL,
    voucher_id           BIGINT,
    action_type          TEXT   NOT NULL,
    action_data          JSONB,                       -- JSON-serialized TEXT in SQLite
    autofill_ledger_id   BIGINT,
    autofill_amount      NUMERIC(18,2),               -- MONEY: never floating point (SQLite REAL)
    autofill_narration   TEXT,
    previous_mode        TEXT,
    new_mode             TEXT,
    additional_details   JSONB,                       -- JSON-serialized TEXT in SQLite
    related_report_type  TEXT,
    related_report_id    BIGINT,
    is_optional          BOOLEAN NOT NULL DEFAULT FALSE,  -- SQLite INTEGER DEFAULT 0 (0=false,1=true)
    optional_reason      TEXT,
    performed_by         TEXT,
    performed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),  -- SQLite TEXT DEFAULT datetime('now')
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()   -- SQLite TEXT DEFAULT datetime('now')
);

COMMENT ON COLUMN voucher_entry_actions.autofill_amount IS
    'Money amount. SQLite REAL -> NUMERIC(18,2). Never store currency in floating point.';
COMMENT ON COLUMN voucher_entry_actions.is_optional IS
    'SQLite stores 0/1; converted to BOOLEAN (0=false, 1=true).';
COMMENT ON COLUMN voucher_entry_actions.action_data IS
    'JSON-serialized payload (service JSON.stringify on write, JSON.parse on read).';
COMMENT ON COLUMN voucher_entry_actions.additional_details IS
    'JSON-serialized payload (service JSON.stringify on write, JSON.parse on read).';

-- ---------------------------------------------------------------------
-- Indexes (mirror the SQLite indexes from the source init)
-- ---------------------------------------------------------------------
CREATE INDEX idx_vea_company        ON voucher_entry_actions (company_id);
CREATE INDEX idx_vea_voucher        ON voucher_entry_actions (voucher_id);
CREATE INDEX idx_vea_performed_at   ON voucher_entry_actions (performed_at DESC);
CREATE INDEX idx_vea_action_type    ON voucher_entry_actions (company_id, action_type);
-- FK support index not present in source but sensible:
CREATE INDEX idx_vea_autofill_ledger ON voucher_entry_actions (autofill_ledger_id);

-- =====================================================================
-- Foreign keys (grouped at bottom to avoid cross-module ordering issues)
-- =====================================================================

-- EXPLICIT in source: company_id INTEGER NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE voucher_entry_actions
    ADD CONSTRAINT fk_vea_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id)
    ON DELETE CASCADE;

-- EXPLICIT in source: voucher_id INTEGER REFERENCES vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_entry_actions
    ADD CONSTRAINT fk_vea_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id)
    ON DELETE CASCADE;

-- EXPLICIT in source: autofill_ledger_id INTEGER REFERENCES ledgers(ledger_id)
ALTER TABLE voucher_entry_actions
    ADD CONSTRAINT fk_vea_autofill_ledger
    FOREIGN KEY (autofill_ledger_id) REFERENCES ledgers (ledger_id);

-- NOTE: related_report_id is a polymorphic reference qualified by
-- related_report_type. No single FK target exists, so NO foreign key is
-- emitted for related_report_id (inferred polymorphic; left unconstrained).
