-- ============================================================================
-- Postgres schema for backend module: voucherType
-- Source: server/voucherType/voucherType.js (SQLite init)
-- Tables: voucher_types, voucher_type_configs
--
-- Translation notes:
--   * SQLite INTEGER PRIMARY KEY AUTOINCREMENT  -> BIGINT GENERATED BY DEFAULT
--     AS IDENTITY PRIMARY KEY.
--   * SQLite 0/1 boolean flags                  -> BOOLEAN (0 -> false, 1 -> true).
--     All flag DEFAULTs translated accordingly (DEFAULT 0 -> DEFAULT false).
--   * created_at / updated_at hold ISO-8601 datetime strings (datetime('now'))
--     -> TIMESTAMPTZ DEFAULT now().
--   * No money/qty/rate columns exist in this module.
--   * FK constraints are declared inline in the SQLite source for
--     company_id, parent_vt_id, and voucher_type_id (marked EXPLICIT below).
--     default_bank_id has NO source FK and is INFERRED here.
--   * FK constraints are grouped at the bottom as ALTER TABLE statements so
--     cross-module load ordering does not matter.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: voucher_types
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_types (
    vt_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT  NOT NULL,                          -- EXPLICIT FK -> companies(company_id) ON DELETE CASCADE
    name                   TEXT    NOT NULL,
    short_name             TEXT,
    category               TEXT,
    default_voucher_class  TEXT,
    affects_inventory      BOOLEAN NOT NULL DEFAULT false,            -- SQLite INTEGER DEFAULT 0 (0->false / 1->true)
    affects_accounting     BOOLEAN NOT NULL DEFAULT true,             -- SQLite INTEGER DEFAULT 1 (0->false / 1->true)
    affects_gst            BOOLEAN NOT NULL DEFAULT false,            -- SQLite INTEGER DEFAULT 0 (0->false / 1->true)
    numbering_method       TEXT    NOT NULL DEFAULT 'Automatic',
    numbering_prefix       TEXT    NOT NULL DEFAULT '',
    numbering_suffix       TEXT    NOT NULL DEFAULT '',
    starts_with            INTEGER NOT NULL DEFAULT 1,
    is_predefined          BOOLEAN NOT NULL DEFAULT false,            -- SQLite INTEGER DEFAULT 0 (0->false / 1->true)
    is_active              BOOLEAN NOT NULL DEFAULT true,             -- SQLite INTEGER DEFAULT 1 (0->false / 1->true); 0/false = soft-deleted
    parent_vt_id           BIGINT,                                    -- EXPLICIT self-FK -> voucher_types(vt_id) ON DELETE SET NULL
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),        -- SQLite TEXT DEFAULT (datetime('now')); app stores ISO strings
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()         -- SQLite TEXT DEFAULT (datetime('now')); app stores ISO strings
);

-- Application-level uniqueness: create rejects an active duplicate name per
-- company (case-insensitive). Enforced in code today; recommended DB guard:
-- (uncomment to enforce a single active name per company, case-insensitive)
-- CREATE UNIQUE INDEX IF NOT EXISTS ux_voucher_types_company_name_active
--     ON voucher_types (company_id, LOWER(name))
--     WHERE is_active = true;

-- ----------------------------------------------------------------------------
-- Table: voucher_type_configs
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_type_configs (
    config_id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_type_id                      BIGINT  NOT NULL,            -- EXPLICIT FK -> voucher_types(vt_id) ON DELETE CASCADE
    use_effective_dates                  BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    allow_zero_value_transactions        BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    make_voucher_optional                BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    allow_narration                      BOOLEAN NOT NULL DEFAULT true,   -- SQLite INTEGER DEFAULT 1
    allow_narration_per_ledger           BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    print_after_save                     BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    whatsapp_after_save                  BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    enable_default_accounting_allocation BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    track_additional_cost_for_purchase   BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    default_title_to_print               TEXT,
    use_for_pos_invoicing                BOOLEAN NOT NULL DEFAULT false,  -- SQLite INTEGER DEFAULT 0
    default_bank_id                      BIGINT,                          -- INFERRED FK -> bank ledger (no FK in source; likely ledgers/banks pk)
    declaration                          TEXT,
    set_alter_declaration                BOOLEAN NOT NULL DEFAULT false   -- SQLite INTEGER DEFAULT 0
);

-- ----------------------------------------------------------------------------
-- Indexes on FK columns
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_voucher_types_company_id
    ON voucher_types (company_id);
CREATE INDEX IF NOT EXISTS ix_voucher_types_parent_vt_id
    ON voucher_types (parent_vt_id);
CREATE INDEX IF NOT EXISTS ix_voucher_type_configs_voucher_type_id
    ON voucher_type_configs (voucher_type_id);
CREATE INDEX IF NOT EXISTS ix_voucher_type_configs_default_bank_id
    ON voucher_type_configs (default_bank_id);

-- ----------------------------------------------------------------------------
-- Foreign keys (grouped; safe to run after all module tables exist)
-- ----------------------------------------------------------------------------

-- EXPLICIT in SQLite source: company_id REFERENCES companies(company_id) ON DELETE CASCADE
ALTER TABLE voucher_types
    ADD CONSTRAINT fk_voucher_types_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source: parent_vt_id REFERENCES voucher_types(vt_id) ON DELETE SET NULL
ALTER TABLE voucher_types
    ADD CONSTRAINT fk_voucher_types_parent
    FOREIGN KEY (parent_vt_id) REFERENCES voucher_types (vt_id) ON DELETE SET NULL;

-- EXPLICIT in SQLite source: voucher_type_id REFERENCES voucher_types(vt_id) ON DELETE CASCADE
ALTER TABLE voucher_type_configs
    ADD CONSTRAINT fk_voucher_type_configs_vt
    FOREIGN KEY (voucher_type_id) REFERENCES voucher_types (vt_id) ON DELETE CASCADE;

-- INFERRED (no FK in source). default_bank_id references a bank ledger account.
-- Target table is owned by another module (ledgers/accounts). Confirm the
-- referenced table/column before enabling. Left commented to avoid binding to
-- an unverified table.
-- ALTER TABLE voucher_type_configs
--     ADD CONSTRAINT fk_voucher_type_configs_default_bank
--     FOREIGN KEY (default_bank_id) REFERENCES ledgers (ledger_id) ON DELETE SET NULL;
