-- =============================================================================
-- Module: voucher  (Postgres DDL contract)
-- Source: server/voucher/voucher.js  (SQLite schema init)
-- =============================================================================
-- Translation notes:
--   * SQLite INTEGER PRIMARY KEY AUTOINCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   * SQLite TEXT                               -> TEXT
--   * ISO-8601 datetime TEXT (created_at/...)   -> TIMESTAMPTZ DEFAULT now()
--       (app stores ISO strings via SQLite datetime('now'))
--   * date-only TEXT (date, *_date)             -> DATE
--   * INTEGER 0/1 flags (is_*)                  -> BOOLEAN  (0->false, 1->true)
--   * REAL holding MONEY (amount/cgst/...)      -> NUMERIC(18,2)   [NEVER float; precision-critical]
--   * REAL holding QTY / RATE                   -> NUMERIC(18,4)   [NEVER float]
--   * Defaults preserved; datetime defaults -> now().
--   * Foreign keys: the SQLite source declares some FKs inline via REFERENCES.
--     Those are reproduced as EXPLICIT here. Columns that are *_id but lack a
--     REFERENCES clause in source are reproduced as INFERRED (commented).
--   * All FK constraints are grouped at the bottom as ALTER TABLE statements so
--     cross-module load ordering is not a concern.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- vouchers  (header)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vouchers (
    voucher_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              BIGINT      NOT NULL,
    fy_id                   BIGINT      NOT NULL,
    voucher_type            TEXT        NOT NULL,
    voucher_number          TEXT,
    date                    DATE        NOT NULL,                 -- date-only TEXT in SQLite
    status                  TEXT        DEFAULT 'Regular',
    supplier_invoice_no     TEXT,
    supplier_invoice_date   DATE,
    reference_number        TEXT,
    reference_date          DATE,
    narration               TEXT,
    party_ledger_id         BIGINT,
    party_name              TEXT,
    place_of_supply         TEXT,
    is_invoice              BOOLEAN     DEFAULT FALSE,            -- SQLite INTEGER 0/1
    is_accounting_voucher   BOOLEAN     DEFAULT TRUE,            -- SQLite INTEGER default 1
    is_inventory_voucher    BOOLEAN     DEFAULT FALSE,
    is_order_voucher        BOOLEAN     DEFAULT FALSE,
    is_cancelled            BOOLEAN     DEFAULT FALSE,
    is_optional             BOOLEAN     DEFAULT FALSE,
    is_post_dated           BOOLEAN     DEFAULT FALSE,
    created_at              TIMESTAMPTZ DEFAULT now(),            -- ISO-8601 string in SQLite
    updated_at              TIMESTAMPTZ DEFAULT now()             -- ISO-8601 string in SQLite
);

-- ---------------------------------------------------------------------------
-- voucher_entries  (accounting Dr/Cr lines)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_entries (
    entry_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id      BIGINT      NOT NULL,
    ledger_id       BIGINT,
    ledger_name     TEXT,
    type            TEXT        NOT NULL,                         -- 'Dr' | 'Cr'
    amount          NUMERIC(18,2) DEFAULT 0,                     -- MONEY: NEVER float
    amount_forex    NUMERIC(18,2) DEFAULT 0,                     -- MONEY: NEVER float
    currency        TEXT        DEFAULT 'INR',
    narration       TEXT
);

-- ---------------------------------------------------------------------------
-- voucher_stock_entries  (inventory lines)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_stock_entries (
    stock_entry_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id          BIGINT      NOT NULL,
    stock_item_id       BIGINT,
    item_name           TEXT,
    godown_id           BIGINT,
    unit_id             BIGINT,
    quantity            NUMERIC(18,4) DEFAULT 0,                 -- QTY: NEVER float
    rate                NUMERIC(18,4) DEFAULT 0,                 -- RATE: NEVER float
    amount              NUMERIC(18,2) DEFAULT 0,                 -- MONEY: NEVER float
    additional_amount   NUMERIC(18,2) DEFAULT 0,                 -- MONEY: NEVER float
    discount_amount     NUMERIC(18,2) DEFAULT 0,                 -- MONEY: NEVER float
    hsn_code            TEXT,
    gst_rate            NUMERIC(18,4) DEFAULT 0,                 -- rate/percentage
    cgst_amount         NUMERIC(18,2) DEFAULT 0,                 -- MONEY: NEVER float
    sgst_amount         NUMERIC(18,2) DEFAULT 0,                 -- MONEY: NEVER float
    igst_amount         NUMERIC(18,2) DEFAULT 0,                 -- MONEY: NEVER float
    is_source           BOOLEAN     DEFAULT FALSE                -- added via ALTER in source; INTEGER 0/1
);

-- ---------------------------------------------------------------------------
-- voucher_batches  (batch breakdown of a stock line)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_batches (
    batch_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id      BIGINT      NOT NULL,
    stock_entry_id  BIGINT      NOT NULL,
    batch_number    TEXT,
    expiry_date     DATE,
    quantity        NUMERIC(18,4) DEFAULT 0,                     -- QTY: NEVER float
    rate            NUMERIC(18,4) DEFAULT 0                      -- RATE: NEVER float
);

-- ---------------------------------------------------------------------------
-- voucher_bill_references  (bill-wise allocation)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_bill_references (
    bill_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id      BIGINT      NOT NULL,
    ledger_id       BIGINT,
    bill_name       TEXT,
    bill_type       TEXT,                                        -- 'New Ref' | 'Advance' | 'Agst Ref' | ...
    amount          NUMERIC(18,2) DEFAULT 0,                     -- MONEY: NEVER float
    credit_period   TEXT,
    due_date        DATE                                         -- added via ALTER in source
);

-- ---------------------------------------------------------------------------
-- voucher_bank_details
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_bank_details (
    bank_detail_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id          BIGINT      NOT NULL,
    ledger_id           BIGINT,
    transaction_type    TEXT        DEFAULT 'Cheque',
    cheque_range        TEXT,                                    -- added via ALTER in source
    instrument_number   TEXT,
    instrument_date     DATE,
    bank_name           TEXT,
    branch              TEXT,
    amount              NUMERIC(18,2) DEFAULT 0                  -- MONEY: NEVER float
);

-- ---------------------------------------------------------------------------
-- voucher_cost_centres  (cost-centre split of an entry)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_cost_centres (
    cc_entry_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id      BIGINT      NOT NULL,
    entry_id        BIGINT,
    cost_centre_id  BIGINT,
    amount          NUMERIC(18,2) DEFAULT 0                      -- MONEY: NEVER float
);

-- ---------------------------------------------------------------------------
-- voucher_cash_denominations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_cash_denominations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id      BIGINT      NOT NULL,
    ledger_id       BIGINT,
    denomination    TEXT,
    quantity        INTEGER     DEFAULT 0,                       -- count of notes (integer)
    amount          NUMERIC(18,2) DEFAULT 0                      -- MONEY: NEVER float
);

-- ---------------------------------------------------------------------------
-- voucher_receipt_details  (single per voucher in practice)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_receipt_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id          BIGINT      NOT NULL,
    receipt_note_no     TEXT,
    receipt_doc_no      TEXT,
    dispatched_through  TEXT,
    destination         TEXT,
    carrier_name        TEXT,
    bill_of_lading_no   TEXT,
    bill_of_lading_date DATE,
    motor_vehicle_no    TEXT
);

-- ---------------------------------------------------------------------------
-- voucher_party_details
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_party_details (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id      BIGINT      NOT NULL,
    supplier_name   TEXT,
    mailing_name    TEXT,
    address         TEXT,
    state           TEXT,
    country         TEXT
);

-- ---------------------------------------------------------------------------
-- voucher_dispatch_details
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_dispatch_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id          BIGINT      NOT NULL,
    delivery_note_nos   TEXT,
    dispatch_doc_no     TEXT,
    dispatched_through  TEXT,
    destination         TEXT,
    carrier_name        TEXT,
    bill_of_lading_no   TEXT,
    bill_of_lading_date DATE,
    motor_vehicle_no    TEXT
);

-- ---------------------------------------------------------------------------
-- voucher_credit_note_details
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_credit_note_details (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id              BIGINT      NOT NULL,
    tracking_no             TEXT,
    dispatch_doc_no         TEXT,
    dispatched_through      TEXT,
    destination             TEXT,
    carrier_name            TEXT,
    bill_of_lading_no       TEXT,
    bill_of_lading_date     DATE,
    motor_vehicle_no        TEXT,
    original_invoice_no     TEXT,
    original_invoice_date   DATE
);

-- ---------------------------------------------------------------------------
-- voucher_debit_note_details
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_debit_note_details (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id              BIGINT      NOT NULL,
    tracking_no             TEXT,
    dispatch_doc_no         TEXT,
    dispatched_through      TEXT,
    destination             TEXT,
    carrier_name            TEXT,
    bill_of_lading_no       TEXT,
    bill_of_lading_date     DATE,
    motor_vehicle_no        TEXT,
    original_invoice_no     TEXT,
    original_invoice_date   DATE
);

-- ---------------------------------------------------------------------------
-- voucher_payroll_entries
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voucher_payroll_entries (
    payroll_entry_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id          BIGINT      NOT NULL,
    employee_id         BIGINT,
    pay_head_id         BIGINT,
    amount              NUMERIC(18,2) DEFAULT 0                  -- MONEY: NEVER float
);

-- =============================================================================
-- Indexes on FK columns
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_vouchers_company_id            ON vouchers (company_id);
CREATE INDEX IF NOT EXISTS idx_vouchers_fy_id                 ON vouchers (fy_id);
CREATE INDEX IF NOT EXISTS idx_vouchers_party_ledger_id       ON vouchers (party_ledger_id);
CREATE INDEX IF NOT EXISTS idx_vouchers_company_fy            ON vouchers (company_id, fy_id);

CREATE INDEX IF NOT EXISTS idx_ventries_voucher_id            ON voucher_entries (voucher_id);
CREATE INDEX IF NOT EXISTS idx_ventries_ledger_id             ON voucher_entries (ledger_id);

CREATE INDEX IF NOT EXISTS idx_vstock_voucher_id              ON voucher_stock_entries (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vstock_stock_item_id           ON voucher_stock_entries (stock_item_id);
CREATE INDEX IF NOT EXISTS idx_vstock_godown_id               ON voucher_stock_entries (godown_id);
CREATE INDEX IF NOT EXISTS idx_vstock_unit_id                 ON voucher_stock_entries (unit_id);

CREATE INDEX IF NOT EXISTS idx_vbatches_voucher_id            ON voucher_batches (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vbatches_stock_entry_id        ON voucher_batches (stock_entry_id);

CREATE INDEX IF NOT EXISTS idx_vbills_voucher_id              ON voucher_bill_references (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vbills_ledger_id               ON voucher_bill_references (ledger_id);

CREATE INDEX IF NOT EXISTS idx_vbank_voucher_id               ON voucher_bank_details (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vbank_ledger_id                ON voucher_bank_details (ledger_id);

CREATE INDEX IF NOT EXISTS idx_vcc_voucher_id                 ON voucher_cost_centres (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vcc_entry_id                   ON voucher_cost_centres (entry_id);
CREATE INDEX IF NOT EXISTS idx_vcc_cost_centre_id             ON voucher_cost_centres (cost_centre_id);

CREATE INDEX IF NOT EXISTS idx_vcash_voucher_id               ON voucher_cash_denominations (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vcash_ledger_id                ON voucher_cash_denominations (ledger_id);

CREATE INDEX IF NOT EXISTS idx_vreceipt_voucher_id            ON voucher_receipt_details (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vparty_voucher_id              ON voucher_party_details (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vdispatch_voucher_id           ON voucher_dispatch_details (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vcredit_voucher_id             ON voucher_credit_note_details (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vdebit_voucher_id              ON voucher_debit_note_details (voucher_id);

CREATE INDEX IF NOT EXISTS idx_vpayroll_voucher_id            ON voucher_payroll_entries (voucher_id);
CREATE INDEX IF NOT EXISTS idx_vpayroll_employee_id           ON voucher_payroll_entries (employee_id);
CREATE INDEX IF NOT EXISTS idx_vpayroll_pay_head_id           ON voucher_payroll_entries (pay_head_id);

-- =============================================================================
-- Foreign key constraints (grouped; safe to run after all modules' tables exist)
--   EXPLICIT  = REFERENCES present in the SQLite source.
--   INFERRED  = derived from *_id naming; no REFERENCES in source.
-- =============================================================================

-- vouchers ------------------------------------------------------------------
-- EXPLICIT: companies(company_id) ON DELETE CASCADE
ALTER TABLE vouchers ADD CONSTRAINT fk_vouchers_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
-- EXPLICIT: financial_years(fy_id) ON DELETE CASCADE
ALTER TABLE vouchers ADD CONSTRAINT fk_vouchers_fy
    FOREIGN KEY (fy_id) REFERENCES financial_years (fy_id) ON DELETE CASCADE;
-- EXPLICIT: ledgers(ledger_id)
ALTER TABLE vouchers ADD CONSTRAINT fk_vouchers_party_ledger
    FOREIGN KEY (party_ledger_id) REFERENCES ledgers (ledger_id);

-- voucher_entries -----------------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_entries ADD CONSTRAINT fk_ventries_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
-- EXPLICIT: ledgers(ledger_id)
ALTER TABLE voucher_entries ADD CONSTRAINT fk_ventries_ledger
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id);

-- voucher_stock_entries -----------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_stock_entries ADD CONSTRAINT fk_vstock_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
-- INFERRED: stock_item_id -> stock_items(stock_item_id)
ALTER TABLE voucher_stock_entries ADD CONSTRAINT fk_vstock_stock_item
    FOREIGN KEY (stock_item_id) REFERENCES stock_items (stock_item_id);
-- INFERRED: godown_id -> godowns(godown_id)
ALTER TABLE voucher_stock_entries ADD CONSTRAINT fk_vstock_godown
    FOREIGN KEY (godown_id) REFERENCES godowns (godown_id);
-- INFERRED: unit_id -> units(unit_id)
ALTER TABLE voucher_stock_entries ADD CONSTRAINT fk_vstock_unit
    FOREIGN KEY (unit_id) REFERENCES units (unit_id);

-- voucher_batches -----------------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_batches ADD CONSTRAINT fk_vbatches_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
-- EXPLICIT: voucher_stock_entries(stock_entry_id) ON DELETE CASCADE
ALTER TABLE voucher_batches ADD CONSTRAINT fk_vbatches_stock_entry
    FOREIGN KEY (stock_entry_id) REFERENCES voucher_stock_entries (stock_entry_id) ON DELETE CASCADE;

-- voucher_bill_references ---------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_bill_references ADD CONSTRAINT fk_vbills_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
-- EXPLICIT: ledgers(ledger_id)
ALTER TABLE voucher_bill_references ADD CONSTRAINT fk_vbills_ledger
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id);

-- voucher_bank_details ------------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_bank_details ADD CONSTRAINT fk_vbank_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
-- EXPLICIT: ledgers(ledger_id)
ALTER TABLE voucher_bank_details ADD CONSTRAINT fk_vbank_ledger
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id);

-- voucher_cost_centres ------------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_cost_centres ADD CONSTRAINT fk_vcc_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
-- EXPLICIT: voucher_entries(entry_id)
ALTER TABLE voucher_cost_centres ADD CONSTRAINT fk_vcc_entry
    FOREIGN KEY (entry_id) REFERENCES voucher_entries (entry_id);
-- INFERRED: cost_centre_id -> cost_centres(cost_centre_id)
ALTER TABLE voucher_cost_centres ADD CONSTRAINT fk_vcc_cost_centre
    FOREIGN KEY (cost_centre_id) REFERENCES cost_centres (cost_centre_id);

-- voucher_cash_denominations ------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_cash_denominations ADD CONSTRAINT fk_vcash_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
-- EXPLICIT: ledgers(ledger_id)
ALTER TABLE voucher_cash_denominations ADD CONSTRAINT fk_vcash_ledger
    FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id);

-- voucher_receipt_details ---------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_receipt_details ADD CONSTRAINT fk_vreceipt_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;

-- voucher_party_details -----------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_party_details ADD CONSTRAINT fk_vparty_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;

-- voucher_dispatch_details --------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_dispatch_details ADD CONSTRAINT fk_vdispatch_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;

-- voucher_credit_note_details -----------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_credit_note_details ADD CONSTRAINT fk_vcredit_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;

-- voucher_debit_note_details ------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_debit_note_details ADD CONSTRAINT fk_vdebit_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;

-- voucher_payroll_entries ---------------------------------------------------
-- EXPLICIT: vouchers(voucher_id) ON DELETE CASCADE
ALTER TABLE voucher_payroll_entries ADD CONSTRAINT fk_vpayroll_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
-- EXPLICIT: employees(employee_id)
ALTER TABLE voucher_payroll_entries ADD CONSTRAINT fk_vpayroll_employee
    FOREIGN KEY (employee_id) REFERENCES employees (employee_id);
-- EXPLICIT: pay_heads(pay_head_id)
ALTER TABLE voucher_payroll_entries ADD CONSTRAINT fk_vpayroll_pay_head
    FOREIGN KEY (pay_head_id) REFERENCES pay_heads (pay_head_id);
