-- =====================================================================
-- Module: whatsapp
-- Source: server/whatsapp/whatsapp.js (SQLite schema init)
-- Target: PostgreSQL
--
-- Type mapping applied:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   TEXT (datetime via datetime('now')) -> TIMESTAMPTZ, DEFAULT now()
--   INTEGER used as boolean (is_active) -> BOOLEAN (0/1 -> false/true)
--   TEXT -> TEXT
-- Foreign keys: company_id FKs are EXPLICIT in the SQLite source
--   (REFERENCES companies(company_id) ON DELETE CASCADE).
--   voucher_id FK is INFERRED (no explicit constraint in source).
-- =====================================================================

CREATE TABLE whatsapp_config (
    config_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    phone_number_id  TEXT        NOT NULL,                 -- Meta phone number id
    waba_id          TEXT        NOT NULL,                 -- WhatsApp Business Account id
    access_token     TEXT        NOT NULL,                 -- Meta Graph bearer token (sensitive)
    is_active        BOOLEAN     NOT NULL DEFAULT TRUE,    -- SQLite INTEGER DEFAULT 1 (0/1 -> false/true)
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),   -- SQLite TEXT DEFAULT datetime('now') (ISO string)
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()    -- SQLite TEXT DEFAULT datetime('now') (ISO string)
);

CREATE TABLE whatsapp_templates (
    template_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    name             TEXT        NOT NULL,
    language         TEXT        NOT NULL DEFAULT 'en',    -- SQLite DEFAULT 'en'
    category         TEXT,
    status           TEXT        NOT NULL DEFAULT 'PENDING', -- SQLite DEFAULT 'PENDING'
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()    -- SQLite TEXT DEFAULT datetime('now') (ISO string)
);

CREATE TABLE whatsapp_logs (
    log_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    voucher_id       BIGINT,                               -- nullable; null for non-invoice sends
    to_number        TEXT        NOT NULL,
    message_type     TEXT        NOT NULL,                 -- INVOICE | PAYMENT_REMINDER | STATEMENT | TEXT
    template_name    TEXT,
    status           TEXT        NOT NULL DEFAULT 'PENDING', -- SQLite DEFAULT 'PENDING'; runtime: SENT | FAILED
    wamid            TEXT,                                 -- WhatsApp message id (on success)
    error            TEXT,                                 -- JSON-stringified Meta error (on failure)
    sent_at          TIMESTAMPTZ NOT NULL DEFAULT now()    -- SQLite TEXT DEFAULT datetime('now') (ISO string)
);

-- No money/quantity columns in this module: nothing maps to NUMERIC here.
-- (Currency amounts live only in transient template payloads, never persisted.)

-- Helpful indexes on FK columns.
CREATE INDEX idx_whatsapp_config_company_id    ON whatsapp_config (company_id);
CREATE INDEX idx_whatsapp_templates_company_id ON whatsapp_templates (company_id);
CREATE INDEX idx_whatsapp_logs_company_id      ON whatsapp_logs (company_id);
CREATE INDEX idx_whatsapp_logs_voucher_id      ON whatsapp_logs (voucher_id);
CREATE INDEX idx_whatsapp_logs_company_sent_at ON whatsapp_logs (company_id, sent_at DESC); -- supports getLogs ordering

-- A company is expected to have at most one active config; the service
-- upserts by company_id. Enforce one config per company.
ALTER TABLE whatsapp_config
    ADD CONSTRAINT uq_whatsapp_config_company UNIQUE (company_id);

-- =====================================================================
-- Foreign keys (grouped at bottom; cross-module ordering safe)
-- =====================================================================

-- EXPLICIT in SQLite source (REFERENCES companies(company_id) ON DELETE CASCADE)
ALTER TABLE whatsapp_config
    ADD CONSTRAINT fk_whatsapp_config_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source
ALTER TABLE whatsapp_templates
    ADD CONSTRAINT fk_whatsapp_templates_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- EXPLICIT in SQLite source
ALTER TABLE whatsapp_logs
    ADD CONSTRAINT fk_whatsapp_logs_company
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

-- INFERRED from voucher_id column (no explicit FK in SQLite source).
-- References the vouchers table. Nullable -> ON DELETE SET NULL keeps logs.
ALTER TABLE whatsapp_logs
    ADD CONSTRAINT fk_whatsapp_logs_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE SET NULL;
