const { pgTable, bigint, boolean, timestamp } = require('drizzle-orm/pg-core');
const { sql } = require('drizzle-orm');
const { companies } = require('./company');

// Mirrors docs/db/modules/companyCreationSuccess.sql (PostgreSQL contract).
//   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
//   * 0/1 INTEGER flag columns -> BOOLEAN (DEFAULT 1/0 -> DEFAULT TRUE/FALSE).
//   * created_at / updated_at ISO datetime TEXT -> TIMESTAMPTZ DEFAULT now().
//   * company_id FK -> companies(company_id) ON DELETE CASCADE.
const companyCreationSuccess = pgTable('company_creation_success', {
  id: bigint('id', { mode: 'number' })
    .primaryKey()
    .generatedByDefaultAsIdentity(),
  companyId: bigint('company_id', { mode: 'number' })
    .notNull()
    .references(() => companies.companyId, { onDelete: 'cascade' }),
  createdSuccessfully: boolean('created_successfully').notNull().default(true),
  successScreenShown: boolean('success_screen_shown').notNull().default(false),
  showMoreFeatures: boolean('show_more_features').notNull().default(false),
  showAllFeatures: boolean('show_all_features').notNull().default(false),
  defaultFeaturesLoaded: boolean('default_features_loaded').notNull().default(true),
  featureSetupCompleted: boolean('feature_setup_completed').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
});

module.exports = { companyCreationSuccess };
