const { pgTable, bigint, text, date, boolean, timestamp } = require('drizzle-orm/pg-core');
const { sql } = require('drizzle-orm');

// employees — see docs/db/modules/employee.sql (pg DDL contract).
//   INTEGER PK AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
//   date_of_* TEXT -> DATE
//   is_active / define_salary_details 0/1 -> BOOLEAN
//   created_at / updated_at -> TIMESTAMPTZ DEFAULT now()
const employees = pgTable('employees', {
  employeeId: bigint('employee_id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
  companyId: bigint('company_id', { mode: 'number' }).notNull(),
  employeeCategoryId: bigint('employee_category_id', { mode: 'number' }),
  employeeGroupId: bigint('employee_group_id', { mode: 'number' }),
  name: text('name').notNull(),
  alias: text('alias'),
  employeeCode: text('employee_code'),
  designation: text('designation'),
  department: text('department'),
  function: text('function'),
  location: text('location'),
  dateOfJoining: date('date_of_joining'),
  dateOfLeaving: date('date_of_leaving'),
  dateOfBirth: date('date_of_birth'),
  gender: text('gender'),
  bloodGroup: text('blood_group'),
  fatherName: text('father_name'),
  motherName: text('mother_name'),
  spouseName: text('spouse_name'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  pincode: text('pincode'),
  mobile: text('mobile'),
  phone: text('phone'),
  email: text('email'),
  defineSalaryDetails: boolean('define_salary_details').notNull().default(false),
  bankAccountNumber: text('bank_account_number'),
  bankName: text('bank_name'),
  bankBranch: text('bank_branch'),
  ifscCode: text('ifsc_code'),
  applicableTaxRegime: text('applicable_tax_regime'),
  pan: text('pan'),
  aadhaar: text('aadhaar'),
  uan: text('uan'),
  pfAccountNumber: text('pf_account_number'),
  epsAccountNumber: text('eps_account_number'),
  dateOfJoiningPf: date('date_of_joining_pf'),
  pran: text('pran'),
  esiNumber: text('esi_number'),
  esiDispensaryName: text('esi_dispensary_name'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
});

module.exports = { employees };
