const { pgTable, bigint, text, numeric, boolean, date, timestamp } = require('drizzle-orm/pg-core');
const { companies } = require('./company');

// Follows docs/db/modules/gstRegistration.sql.
// gst_id: BIGINT GENERATED BY DEFAULT AS IDENTITY PK.
// 0/1 flags -> BOOLEAN; ISO date strings -> DATE; composition_tax_rate -> NUMERIC(18,4);
// created_at/updated_at -> TIMESTAMPTZ DEFAULT now().
// company_id is a FK to companies(company_id) ON DELETE CASCADE.
const gstRegistrations = pgTable('gst_registrations', {
  gstId: bigint('gst_id', { mode: 'number' })
    .primaryKey()
    .generatedByDefaultAsIdentity(),
  companyId: bigint('company_id', { mode: 'number' }).notNull().references(() => companies.companyId, { onDelete: 'cascade' }),
  registrationType: text('registration_type').default('Regular'),
  registrationStatus: text('registration_status').default('Active'),
  assesseeOfOtherTerritory: boolean('assessee_of_other_territory').notNull().default(false),
  periodicityOfGstr1: text('periodicity_of_gstr1').default('Monthly'),
  gstin: text('gstin'),
  gstUsername: text('gst_username'),
  modeOfFiling: text('mode_of_filing').default('Online'),
  eInvoiceDetails: text('e_invoice_details'),
  eInvoiceApplication: boolean('e_invoice_application').notNull().default(false),
  eWayBillApplicable: boolean('e_way_bill_applicable').notNull().default(false),
  eWayBillApplicableFrom: date('e_way_bill_applicable_from'),
  applicableForIntrastat: boolean('applicable_for_intrastat').notNull().default(false),
  legalName: text('legal_name'),
  tradeName: text('trade_name'),
  stateId: text('state_id'),
  registrationDate: date('registration_date'),
  effectiveFrom: date('effective_from'),
  addressType: text('address_type').default('Primary'),
  goodsDispatchedFrom: text('goods_dispatched_from').default('Primary'),
  eInvoiceApplicableFrom: date('e_invoice_applicable_from'),
  eInvoiceBillFromPlace: text('e_invoice_bill_from_place'),
  compositionTaxRate: numeric('composition_tax_rate', { precision: 18, scale: 4 }),
  compositionTaxCalcBasis: text('composition_tax_calc_basis'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

module.exports = { gstRegistrations };
