module.exports = {
  trialBalance: require('./services/trailbalanceService').trialBalance,
  groupSummaryDrilldown: require('./services/trailbalanceService').groupSummary,
  ledgerMonthlySummary: require('./services/trailbalanceService').ledgerMonthlySummary,
  balanceSheet: require('./services/balanceSheetService').balanceSheet,
  profitLoss: require('./financial/profitAndLoss'),
  ledgerReport: require('./ledger/ledgerReport'),
  cashBook: require('./ledger/cashBook'),
  bankBook: require('./ledger/bankBook'),
  daybook: require('./daybook/daybook'),
  groupSummary: require('./financial/groupSummary'),
  statistics: require('./financial/statistics'),
  costCategorySummary: require('./financial/costCategorySummary'),
  stockItemSummary: require('./inventory/stockItemSummary'),
  stockGroupSummary: require('./inventory/stockGroupSummary'),
  stockCategorySummary: require('./inventory/stockCategorySummary'),
  journalRegister: require('./registers/journalRegister'),
  debitNoteRegister: require('./registers/debitNoteRegister'),
  creditNoteRegister: require('./registers/creditNoteRegister'),
  purchaseRegister: require('./registers/purchaseRegister'),
  salesRegister: require('./registers/salesRegister'),
  memorandumRegister: require('./registers/memorandumRegister'),
};