CREATE TABLE "attendance_vouchers" (
	"attendance_voucher_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attendance_vouchers_attendance_voucher_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"voucher_number" text,
	"date" date NOT NULL,
	"narration" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "attendance_voucher_entries" (
	"entry_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attendance_voucher_entries_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"attendance_voucher_id" bigint NOT NULL,
	"employee_id" bigint,
	"attendance_type_id" bigint,
	"value" numeric(18, 4) DEFAULT '0'
);
--> statement-breakpoint
CREATE TABLE "attendance_types" (
	"attendance_type_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attendance_types_attendance_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"type" text DEFAULT 'Attendance / Leave with Pay' NOT NULL,
	"unit_id" bigint,
	"period" text DEFAULT 'Per Day' NOT NULL,
	"carry_forward" boolean DEFAULT false NOT NULL,
	"encashment" boolean DEFAULT false NOT NULL,
	"max_days" numeric(18, 4) DEFAULT '0' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "balance_sheet_reports" (
	"report_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "balance_sheet_reports_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"report_name" text DEFAULT 'Balance Sheet',
	"report_date" date,
	"comparison_period_start" date,
	"comparison_period_end" date,
	"format_type" text DEFAULT 'Vertical',
	"method_of_showing" text DEFAULT 'Net Balance',
	"show_vertical_balance_sheet" boolean DEFAULT true NOT NULL,
	"show_working_capital_figures" boolean DEFAULT false NOT NULL,
	"profit_or_loss_as_liability" boolean DEFAULT true NOT NULL,
	"show_detail_view" boolean DEFAULT false NOT NULL,
	"show_condensed_view" boolean DEFAULT false NOT NULL,
	"show_schedule_vi" boolean DEFAULT false NOT NULL,
	"include_closing_stock" boolean DEFAULT true NOT NULL,
	"compare_quarterly" boolean DEFAULT false NOT NULL,
	"basis_of_values" text DEFAULT 'Default',
	"change_view" text,
	"exception_reports_enabled" boolean DEFAULT false NOT NULL,
	"filter_enabled" boolean DEFAULT false NOT NULL,
	"saved_view_name" text,
	"filter_details" text,
	"show_profit" boolean DEFAULT true NOT NULL,
	"show_columnar" boolean DEFAULT false NOT NULL,
	"show_optional" boolean DEFAULT false NOT NULL,
	"show_post_dated" boolean DEFAULT false NOT NULL,
	"show_stat_adjustment" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "balance_sheet_views" (
	"view_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "balance_sheet_views_view_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"report_id" bigint NOT NULL,
	"company_id" bigint NOT NULL,
	"report_date" date,
	"group_name" text,
	"parent_group_name" text,
	"opening_balance" numeric(18, 2) DEFAULT '0' NOT NULL,
	"side" text DEFAULT 'Assets' NOT NULL,
	"current_period_debit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"current_period_credit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"closing_balance" numeric(18, 2) DEFAULT '0' NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_total_row" boolean DEFAULT false NOT NULL,
	"is_drill_down_available" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reconciliations" (
	"reconciliation_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reconciliations_reconciliation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entry_id" bigint NOT NULL,
	"voucher_id" bigint NOT NULL,
	"ledger_id" bigint NOT NULL,
	"reconciled_date" date,
	"bank_date" date,
	"bank_reference" text,
	"reconciled_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "companies" (
	"company_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "companies_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"mailing_name" text,
	"address1" text,
	"address2" text,
	"state" text,
	"country" text,
	"pincode" text,
	"telephone" text,
	"mobile" text,
	"fax" text,
	"email" text,
	"website" text,
	"base_currency_symbol" text,
	"formal_name" text,
	"financial_year_beginning_from" text,
	"books_beginning_from" text,
	"password" text,
	"access_control" text,
	"edit_log" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company_creation_success" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_creation_success_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"created_successfully" boolean DEFAULT true NOT NULL,
	"success_screen_shown" boolean DEFAULT false NOT NULL,
	"show_more_features" boolean DEFAULT false NOT NULL,
	"show_all_features" boolean DEFAULT false NOT NULL,
	"default_features_loaded" boolean DEFAULT true NOT NULL,
	"feature_setup_completed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company_feature_values" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_feature_values_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"feature_item_id" bigint NOT NULL,
	"value_boolean" boolean DEFAULT false NOT NULL,
	"value_text" text,
	"value_number" double precision,
	"value_date" date,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company_gst_details" (
	"company_id" bigint PRIMARY KEY NOT NULL,
	"hsn_sac_type" text DEFAULT 'Not Defined',
	"hsn_sac_code" text,
	"description" text,
	"taxability_type" text DEFAULT 'Not Defined',
	"gst_rate" numeric(18, 4) DEFAULT '0',
	"interstate_threshold_limit" numeric(18, 2) DEFAULT '50000',
	"intrastate_threshold_limit" numeric(18, 2) DEFAULT '50000',
	"threshold_limit_includes" text DEFAULT 'Value of Invoice',
	"create_hsn_summary_for" text DEFAULT 'All Sections',
	"minimum_hsn_length" integer DEFAULT 4,
	"show_gst_advances" boolean DEFAULT false,
	"update_gst_status" boolean DEFAULT false,
	"gst_returns_configured" boolean DEFAULT false,
	"effective_date" text DEFAULT '1-Apr-26',
	"download_gst_registration" text,
	"download_return_type" text DEFAULT 'All Returns',
	"set_state_wise_threshold_limit" boolean DEFAULT false,
	"state_wise_limits" jsonb,
	"gst_advances_applicable_from" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company_pan_cin_details" (
	"company_id" bigint PRIMARY KEY NOT NULL,
	"pan" text,
	"cin" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company_tcs_details" (
	"company_id" bigint PRIMARY KEY NOT NULL,
	"tan_reg_number" text,
	"tan" text,
	"collector_type" text DEFAULT 'Company',
	"collector_branch" text,
	"set_alter_person_responsible" boolean DEFAULT false NOT NULL,
	"person_responsible_name" text,
	"person_responsible_son_daughter_of" text,
	"person_responsible_designation" text,
	"person_responsible_pan" text,
	"person_responsible_flat_no" text,
	"person_responsible_premises" text,
	"person_responsible_road" text,
	"person_responsible_area" text,
	"person_responsible_city" text,
	"person_responsible_state" text,
	"person_responsible_pincode" text,
	"person_responsible_phone" text,
	"person_responsible_std_code" text,
	"person_responsible_telephone" text,
	"person_responsible_email" text,
	"ignore_it_exemption" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company_tds_details" (
	"company_id" bigint PRIMARY KEY NOT NULL,
	"tan_reg_number" text,
	"tan" text,
	"deductor_type" text DEFAULT 'Company' NOT NULL,
	"deductor_branch" text,
	"set_alter_person_responsible" boolean DEFAULT false NOT NULL,
	"person_responsible_name" text,
	"person_responsible_designation" text,
	"person_responsible_pan" text,
	"person_responsible_phone" text,
	"person_responsible_email" text,
	"ignore_it_exemption" boolean DEFAULT true NOT NULL,
	"activate_tds_for_items" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cost_centres" (
	"cc_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cost_centres_cc_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"parent_id" bigint,
	"category" text DEFAULT 'Primary' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "currencies" (
	"currency_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "currencies_currency_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"formal_name" text,
	"iso_code" text NOT NULL,
	"symbol" text,
	"decimal_places" integer DEFAULT 2 NOT NULL,
	"decimal_symbol" text DEFAULT '.' NOT NULL,
	"decimal_places_in_words" text,
	"suffix_symbol_to_amount" boolean DEFAULT false NOT NULL,
	"show_amount_in_millions" boolean DEFAULT false NOT NULL,
	"word_representing_amount_after_decimal" text,
	"add_space_between_amount_and_symbol" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "day_book_reports" (
	"report_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "day_book_reports_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"report_name" text DEFAULT 'Day Book',
	"date_from" date,
	"date_to" date,
	"selected_company_id" bigint,
	"basis_of_values" text DEFAULT 'Default',
	"change_view" text,
	"exception_reports_enabled" boolean DEFAULT false NOT NULL,
	"saved_view_name" text,
	"filter_enabled" boolean DEFAULT false NOT NULL,
	"filter_details" text,
	"show_profit" boolean DEFAULT false NOT NULL,
	"show_columnar" boolean DEFAULT false NOT NULL,
	"show_optional" boolean DEFAULT false NOT NULL,
	"show_post_dated" boolean DEFAULT false NOT NULL,
	"show_stat_adjustment" boolean DEFAULT false NOT NULL,
	"show_details" boolean DEFAULT true NOT NULL,
	"show_related_reports" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "day_book_entries" (
	"entry_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "day_book_entries_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"report_id" bigint NOT NULL,
	"company_id" bigint NOT NULL,
	"voucher_id" bigint,
	"voucher_date" date,
	"particulars" text,
	"voucher_type" text,
	"voucher_number" text,
	"debit_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"credit_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"narration" text,
	"party_ledger_name" text,
	"show_profit" boolean DEFAULT false NOT NULL,
	"is_optional" boolean DEFAULT false NOT NULL,
	"is_post_dated" boolean DEFAULT false NOT NULL,
	"is_stat_adjustment" boolean DEFAULT false NOT NULL,
	"gross_profit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"cost" numeric(18, 2) DEFAULT '0' NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_drillable" boolean DEFAULT true NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "day_book_entry_lines" (
	"line_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "day_book_entry_lines_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entry_id" bigint NOT NULL,
	"ledger_id" bigint,
	"particulars" text,
	"debit_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"credit_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"line_order" integer DEFAULT 0 NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "einvoice_credentials" (
	"cred_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "einvoice_credentials_cred_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"client_id" text NOT NULL,
	"client_secret" text NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	"app_key" text NOT NULL,
	"is_sandbox" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "einvoice_records" (
	"irn_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "einvoice_records_irn_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"voucher_id" bigint,
	"invoice_number" text NOT NULL,
	"invoice_date" text NOT NULL,
	"buyer_gstin" text,
	"irn" text,
	"ack_no" text,
	"ack_dt" text,
	"signed_invoice" text,
	"signed_qr_code" text,
	"ewb_no" text,
	"ewb_dt" text,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"cancel_reason" integer,
	"cancel_remarks" text,
	"cancelled_at" timestamp with time zone,
	"raw_response" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employees" (
	"employee_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employees_employee_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"employee_category_id" bigint,
	"employee_group_id" bigint,
	"name" text NOT NULL,
	"alias" text,
	"employee_code" text,
	"designation" text,
	"department" text,
	"function" text,
	"location" text,
	"date_of_joining" date,
	"date_of_leaving" date,
	"date_of_birth" date,
	"gender" text,
	"blood_group" text,
	"father_name" text,
	"mother_name" text,
	"spouse_name" text,
	"address" text,
	"city" text,
	"state" text,
	"pincode" text,
	"mobile" text,
	"phone" text,
	"email" text,
	"define_salary_details" boolean DEFAULT false NOT NULL,
	"bank_account_number" text,
	"bank_name" text,
	"bank_branch" text,
	"ifsc_code" text,
	"applicable_tax_regime" text,
	"pan" text,
	"aadhaar" text,
	"uan" text,
	"pf_account_number" text,
	"eps_account_number" text,
	"date_of_joining_pf" date,
	"pran" text,
	"esi_number" text,
	"esi_dispensary_name" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employee_categories" (
	"employee_category_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employee_categories_employee_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"allocate_revenue" boolean DEFAULT false NOT NULL,
	"allocate_non_revenue" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employee_groups" (
	"employee_group_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employee_groups_employee_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"employee_category_id" bigint,
	"name" text NOT NULL,
	"alias" text,
	"parent_group_id" bigint,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "feature_groups" (
	"feature_group_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feature_groups_feature_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_key" text NOT NULL,
	"group_name" text NOT NULL,
	"online_access" boolean DEFAULT false NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "feature_groups_group_key_unique" UNIQUE("group_key")
);
--> statement-breakpoint
CREATE TABLE "feature_items" (
	"feature_item_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feature_items_feature_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"feature_group_id" bigint NOT NULL,
	"feature_key" text NOT NULL,
	"feature_name" text NOT NULL,
	"description" text,
	"control_type" text DEFAULT 'boolean' NOT NULL,
	"default_value_boolean" boolean DEFAULT false NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_mandatory" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "feature_items_feature_key_unique" UNIQUE("feature_key")
);
--> statement-breakpoint
CREATE TABLE "financial_years" (
	"fy_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "financial_years_fy_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"is_closed" boolean DEFAULT false NOT NULL,
	"closing_date" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "godowns" (
	"godown_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "godowns_godown_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"parent_godown_id" bigint,
	"address" text,
	"city" text,
	"state" text,
	"pincode" text,
	"is_primary" boolean DEFAULT false NOT NULL,
	"is_main_location" boolean DEFAULT false NOT NULL,
	"allow_storage_of_materials" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "groups" (
	"group_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "groups_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"parent_group_id" bigint,
	"is_primary" boolean DEFAULT false NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"nature" text,
	"set_alter_tds_details" boolean DEFAULT false NOT NULL,
	"set_alter_tcs_details" boolean DEFAULT false NOT NULL,
	"set_alter_other_statutory_details" boolean DEFAULT false NOT NULL,
	"hsn_sac_source" text,
	"hsn_sac_description" text,
	"gst_rate_source" text,
	"taxability_type" text,
	"behaves_like_subledger" boolean DEFAULT false NOT NULL,
	"show_net_debit_credit" boolean DEFAULT false NOT NULL,
	"used_for_calculation" boolean DEFAULT false NOT NULL,
	"allocation_method" text DEFAULT 'Average Cost' NOT NULL,
	"gst_rate" numeric(18, 4),
	"cgst_rate" numeric(18, 4),
	"sgst_rate" numeric(18, 4),
	"igst_rate" numeric(18, 4),
	"hsn_sac_code" text,
	"statutory_details" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"group_type" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gst_hsn_rates" (
	"rate_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gst_hsn_rates_rate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"hsn_code" text NOT NULL,
	"effective_from" date NOT NULL,
	"effective_to" date,
	"taxability" text DEFAULT 'Taxable' NOT NULL,
	"gst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"cgst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"sgst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"igst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"cess_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"type_of_supply" text DEFAULT 'Goods' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gst_voucher_tax_lines" (
	"tax_line_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gst_voucher_tax_lines_tax_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"entry_id" bigint,
	"hsn_code" text,
	"description" text,
	"quantity" numeric(18, 4) DEFAULT '0' NOT NULL,
	"unit" text,
	"assessable_value" numeric(18, 2) DEFAULT '0' NOT NULL,
	"tax_type" text,
	"rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"is_inter_state" boolean DEFAULT false NOT NULL,
	"party_gstin" text,
	"party_state" text,
	"gst_classification_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gstr1_exports" (
	"export_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gstr1_exports_export_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"fy_id" bigint NOT NULL,
	"return_period" text NOT NULL,
	"filed_date" date,
	"status" text DEFAULT 'Draft' NOT NULL,
	"b2b_json" text,
	"b2cl_json" text,
	"b2cs_json" text,
	"cdnr_json" text,
	"hsn_json" text,
	"errors_json" text,
	"full_payload_json" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gst_classifications" (
	"gc_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gst_classifications_gc_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"hsn_sac_code" text,
	"is_non_gst_goods" boolean DEFAULT false NOT NULL,
	"nature_of_transaction" text DEFAULT 'Not Applicable' NOT NULL,
	"taxability" text DEFAULT 'Unknown' NOT NULL,
	"is_reverse_charge" boolean DEFAULT false NOT NULL,
	"is_ineligible_for_itc" boolean DEFAULT false NOT NULL,
	"rate_type" text DEFAULT 'Fixed Rate' NOT NULL,
	"igst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"igst_valuation_type" text DEFAULT 'Based on Value' NOT NULL,
	"cgst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"cgst_valuation_type" text DEFAULT 'Based on Value' NOT NULL,
	"sgst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"sgst_valuation_type" text DEFAULT 'Based on Value' NOT NULL,
	"cess_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"cess_valuation_type" text DEFAULT 'Based on Value' NOT NULL,
	"gst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"gst_rate_details" text,
	"valuation_type" text DEFAULT 'Based on Value' NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gst_registrations" (
	"gst_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gst_registrations_gst_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"registration_type" text DEFAULT 'Regular',
	"registration_status" text DEFAULT 'Active',
	"assessee_of_other_territory" boolean DEFAULT false NOT NULL,
	"periodicity_of_gstr1" text DEFAULT 'Monthly',
	"gstin" text,
	"gst_username" text,
	"mode_of_filing" text DEFAULT 'Online',
	"e_invoice_details" text,
	"e_invoice_application" boolean DEFAULT false NOT NULL,
	"e_way_bill_applicable" boolean DEFAULT false NOT NULL,
	"e_way_bill_applicable_from" date,
	"applicable_for_intrastat" boolean DEFAULT false NOT NULL,
	"legal_name" text,
	"trade_name" text,
	"state_id" text,
	"registration_date" date,
	"effective_from" date,
	"address_type" text DEFAULT 'Primary',
	"goods_dispatched_from" text DEFAULT 'Primary',
	"e_invoice_applicable_from" date,
	"e_invoice_bill_from_place" text,
	"composition_tax_rate" numeric(18, 4),
	"composition_tax_calc_basis" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ledgers" (
	"ledger_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ledgers_ledger_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"group_id" bigint,
	"name" text NOT NULL,
	"alias" text,
	"ledger_type" text DEFAULT 'General',
	"nature" text,
	"opening_balance" numeric(18, 2) DEFAULT '0',
	"closing_balance" numeric(18, 2) DEFAULT '0',
	"is_bill_wise" boolean DEFAULT false,
	"maintain_inventory_values" boolean DEFAULT false,
	"mailing_name" text,
	"address1" text,
	"address2" text,
	"city" text,
	"state" text,
	"country" text,
	"pincode" text,
	"phone" text,
	"email" text,
	"gstin" text,
	"pan" text,
	"registration_type" text DEFAULT 'Unregistered',
	"allow_cost_centres" boolean DEFAULT false,
	"default_credit_period" integer DEFAULT 0,
	"check_credit_days" integer DEFAULT 0,
	"invoice_rounding" boolean DEFAULT false,
	"rounding_method" text,
	"rounding_limit" numeric(18, 4) DEFAULT '0',
	"additional_gst_details" boolean DEFAULT false,
	"service_tax_details" boolean DEFAULT false,
	"include_assessable_value" text DEFAULT 'Not Applicable',
	"method_of_calculation" text DEFAULT 'Based on Value',
	"other_statutory_details" boolean DEFAULT false,
	"is_active" boolean DEFAULT true,
	"is_predefined" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ledger_bank_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ledger_bank_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ledger_id" bigint NOT NULL,
	"account_holder_name" text,
	"account_number" text,
	"ifsc_code" text,
	"swift_code" text,
	"bank_name" text,
	"branch_name" text,
	"bank_configuration" text,
	"cheque_book_start_no" text,
	"cheque_book_end_no" text,
	"enable_cheque_printing" boolean DEFAULT false,
	"cheque_printing_configuration" text,
	"od_limit" numeric(18, 2) DEFAULT '0',
	"transaction_type" text,
	"cross_using" text DEFAULT 'A/c Payee',
	"company_bank" text
);
--> statement-breakpoint
CREATE TABLE "ledger_statutory_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ledger_statutory_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ledger_id" bigint NOT NULL,
	"gst_applicability" text DEFAULT 'Not Applicable',
	"hsn_sac_code" text,
	"hsn_sac_description" text,
	"gst_rate" numeric(18, 4) DEFAULT '0',
	"cgst_rate" numeric(18, 4) DEFAULT '0',
	"sgst_rate" numeric(18, 4) DEFAULT '0',
	"igst_rate" numeric(18, 4) DEFAULT '0',
	"type_of_duty_tax" text,
	"percentage_of_calculation" numeric(18, 4) DEFAULT '0',
	"statutory_details" text,
	"include_in_assessable_value_calculation" text DEFAULT 'Not Applicable',
	"appropriate_to" text DEFAULT 'Goods',
	"method_of_calculation" text DEFAULT 'Based on Quantity'
);
--> statement-breakpoint
CREATE TABLE "pay_heads" (
	"pay_head_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pay_heads_pay_head_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"pay_head_type" text DEFAULT 'Earnings for Employees',
	"income_type" text DEFAULT 'Fixed',
	"under_group" text,
	"affects_net_salary" boolean DEFAULT true,
	"payslip_display_name" text,
	"use_for_gratuity" boolean DEFAULT false,
	"set_alter_income_tax" boolean DEFAULT false,
	"calculation_type" text DEFAULT 'As User Defined Value',
	"calculation_period" text DEFAULT 'Months',
	"rounding_method" text DEFAULT 'Not Applicable',
	"rounding_limit" numeric(18, 4) DEFAULT '0',
	"statutory_component" text,
	"percentage_or_amount" numeric(18, 4) DEFAULT '0',
	"is_active" boolean DEFAULT true,
	"is_predefined" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "pay_head_slab_lines" (
	"slab_line_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pay_head_slab_lines_slab_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"pay_head_id" bigint NOT NULL,
	"effective_from" date,
	"amount_gt" numeric(18, 4) DEFAULT '0',
	"amount_up_to" numeric(18, 4) DEFAULT '0',
	"slab_type" text,
	"value" numeric(18, 4) DEFAULT '0',
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "pay_head_formula_lines" (
	"formula_line_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pay_head_formula_lines_formula_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"pay_head_id" bigint NOT NULL,
	"sequence" integer DEFAULT 0,
	"function" text,
	"pay_head_id_ref" bigint,
	"operator" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "payroll_units" (
	"payroll_unit_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payroll_units_payroll_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"symbol" text,
	"formal_name" text,
	"unit_type" text DEFAULT 'Simple' NOT NULL,
	"decimal_places" integer DEFAULT 0 NOT NULL,
	"first_unit" text,
	"conversion" numeric(18, 4),
	"second_unit" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "physical_stock_entries" (
	"physical_stock_entry_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "physical_stock_entries_physical_stock_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"voucher_no" text,
	"voucher_date" date NOT NULL,
	"reference_no" text,
	"narration" text,
	"is_optional" boolean DEFAULT false NOT NULL,
	"is_post_dated" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "physical_stock_entry_lines" (
	"line_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "physical_stock_entry_lines_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"physical_stock_entry_id" bigint NOT NULL,
	"stock_item_id" bigint,
	"godown_id" bigint,
	"batch_no" text,
	"lot_no" text,
	"manufacturing_date" date,
	"expiry_date" date,
	"quantity" numeric(18, 4) DEFAULT '0' NOT NULL,
	"rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"line_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price_levels" (
	"price_level_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_levels_price_level_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"level_index" integer NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "uq_price_levels_company_level" UNIQUE("company_id","level_index")
);
--> statement-breakpoint
CREATE TABLE "price_lists" (
	"price_list_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_lists_price_list_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"stock_group" text DEFAULT 'All Items' NOT NULL,
	"price_level" text NOT NULL,
	"applicable_from" date NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price_list_lines" (
	"line_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_list_lines_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"price_list_id" bigint NOT NULL,
	"item_id" bigint,
	"particulars" text NOT NULL,
	"qty_from" numeric(18, 4) DEFAULT '0' NOT NULL,
	"qty_less_than" numeric(18, 4) DEFAULT '0' NOT NULL,
	"rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"disc_percent" numeric(18, 4) DEFAULT '0' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "profit_loss_reports" (
	"report_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "profit_loss_reports_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"report_name" text DEFAULT 'Profit & Loss A/c',
	"report_date" date,
	"period_start" date,
	"period_end" date,
	"format_type" text DEFAULT 'Vertical',
	"compare_with_previous_period" boolean DEFAULT false NOT NULL,
	"comparison_period_start" date,
	"comparison_period_end" date,
	"basis_of_values" text DEFAULT 'Default',
	"change_view" text,
	"exception_report_enabled" boolean DEFAULT false NOT NULL,
	"saved_view_name" text,
	"filter_enabled" boolean DEFAULT false NOT NULL,
	"filter_details" text,
	"show_detail_view" boolean DEFAULT false NOT NULL,
	"show_condensed_view" boolean DEFAULT false NOT NULL,
	"show_percentage_of_sales" boolean DEFAULT false NOT NULL,
	"show_auto_column" boolean DEFAULT false NOT NULL,
	"show_profit" boolean DEFAULT true NOT NULL,
	"show_optional" boolean DEFAULT false NOT NULL,
	"show_post_dated" boolean DEFAULT false NOT NULL,
	"show_stat_adjustment" boolean DEFAULT false NOT NULL,
	"show_schedule_vi" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "profit_loss_views" (
	"view_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "profit_loss_views_view_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"report_id" bigint NOT NULL,
	"company_id" bigint NOT NULL,
	"report_date" date,
	"section" text DEFAULT 'Income',
	"group_name" text,
	"parent_group_name" text,
	"opening_balance" numeric(18, 2) DEFAULT '0' NOT NULL,
	"current_period_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"closing_balance" numeric(18, 2) DEFAULT '0' NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_total_row" boolean DEFAULT false NOT NULL,
	"is_gross_profit_row" boolean DEFAULT false NOT NULL,
	"is_drill_down_available" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "salary_structures" (
	"structure_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "salary_structures_structure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"employee_id" bigint NOT NULL,
	"effective_from" date NOT NULL,
	"pay_head_id" bigint NOT NULL,
	"amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"calculation_mode" text DEFAULT 'Flat Rate' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock_categories" (
	"sc_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_categories_sc_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"description" text,
	"parent_category_id" bigint,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock_groups" (
	"sg_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_groups_sg_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"parent_group_id" bigint,
	"should_quantities_be_added" boolean DEFAULT false NOT NULL,
	"hsn_sac_code" text,
	"hsn_sac_description" text,
	"gst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"cgst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"sgst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"taxability_type" text,
	"statutory_details" text,
	"is_primary" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock_items" (
	"item_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_items_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"group_id" bigint,
	"category_id" bigint,
	"unit_id" bigint,
	"gst_applicable" text DEFAULT 'Not Applicable' NOT NULL,
	"hsn_sac" text,
	"source_of_details" text DEFAULT 'As per Company/Stock Group' NOT NULL,
	"hsn_sac_description" text,
	"hsn_code" text,
	"sac_code" text,
	"gst_rate_details" text,
	"source_of_gst_rate" text DEFAULT 'As per Company/Stock Group' NOT NULL,
	"taxability_type" text,
	"gst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"cgst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"sgst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"igst_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"type_of_supply" text DEFAULT 'Goods' NOT NULL,
	"rate_of_duty" numeric(18, 4) DEFAULT '0' NOT NULL,
	"statutory_details" text,
	"opening_quantity" numeric(18, 4) DEFAULT '0' NOT NULL,
	"opening_rate" numeric(18, 2) DEFAULT '0' NOT NULL,
	"opening_value" numeric(18, 2) DEFAULT '0' NOT NULL,
	"reorder_level" numeric(18, 4) DEFAULT '0' NOT NULL,
	"reorder_quantity" numeric(18, 4) DEFAULT '0' NOT NULL,
	"track_batches" boolean DEFAULT false NOT NULL,
	"track_expiry" boolean DEFAULT false NOT NULL,
	"track_date_of_manufacturing" boolean DEFAULT false NOT NULL,
	"enable_cost_tracking" boolean DEFAULT false NOT NULL,
	"has_bom" boolean DEFAULT false NOT NULL,
	"bom_name" text,
	"excise_applicable" text DEFAULT 'Not Applicable' NOT NULL,
	"excise_details" text,
	"excise_tariff_name" text,
	"excise_tariff_hsn_code" text,
	"excise_tariff_uom" text DEFAULT 'Undefined' NOT NULL,
	"excise_tariff_valuation_type" text DEFAULT 'Undefined' NOT NULL,
	"excise_tariff_rate" numeric(18, 4) DEFAULT '0' NOT NULL,
	"excise_tariff_rate_per_unit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"vat_applicable" text DEFAULT 'Applicable' NOT NULL,
	"vat_details" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock_item_opening_allocations" (
	"allocation_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_item_opening_allocations_allocation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"item_id" bigint NOT NULL,
	"godown_id" bigint,
	"batch_number" text,
	"mfg_date" date,
	"expiry_date" date,
	"quantity" numeric(18, 4) DEFAULT '0' NOT NULL,
	"rate" numeric(18, 2) DEFAULT '0' NOT NULL,
	"amount" numeric(18, 2) DEFAULT '0' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tally_features" (
	"tally_feature_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tally_features_tally_feature_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"maintain_accounts" boolean DEFAULT true NOT NULL,
	"enable_bill_wise_entry" boolean DEFAULT false NOT NULL,
	"enable_cost_centres" boolean DEFAULT false NOT NULL,
	"maintain_inventory" boolean DEFAULT true NOT NULL,
	"integrate_accounts_with_inventory" boolean DEFAULT true NOT NULL,
	"enable_multiple_price_levels" boolean DEFAULT false NOT NULL,
	"enable_batches" boolean DEFAULT false NOT NULL,
	"maintain_expiry_date_for_batches" boolean DEFAULT false NOT NULL,
	"use_discount_column_in_invoices" boolean DEFAULT false NOT NULL,
	"use_separate_actual_billed_qty" boolean DEFAULT false NOT NULL,
	"enable_gst" boolean DEFAULT false NOT NULL,
	"set_alter_company_gst_details" boolean DEFAULT false NOT NULL,
	"enable_tds" boolean DEFAULT false NOT NULL,
	"enable_tcs" boolean DEFAULT false NOT NULL,
	"enable_browser_access_for_reports" boolean DEFAULT false NOT NULL,
	"enable_tally_net_services" boolean DEFAULT false NOT NULL,
	"enable_payment_request_qr" boolean DEFAULT false NOT NULL,
	"enable_multiple_addresses" boolean DEFAULT false NOT NULL,
	"mark_modified_vouchers" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tax_units" (
	"tax_unit_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tax_units_tax_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"alias" text,
	"address_line1" text,
	"address_line2" text,
	"address_line3" text,
	"address_line4" text,
	"state" text,
	"pincode" text,
	"telephone" text,
	"registered_for" text DEFAULT 'Excise' NOT NULL,
	"set_alter_excise_details" boolean DEFAULT false NOT NULL,
	"registration_type" text DEFAULT 'Importer' NOT NULL,
	"ecc_number" text,
	"set_alter_excise_tariff" boolean DEFAULT false NOT NULL,
	"set_alter_rule11_book" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tcs_nature_of_goods" (
	"tcs_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tcs_nature_of_goods_tcs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"section" text,
	"payment_code" text,
	"rate_individual_with_pan" numeric(18, 4) DEFAULT '0' NOT NULL,
	"rate_individual_without_pan" numeric(18, 4) DEFAULT '0' NOT NULL,
	"rate_other_with_pan" numeric(18, 4) DEFAULT '0' NOT NULL,
	"rate_other_without_pan" numeric(18, 4) DEFAULT '0' NOT NULL,
	"is_own_status" boolean DEFAULT false NOT NULL,
	"tax_on_receipt_or_realization" text DEFAULT 'Tax Calculated on Receipt' NOT NULL,
	"threshold_level" numeric(18, 2) DEFAULT '0' NOT NULL,
	"is_zero_rated" boolean DEFAULT false NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tds_nature_of_payment" (
	"tds_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tds_nature_of_payment_tds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"section" text,
	"payment_code" text,
	"remittance_code" text,
	"rate_individual_with_pan" numeric(18, 4) DEFAULT '0' NOT NULL,
	"rate_other_with_pan" numeric(18, 4) DEFAULT '0' NOT NULL,
	"is_zero_rated" boolean DEFAULT false NOT NULL,
	"threshold_limit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trial_balance_reports" (
	"report_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trial_balance_reports_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"company_name" text,
	"report_date" date,
	"period_start" date,
	"period_end" date,
	"show_closing_balance" boolean DEFAULT true NOT NULL,
	"show_debit_credit" boolean DEFAULT true NOT NULL,
	"show_groups" boolean DEFAULT true NOT NULL,
	"show_grand_total" boolean DEFAULT true NOT NULL,
	"detailed_mode" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trial_balance_rows" (
	"row_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trial_balance_rows_row_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"report_id" bigint NOT NULL,
	"parent_row_id" bigint,
	"row_type" text DEFAULT 'Ledger' NOT NULL,
	"particulars" text,
	"group_id" bigint,
	"ledger_id" bigint,
	"display_order" integer DEFAULT 0 NOT NULL,
	"opening_debit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"opening_credit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"period_debit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"period_credit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"closing_debit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"closing_credit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"is_drillable" boolean DEFAULT true NOT NULL,
	"is_grand_total" boolean DEFAULT false NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "units" (
	"unit_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "units_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"symbol" text NOT NULL,
	"formal_name" text,
	"decimal_places" integer DEFAULT 0 NOT NULL,
	"unit_quantity_code" text,
	"unit_type" text DEFAULT 'Simple' NOT NULL,
	"is_simple" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"first_unit_id" bigint,
	"second_unit_id" bigint,
	"conversion_factor" numeric(18, 4) DEFAULT '1',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vouchers" (
	"voucher_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vouchers_voucher_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"fy_id" bigint NOT NULL,
	"voucher_type" text NOT NULL,
	"voucher_number" text,
	"date" date NOT NULL,
	"status" text DEFAULT 'Regular',
	"supplier_invoice_no" text,
	"supplier_invoice_date" date,
	"reference_number" text,
	"reference_date" date,
	"narration" text,
	"party_ledger_id" bigint,
	"party_name" text,
	"place_of_supply" text,
	"is_invoice" boolean DEFAULT false,
	"is_accounting_voucher" boolean DEFAULT true,
	"is_inventory_voucher" boolean DEFAULT false,
	"is_order_voucher" boolean DEFAULT false,
	"is_cancelled" boolean DEFAULT false,
	"is_optional" boolean DEFAULT false,
	"is_post_dated" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "voucher_entries" (
	"entry_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_entries_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"ledger_id" bigint,
	"ledger_name" text,
	"type" text NOT NULL,
	"amount" numeric(18, 2) DEFAULT '0',
	"amount_forex" numeric(18, 2) DEFAULT '0',
	"currency" text DEFAULT 'INR',
	"narration" text
);
--> statement-breakpoint
CREATE TABLE "voucher_stock_entries" (
	"stock_entry_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_stock_entries_stock_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"stock_item_id" bigint,
	"item_name" text,
	"godown_id" bigint,
	"unit_id" bigint,
	"quantity" numeric(18, 4) DEFAULT '0',
	"rate" numeric(18, 4) DEFAULT '0',
	"amount" numeric(18, 2) DEFAULT '0',
	"additional_amount" numeric(18, 2) DEFAULT '0',
	"discount_amount" numeric(18, 2) DEFAULT '0',
	"hsn_code" text,
	"gst_rate" numeric(18, 4) DEFAULT '0',
	"cgst_amount" numeric(18, 2) DEFAULT '0',
	"sgst_amount" numeric(18, 2) DEFAULT '0',
	"igst_amount" numeric(18, 2) DEFAULT '0',
	"is_source" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "voucher_batches" (
	"batch_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_batches_batch_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"stock_entry_id" bigint NOT NULL,
	"batch_number" text,
	"expiry_date" date,
	"quantity" numeric(18, 4) DEFAULT '0',
	"rate" numeric(18, 4) DEFAULT '0'
);
--> statement-breakpoint
CREATE TABLE "voucher_bill_references" (
	"bill_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_bill_references_bill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"ledger_id" bigint,
	"bill_name" text,
	"bill_type" text,
	"amount" numeric(18, 2) DEFAULT '0',
	"credit_period" text,
	"due_date" date
);
--> statement-breakpoint
CREATE TABLE "voucher_bank_details" (
	"bank_detail_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_bank_details_bank_detail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"ledger_id" bigint,
	"transaction_type" text DEFAULT 'Cheque',
	"cheque_range" text,
	"instrument_number" text,
	"instrument_date" date,
	"bank_name" text,
	"branch" text,
	"amount" numeric(18, 2) DEFAULT '0'
);
--> statement-breakpoint
CREATE TABLE "voucher_cost_centres" (
	"cc_entry_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_cost_centres_cc_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"entry_id" bigint,
	"cost_centre_id" bigint,
	"amount" numeric(18, 2) DEFAULT '0'
);
--> statement-breakpoint
CREATE TABLE "voucher_cash_denominations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_cash_denominations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"ledger_id" bigint,
	"denomination" text,
	"quantity" integer DEFAULT 0,
	"amount" numeric(18, 2) DEFAULT '0'
);
--> statement-breakpoint
CREATE TABLE "voucher_receipt_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_receipt_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"receipt_note_no" text,
	"receipt_doc_no" text,
	"dispatched_through" text,
	"destination" text,
	"carrier_name" text,
	"bill_of_lading_no" text,
	"bill_of_lading_date" date,
	"motor_vehicle_no" text
);
--> statement-breakpoint
CREATE TABLE "voucher_party_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_party_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"supplier_name" text,
	"mailing_name" text,
	"address" text,
	"state" text,
	"country" text
);
--> statement-breakpoint
CREATE TABLE "voucher_dispatch_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_dispatch_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"delivery_note_nos" text,
	"dispatch_doc_no" text,
	"dispatched_through" text,
	"destination" text,
	"carrier_name" text,
	"bill_of_lading_no" text,
	"bill_of_lading_date" date,
	"motor_vehicle_no" text
);
--> statement-breakpoint
CREATE TABLE "voucher_credit_note_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_credit_note_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"tracking_no" text,
	"dispatch_doc_no" text,
	"dispatched_through" text,
	"destination" text,
	"carrier_name" text,
	"bill_of_lading_no" text,
	"bill_of_lading_date" date,
	"motor_vehicle_no" text,
	"original_invoice_no" text,
	"original_invoice_date" date
);
--> statement-breakpoint
CREATE TABLE "voucher_debit_note_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_debit_note_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"tracking_no" text,
	"dispatch_doc_no" text,
	"dispatched_through" text,
	"destination" text,
	"carrier_name" text,
	"bill_of_lading_no" text,
	"bill_of_lading_date" date,
	"motor_vehicle_no" text,
	"original_invoice_no" text,
	"original_invoice_date" date
);
--> statement-breakpoint
CREATE TABLE "voucher_payroll_entries" (
	"payroll_entry_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_payroll_entries_payroll_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_id" bigint NOT NULL,
	"employee_id" bigint,
	"pay_head_id" bigint,
	"amount" numeric(18, 2) DEFAULT '0'
);
--> statement-breakpoint
CREATE TABLE "voucher_entry_actions" (
	"action_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_entry_actions_action_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"voucher_id" bigint,
	"action_type" text NOT NULL,
	"action_data" jsonb,
	"autofill_ledger_id" bigint,
	"autofill_amount" numeric(18, 2),
	"autofill_narration" text,
	"previous_mode" text,
	"new_mode" text,
	"additional_details" jsonb,
	"related_report_type" text,
	"related_report_id" bigint,
	"is_optional" boolean DEFAULT false NOT NULL,
	"optional_reason" text,
	"performed_by" text,
	"performed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "voucher_types" (
	"vt_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_types_vt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"short_name" text,
	"category" text,
	"default_voucher_class" text,
	"affects_inventory" boolean DEFAULT false NOT NULL,
	"affects_accounting" boolean DEFAULT true NOT NULL,
	"affects_gst" boolean DEFAULT false NOT NULL,
	"numbering_method" text DEFAULT 'Automatic' NOT NULL,
	"numbering_prefix" text DEFAULT '' NOT NULL,
	"numbering_suffix" text DEFAULT '' NOT NULL,
	"starts_with" integer DEFAULT 1 NOT NULL,
	"is_predefined" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"parent_vt_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "voucher_type_configs" (
	"config_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voucher_type_configs_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"voucher_type_id" bigint NOT NULL,
	"use_effective_dates" boolean DEFAULT false NOT NULL,
	"allow_zero_value_transactions" boolean DEFAULT false NOT NULL,
	"make_voucher_optional" boolean DEFAULT false NOT NULL,
	"allow_narration" boolean DEFAULT true NOT NULL,
	"allow_narration_per_ledger" boolean DEFAULT false NOT NULL,
	"print_after_save" boolean DEFAULT false NOT NULL,
	"whatsapp_after_save" boolean DEFAULT false NOT NULL,
	"enable_default_accounting_allocation" boolean DEFAULT false NOT NULL,
	"track_additional_cost_for_purchase" boolean DEFAULT false NOT NULL,
	"default_title_to_print" text,
	"use_for_pos_invoicing" boolean DEFAULT false NOT NULL,
	"default_bank_id" bigint,
	"declaration" text,
	"set_alter_declaration" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "whatsapp_config" (
	"config_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "whatsapp_config_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"phone_number_id" text NOT NULL,
	"waba_id" text NOT NULL,
	"access_token" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "whatsapp_templates" (
	"template_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "whatsapp_templates_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL,
	"language" text DEFAULT 'en' NOT NULL,
	"category" text,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "whatsapp_logs" (
	"log_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "whatsapp_logs_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"voucher_id" bigint,
	"to_number" text NOT NULL,
	"message_type" text NOT NULL,
	"template_name" text,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"wamid" text,
	"error" text,
	"sent_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "attendance_voucher_entries" ADD CONSTRAINT "attendance_voucher_entries_attendance_voucher_id_attendance_vouchers_attendance_voucher_id_fk" FOREIGN KEY ("attendance_voucher_id") REFERENCES "public"."attendance_vouchers"("attendance_voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "balance_sheet_views" ADD CONSTRAINT "balance_sheet_views_report_id_balance_sheet_reports_report_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."balance_sheet_reports"("report_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "company_creation_success" ADD CONSTRAINT "company_creation_success_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "company_gst_details" ADD CONSTRAINT "company_gst_details_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "company_pan_cin_details" ADD CONSTRAINT "company_pan_cin_details_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "company_tcs_details" ADD CONSTRAINT "company_tcs_details_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "company_tds_details" ADD CONSTRAINT "company_tds_details_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cost_centres" ADD CONSTRAINT "cost_centres_parent_id_cost_centres_cc_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."cost_centres"("cc_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "day_book_entries" ADD CONSTRAINT "day_book_entries_report_id_day_book_reports_report_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."day_book_reports"("report_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "day_book_entry_lines" ADD CONSTRAINT "day_book_entry_lines_entry_id_day_book_entries_entry_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."day_book_entries"("entry_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "employee_groups" ADD CONSTRAINT "employee_groups_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "employee_groups" ADD CONSTRAINT "employee_groups_employee_category_id_employee_categories_employee_category_id_fk" FOREIGN KEY ("employee_category_id") REFERENCES "public"."employee_categories"("employee_category_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "employee_groups" ADD CONSTRAINT "employee_groups_parent_group_id_employee_groups_employee_group_id_fk" FOREIGN KEY ("parent_group_id") REFERENCES "public"."employee_groups"("employee_group_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feature_items" ADD CONSTRAINT "feature_items_feature_group_id_feature_groups_feature_group_id_fk" FOREIGN KEY ("feature_group_id") REFERENCES "public"."feature_groups"("feature_group_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "godowns" ADD CONSTRAINT "godowns_parent_godown_id_godowns_godown_id_fk" FOREIGN KEY ("parent_godown_id") REFERENCES "public"."godowns"("godown_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "groups" ADD CONSTRAINT "groups_parent_group_id_groups_group_id_fk" FOREIGN KEY ("parent_group_id") REFERENCES "public"."groups"("group_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gst_classifications" ADD CONSTRAINT "gst_classifications_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gst_registrations" ADD CONSTRAINT "gst_registrations_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_bank_details" ADD CONSTRAINT "ledger_bank_details_ledger_id_ledgers_ledger_id_fk" FOREIGN KEY ("ledger_id") REFERENCES "public"."ledgers"("ledger_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_statutory_details" ADD CONSTRAINT "ledger_statutory_details_ledger_id_ledgers_ledger_id_fk" FOREIGN KEY ("ledger_id") REFERENCES "public"."ledgers"("ledger_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pay_head_slab_lines" ADD CONSTRAINT "pay_head_slab_lines_pay_head_id_pay_heads_pay_head_id_fk" FOREIGN KEY ("pay_head_id") REFERENCES "public"."pay_heads"("pay_head_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pay_head_formula_lines" ADD CONSTRAINT "pay_head_formula_lines_pay_head_id_pay_heads_pay_head_id_fk" FOREIGN KEY ("pay_head_id") REFERENCES "public"."pay_heads"("pay_head_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pay_head_formula_lines" ADD CONSTRAINT "pay_head_formula_lines_pay_head_id_ref_pay_heads_pay_head_id_fk" FOREIGN KEY ("pay_head_id_ref") REFERENCES "public"."pay_heads"("pay_head_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "physical_stock_entry_lines" ADD CONSTRAINT "physical_stock_entry_lines_physical_stock_entry_id_physical_stock_entries_physical_stock_entry_id_fk" FOREIGN KEY ("physical_stock_entry_id") REFERENCES "public"."physical_stock_entries"("physical_stock_entry_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "price_levels" ADD CONSTRAINT "price_levels_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "price_list_lines" ADD CONSTRAINT "price_list_lines_price_list_id_price_lists_price_list_id_fk" FOREIGN KEY ("price_list_id") REFERENCES "public"."price_lists"("price_list_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profit_loss_views" ADD CONSTRAINT "profit_loss_views_report_id_profit_loss_reports_report_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."profit_loss_reports"("report_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_categories" ADD CONSTRAINT "stock_categories_parent_category_id_stock_categories_sc_id_fk" FOREIGN KEY ("parent_category_id") REFERENCES "public"."stock_categories"("sc_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_groups" ADD CONSTRAINT "stock_groups_parent_group_id_stock_groups_sg_id_fk" FOREIGN KEY ("parent_group_id") REFERENCES "public"."stock_groups"("sg_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_item_opening_allocations" ADD CONSTRAINT "stock_item_opening_allocations_item_id_stock_items_item_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."stock_items"("item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tally_features" ADD CONSTRAINT "tally_features_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tax_units" ADD CONSTRAINT "tax_units_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tcs_nature_of_goods" ADD CONSTRAINT "tcs_nature_of_goods_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tds_nature_of_payment" ADD CONSTRAINT "tds_nature_of_payment_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trial_balance_rows" ADD CONSTRAINT "trial_balance_rows_report_id_trial_balance_reports_report_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."trial_balance_reports"("report_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "units" ADD CONSTRAINT "units_first_unit_id_units_unit_id_fk" FOREIGN KEY ("first_unit_id") REFERENCES "public"."units"("unit_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "units" ADD CONSTRAINT "units_second_unit_id_units_unit_id_fk" FOREIGN KEY ("second_unit_id") REFERENCES "public"."units"("unit_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_entries" ADD CONSTRAINT "voucher_entries_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_stock_entries" ADD CONSTRAINT "voucher_stock_entries_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_batches" ADD CONSTRAINT "voucher_batches_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_batches" ADD CONSTRAINT "voucher_batches_stock_entry_id_voucher_stock_entries_stock_entry_id_fk" FOREIGN KEY ("stock_entry_id") REFERENCES "public"."voucher_stock_entries"("stock_entry_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_bill_references" ADD CONSTRAINT "voucher_bill_references_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_bank_details" ADD CONSTRAINT "voucher_bank_details_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_cost_centres" ADD CONSTRAINT "voucher_cost_centres_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_cost_centres" ADD CONSTRAINT "voucher_cost_centres_entry_id_voucher_entries_entry_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."voucher_entries"("entry_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_cash_denominations" ADD CONSTRAINT "voucher_cash_denominations_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_receipt_details" ADD CONSTRAINT "voucher_receipt_details_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_party_details" ADD CONSTRAINT "voucher_party_details_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_dispatch_details" ADD CONSTRAINT "voucher_dispatch_details_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_credit_note_details" ADD CONSTRAINT "voucher_credit_note_details_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_debit_note_details" ADD CONSTRAINT "voucher_debit_note_details_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_payroll_entries" ADD CONSTRAINT "voucher_payroll_entries_voucher_id_vouchers_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."vouchers"("voucher_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_types" ADD CONSTRAINT "voucher_types_parent_vt_id_voucher_types_vt_id_fk" FOREIGN KEY ("parent_vt_id") REFERENCES "public"."voucher_types"("vt_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voucher_type_configs" ADD CONSTRAINT "voucher_type_configs_voucher_type_id_voucher_types_vt_id_fk" FOREIGN KEY ("voucher_type_id") REFERENCES "public"."voucher_types"("vt_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "whatsapp_config" ADD CONSTRAINT "whatsapp_config_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "whatsapp_templates" ADD CONSTRAINT "whatsapp_templates_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "whatsapp_logs" ADD CONSTRAINT "whatsapp_logs_company_id_companies_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("company_id") ON DELETE cascade ON UPDATE no action;