import type { ReportConfig } from "./types";

export const ACCOUNT_BOOKS_DEFINITIONS: Record<string, ReportConfig> = {
  "day-book": {
    title: "Day Book",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-sales-view": {
    title: "Day Book - Sales View",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-purchase-view": {
    title: "Day Book - Purchase View",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-receipt-view": {
    title: "Day Book - Receipt View",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-payment-view": {
    title: "Day Book - Payment View",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-contra-view": {
    title: "Day Book - Contra View",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-journal-view": {
    title: "Day Book - Journal View",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-debit-note-view": {
    title: "Day Book - Debit Note View",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-credit-note-view": {
    title: "Day Book - Credit Note View",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "day-book-with-gross-profit": {
    title: "Day Book with Gross Profit",
    apiMethod: "daybook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Narration", field: "narration" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "ledger-vouchers": {
    title: "Ledger Vouchers",
    apiMethod: "ledgerReport",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "ledger-monthly-summary": {
    title: "Ledger Monthly Summary",
    apiMethod: "ledgerReport",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "ledger-statement": {
    title: "Ledger Statement",
    apiMethod: "ledgerReport",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "group-summary": {
    title: "Group Summary",
    apiMethod: "groupSummary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "ledger-summary": {
    title: "Ledger Monthly Summary",
    apiMethod: "ledgerMonthlySummary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Closing Balance", field: "closing", type: "currency", align: "right" },
    ],
  },
  "group-vouchers": {
    title: "Group Vouchers",
    apiMethod: "run",
    reportId: "group_vouchers",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "cash-or-bank-summary": {
    title: "Cash/Bank Summary",
    apiMethod: "run",
    reportId: "cash_or_bank_summary",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "cash-book": {
    title: "Cash Book",
    apiMethod: "cashBook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "bank-book": {
    title: "Bank Book",
    apiMethod: "bankBook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Voucher Type", field: "voucher_type" },
      { header: "Vch No", field: "voucher_number" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "sales-register": {
    title: "Sales Register",
    apiMethod: "run",
    reportId: "sales_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "purchase-register": {
    title: "Purchase Register",
    apiMethod: "run",
    reportId: "purchase_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "journal-register": {
    title: "Journal Register",
    apiMethod: "run",
    reportId: "journal_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "payment-register": {
    title: "Payment Register",
    apiMethod: "paymentRegister",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "receipt-register": {
    title: "Receipt Register",
    apiMethod: "receiptRegister",
    reportId: "receipt_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "contra-register": {
    title: "Contra Register",
    apiMethod: "run",
    reportId: "contra_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "debit-note-register": {
    title: "Debit Note Register",
    apiMethod: "run",
    reportId: "debit_note_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "credit-note-register": {
    title: "Credit Note Register",
    apiMethod: "run",
    reportId: "credit_note_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "memorandum-register": {
    title: "Memorandum Register",
    apiMethod: "run",
    reportId: "memorandum_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "optional-voucher-register": {
    title: "Optional Voucher Register",
    apiMethod: "run",
    reportId: "optional_voucher_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "cancelled-voucher-register": {
    title: "Cancelled Voucher Register",
    apiMethod: "run",
    reportId: "cancelled_voucher_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "reversing-journal-register": {
    title: "Reversing Journal Register",
    apiMethod: "run",
    reportId: "reversing_journal_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "payroll-voucher-register": {
    title: "Payroll Voucher Register",
    apiMethod: "run",
    reportId: "payroll_voucher_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "stock-journal-register": {
    title: "Stock Journal Register",
    apiMethod: "run",
    reportId: "stock_journal_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "manufacturing-journal-register": {
    title: "Manufacturing Journal Register",
    apiMethod: "run",
    reportId: "manufacturing_journal_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "physical-stock-register": {
    title: "Physical Stock Register",
    apiMethod: "run",
    reportId: "physical_stock_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "sales-order-register": {
    title: "Sales Order Register",
    apiMethod: "run",
    reportId: "sales_order_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "purchase-order-register": {
    title: "Purchase Order Register",
    apiMethod: "run",
    reportId: "purchase_order_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "delivery-note-register": {
    title: "Delivery Note Register",
    apiMethod: "run",
    reportId: "delivery_note_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "receipt-note-register": {
    title: "Receipt Note Register",
    apiMethod: "run",
    reportId: "receipt_note_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "rejection-in-register": {
    title: "Rejection In Register",
    apiMethod: "run",
    reportId: "rejection_in_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "rejection-out-register": {
    title: "Rejection Out Register",
    apiMethod: "run",
    reportId: "rejection_out_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "voucher-numbering-report": {
    title: "Voucher Numbering Report",
    apiMethod: "run",
    reportId: "voucher_numbering_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "voucher-audit-trail": {
    title: "Voucher Audit Trail",
    apiMethod: "run",
    reportId: "voucher_audit_trail",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "voucher-alteration-history": {
    title: "Voucher Alteration History",
    apiMethod: "run",
    reportId: "voucher_alteration_history",
    columns: [
      { header: "Metric", field: "metric" },
      { header: "Formula/Source", field: "formula_source" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Previous Value", field: "previous_value", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "deleted-voucher-log": {
    title: "Deleted Voucher Log",
    apiMethod: "run",
    reportId: "deleted_voucher_log",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "voucher-type-summary": {
    title: "Voucher Type Summary",
    apiMethod: "run",
    reportId: "voucher_type_summary",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
};
