import type { ReportConfig } from "./types";

export const AUDIT_DEFINITIONS: Record<string, ReportConfig> = {
  "audit-and-compliance-menu": {
    title: "Audit & Compliance Menu",
    apiMethod: "run",
    reportId: "audit_and_compliance_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "tally-audit-listing": {
    title: "Tally Audit Listing",
    apiMethod: "run",
    reportId: "tally_audit_listing",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "voucher-audit": {
    title: "Voucher Audit",
    apiMethod: "run",
    reportId: "voucher_audit",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "ledger-audit": {
    title: "Ledger Audit",
    apiMethod: "run",
    reportId: "ledger_audit",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "master-alteration-audit": {
    title: "Master Alteration Audit",
    apiMethod: "run",
    reportId: "master_alteration_audit",
    columns: [
      { header: "Metric", field: "metric" },
      { header: "Formula/Source", field: "formula_source" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Previous Value", field: "previous_value", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "deleted-masters-report": {
    title: "Deleted Masters Report",
    apiMethod: "run",
    reportId: "deleted_masters_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "deleted-vouchers-report": {
    title: "Deleted Vouchers Report",
    apiMethod: "run",
    reportId: "deleted_vouchers_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "altered-vouchers-report": {
    title: "Altered Vouchers Report",
    apiMethod: "run",
    reportId: "altered_vouchers_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "altered-ledgers-report": {
    title: "Altered Ledgers Report",
    apiMethod: "run",
    reportId: "altered_ledgers_report",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "edit-log-report": {
    title: "Edit Log Report",
    apiMethod: "run",
    reportId: "edit_log_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "edit-log-voucher-wise": {
    title: "Edit Log Voucher-wise",
    apiMethod: "run",
    reportId: "edit_log_voucher_wise",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "edit-log-master-wise": {
    title: "Edit Log Master-wise",
    apiMethod: "run",
    reportId: "edit_log_master_wise",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "user-activity-log": {
    title: "User Activity Log",
    apiMethod: "run",
    reportId: "user_activity_log",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "login-or-logout-report": {
    title: "Login/Logout Report",
    apiMethod: "run",
    reportId: "login_or_logout_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "company-access-log": {
    title: "Company Access Log",
    apiMethod: "run",
    reportId: "company_access_log",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "security-control-report": {
    title: "Security Control Report",
    apiMethod: "run",
    reportId: "security_control_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "user-rights-report": {
    title: "User Rights Report",
    apiMethod: "run",
    reportId: "user_rights_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "role-permission-report": {
    title: "Role Permission Report",
    apiMethod: "run",
    reportId: "role_permission_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "data-synchronisation-report": {
    title: "Data Synchronisation Report",
    apiMethod: "run",
    reportId: "data_synchronisation_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "backup-status-report": {
    title: "Backup Status Report",
    apiMethod: "run",
    reportId: "backup_status_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "restore-history-report": {
    title: "Restore History Report",
    apiMethod: "run",
    reportId: "restore_history_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "data-import-log": {
    title: "Data Import Log",
    apiMethod: "run",
    reportId: "data_import_log",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "data-export-log": {
    title: "Data Export Log",
    apiMethod: "run",
    reportId: "data_export_log",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "remote-access-report": {
    title: "Remote Access Report",
    apiMethod: "run",
    reportId: "remote_access_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "connected-services-status": {
    title: "Connected Services Status",
    apiMethod: "run",
    reportId: "connected_services_status",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "license-or-subscription-status": {
    title: "License/Subscription Status",
    apiMethod: "run",
    reportId: "license_or_subscription_status",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "company-features-report": {
    title: "Company Features Report",
    apiMethod: "run",
    reportId: "company_features_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "statutory-features-report": {
    title: "Statutory Features Report",
    apiMethod: "run",
    reportId: "statutory_features_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "inventory-features-report": {
    title: "Inventory Features Report",
    apiMethod: "run",
    reportId: "inventory_features_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "accounting-features-report": {
    title: "Accounting Features Report",
    apiMethod: "run",
    reportId: "accounting_features_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "exception-reports-summary": {
    title: "Exception Reports Summary",
    apiMethod: "run",
    reportId: "exception_reports_summary",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "negative-cash-exception": {
    title: "Negative Cash Exception",
    apiMethod: "run",
    reportId: "negative_cash_exception",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "duplicate-voucher-number-exception": {
    title: "Duplicate Voucher Number Exception",
    apiMethod: "run",
    reportId: "duplicate_voucher_number_exception",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "missing-master-details-exception": {
    title: "Missing Master Details Exception",
    apiMethod: "run",
    reportId: "missing_master_details_exception",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },
  "data-health-check-report": {
    title: "Data Health Check Report",
    apiMethod: "run",
    reportId: "data_health_check_report",
    columns: [
      { header: "Date/Time", field: "date_time", type: "date" },
      { header: "User", field: "user" },
      { header: "Object/Module", field: "object_module" },
      { header: "Action", field: "action" },
      { header: "Old/New Value", field: "old_new_value" },
      { header: "Status", field: "status" },
    ],
  },

};
