import type { ReportConfig } from "./types";

export const CASH_BANK_DEFINITIONS: Record<string, ReportConfig> = {
  "cash-book-detailed": {
    title: "Cash Book Detailed",
    apiMethod: "cashBook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "bank-book-detailed": {
    title: "Bank Book Detailed",
    apiMethod: "bankBook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "cash-summary": {
    title: "Cash Summary",
    apiMethod: "run",
    reportId: "cash_summary",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "bank-summary": {
    title: "Bank Summary",
    apiMethod: "run",
    reportId: "bank_summary",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "petty-cash-book": {
    title: "Petty Cash Book",
    apiMethod: "cashBook",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "cash-deposit-report": {
    title: "Cash Deposit Report",
    apiMethod: "run",
    reportId: "cash_deposit_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "cash-withdrawal-report": {
    title: "Cash Withdrawal Report",
    apiMethod: "run",
    reportId: "cash_withdrawal_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "contra-cash-bank-movement": {
    title: "Contra Cash-Bank Movement",
    apiMethod: "run",
    reportId: "contra_cash_bank_movement",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "bank-reconciliation": {
    title: "Bank Reconciliation",
    apiMethod: "run",
    reportId: "bank_reconciliation",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "bank-reconciliation-detailed": {
    title: "Bank Reconciliation Detailed",
    apiMethod: "run",
    reportId: "bank_reconciliation_detailed",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "imported-bank-statement": {
    title: "Imported Bank Statement",
    apiMethod: "run",
    reportId: "imported_bank_statement",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "bank-statement-matching": {
    title: "Bank Statement Matching",
    apiMethod: "run",
    reportId: "bank_statement_matching",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "unreconciled-bank-entries": {
    title: "Unreconciled Bank Entries",
    apiMethod: "run",
    reportId: "unreconciled_bank_entries",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "reconciled-bank-entries": {
    title: "Reconciled Bank Entries",
    apiMethod: "run",
    reportId: "reconciled_bank_entries",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "cheque-register": {
    title: "Cheque Register",
    apiMethod: "run",
    reportId: "cheque_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "cheque-issued-register": {
    title: "Cheque Issued Register",
    apiMethod: "run",
    reportId: "cheque_issued_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "cheque-received-register": {
    title: "Cheque Received Register",
    apiMethod: "run",
    reportId: "cheque_received_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "post-dated-cheques-issued": {
    title: "Post-dated Cheques Issued",
    apiMethod: "run",
    reportId: "post_dated_cheques_issued",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "post-dated-cheques-received": {
    title: "Post-dated Cheques Received",
    apiMethod: "run",
    reportId: "post_dated_cheques_received",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "bounced-cheque-report": {
    title: "Bounced Cheque Report",
    apiMethod: "run",
    reportId: "bounced_cheque_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "cancelled-cheque-report": {
    title: "Cancelled Cheque Report",
    apiMethod: "run",
    reportId: "cancelled_cheque_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "upi-receipts-report": {
    title: "UPI Receipts Report",
    apiMethod: "run",
    reportId: "upi_receipts_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "neft-or-rtgs-payments-report": {
    title: "NEFT/RTGS Payments Report",
    apiMethod: "run",
    reportId: "neft_or_rtgs_payments_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "loan-register": {
    title: "Loan Register",
    apiMethod: "run",
    reportId: "loan_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "loan-emi-schedule": {
    title: "Loan EMI Schedule",
    apiMethod: "run",
    reportId: "loan_emi_schedule",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "interest-on-loan-report": {
    title: "Interest on Loan Report",
    apiMethod: "run",
    reportId: "interest_on_loan_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "cash-flow-forecast": {
    title: "Cash Flow Forecast",
    apiMethod: "cashFlow",
    columns: [
      { header: "Counter Ledger", field: "ledger_name" },
      { header: "Inflow", field: "inflow", type: "currency", align: "right" },
      { header: "Outflow", field: "outflow", type: "currency", align: "right" },
      { header: "Net", field: "net", type: "currency", align: "right" },
    ],
  },
  "daily-cash-position": {
    title: "Daily Cash Position",
    apiMethod: "run",
    reportId: "daily_cash_position",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "bank-wise-balance-report": {
    title: "Bank-wise Balance Report",
    apiMethod: "run",
    reportId: "bank_wise_balance_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "payment-planning-report": {
    title: "Payment Planning Report",
    apiMethod: "run",
    reportId: "payment_planning_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
};
