import type { ReportConfig } from "./types";

export const E_INVOICE_DEFINITIONS: Record<string, ReportConfig> = {
  "e-invoice-report": {
    title: "e-Invoice Report",
    apiMethod: "run",
    reportId: "e_invoice_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-invoice-register": {
    title: "e-Invoice Register",
    apiMethod: "run",
    reportId: "e_invoice_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "e-invoice-pending-for-generation": {
    title: "e-Invoice Pending for Generation",
    apiMethod: "run",
    reportId: "e_invoice_pending_for_generation",
    columns: [
      { header: "Metric", field: "metric" },
      { header: "Formula/Source", field: "formula_source" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Previous Value", field: "previous_value", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "e-invoice-generated": {
    title: "e-Invoice Generated",
    apiMethod: "run",
    reportId: "e_invoice_generated",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-invoice-cancelled": {
    title: "e-Invoice Cancelled",
    apiMethod: "run",
    reportId: "e_invoice_cancelled",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-invoice-failed": {
    title: "e-Invoice Failed",
    apiMethod: "run",
    reportId: "e_invoice_failed",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-invoice-error-report": {
    title: "e-Invoice Error Report",
    apiMethod: "run",
    reportId: "e_invoice_error_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "irn-details-report": {
    title: "IRN Details Report",
    apiMethod: "run",
    reportId: "irn_details_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "ack-number-register": {
    title: "Ack Number Register",
    apiMethod: "run",
    reportId: "ack_number_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "e-invoice-correction-report": {
    title: "e-Invoice Correction Report",
    apiMethod: "run",
    reportId: "e_invoice_correction_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-way-bill-report": {
    title: "e-Way Bill Report",
    apiMethod: "run",
    reportId: "e_way_bill_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-way-bill-register": {
    title: "e-Way Bill Register",
    apiMethod: "run",
    reportId: "e_way_bill_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "e-way-bill-pending": {
    title: "e-Way Bill Pending",
    apiMethod: "run",
    reportId: "e_way_bill_pending",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-way-bill-generated": {
    title: "e-Way Bill Generated",
    apiMethod: "run",
    reportId: "e_way_bill_generated",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-way-bill-cancelled": {
    title: "e-Way Bill Cancelled",
    apiMethod: "run",
    reportId: "e_way_bill_cancelled",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-way-bill-expired": {
    title: "e-Way Bill Expired",
    apiMethod: "run",
    reportId: "e_way_bill_expired",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-way-bill-extended-validity": {
    title: "e-Way Bill Extended Validity",
    apiMethod: "run",
    reportId: "e_way_bill_extended_validity",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "e-way-bill-part-b-pending": {
    title: "e-Way Bill Part-B Pending",
    apiMethod: "run",
    reportId: "e_way_bill_part_b_pending",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "transporter-id-pending": {
    title: "Transporter ID Pending",
    apiMethod: "run",
    reportId: "transporter_id_pending",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "vehicle-number-pending": {
    title: "Vehicle Number Pending",
    apiMethod: "run",
    reportId: "vehicle_number_pending",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "distance-exception-report": {
    title: "Distance Exception Report",
    apiMethod: "run",
    reportId: "distance_exception_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "consolidated-e-way-bill-report": {
    title: "Consolidated e-Way Bill Report",
    apiMethod: "run",
    reportId: "consolidated_e_way_bill_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "exchange-activity-log": {
    title: "Exchange Activity Log",
    apiMethod: "run",
    reportId: "exchange_activity_log",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "upload-gst-returns-log": {
    title: "Upload GST Returns Log",
    apiMethod: "run",
    reportId: "upload_gst_returns_log",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "download-gst-data-log": {
    title: "Download GST Data Log",
    apiMethod: "run",
    reportId: "download_gst_data_log",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-portal-sync-status": {
    title: "GST Portal Sync Status",
    apiMethod: "run",
    reportId: "gst_portal_sync_status",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "failed-uploads-report": {
    title: "Failed Uploads Report",
    apiMethod: "run",
    reportId: "failed_uploads_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "imported-gst-data-report": {
    title: "Imported GST Data Report",
    apiMethod: "run",
    reportId: "imported_gst_data_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
  "exported-json-report": {
    title: "Exported JSON Report",
    apiMethod: "run",
    reportId: "exported_json_report",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "portal-difference-report": {
    title: "Portal Difference Report",
    apiMethod: "run",
    reportId: "portal_difference_report",
    columns: [
      { header: "Invoice/Doc No.", field: "invoice_doc_no" },
      { header: "Party", field: "party" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "IRN/EWB/Ack No.", field: "irn_ewb_ack_no" },
      { header: "Valid Till", field: "valid_till", type: "date" },
      { header: "Error/Status", field: "error_status" },
    ],
  },
};
