import type { ReportConfig } from "./types";

export const FINANCIAL_DEFINITIONS: Record<string, ReportConfig> = {
  "balance-sheet": {
    title: "Balance Sheet",
    apiMethod: "balanceSheet",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Current Period", field: "current_period", type: "currency", align: "right" },
      { header: "Previous Period", field: "previous_period", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Drill", field: "drill" },
    ],
  },
  "vertical-balance-sheet": {
    title: "Vertical Balance Sheet",
    apiMethod: "balanceSheet",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Current Period", field: "current_period" },
      { header: "Previous Period", field: "previous_period" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Drill", field: "drill" },
    ],
  },
  "consolidated-balance-sheet": {
    title: "Consolidated Balance Sheet",
    apiMethod: "balanceSheet",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Current Period", field: "current_period" },
      { header: "Previous Period", field: "previous_period" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Drill", field: "drill" },
    ],
  },
  "schedule-vi-balance-sheet": {
    title: "Schedule VI Balance Sheet",
    apiMethod: "balanceSheet",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Current Period", field: "current_period" },
      { header: "Previous Period", field: "previous_period" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Drill", field: "drill" },
    ],
  },
  "balance-sheet-with-previous-year": {
    title: "Balance Sheet with Previous Year",
    apiMethod: "balanceSheet",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Current Period", field: "current_period" },
      { header: "Previous Period", field: "previous_period" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Drill", field: "drill" },
    ],
  },
  "balance-sheet-with-monthly-columns": {
    title: "Balance Sheet with Monthly Columns",
    apiMethod: "balanceSheet",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Current Period", field: "current_period" },
      { header: "Previous Period", field: "previous_period" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Drill", field: "drill" },
    ],
  },
  "profit-and-loss-account": {
    title: "Profit & Loss Account",
    apiMethod: "profitLoss",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Current Period", field: "current_period", type: "currency", align: "right" },
      { header: "Previous Period", field: "previous_period", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Drill", field: "drill" },
    ],
  },
  "vertical-profit-and-loss-account": {
    title: "Vertical Profit & Loss Account",
    apiMethod: "profitLoss",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Expense/Debit", field: "expense_debit", type: "currency", align: "right" },
      { header: "Income/Credit", field: "income_credit", type: "currency", align: "right" },
      { header: "Current Amount", field: "current_amount", type: "currency", align: "right" },
      { header: "Previous Amount", field: "previous_amount", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
    ],
  },
  "profit-and-loss-with-gross-profit-split": {
    title: "Profit & Loss with Gross Profit Split",
    apiMethod: "profitLoss",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Expense/Debit", field: "expense_debit", type: "currency", align: "right" },
      { header: "Income/Credit", field: "income_credit", type: "currency", align: "right" },
      { header: "Current Amount", field: "current_amount", type: "currency", align: "right" },
      { header: "Previous Amount", field: "previous_amount", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
    ],
  },
  "profit-and-loss-monthly-comparison": {
    title: "Profit & Loss Monthly Comparison",
    apiMethod: "profitLoss",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Expense/Debit", field: "expense_debit", type: "currency", align: "right" },
      { header: "Income/Credit", field: "income_credit", type: "currency", align: "right" },
      { header: "Current Amount", field: "current_amount", type: "currency", align: "right" },
      { header: "Previous Amount", field: "previous_amount", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
    ],
  },
  "profit-and-loss-cost-centre-wise": {
    title: "Profit & Loss Cost Centre-wise",
    apiMethod: "profitLoss",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Expense/Debit", field: "expense_debit", type: "currency", align: "right" },
      { header: "Income/Credit", field: "income_credit", type: "currency", align: "right" },
      { header: "Current Amount", field: "current_amount", type: "currency", align: "right" },
      { header: "Previous Amount", field: "previous_amount", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
    ],
  },
  "trial-balance": {
    title: "Trial Balance",
    apiMethod: "trialBalance",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening Balance", field: "opening_balance", type: "currency", align: "right" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Closing Balance", field: "closing_balance", type: "currency", align: "right" },
    ],
  },
  "group-wise-trial-balance": {
    title: "Group-wise Trial Balance",
    apiMethod: "trialBalance",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening Balance", field: "opening_balance", type: "currency", align: "right" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Closing Balance", field: "closing_balance", type: "currency", align: "right" },
    ],
  },
  "ledger-wise-trial-balance": {
    title: "Ledger-wise Trial Balance",
    apiMethod: "trialBalance",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening Balance", field: "opening_balance", type: "currency", align: "right" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Closing Balance", field: "closing_balance", type: "currency", align: "right" },
    ],
  },
  "opening-balance-trial-balance": {
    title: "Opening Balance Trial Balance",
    apiMethod: "trialBalance",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening Balance", field: "opening_balance", type: "currency", align: "right" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Closing Balance", field: "closing_balance", type: "currency", align: "right" },
    ],
  },
  "closing-balance-trial-balance": {
    title: "Closing Balance Trial Balance",
    apiMethod: "trialBalance",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening Balance", field: "opening_balance", type: "currency", align: "right" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Closing Balance", field: "closing_balance", type: "currency", align: "right" },
    ],
  },
  "trial-balance-with-transactions": {
    title: "Trial Balance with Transactions",
    apiMethod: "trialBalance",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening Balance", field: "opening_balance", type: "currency", align: "right" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Closing Balance", field: "closing_balance", type: "currency", align: "right" },
    ],
  },
  "cash-flow-statement": {
    title: "Cash Flow Statement",
    apiMethod: "cashFlow",
    columns: [
      { header: "Counter Ledger", field: "ledger_name" },
      { header: "Inflow", field: "inflow", type: "currency", align: "right" },
      { header: "Outflow", field: "outflow", type: "currency", align: "right" },
      { header: "Net", field: "net", type: "currency", align: "right" },
    ],
  },
  "cash-flow-projection": {
    title: "Cash Flow Projection",
    apiMethod: "cashFlow",
    columns: [
      { header: "Counter Ledger", field: "ledger_name" },
      { header: "Inflow", field: "inflow", type: "currency", align: "right" },
      { header: "Outflow", field: "outflow", type: "currency", align: "right" },
      { header: "Net", field: "net", type: "currency", align: "right" },
    ],
  },
  "fund-flow-statement": {
    title: "Fund Flow Statement",
    apiMethod: "run",
    reportId: "fund_flow_statement",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "ratio-analysis": {
    title: "Ratio Analysis",
    apiMethod: "ratioAnalysis",
    columns: [
      { header: "Ratio / Metric", field: "label" },
      { header: "Value", field: "displayValue" },
    ],
  },
  "statistics-report": {
    title: "Statistics Report",
    apiMethod: "statistics",
    columns: [
      { header: "Metric", field: "metric" },
      { header: "Formula/Source", field: "formula_source" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Previous Value", field: "previous_value", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "working-capital-report": {
    title: "Working Capital Report",
    apiMethod: "run",
    reportId: "working_capital_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "net-worth-report": {
    title: "Net Worth Report",
    apiMethod: "run",
    reportId: "net_worth_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "capital-account-summary": {
    title: "Capital Account Summary",
    apiMethod: "run",
    reportId: "capital_account_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "reserves-and-surplus-summary": {
    title: "Reserves & Surplus Summary",
    apiMethod: "run",
    reportId: "reserves_and_surplus_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "drawings-summary": {
    title: "Drawings Summary",
    apiMethod: "run",
    reportId: "drawings_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "fixed-assets-summary": {
    title: "Fixed Assets Summary",
    apiMethod: "run",
    reportId: "fixed_assets_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "depreciation-summary": {
    title: "Depreciation Summary",
    apiMethod: "run",
    reportId: "depreciation_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "loans-and-advances-summary": {
    title: "Loans & Advances Summary",
    apiMethod: "run",
    reportId: "loans_and_advances_summary",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "secured-loans-summary": {
    title: "Secured Loans Summary",
    apiMethod: "run",
    reportId: "secured_loans_summary",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "unsecured-loans-summary": {
    title: "Unsecured Loans Summary",
    apiMethod: "run",
    reportId: "unsecured_loans_summary",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "current-assets-summary": {
    title: "Current Assets Summary",
    apiMethod: "run",
    reportId: "current_assets_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "current-liabilities-summary": {
    title: "Current Liabilities Summary",
    apiMethod: "run",
    reportId: "current_liabilities_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "monthly-financial-snapshot": {
    title: "Monthly Financial Snapshot",
    apiMethod: "run",
    reportId: "monthly_financial_snapshot",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
};
