import type { ReportConfig } from "./types";

export const GATEWAY_DEFINITIONS: Record<string, ReportConfig> = {
  "gateway-of-business": {
    title: "Gateway of Business",
    apiMethod: "run",
    reportId: "gateway_of_business",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "display-more-reports": {
    title: "Display More Reports",
    apiMethod: "run",
    reportId: "display_more_reports",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "go-to-search-results": {
    title: "Go To Search Results",
    apiMethod: "run",
    reportId: "go_to_search_results",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "saved-views-list": {
    title: "Saved Views List",
    apiMethod: "run",
    reportId: "saved_views_list",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "report-browser-by-module": {
    title: "Report Browser by Module",
    apiMethod: "run",
    reportId: "report_browser_by_module",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "company-summary": {
    title: "Company Summary",
    apiMethod: "run",
    reportId: "company_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "current-period-summary": {
    title: "Current Period Summary",
    apiMethod: "run",
    reportId: "current_period_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "last-entry-summary": {
    title: "Last Entry Summary",
    apiMethod: "run",
    reportId: "last_entry_summary",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "multi-company-selector": {
    title: "Multi-Company Selector",
    apiMethod: "run",
    reportId: "multi_company_selector",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "period-change-panel": {
    title: "Period Change Panel",
    apiMethod: "run",
    reportId: "period_change_panel",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "company-change-panel": {
    title: "Company Change Panel",
    apiMethod: "run",
    reportId: "company_change_panel",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "basis-of-values-panel": {
    title: "Basis of Values Panel",
    apiMethod: "run",
    reportId: "basis_of_values_panel",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "report-configure-panel": {
    title: "Report Configure Panel",
    apiMethod: "run",
    reportId: "report_configure_panel",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "report-filter-panel": {
    title: "Report Filter Panel",
    apiMethod: "run",
    reportId: "report_filter_panel",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "exception-reports-launcher": {
    title: "Exception Reports Launcher",
    apiMethod: "run",
    reportId: "exception_reports_launcher",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "export-report-panel": {
    title: "Export Report Panel",
    apiMethod: "run",
    reportId: "export_report_panel",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "print-report-panel": {
    title: "Print Report Panel",
    apiMethod: "run",
    reportId: "print_report_panel",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "share-report-panel": {
    title: "Share Report Panel",
    apiMethod: "run",
    reportId: "share_report_panel",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "import-or-exchange-status": {
    title: "Import/Exchange Status",
    apiMethod: "run",
    reportId: "import_or_exchange_status",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "user-shortcut-help": {
    title: "User Shortcut Help",
    apiMethod: "run",
    reportId: "user_shortcut_help",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
};
