import type { ReportConfig } from "./types";

export const GST_DEFINITIONS: Record<string, ReportConfig> = {
  "gst-reports-menu": {
    title: "GST Reports Menu",
    apiMethod: "run",
    reportId: "gst_reports_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "gst-return-activities": {
    title: "GST Return Activities",
    apiMethod: "run",
    reportId: "gst_return_activities",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1": {
    title: "GSTR-1",
    apiMethod: "run",
    reportId: "gstr_1",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-summary": {
    title: "GSTR-1 Summary",
    apiMethod: "run",
    reportId: "gstr_1_summary",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-b2b": {
    title: "GSTR-1 B2B",
    apiMethod: "run",
    reportId: "gstr_1_b2b",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-b2c-large": {
    title: "GSTR-1 B2C Large",
    apiMethod: "run",
    reportId: "gstr_1_b2c_large",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-b2c-small": {
    title: "GSTR-1 B2C Small",
    apiMethod: "run",
    reportId: "gstr_1_b2c_small",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-credit-or-debit-notes": {
    title: "GSTR-1 Credit/Debit Notes",
    apiMethod: "run",
    reportId: "gstr_1_credit_or_debit_notes",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-export-invoices": {
    title: "GSTR-1 Export Invoices",
    apiMethod: "run",
    reportId: "gstr_1_export_invoices",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "gstr-1-nil-rated-supplies": {
    title: "GSTR-1 Nil Rated Supplies",
    apiMethod: "run",
    reportId: "gstr_1_nil_rated_supplies",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-hsn-summary": {
    title: "GSTR-1 HSN Summary",
    apiMethod: "run",
    reportId: "gstr_1_hsn_summary",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-document-summary": {
    title: "GSTR-1 Document Summary",
    apiMethod: "run",
    reportId: "gstr_1_document_summary",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-uncertain-transactions": {
    title: "GSTR-1 Uncertain Transactions",
    apiMethod: "run",
    reportId: "gstr_1_uncertain_transactions",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-not-relevant-in-return": {
    title: "GSTR-1 Not Relevant in Return",
    apiMethod: "run",
    reportId: "gstr_1_not_relevant_in_return",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-included-in-return": {
    title: "GSTR-1 Included in Return",
    apiMethod: "run",
    reportId: "gstr_1_included_in_return",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-uploaded-transactions": {
    title: "GSTR-1 Uploaded Transactions",
    apiMethod: "run",
    reportId: "gstr_1_uploaded_transactions",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-mismatched-transactions": {
    title: "GSTR-1 Mismatched Transactions",
    apiMethod: "run",
    reportId: "gstr_1_mismatched_transactions",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-rejected-transactions": {
    title: "GSTR-1 Rejected Transactions",
    apiMethod: "run",
    reportId: "gstr_1_rejected_transactions",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-1-reconciliation": {
    title: "GSTR-1 Reconciliation",
    apiMethod: "run",
    reportId: "gstr_1_reconciliation",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b": {
    title: "GSTR-3B",
    apiMethod: "run",
    reportId: "gstr_3b",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-summary": {
    title: "GSTR-3B Summary",
    apiMethod: "run",
    reportId: "gstr_3b_summary",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-return-format": {
    title: "GSTR-3B Return Format",
    apiMethod: "run",
    reportId: "gstr_3b_return_format",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-books-vs-portal": {
    title: "GSTR-3B Books vs Portal",
    apiMethod: "run",
    reportId: "gstr_3b_books_vs_portal",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-outward-supplies": {
    title: "GSTR-3B Outward Supplies",
    apiMethod: "run",
    reportId: "gstr_3b_outward_supplies",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-itc-available": {
    title: "GSTR-3B ITC Available",
    apiMethod: "run",
    reportId: "gstr_3b_itc_available",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-itc-reversed": {
    title: "GSTR-3B ITC Reversed",
    apiMethod: "run",
    reportId: "gstr_3b_itc_reversed",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-exempt-or-nil-or-non-gst": {
    title: "GSTR-3B Exempt/Nil/Non-GST",
    apiMethod: "run",
    reportId: "gstr_3b_exempt_or_nil_or_non_gst",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-interest-and-late-fee": {
    title: "GSTR-3B Interest & Late Fee",
    apiMethod: "run",
    reportId: "gstr_3b_interest_and_late_fee",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-payment-details": {
    title: "GSTR-3B Payment Details",
    apiMethod: "run",
    reportId: "gstr_3b_payment_details",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-uncertain-transactions": {
    title: "GSTR-3B Uncertain Transactions",
    apiMethod: "run",
    reportId: "gstr_3b_uncertain_transactions",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-not-relevant-in-return": {
    title: "GSTR-3B Not Relevant in Return",
    apiMethod: "run",
    reportId: "gstr_3b_not_relevant_in_return",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-3b-reconciliation": {
    title: "GSTR-3B Reconciliation",
    apiMethod: "run",
    reportId: "gstr_3b_reconciliation",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-2a-reconciliation": {
    title: "GSTR-2A Reconciliation",
    apiMethod: "run",
    reportId: "gstr_2a_reconciliation",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-2b-reconciliation": {
    title: "GSTR-2B Reconciliation",
    apiMethod: "run",
    reportId: "gstr_2b_reconciliation",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-annual-computation": {
    title: "GST Annual Computation",
    apiMethod: "run",
    reportId: "gst_annual_computation",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-9-annual-return-summary": {
    title: "GSTR-9 Annual Return Summary",
    apiMethod: "run",
    reportId: "gstr_9_annual_return_summary",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-9-outward-supplies": {
    title: "GSTR-9 Outward Supplies",
    apiMethod: "run",
    reportId: "gstr_9_outward_supplies",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-9-itc-summary": {
    title: "GSTR-9 ITC Summary",
    apiMethod: "run",
    reportId: "gstr_9_itc_summary",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstr-9-hsn-summary": {
    title: "GSTR-9 HSN Summary",
    apiMethod: "run",
    reportId: "gstr_9_hsn_summary",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-challan-reconciliation": {
    title: "GST Challan Reconciliation",
    apiMethod: "run",
    reportId: "gst_challan_reconciliation",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-payment-register": {
    title: "GST Payment Register",
    apiMethod: "run",
    reportId: "gst_payment_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-liability-register": {
    title: "GST Liability Register",
    apiMethod: "run",
    reportId: "gst_liability_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-input-tax-credit-ledger": {
    title: "GST Input Tax Credit Ledger",
    apiMethod: "run",
    reportId: "gst_input_tax_credit_ledger",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "gst-output-tax-ledger": {
    title: "GST Output Tax Ledger",
    apiMethod: "run",
    reportId: "gst_output_tax_ledger",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "gst-tax-rate-wise-sales": {
    title: "GST Tax Rate-wise Sales",
    apiMethod: "run",
    reportId: "gst_tax_rate_wise_sales",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-tax-rate-wise-purchase": {
    title: "GST Tax Rate-wise Purchase",
    apiMethod: "run",
    reportId: "gst_tax_rate_wise_purchase",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-hsn-or-sac-summary": {
    title: "GST HSN/SAC Summary",
    apiMethod: "run",
    reportId: "gst_hsn_or_sac_summary",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-state-wise-sales": {
    title: "GST State-wise Sales",
    apiMethod: "run",
    reportId: "gst_state_wise_sales",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-state-wise-purchase": {
    title: "GST State-wise Purchase",
    apiMethod: "run",
    reportId: "gst_state_wise_purchase",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-party-wise-sales": {
    title: "GST Party-wise Sales",
    apiMethod: "run",
    reportId: "gst_party_wise_sales",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-party-wise-purchase": {
    title: "GST Party-wise Purchase",
    apiMethod: "run",
    reportId: "gst_party_wise_purchase",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gstin-validation-exception": {
    title: "GSTIN Validation Exception",
    apiMethod: "run",
    reportId: "gstin_validation_exception",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "missing-hsn-or-sac-report": {
    title: "Missing HSN/SAC Report",
    apiMethod: "run",
    reportId: "missing_hsn_or_sac_report",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "missing-gstin-report": {
    title: "Missing GSTIN Report",
    apiMethod: "run",
    reportId: "missing_gstin_report",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "place-of-supply-exception": {
    title: "Place of Supply Exception",
    apiMethod: "run",
    reportId: "place_of_supply_exception",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "reverse-charge-report": {
    title: "Reverse Charge Report",
    apiMethod: "run",
    reportId: "reverse_charge_report",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "advance-receipt-gst-report": {
    title: "Advance Receipt GST Report",
    apiMethod: "run",
    reportId: "advance_receipt_gst_report",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "advance-adjustment-gst-report": {
    title: "Advance Adjustment GST Report",
    apiMethod: "run",
    reportId: "advance_adjustment_gst_report",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-audit-trail": {
    title: "GST Audit Trail",
    apiMethod: "run",
    reportId: "gst_audit_trail",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "gst-exception-resolution-report": {
    title: "GST Exception Resolution Report",
    apiMethod: "run",
    reportId: "gst_exception_resolution_report",
    columns: [
      { header: "Section/Invoice", field: "section_invoice" },
      { header: "Party/GSTIN", field: "party_gstin" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "IGST", field: "igst", type: "currency", align: "right" },
      { header: "CGST", field: "cgst", type: "currency", align: "right" },
      { header: "SGST", field: "sgst", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
};
