export type { ReportConfig } from "./types";
export type { ReportColumn } from "@/components/reports/ReportTable";
import type { ReportConfig } from "./types";

import { GATEWAY_DEFINITIONS } from "./gateway";
import { FINANCIAL_DEFINITIONS } from "./financial";
import { ACCOUNT_BOOKS_DEFINITIONS } from "./accountBooks";
import { RECEIVABLES_DEFINITIONS } from "./receivables";
import { CASH_BANK_DEFINITIONS } from "./cashBank";
import { SALES_PURCHASE_DEFINITIONS } from "./salesPurchase";
import { INVENTORY_DEFINITIONS } from "./inventory";
import { MANUFACTURING_DEFINITIONS } from "./manufacturing";
import { GST_DEFINITIONS } from "./gst";
import { E_INVOICE_DEFINITIONS } from "./eInvoice";
import { TDS_DEFINITIONS } from "./tds";
import { TCS_DEFINITIONS } from "./tcs";
import { PAYROLL_DEFINITIONS } from "./payroll";
import { STATUTORY_DEFINITIONS } from "./statutory";
import { AUDIT_DEFINITIONS } from "./audit";

export const REPORT_DEFINITIONS: Record<string, ReportConfig> = {
  ...GATEWAY_DEFINITIONS,
  ...FINANCIAL_DEFINITIONS,
  ...ACCOUNT_BOOKS_DEFINITIONS,
  ...RECEIVABLES_DEFINITIONS,
  ...CASH_BANK_DEFINITIONS,
  ...SALES_PURCHASE_DEFINITIONS,
  ...INVENTORY_DEFINITIONS,
  ...MANUFACTURING_DEFINITIONS,
  ...GST_DEFINITIONS,
  ...E_INVOICE_DEFINITIONS,
  ...TDS_DEFINITIONS,
  ...TCS_DEFINITIONS,
  ...PAYROLL_DEFINITIONS,
  ...STATUTORY_DEFINITIONS,
  ...AUDIT_DEFINITIONS,
};

// Apply backward-compatible route aliases (referencing merged object so aliases resolve correctly)
Object.assign(REPORT_DEFINITIONS, {
  "ledger": REPORT_DEFINITIONS["ledger-vouchers"],
  "cash-flow": REPORT_DEFINITIONS["cash-flow-statement"],
  "outstandings-receivable": REPORT_DEFINITIONS["bills-receivable"],
  "outstandings-payable": REPORT_DEFINITIONS["bills-payable"],
  "outstandings-ledger": REPORT_DEFINITIONS["ledger-outstandings"],
  "outstandings-group": REPORT_DEFINITIONS["group-outstandings"],
  "stock-category": REPORT_DEFINITIONS["stock-category-summary"],
  "godown": REPORT_DEFINITIONS["godown-summary"],
  "ageing-analysis": REPORT_DEFINITIONS["stock-ageing-analysis"],
  "sales-order-book": REPORT_DEFINITIONS["sales-order-register"],
  "purchase-order-book": REPORT_DEFINITIONS["purchase-order-register"],
  "cost-centre": REPORT_DEFINITIONS["cost-centre-summary"],
  "negative-stock": REPORT_DEFINITIONS["negative-stock-report"],
  "edit-log": REPORT_DEFINITIONS["edit-log-report"],
  "confirmation-of-accounts": REPORT_DEFINITIONS["ledger-confirmation-report"],
  "gratuity": REPORT_DEFINITIONS["gratuity-report"],
  "professional-tax": REPORT_DEFINITIONS["professional-tax-summary"],
  "pay-head-breakup": REPORT_DEFINITIONS["pay-head-employee-wise"],
  "profit-loss": REPORT_DEFINITIONS["profit-and-loss-account"],
  "funds-flow": REPORT_DEFINITIONS["fund-flow-statement"],
  "interest-calculations": REPORT_DEFINITIONS["interest-calculation-ledger-wise"],
  "statistics": REPORT_DEFINITIONS["statistics-report"],
  "batch-vouchers": REPORT_DEFINITIONS["batch-wise-stock-report"],
  "job-work": REPORT_DEFINITIONS["job-work-in-register"],
  "pf": REPORT_DEFINITIONS["provident-fund-summary"],
  "esi": REPORT_DEFINITIONS["employee-state-insurance-summary"],
  "e-invoice-status": REPORT_DEFINITIONS["e-invoice-report"],
});

/** Groups all reports by their Tally category for menu/sidebar generation */
export const REPORT_CATEGORIES: Record<string, { slug: string; title: string }[]> = {
  "Gateway, Navigation & Global Report Shells": [
    { slug: "gateway-of-business", title: "Gateway of Business" },
    { slug: "display-more-reports", title: "Display More Reports" },
    { slug: "go-to-search-results", title: "Go To Search Results" },
    { slug: "saved-views-list", title: "Saved Views List" },
    { slug: "report-browser-by-module", title: "Report Browser by Module" },
    { slug: "company-summary", title: "Company Summary" },
    { slug: "current-period-summary", title: "Current Period Summary" },
    { slug: "last-entry-summary", title: "Last Entry Summary" },
    { slug: "multi-company-selector", title: "Multi-Company Selector" },
    { slug: "period-change-panel", title: "Period Change Panel" },
    { slug: "company-change-panel", title: "Company Change Panel" },
    { slug: "basis-of-values-panel", title: "Basis of Values Panel" },
    { slug: "report-configure-panel", title: "Report Configure Panel" },
    { slug: "report-filter-panel", title: "Report Filter Panel" },
    { slug: "exception-reports-launcher", title: "Exception Reports Launcher" },
    { slug: "export-report-panel", title: "Export Report Panel" },
    { slug: "print-report-panel", title: "Print Report Panel" },
    { slug: "share-report-panel", title: "Share Report Panel" },
    { slug: "import-or-exchange-status", title: "Import/Exchange Status" },
    { slug: "user-shortcut-help", title: "User Shortcut Help" },
  ],
  "Core Financial Statements": [
    { slug: "balance-sheet", title: "Balance Sheet" },
    { slug: "vertical-balance-sheet", title: "Vertical Balance Sheet" },
    { slug: "consolidated-balance-sheet", title: "Consolidated Balance Sheet" },
    { slug: "schedule-vi-balance-sheet", title: "Schedule VI Balance Sheet" },
    { slug: "balance-sheet-with-previous-year", title: "Balance Sheet with Previous Year" },
    { slug: "balance-sheet-with-monthly-columns", title: "Balance Sheet with Monthly Columns" },
    { slug: "profit-and-loss-account", title: "Profit & Loss Account" },
    { slug: "vertical-profit-and-loss-account", title: "Vertical Profit & Loss Account" },
    { slug: "profit-and-loss-with-gross-profit-split", title: "Profit & Loss with Gross Profit Split" },
    { slug: "profit-and-loss-monthly-comparison", title: "Profit & Loss Monthly Comparison" },
    { slug: "profit-and-loss-cost-centre-wise", title: "Profit & Loss Cost Centre-wise" },
    { slug: "trial-balance", title: "Trial Balance" },
    { slug: "group-wise-trial-balance", title: "Group-wise Trial Balance" },
    { slug: "ledger-wise-trial-balance", title: "Ledger-wise Trial Balance" },
    { slug: "opening-balance-trial-balance", title: "Opening Balance Trial Balance" },
    { slug: "closing-balance-trial-balance", title: "Closing Balance Trial Balance" },
    { slug: "trial-balance-with-transactions", title: "Trial Balance with Transactions" },
    { slug: "cash-flow-statement", title: "Cash Flow Statement" },
    { slug: "cash-flow-projection", title: "Cash Flow Projection" },
    { slug: "fund-flow-statement", title: "Fund Flow Statement" },
    { slug: "ratio-analysis", title: "Ratio Analysis" },
    { slug: "statistics-report", title: "Statistics Report" },
    { slug: "working-capital-report", title: "Working Capital Report" },
    { slug: "net-worth-report", title: "Net Worth Report" },
    { slug: "capital-account-summary", title: "Capital Account Summary" },
    { slug: "reserves-and-surplus-summary", title: "Reserves & Surplus Summary" },
    { slug: "drawings-summary", title: "Drawings Summary" },
    { slug: "fixed-assets-summary", title: "Fixed Assets Summary" },
    { slug: "depreciation-summary", title: "Depreciation Summary" },
    { slug: "loans-and-advances-summary", title: "Loans & Advances Summary" },
    { slug: "secured-loans-summary", title: "Secured Loans Summary" },
    { slug: "unsecured-loans-summary", title: "Unsecured Loans Summary" },
    { slug: "current-assets-summary", title: "Current Assets Summary" },
    { slug: "current-liabilities-summary", title: "Current Liabilities Summary" },
    { slug: "monthly-financial-snapshot", title: "Monthly Financial Snapshot" },
  ],
  "Account Books & Voucher Registers": [
    { slug: "day-book", title: "Day Book" },
    { slug: "day-book-sales-view", title: "Day Book - Sales View" },
    { slug: "day-book-purchase-view", title: "Day Book - Purchase View" },
    { slug: "day-book-receipt-view", title: "Day Book - Receipt View" },
    { slug: "day-book-payment-view", title: "Day Book - Payment View" },
    { slug: "day-book-contra-view", title: "Day Book - Contra View" },
    { slug: "day-book-journal-view", title: "Day Book - Journal View" },
    { slug: "day-book-debit-note-view", title: "Day Book - Debit Note View" },
    { slug: "day-book-credit-note-view", title: "Day Book - Credit Note View" },
    { slug: "day-book-with-gross-profit", title: "Day Book with Gross Profit" },
    { slug: "ledger-vouchers", title: "Ledger Vouchers" },
    { slug: "ledger-monthly-summary", title: "Ledger Monthly Summary" },
    { slug: "ledger-statement", title: "Ledger Statement" },
    { slug: "group-summary", title: "Group Summary" },
    { slug: "group-vouchers", title: "Group Vouchers" },
    { slug: "cash-or-bank-summary", title: "Cash/Bank Summary" },
    { slug: "cash-book", title: "Cash Book" },
    { slug: "bank-book", title: "Bank Book" },
    { slug: "sales-register", title: "Sales Register" },
    { slug: "purchase-register", title: "Purchase Register" },
    { slug: "journal-register", title: "Journal Register" },
    { slug: "payment-register", title: "Payment Register" },
    { slug: "receipt-register", title: "Receipt Register" },
    { slug: "contra-register", title: "Contra Register" },
    { slug: "debit-note-register", title: "Debit Note Register" },
    { slug: "credit-note-register", title: "Credit Note Register" },
    { slug: "memorandum-register", title: "Memorandum Register" },
    { slug: "optional-voucher-register", title: "Optional Voucher Register" },
    { slug: "cancelled-voucher-register", title: "Cancelled Voucher Register" },
    { slug: "reversing-journal-register", title: "Reversing Journal Register" },
    { slug: "payroll-voucher-register", title: "Payroll Voucher Register" },
    { slug: "stock-journal-register", title: "Stock Journal Register" },
    { slug: "manufacturing-journal-register", title: "Manufacturing Journal Register" },
    { slug: "physical-stock-register", title: "Physical Stock Register" },
    { slug: "sales-order-register", title: "Sales Order Register" },
    { slug: "purchase-order-register", title: "Purchase Order Register" },
    { slug: "delivery-note-register", title: "Delivery Note Register" },
    { slug: "receipt-note-register", title: "Receipt Note Register" },
    { slug: "rejection-in-register", title: "Rejection In Register" },
    { slug: "rejection-out-register", title: "Rejection Out Register" },
    { slug: "voucher-numbering-report", title: "Voucher Numbering Report" },
    { slug: "voucher-audit-trail", title: "Voucher Audit Trail" },
    { slug: "voucher-alteration-history", title: "Voucher Alteration History" },
    { slug: "deleted-voucher-log", title: "Deleted Voucher Log" },
    { slug: "voucher-type-summary", title: "Voucher Type Summary" },
  ],
  "Receivables, Payables & Bill-wise Reports": [
    { slug: "bills-receivable", title: "Bills Receivable" },
    { slug: "bills-payable", title: "Bills Payable" },
    { slug: "ledger-outstandings", title: "Ledger Outstandings" },
    { slug: "group-outstandings", title: "Group Outstandings" },
    { slug: "receivables-ageing", title: "Receivables Ageing" },
    { slug: "payables-ageing", title: "Payables Ageing" },
    { slug: "bill-wise-receivables", title: "Bill-wise Receivables" },
    { slug: "bill-wise-payables", title: "Bill-wise Payables" },
    { slug: "customer-wise-outstanding", title: "Customer-wise Outstanding" },
    { slug: "supplier-wise-outstanding", title: "Supplier-wise Outstanding" },
    { slug: "salesperson-wise-outstanding", title: "Salesperson-wise Outstanding" },
    { slug: "area-wise-outstanding", title: "Area-wise Outstanding" },
    { slug: "due-today-receivables", title: "Due Today Receivables" },
    { slug: "due-today-payables", title: "Due Today Payables" },
    { slug: "overdue-receivables", title: "Overdue Receivables" },
    { slug: "overdue-payables", title: "Overdue Payables" },
    { slug: "credit-limit-exception", title: "Credit Limit Exception" },
    { slug: "credit-period-exception", title: "Credit Period Exception" },
    { slug: "interest-receivable", title: "Interest Receivable" },
    { slug: "interest-payable", title: "Interest Payable" },
    { slug: "interest-calculation-ledger-wise", title: "Interest Calculation Ledger-wise" },
    { slug: "interest-calculation-bill-wise", title: "Interest Calculation Bill-wise" },
    { slug: "collection-follow-up", title: "Collection Follow-up" },
    { slug: "payment-follow-up", title: "Payment Follow-up" },
    { slug: "promise-to-pay-report", title: "Promise-to-Pay Report" },
    { slug: "broken-promise-report", title: "Broken Promise Report" },
    { slug: "disputed-bills-report", title: "Disputed Bills Report" },
    { slug: "unadjusted-receipts", title: "Unadjusted Receipts" },
    { slug: "unadjusted-payments", title: "Unadjusted Payments" },
    { slug: "advance-from-customers", title: "Advance from Customers" },
    { slug: "advance-to-suppliers", title: "Advance to Suppliers" },
    { slug: "pending-bill-allocations", title: "Pending Bill Allocations" },
    { slug: "bill-settlement-register", title: "Bill Settlement Register" },
    { slug: "party-statement", title: "Party Statement" },
    { slug: "ledger-confirmation-report", title: "Ledger Confirmation Report" },
  ],
  "Cash, Bank, Finance & Banking": [
    { slug: "cash-book-detailed", title: "Cash Book Detailed" },
    { slug: "bank-book-detailed", title: "Bank Book Detailed" },
    { slug: "cash-summary", title: "Cash Summary" },
    { slug: "bank-summary", title: "Bank Summary" },
    { slug: "petty-cash-book", title: "Petty Cash Book" },
    { slug: "cash-deposit-report", title: "Cash Deposit Report" },
    { slug: "cash-withdrawal-report", title: "Cash Withdrawal Report" },
    { slug: "contra-cash-bank-movement", title: "Contra Cash-Bank Movement" },
    { slug: "bank-reconciliation", title: "Bank Reconciliation" },
    { slug: "bank-reconciliation-detailed", title: "Bank Reconciliation Detailed" },
    { slug: "imported-bank-statement", title: "Imported Bank Statement" },
    { slug: "bank-statement-matching", title: "Bank Statement Matching" },
    { slug: "unreconciled-bank-entries", title: "Unreconciled Bank Entries" },
    { slug: "reconciled-bank-entries", title: "Reconciled Bank Entries" },
    { slug: "cheque-register", title: "Cheque Register" },
    { slug: "cheque-issued-register", title: "Cheque Issued Register" },
    { slug: "cheque-received-register", title: "Cheque Received Register" },
    { slug: "post-dated-cheques-issued", title: "Post-dated Cheques Issued" },
    { slug: "post-dated-cheques-received", title: "Post-dated Cheques Received" },
    { slug: "bounced-cheque-report", title: "Bounced Cheque Report" },
    { slug: "cancelled-cheque-report", title: "Cancelled Cheque Report" },
    { slug: "upi-receipts-report", title: "UPI Receipts Report" },
    { slug: "neft-or-rtgs-payments-report", title: "NEFT/RTGS Payments Report" },
    { slug: "loan-register", title: "Loan Register" },
    { slug: "loan-emi-schedule", title: "Loan EMI Schedule" },
    { slug: "interest-on-loan-report", title: "Interest on Loan Report" },
    { slug: "cash-flow-forecast", title: "Cash Flow Forecast" },
    { slug: "daily-cash-position", title: "Daily Cash Position" },
    { slug: "bank-wise-balance-report", title: "Bank-wise Balance Report" },
    { slug: "payment-planning-report", title: "Payment Planning Report" },
  ],
  "Sales, Purchase & Party Analysis": [
    { slug: "sales-register-detailed", title: "Sales Register Detailed" },
    { slug: "sales-register-monthly", title: "Sales Register Monthly" },
    { slug: "sales-register-party-wise", title: "Sales Register Party-wise" },
    { slug: "sales-register-item-wise", title: "Sales Register Item-wise" },
    { slug: "sales-register-voucher-wise", title: "Sales Register Voucher-wise" },
    { slug: "sales-register-gst-wise", title: "Sales Register GST-wise" },
    { slug: "sales-register-state-wise", title: "Sales Register State-wise" },
    { slug: "sales-register-salesperson-wise", title: "Sales Register Salesperson-wise" },
    { slug: "sales-register-cost-centre-wise", title: "Sales Register Cost Centre-wise" },
    { slug: "sales-return-register", title: "Sales Return Register" },
    { slug: "purchase-register-detailed", title: "Purchase Register Detailed" },
    { slug: "purchase-register-monthly", title: "Purchase Register Monthly" },
    { slug: "purchase-register-supplier-wise", title: "Purchase Register Supplier-wise" },
    { slug: "purchase-register-item-wise", title: "Purchase Register Item-wise" },
    { slug: "purchase-register-voucher-wise", title: "Purchase Register Voucher-wise" },
    { slug: "purchase-register-gst-wise", title: "Purchase Register GST-wise" },
    { slug: "purchase-register-state-wise", title: "Purchase Register State-wise" },
    { slug: "purchase-register-cost-centre-wise", title: "Purchase Register Cost Centre-wise" },
    { slug: "purchase-return-register", title: "Purchase Return Register" },
    { slug: "customer-summary", title: "Customer Summary" },
    { slug: "supplier-summary", title: "Supplier Summary" },
    { slug: "customer-profitability", title: "Customer Profitability" },
    { slug: "supplier-purchase-analysis", title: "Supplier Purchase Analysis" },
    { slug: "top-customers-by-sales", title: "Top Customers by Sales" },
    { slug: "top-suppliers-by-purchase", title: "Top Suppliers by Purchase" },
    { slug: "dormant-customers", title: "Dormant Customers" },
    { slug: "dormant-suppliers", title: "Dormant Suppliers" },
    { slug: "new-customers-report", title: "New Customers Report" },
    { slug: "new-suppliers-report", title: "New Suppliers Report" },
    { slug: "customer-credit-analysis", title: "Customer Credit Analysis" },
    { slug: "supplier-credit-analysis", title: "Supplier Credit Analysis" },
    { slug: "discount-analysis", title: "Discount Analysis" },
    { slug: "additional-charges-analysis", title: "Additional Charges Analysis" },
    { slug: "freight-analysis", title: "Freight Analysis" },
    { slug: "salesperson-performance", title: "Salesperson Performance" },
    { slug: "sales-target-report", title: "Sales Target Report" },
    { slug: "sales-target-vs-actual", title: "Sales Target vs Actual" },
    { slug: "order-to-invoice-report", title: "Order to Invoice Report" },
    { slug: "purchase-order-to-bill-report", title: "Purchase Order to Bill Report" },
    { slug: "pending-sales-orders", title: "Pending Sales Orders" },
    { slug: "pending-purchase-orders", title: "Pending Purchase Orders" },
    { slug: "cancelled-sales-orders", title: "Cancelled Sales Orders" },
    { slug: "cancelled-purchase-orders", title: "Cancelled Purchase Orders" },
    { slug: "preclosed-sales-orders", title: "Preclosed Sales Orders" },
    { slug: "preclosed-purchase-orders", title: "Preclosed Purchase Orders" },
    { slug: "delivery-pending-sales-orders", title: "Delivery Pending Sales Orders" },
    { slug: "receipt-pending-purchase-orders", title: "Receipt Pending Purchase Orders" },
    { slug: "party-wise-sales-return", title: "Party-wise Sales Return" },
    { slug: "party-wise-purchase-return", title: "Party-wise Purchase Return" },
    { slug: "item-wise-sales-return", title: "Item-wise Sales Return" },
    { slug: "item-wise-purchase-return", title: "Item-wise Purchase Return" },
    { slug: "price-list-report", title: "Price List Report" },
    { slug: "price-change-history", title: "Price Change History" },
    { slug: "margin-analysis", title: "Margin Analysis" },
    { slug: "gross-profit-by-invoice", title: "Gross Profit by Invoice" },
  ],
  "Inventory, Stock & Godown Reports": [
    { slug: "stock-summary", title: "Stock Summary" },
    { slug: "stock-summary-group-wise", title: "Stock Summary Group-wise" },
    { slug: "stock-summary-item-wise", title: "Stock Summary Item-wise" },
    { slug: "stock-summary-godown-wise", title: "Stock Summary Godown-wise" },
    { slug: "stock-summary-batch-wise", title: "Stock Summary Batch-wise" },
    { slug: "stock-summary-category-wise", title: "Stock Summary Category-wise" },
    { slug: "stock-summary-with-rates", title: "Stock Summary with Rates" },
    { slug: "stock-summary-with-values", title: "Stock Summary with Values" },
    { slug: "stock-item-ledger", title: "Stock Item Ledger" },
    { slug: "stock-group-ledger", title: "Stock Group Ledger" },
    { slug: "godown-summary", title: "Godown Summary" },
    { slug: "godown-item-summary", title: "Godown Item Summary" },
    { slug: "godown-batch-summary", title: "Godown Batch Summary" },
    { slug: "stock-query", title: "Stock Query" },
    { slug: "stock-query-godown-wise", title: "Stock Query Godown-wise" },
    { slug: "stock-query-batch-wise", title: "Stock Query Batch-wise" },
    { slug: "stock-query-order-wise", title: "Stock Query Order-wise" },
    { slug: "movement-analysis", title: "Movement Analysis" },
    { slug: "movement-analysis-stock-item-wise", title: "Movement Analysis Stock Item-wise" },
    { slug: "movement-analysis-stock-group-wise", title: "Movement Analysis Stock Group-wise" },
    { slug: "movement-analysis-party-wise", title: "Movement Analysis Party-wise" },
    { slug: "movement-analysis-supplier-wise", title: "Movement Analysis Supplier-wise" },
    { slug: "movement-analysis-buyer-wise", title: "Movement Analysis Buyer-wise" },
    { slug: "movement-analysis-consumption-wise", title: "Movement Analysis Consumption-wise" },
    { slug: "stock-ageing-analysis", title: "Stock Ageing Analysis" },
    { slug: "stock-ageing-by-purchase-date", title: "Stock Ageing by Purchase Date" },
    { slug: "stock-ageing-by-manufacturing-date", title: "Stock Ageing by Manufacturing Date" },
    { slug: "stock-ageing-by-expiry-date", title: "Stock Ageing by Expiry Date" },
    { slug: "to-be-expired-stock-report", title: "To-be-Expired Stock Report" },
    { slug: "expired-stock-report", title: "Expired Stock Report" },
    { slug: "batch-wise-stock-report", title: "Batch-wise Stock Report" },
    { slug: "mrp-wise-stock-report", title: "MRP-wise Stock Report" },
    { slug: "reorder-status", title: "Reorder Status" },
    { slug: "reorder-quantity-report", title: "Reorder Quantity Report" },
    { slug: "negative-stock-report", title: "Negative Stock Report" },
    { slug: "zero-stock-report", title: "Zero Stock Report" },
    { slug: "low-stock-report", title: "Low Stock Report" },
    { slug: "fast-moving-items", title: "Fast Moving Items" },
    { slug: "slow-moving-items", title: "Slow Moving Items" },
    { slug: "non-moving-items", title: "Non-moving Items" },
    { slug: "stock-valuation", title: "Stock Valuation" },
    { slug: "fifo-stock-valuation", title: "FIFO Stock Valuation" },
    { slug: "average-cost-stock-valuation", title: "Average Cost Stock Valuation" },
    { slug: "last-purchase-cost-valuation", title: "Last Purchase Cost Valuation" },
    { slug: "standard-cost-valuation", title: "Standard Cost Valuation" },
    { slug: "physical-stock-register-inventory", title: "Physical Stock Register" },
    { slug: "physical-stock-variance", title: "Physical Stock Variance" },
    { slug: "stock-journal-register-inventory", title: "Stock Journal Register" },
    { slug: "stock-transfer-register", title: "Stock Transfer Register" },
    { slug: "inter-godown-transfer-report", title: "Inter-Godown Transfer Report" },
    { slug: "material-in-report", title: "Material In Report" },
    { slug: "material-out-report", title: "Material Out Report" },
    { slug: "rejection-in-report", title: "Rejection In Report" },
    { slug: "rejection-out-report", title: "Rejection Out Report" },
    { slug: "delivery-note-register-inventory", title: "Delivery Note Register" },
    { slug: "receipt-note-register-inventory", title: "Receipt Note Register" },
    { slug: "inventory-voucher-register", title: "Inventory Voucher Register" },
    { slug: "stock-item-profitability", title: "Stock Item Profitability" },
    { slug: "stock-category-summary", title: "Stock Category Summary" },
    { slug: "stock-category-movement", title: "Stock Category Movement" },
    { slug: "stock-group-profitability", title: "Stock Group Profitability" },
    { slug: "stock-item-cost-analysis", title: "Stock Item Cost Analysis" },
    { slug: "stock-item-sales-trend", title: "Stock Item Sales Trend" },
    { slug: "stock-item-purchase-trend", title: "Stock Item Purchase Trend" },
    { slug: "inventory-exception-report", title: "Inventory Exception Report" },
  ],
  "Manufacturing, Job Work & Costing": [
    { slug: "bill-of-materials-report", title: "Bill of Materials Report" },
    { slug: "bom-component-summary", title: "BOM Component Summary" },
    { slug: "bom-cost-report", title: "BOM Cost Report" },
    { slug: "manufacturing-journal-register-manufacturing", title: "Manufacturing Journal Register" },
    { slug: "production-summary", title: "Production Summary" },
    { slug: "production-voucher-register", title: "Production Voucher Register" },
    { slug: "finished-goods-production-report", title: "Finished Goods Production Report" },
    { slug: "raw-material-consumption-report", title: "Raw Material Consumption Report" },
    { slug: "wastage-report", title: "Wastage Report" },
    { slug: "scrap-report", title: "Scrap Report" },
    { slug: "yield-analysis", title: "Yield Analysis" },
    { slug: "standard-vs-actual-consumption", title: "Standard vs Actual Consumption" },
    { slug: "production-cost-sheet", title: "Production Cost Sheet" },
    { slug: "job-work-in-register", title: "Job Work In Register" },
    { slug: "job-work-out-register", title: "Job Work Out Register" },
    { slug: "material-sent-to-job-worker", title: "Material Sent to Job Worker" },
    { slug: "material-received-from-job-worker", title: "Material Received from Job Worker" },
    { slug: "pending-job-work-material", title: "Pending Job Work Material" },
    { slug: "job-worker-wise-stock", title: "Job Worker-wise Stock" },
    { slug: "principal-manufacturer-wise-stock", title: "Principal Manufacturer-wise Stock" },
    { slug: "cost-centre-summary", title: "Cost Centre Summary" },
    { slug: "cost-category-summary", title: "Cost Category Summary" },
    { slug: "cost-centre-break-up", title: "Cost Centre Break-up" },
    { slug: "cost-centre-ledger", title: "Cost Centre Ledger" },
    { slug: "cost-centre-wise-p-and-l", title: "Cost Centre-wise P&L" },
    { slug: "project-cost-report", title: "Project Cost Report" },
    { slug: "project-profitability", title: "Project Profitability" },
    { slug: "department-cost-report", title: "Department Cost Report" },
    { slug: "batch-costing-report", title: "Batch Costing Report" },
    { slug: "order-costing-report", title: "Order Costing Report" },
  ],
  "GST Reports": [
    { slug: "gst-reports-menu", title: "GST Reports Menu" },
    { slug: "gst-return-activities", title: "GST Return Activities" },
    { slug: "gstr-1", title: "GSTR-1" },
    { slug: "gstr-1-summary", title: "GSTR-1 Summary" },
    { slug: "gstr-1-b2b", title: "GSTR-1 B2B" },
    { slug: "gstr-1-b2c-large", title: "GSTR-1 B2C Large" },
    { slug: "gstr-1-b2c-small", title: "GSTR-1 B2C Small" },
    { slug: "gstr-1-credit-or-debit-notes", title: "GSTR-1 Credit/Debit Notes" },
    { slug: "gstr-1-export-invoices", title: "GSTR-1 Export Invoices" },
    { slug: "gstr-1-nil-rated-supplies", title: "GSTR-1 Nil Rated Supplies" },
    { slug: "gstr-1-hsn-summary", title: "GSTR-1 HSN Summary" },
    { slug: "gstr-1-document-summary", title: "GSTR-1 Document Summary" },
    { slug: "gstr-1-uncertain-transactions", title: "GSTR-1 Uncertain Transactions" },
    { slug: "gstr-1-not-relevant-in-return", title: "GSTR-1 Not Relevant in Return" },
    { slug: "gstr-1-included-in-return", title: "GSTR-1 Included in Return" },
    { slug: "gstr-1-uploaded-transactions", title: "GSTR-1 Uploaded Transactions" },
    { slug: "gstr-1-mismatched-transactions", title: "GSTR-1 Mismatched Transactions" },
    { slug: "gstr-1-rejected-transactions", title: "GSTR-1 Rejected Transactions" },
    { slug: "gstr-1-reconciliation", title: "GSTR-1 Reconciliation" },
    { slug: "gstr-3b", title: "GSTR-3B" },
    { slug: "gstr-3b-summary", title: "GSTR-3B Summary" },
    { slug: "gstr-3b-return-format", title: "GSTR-3B Return Format" },
    { slug: "gstr-3b-books-vs-portal", title: "GSTR-3B Books vs Portal" },
    { slug: "gstr-3b-outward-supplies", title: "GSTR-3B Outward Supplies" },
    { slug: "gstr-3b-itc-available", title: "GSTR-3B ITC Available" },
    { slug: "gstr-3b-itc-reversed", title: "GSTR-3B ITC Reversed" },
    { slug: "gstr-3b-exempt-or-nil-or-non-gst", title: "GSTR-3B Exempt/Nil/Non-GST" },
    { slug: "gstr-3b-interest-and-late-fee", title: "GSTR-3B Interest & Late Fee" },
    { slug: "gstr-3b-payment-details", title: "GSTR-3B Payment Details" },
    { slug: "gstr-3b-uncertain-transactions", title: "GSTR-3B Uncertain Transactions" },
    { slug: "gstr-3b-not-relevant-in-return", title: "GSTR-3B Not Relevant in Return" },
    { slug: "gstr-3b-reconciliation", title: "GSTR-3B Reconciliation" },
    { slug: "gstr-2a-reconciliation", title: "GSTR-2A Reconciliation" },
    { slug: "gstr-2b-reconciliation", title: "GSTR-2B Reconciliation" },
    { slug: "gst-annual-computation", title: "GST Annual Computation" },
    { slug: "gstr-9-annual-return-summary", title: "GSTR-9 Annual Return Summary" },
    { slug: "gstr-9-outward-supplies", title: "GSTR-9 Outward Supplies" },
    { slug: "gstr-9-itc-summary", title: "GSTR-9 ITC Summary" },
    { slug: "gstr-9-hsn-summary", title: "GSTR-9 HSN Summary" },
    { slug: "gst-challan-reconciliation", title: "GST Challan Reconciliation" },
    { slug: "gst-payment-register", title: "GST Payment Register" },
    { slug: "gst-liability-register", title: "GST Liability Register" },
    { slug: "gst-input-tax-credit-ledger", title: "GST Input Tax Credit Ledger" },
    { slug: "gst-output-tax-ledger", title: "GST Output Tax Ledger" },
    { slug: "gst-tax-rate-wise-sales", title: "GST Tax Rate-wise Sales" },
    { slug: "gst-tax-rate-wise-purchase", title: "GST Tax Rate-wise Purchase" },
    { slug: "gst-hsn-or-sac-summary", title: "GST HSN/SAC Summary" },
    { slug: "gst-state-wise-sales", title: "GST State-wise Sales" },
    { slug: "gst-state-wise-purchase", title: "GST State-wise Purchase" },
    { slug: "gst-party-wise-sales", title: "GST Party-wise Sales" },
    { slug: "gst-party-wise-purchase", title: "GST Party-wise Purchase" },
    { slug: "gstin-validation-exception", title: "GSTIN Validation Exception" },
    { slug: "missing-hsn-or-sac-report", title: "Missing HSN/SAC Report" },
    { slug: "missing-gstin-report", title: "Missing GSTIN Report" },
    { slug: "place-of-supply-exception", title: "Place of Supply Exception" },
    { slug: "reverse-charge-report", title: "Reverse Charge Report" },
    { slug: "advance-receipt-gst-report", title: "Advance Receipt GST Report" },
    { slug: "advance-adjustment-gst-report", title: "Advance Adjustment GST Report" },
    { slug: "gst-audit-trail", title: "GST Audit Trail" },
    { slug: "gst-exception-resolution-report", title: "GST Exception Resolution Report" },
  ],
  "e-Invoice, e-Way Bill & Exchange": [
    { slug: "e-invoice-report", title: "e-Invoice Report" },
    { slug: "e-invoice-register", title: "e-Invoice Register" },
    { slug: "e-invoice-pending-for-generation", title: "e-Invoice Pending for Generation" },
    { slug: "e-invoice-generated", title: "e-Invoice Generated" },
    { slug: "e-invoice-cancelled", title: "e-Invoice Cancelled" },
    { slug: "e-invoice-failed", title: "e-Invoice Failed" },
    { slug: "e-invoice-error-report", title: "e-Invoice Error Report" },
    { slug: "irn-details-report", title: "IRN Details Report" },
    { slug: "ack-number-register", title: "Ack Number Register" },
    { slug: "e-invoice-correction-report", title: "e-Invoice Correction Report" },
    { slug: "e-way-bill-report", title: "e-Way Bill Report" },
    { slug: "e-way-bill-register", title: "e-Way Bill Register" },
    { slug: "e-way-bill-pending", title: "e-Way Bill Pending" },
    { slug: "e-way-bill-generated", title: "e-Way Bill Generated" },
    { slug: "e-way-bill-cancelled", title: "e-Way Bill Cancelled" },
    { slug: "e-way-bill-expired", title: "e-Way Bill Expired" },
    { slug: "e-way-bill-extended-validity", title: "e-Way Bill Extended Validity" },
    { slug: "e-way-bill-part-b-pending", title: "e-Way Bill Part-B Pending" },
    { slug: "transporter-id-pending", title: "Transporter ID Pending" },
    { slug: "vehicle-number-pending", title: "Vehicle Number Pending" },
    { slug: "distance-exception-report", title: "Distance Exception Report" },
    { slug: "consolidated-e-way-bill-report", title: "Consolidated e-Way Bill Report" },
    { slug: "exchange-activity-log", title: "Exchange Activity Log" },
    { slug: "upload-gst-returns-log", title: "Upload GST Returns Log" },
    { slug: "download-gst-data-log", title: "Download GST Data Log" },
    { slug: "gst-portal-sync-status", title: "GST Portal Sync Status" },
    { slug: "failed-uploads-report", title: "Failed Uploads Report" },
    { slug: "imported-gst-data-report", title: "Imported GST Data Report" },
    { slug: "exported-json-report", title: "Exported JSON Report" },
    { slug: "portal-difference-report", title: "Portal Difference Report" },
  ],
  "TDS Reports": [
    { slug: "tds-reports-menu", title: "TDS Reports Menu" },
    { slug: "tds-challan-reconciliation", title: "TDS Challan Reconciliation" },
    { slug: "tds-challan-details", title: "TDS Challan Details" },
    { slug: "tds-challan-status", title: "TDS Challan Status" },
    { slug: "form-26q", title: "Form 26Q" },
    { slug: "form-27q", title: "Form 27Q" },
    { slug: "form-24q", title: "Form 24Q" },
    { slug: "tds-return-transaction-book", title: "TDS Return Transaction Book" },
    { slug: "tds-outstandings", title: "TDS Outstandings" },
    { slug: "tds-outstandings-nature-of-payment-wise", title: "TDS Outstandings Nature of Payment-wise" },
    { slug: "tds-outstandings-party-wise", title: "TDS Outstandings Party-wise" },
    { slug: "ledgers-without-pan-deductees", title: "Ledgers Without PAN - Deductees" },
    { slug: "deductee-pan-exception", title: "Deductee PAN Exception" },
    { slug: "deductee-type-exception", title: "Deductee Type Exception" },
    { slug: "resident-type-exception", title: "Resident Type Exception" },
    { slug: "section-number-exception", title: "Section Number Exception" },
    { slug: "tds-deduction-details", title: "TDS Deduction Details" },
    { slug: "tds-deducted-at-normal-rate", title: "TDS Deducted at Normal Rate" },
    { slug: "tds-deducted-at-higher-rate", title: "TDS Deducted at Higher Rate" },
    { slug: "tds-zero-or-lower-rate-deduction", title: "TDS Zero/Lower Rate Deduction" },
    { slug: "tds-exemption-limit-report", title: "TDS Exemption Limit Report" },
    { slug: "tds-payment-details", title: "TDS Payment Details" },
    { slug: "tds-balance-payable", title: "TDS Balance Payable" },
    { slug: "tds-recompute-return", title: "TDS Recompute Return" },
    { slug: "tds-revised-return", title: "TDS Revised Return" },
    { slug: "tds-save-return", title: "TDS Save Return" },
    { slug: "tds-remarks-report", title: "TDS Remarks Report" },
    { slug: "tds-exception-report", title: "TDS Exception Report" },
    { slug: "tds-validation-or-fvu-report", title: "TDS Validation/FVU Report" },
    { slug: "tds-return-export-report", title: "TDS Return Export Report" },
  ],
  "TCS Reports": [
    { slug: "tcs-reports-menu", title: "TCS Reports Menu" },
    { slug: "tcs-challan-reconciliation", title: "TCS Challan Reconciliation" },
    { slug: "tcs-challan-details", title: "TCS Challan Details" },
    { slug: "form-27eq", title: "Form 27EQ" },
    { slug: "tcs-return-transaction-book", title: "TCS Return Transaction Book" },
    { slug: "tcs-outstandings", title: "TCS Outstandings" },
    { slug: "tcs-outstandings-nature-of-goods-wise", title: "TCS Outstandings Nature of Goods-wise" },
    { slug: "tcs-outstandings-party-wise", title: "TCS Outstandings Party-wise" },
    { slug: "ledgers-without-pan-collectees", title: "Ledgers Without PAN - Collectees" },
    { slug: "buyer-ledger-without-pan", title: "Buyer Ledger Without PAN" },
    { slug: "tcs-collection-details", title: "TCS Collection Details" },
    { slug: "tcs-collection-at-normal-rate", title: "TCS Collection at Normal Rate" },
    { slug: "tcs-collection-at-higher-rate", title: "TCS Collection at Higher Rate" },
    { slug: "tcs-zero-or-lower-rate-collection", title: "TCS Zero/Lower Rate Collection" },
    { slug: "tcs-exemption-limit-report", title: "TCS Exemption Limit Report" },
    { slug: "tcs-payment-details", title: "TCS Payment Details" },
    { slug: "tcs-balance-payable", title: "TCS Balance Payable" },
    { slug: "tcs-recompute-return", title: "TCS Recompute Return" },
    { slug: "tcs-revised-return", title: "TCS Revised Return" },
    { slug: "tcs-save-return", title: "TCS Save Return" },
    { slug: "tcs-remarks-report", title: "TCS Remarks Report" },
    { slug: "tcs-exception-report", title: "TCS Exception Report" },
    { slug: "tcs-challan-details-of-buyer", title: "TCS Challan Details of Buyer" },
    { slug: "tcs-validation-report", title: "TCS Validation Report" },
    { slug: "tcs-return-export-report", title: "TCS Return Export Report" },
  ],
  "Payroll & HR Reports": [
    { slug: "payroll-reports-menu", title: "Payroll Reports Menu" },
    { slug: "payroll-summary", title: "Payroll Summary" },
    { slug: "employee-summary", title: "Employee Summary" },
    { slug: "employee-pay-slip", title: "Employee Pay Slip" },
    { slug: "pay-sheet", title: "Pay Sheet" },
    { slug: "salary-register", title: "Salary Register" },
    { slug: "attendance-register", title: "Attendance Register" },
    { slug: "attendance-sheet", title: "Attendance Sheet" },
    { slug: "overtime-register", title: "Overtime Register" },
    { slug: "leave-register", title: "Leave Register" },
    { slug: "leave-encashment-report", title: "Leave Encashment Report" },
    { slug: "gratuity-report", title: "Gratuity Report" },
    { slug: "employee-loan-or-advance-report", title: "Employee Loan/Advance Report" },
    { slug: "payroll-voucher-register-payroll", title: "Payroll Voucher Register" },
    { slug: "payroll-cost-centre-report", title: "Payroll Cost Centre Report" },
    { slug: "department-wise-payroll", title: "Department-wise Payroll" },
    { slug: "employee-group-wise-payroll", title: "Employee Group-wise Payroll" },
    { slug: "pay-head-summary", title: "Pay Head Summary" },
    { slug: "pay-head-employee-wise", title: "Pay Head Employee-wise" },
    { slug: "earnings-summary", title: "Earnings Summary" },
    { slug: "deductions-summary", title: "Deductions Summary" },
    { slug: "employer-contribution-summary", title: "Employer Contribution Summary" },
    { slug: "payroll-statutory-summary", title: "Payroll Statutory Summary" },
    { slug: "payroll-statutory-pay-head-details", title: "Payroll Statutory Pay Head Details" },
    { slug: "provident-fund-summary", title: "Provident Fund Summary" },
    { slug: "pf-form-5", title: "PF Form 5" },
    { slug: "pf-form-10", title: "PF Form 10" },
    { slug: "pf-form-12a", title: "PF Form 12A" },
    { slug: "pf-monthly-statement", title: "PF Monthly Statement" },
    { slug: "pf-e-challan-cum-return", title: "PF E-Challan-cum-Return" },
    { slug: "pf-form-3a", title: "PF Form 3A" },
    { slug: "pf-form-6a", title: "PF Form 6A" },
    { slug: "pf-e-return", title: "PF E-Return" },
    { slug: "employee-state-insurance-summary", title: "Employee State Insurance Summary" },
    { slug: "esi-monthly-contribution", title: "ESI Monthly Contribution" },
    { slug: "esi-employee-wise-contribution", title: "ESI Employee-wise Contribution" },
    { slug: "esi-employer-contribution", title: "ESI Employer Contribution" },
    { slug: "professional-tax-summary", title: "Professional Tax Summary" },
    { slug: "professional-tax-employee-wise", title: "Professional Tax Employee-wise" },
    { slug: "professional-tax-state-wise", title: "Professional Tax State-wise" },
    { slug: "national-pension-scheme-summary", title: "National Pension Scheme Summary" },
    { slug: "nps-employee-contribution", title: "NPS Employee Contribution" },
    { slug: "nps-employer-contribution", title: "NPS Employer Contribution" },
    { slug: "income-tax-summary", title: "Income Tax Summary" },
    { slug: "form-16", title: "Form 16" },
    { slug: "form-12ba", title: "Form 12BA" },
    { slug: "annexure-i", title: "Annexure I" },
    { slug: "annexure-ii", title: "Annexure II" },
    { slug: "form-24q-payroll", title: "Form 24Q Payroll" },
    { slug: "e-24q-return", title: "E-24Q Return" },
    { slug: "tds-variance-payroll", title: "TDS Variance Payroll" },
    { slug: "income-tax-projection", title: "Income Tax Projection" },
    { slug: "tax-regime-comparison", title: "Tax Regime Comparison" },
    { slug: "employee-investment-declaration", title: "Employee Investment Declaration" },
    { slug: "employee-tax-computation", title: "Employee Tax Computation" },
  ],
  "VAT, Excise, Service Tax, MSME & Legacy Statutory": [
    { slug: "vat-reports-menu", title: "VAT Reports Menu" },
    { slug: "vat-computation", title: "VAT Computation" },
    { slug: "vat-return-summary", title: "VAT Return Summary" },
    { slug: "vat-sales-annexure", title: "VAT Sales Annexure" },
    { slug: "vat-purchase-annexure", title: "VAT Purchase Annexure" },
    { slug: "vat-commodity-wise-report", title: "VAT Commodity-wise Report" },
    { slug: "vat-party-wise-report", title: "VAT Party-wise Report" },
    { slug: "vat-form-rt-iii", title: "VAT Form RT-III" },
    { slug: "vat-payment-details", title: "VAT Payment Details" },
    { slug: "vat-exception-report", title: "VAT Exception Report" },
    { slug: "central-excise-reports-menu", title: "Central Excise Reports Menu" },
    { slug: "excise-computation", title: "Excise Computation" },
    { slug: "excise-duty-payable", title: "Excise Duty Payable" },
    { slug: "excise-sales-register", title: "Excise Sales Register" },
    { slug: "excise-purchase-register", title: "Excise Purchase Register" },
    { slug: "excise-stock-register", title: "Excise Stock Register" },
    { slug: "excise-invoice-register", title: "Excise Invoice Register" },
    { slug: "excise-payment-register", title: "Excise Payment Register" },
    { slug: "excise-exception-report", title: "Excise Exception Report" },
    { slug: "service-tax-reports-menu", title: "Service Tax Reports Menu" },
    { slug: "service-tax-computation", title: "Service Tax Computation" },
    { slug: "form-st-3", title: "Form ST-3" },
    { slug: "service-tax-payable", title: "Service Tax Payable" },
    { slug: "service-tax-input-credit", title: "Service Tax Input Credit" },
    { slug: "service-tax-payment-details", title: "Service Tax Payment Details" },
    { slug: "service-tax-exception-report", title: "Service Tax Exception Report" },
    { slug: "msme-reports-menu", title: "MSME Reports Menu" },
    { slug: "msme-form-1", title: "MSME Form 1" },
    { slug: "msme-outstanding-to-micro-or-small-enterprises", title: "MSME Outstanding to Micro/Small Enterprises" },
    { slug: "msme-supplier-ageing", title: "MSME Supplier Ageing" },
    { slug: "msme-interest-payable", title: "MSME Interest Payable" },
    { slug: "msme-pending-acceptance-report", title: "MSME Pending Acceptance Report" },
    { slug: "msme-party-classification-exception", title: "MSME Party Classification Exception" },
    { slug: "msme-payment-delay-report", title: "MSME Payment Delay Report" },
    { slug: "msme-compliance-summary", title: "MSME Compliance Summary" },
  ],
  "Audit, Edit Log, Security & Admin": [
    { slug: "audit-and-compliance-menu", title: "Audit & Compliance Menu" },
    { slug: "tally-audit-listing", title: "Tally Audit Listing" },
    { slug: "voucher-audit", title: "Voucher Audit" },
    { slug: "ledger-audit", title: "Ledger Audit" },
    { slug: "master-alteration-audit", title: "Master Alteration Audit" },
    { slug: "deleted-masters-report", title: "Deleted Masters Report" },
    { slug: "deleted-vouchers-report", title: "Deleted Vouchers Report" },
    { slug: "altered-vouchers-report", title: "Altered Vouchers Report" },
    { slug: "altered-ledgers-report", title: "Altered Ledgers Report" },
    { slug: "edit-log-report", title: "Edit Log Report" },
    { slug: "edit-log-voucher-wise", title: "Edit Log Voucher-wise" },
    { slug: "edit-log-master-wise", title: "Edit Log Master-wise" },
    { slug: "user-activity-log", title: "User Activity Log" },
    { slug: "login-or-logout-report", title: "Login/Logout Report" },
    { slug: "company-access-log", title: "Company Access Log" },
    { slug: "security-control-report", title: "Security Control Report" },
    { slug: "user-rights-report", title: "User Rights Report" },
    { slug: "role-permission-report", title: "Role Permission Report" },
    { slug: "data-synchronisation-report", title: "Data Synchronisation Report" },
    { slug: "backup-status-report", title: "Backup Status Report" },
    { slug: "restore-history-report", title: "Restore History Report" },
    { slug: "data-import-log", title: "Data Import Log" },
    { slug: "data-export-log", title: "Data Export Log" },
    { slug: "remote-access-report", title: "Remote Access Report" },
    { slug: "connected-services-status", title: "Connected Services Status" },
    { slug: "license-or-subscription-status", title: "License/Subscription Status" },
    { slug: "company-features-report", title: "Company Features Report" },
    { slug: "statutory-features-report", title: "Statutory Features Report" },
    { slug: "inventory-features-report", title: "Inventory Features Report" },
    { slug: "accounting-features-report", title: "Accounting Features Report" },
    { slug: "exception-reports-summary", title: "Exception Reports Summary" },
    { slug: "negative-cash-exception", title: "Negative Cash Exception" },
    { slug: "duplicate-voucher-number-exception", title: "Duplicate Voucher Number Exception" },
    { slug: "missing-master-details-exception", title: "Missing Master Details Exception" },
    { slug: "data-health-check-report", title: "Data Health Check Report" },
  ],
};

// Re-export individual category constants for consumers who want a specific slice
export {
  GATEWAY_DEFINITIONS,
  FINANCIAL_DEFINITIONS,
  ACCOUNT_BOOKS_DEFINITIONS,
  RECEIVABLES_DEFINITIONS,
  CASH_BANK_DEFINITIONS,
  SALES_PURCHASE_DEFINITIONS,
  INVENTORY_DEFINITIONS,
  MANUFACTURING_DEFINITIONS,
  GST_DEFINITIONS,
  E_INVOICE_DEFINITIONS,
  TDS_DEFINITIONS,
  TCS_DEFINITIONS,
  PAYROLL_DEFINITIONS,
  STATUTORY_DEFINITIONS,
  AUDIT_DEFINITIONS,
};
