import type { ReportConfig } from "./types";

export const INVENTORY_DEFINITIONS: Record<string, ReportConfig> = {
  "stock-summary": {
    title: "Stock Summary",
    apiMethod: "stockSummary",
    columns: [
      { header: "Stock Item", field: "item_name" },
      { header: "Group", field: "group_name" },
      { header: "Opening Qty", field: "opening_qty", type: "number", align: "center" },
      { header: "Opening Value", field: "opening_value", type: "currency", align: "right" },
      { header: "Inward Qty", field: "inwards_qty", type: "number", align: "center" },
      { header: "Inward Value", field: "inwards_value", type: "currency", align: "right" },
      { header: "Outward Qty", field: "outwards_qty", type: "number", align: "center" },
      { header: "Outward Value", field: "outwards_value", type: "currency", align: "right" },
      { header: "Closing Qty", field: "closing_qty", type: "number", align: "center" },
      { header: "Closing Value", field: "closing_value", type: "currency", align: "right" },
    ],
  },
  "stock-summary-group-wise": {
    title: "Stock Summary Group-wise",
    apiMethod: "stockSummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-summary-item-wise": {
    title: "Stock Summary Item-wise",
    apiMethod: "stockSummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-summary-godown-wise": {
    title: "Stock Summary Godown-wise",
    apiMethod: "stockSummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-summary-batch-wise": {
    title: "Stock Summary Batch-wise",
    apiMethod: "stockSummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-summary-category-wise": {
    title: "Stock Summary Category-wise",
    apiMethod: "stockSummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-summary-with-rates": {
    title: "Stock Summary with Rates",
    apiMethod: "stockSummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-summary-with-values": {
    title: "Stock Summary with Values",
    apiMethod: "stockSummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-item-ledger": {
    title: "Stock Item Ledger",
    apiMethod: "run",
    reportId: "stock_item_ledger",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "stock-group-ledger": {
    title: "Stock Group Ledger",
    apiMethod: "run",
    reportId: "stock_group_ledger",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "godown-summary": {
    title: "Godown Summary",
    apiMethod: "godownSummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "godown-item-summary": {
    title: "Godown Item Summary",
    apiMethod: "run",
    reportId: "godown_item_summary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "godown-batch-summary": {
    title: "Godown Batch Summary",
    apiMethod: "run",
    reportId: "godown_batch_summary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-query": {
    title: "Stock Query",
    apiMethod: "run",
    reportId: "stock_query",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-query-godown-wise": {
    title: "Stock Query Godown-wise",
    apiMethod: "run",
    reportId: "stock_query_godown_wise",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-query-batch-wise": {
    title: "Stock Query Batch-wise",
    apiMethod: "run",
    reportId: "stock_query_batch_wise",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-query-order-wise": {
    title: "Stock Query Order-wise",
    apiMethod: "run",
    reportId: "stock_query_order_wise",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "movement-analysis": {
    title: "Movement Analysis",
    apiMethod: "movementAnalysis",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "movement-analysis-stock-item-wise": {
    title: "Movement Analysis Stock Item-wise",
    apiMethod: "movementAnalysis",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "movement-analysis-stock-group-wise": {
    title: "Movement Analysis Stock Group-wise",
    apiMethod: "movementAnalysis",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "movement-analysis-party-wise": {
    title: "Movement Analysis Party-wise",
    apiMethod: "movementAnalysis",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "movement-analysis-supplier-wise": {
    title: "Movement Analysis Supplier-wise",
    apiMethod: "movementAnalysis",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "movement-analysis-buyer-wise": {
    title: "Movement Analysis Buyer-wise",
    apiMethod: "movementAnalysis",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "movement-analysis-consumption-wise": {
    title: "Movement Analysis Consumption-wise",
    apiMethod: "movementAnalysis",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-ageing-analysis": {
    title: "Stock Ageing Analysis",
    apiMethod: "stockAgeing",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-ageing-by-purchase-date": {
    title: "Stock Ageing by Purchase Date",
    apiMethod: "stockAgeing",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "stock-ageing-by-manufacturing-date": {
    title: "Stock Ageing by Manufacturing Date",
    apiMethod: "stockAgeing",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-ageing-by-expiry-date": {
    title: "Stock Ageing by Expiry Date",
    apiMethod: "stockAgeing",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "to-be-expired-stock-report": {
    title: "To-be-Expired Stock Report",
    apiMethod: "run",
    reportId: "to_be_expired_stock_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "expired-stock-report": {
    title: "Expired Stock Report",
    apiMethod: "run",
    reportId: "expired_stock_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "batch-wise-stock-report": {
    title: "Batch-wise Stock Report",
    apiMethod: "run",
    reportId: "batch_wise_stock_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "mrp-wise-stock-report": {
    title: "MRP-wise Stock Report",
    apiMethod: "run",
    reportId: "mrp_wise_stock_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "reorder-status": {
    title: "Reorder Status",
    apiMethod: "reorderStatus",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "reorder-quantity-report": {
    title: "Reorder Quantity Report",
    apiMethod: "run",
    reportId: "reorder_quantity_report",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "negative-stock-report": {
    title: "Negative Stock Report",
    apiMethod: "run",
    reportId: "negative_stock_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "zero-stock-report": {
    title: "Zero Stock Report",
    apiMethod: "run",
    reportId: "zero_stock_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "low-stock-report": {
    title: "Low Stock Report",
    apiMethod: "run",
    reportId: "low_stock_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "fast-moving-items": {
    title: "Fast Moving Items",
    apiMethod: "run",
    reportId: "fast_moving_items",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "slow-moving-items": {
    title: "Slow Moving Items",
    apiMethod: "run",
    reportId: "slow_moving_items",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "non-moving-items": {
    title: "Non-moving Items",
    apiMethod: "run",
    reportId: "non_moving_items",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-valuation": {
    title: "Stock Valuation",
    apiMethod: "run",
    reportId: "stock_valuation",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "fifo-stock-valuation": {
    title: "FIFO Stock Valuation",
    apiMethod: "run",
    reportId: "fifo_stock_valuation",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "average-cost-stock-valuation": {
    title: "Average Cost Stock Valuation",
    apiMethod: "run",
    reportId: "average_cost_stock_valuation",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "last-purchase-cost-valuation": {
    title: "Last Purchase Cost Valuation",
    apiMethod: "run",
    reportId: "last_purchase_cost_valuation",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "standard-cost-valuation": {
    title: "Standard Cost Valuation",
    apiMethod: "run",
    reportId: "standard_cost_valuation",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "physical-stock-register-inventory": {
    title: "Physical Stock Register",
    apiMethod: "run",
    reportId: "physical_stock_register_inventory",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "physical-stock-variance": {
    title: "Physical Stock Variance",
    apiMethod: "run",
    reportId: "physical_stock_variance",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-journal-register-inventory": {
    title: "Stock Journal Register",
    apiMethod: "run",
    reportId: "stock_journal_register_inventory",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "stock-transfer-register": {
    title: "Stock Transfer Register",
    apiMethod: "run",
    reportId: "stock_transfer_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "inter-godown-transfer-report": {
    title: "Inter-Godown Transfer Report",
    apiMethod: "run",
    reportId: "inter_godown_transfer_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "material-in-report": {
    title: "Material In Report",
    apiMethod: "run",
    reportId: "material_in_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "material-out-report": {
    title: "Material Out Report",
    apiMethod: "run",
    reportId: "material_out_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "rejection-in-report": {
    title: "Rejection In Report",
    apiMethod: "run",
    reportId: "rejection_in_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "rejection-out-report": {
    title: "Rejection Out Report",
    apiMethod: "run",
    reportId: "rejection_out_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "delivery-note-register-inventory": {
    title: "Delivery Note Register",
    apiMethod: "run",
    reportId: "delivery_note_register_inventory",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "receipt-note-register-inventory": {
    title: "Receipt Note Register",
    apiMethod: "run",
    reportId: "receipt_note_register_inventory",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "inventory-voucher-register": {
    title: "Inventory Voucher Register",
    apiMethod: "run",
    reportId: "inventory_voucher_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "stock-item-profitability": {
    title: "Stock Item Profitability",
    apiMethod: "run",
    reportId: "stock_item_profitability",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-category-summary": {
    title: "Stock Category Summary",
    apiMethod: "stockCategorySummary",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-category-movement": {
    title: "Stock Category Movement",
    apiMethod: "run",
    reportId: "stock_category_movement",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-group-profitability": {
    title: "Stock Group Profitability",
    apiMethod: "run",
    reportId: "stock_group_profitability",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-item-cost-analysis": {
    title: "Stock Item Cost Analysis",
    apiMethod: "run",
    reportId: "stock_item_cost_analysis",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "stock-item-sales-trend": {
    title: "Stock Item Sales Trend",
    apiMethod: "run",
    reportId: "stock_item_sales_trend",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "stock-item-purchase-trend": {
    title: "Stock Item Purchase Trend",
    apiMethod: "run",
    reportId: "stock_item_purchase_trend",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "inventory-exception-report": {
    title: "Inventory Exception Report",
    apiMethod: "run",
    reportId: "inventory_exception_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "bill-of-materials-report": {
    title: "Bill of Materials Report",
    apiMethod: "run",
    reportId: "bill_of_materials_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "bom-component-summary": {
    title: "BOM Component Summary",
    apiMethod: "run",
    reportId: "bom_component_summary",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "bom-cost-report": {
    title: "BOM Cost Report",
    apiMethod: "run",
    reportId: "bom_cost_report",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "manufacturing-journal-register-manufacturing": {
    title: "Manufacturing Journal Register",
    apiMethod: "run",
    reportId: "manufacturing_journal_register_manufacturing",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "production-summary": {
    title: "Production Summary",
    apiMethod: "run",
    reportId: "production_summary",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "production-voucher-register": {
    title: "Production Voucher Register",
    apiMethod: "run",
    reportId: "production_voucher_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "finished-goods-production-report": {
    title: "Finished Goods Production Report",
    apiMethod: "run",
    reportId: "finished_goods_production_report",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "raw-material-consumption-report": {
    title: "Raw Material Consumption Report",
    apiMethod: "run",
    reportId: "raw_material_consumption_report",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "wastage-report": {
    title: "Wastage Report",
    apiMethod: "run",
    reportId: "wastage_report",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "scrap-report": {
    title: "Scrap Report",
    apiMethod: "run",
    reportId: "scrap_report",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "yield-analysis": {
    title: "Yield Analysis",
    apiMethod: "run",
    reportId: "yield_analysis",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "standard-vs-actual-consumption": {
    title: "Standard vs Actual Consumption",
    apiMethod: "run",
    reportId: "standard_vs_actual_consumption",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "production-cost-sheet": {
    title: "Production Cost Sheet",
    apiMethod: "run",
    reportId: "production_cost_sheet",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
};
