import type { ReportConfig } from './types';

// Inventory report definitions, part 2 (movement/profitability, order books,
// job work, batch/expiry registers) — split from inventory.ts; the combined
// INVENTORY_DEFINITIONS map re-exported there is unchanged.
export const INVENTORY_DEFINITIONS_PART2: Record<string, ReportConfig> = {
  'slow-moving-items': {
    title: 'Slow Moving Items',
    apiMethod: 'run',
    reportId: 'slow_moving_items',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'non-moving-items': {
    title: 'Non-moving Items',
    apiMethod: 'run',
    reportId: 'non_moving_items',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-valuation': {
    title: 'Stock Valuation',
    apiMethod: 'run',
    reportId: 'stock_valuation',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'fifo-stock-valuation': {
    title: 'FIFO Stock Valuation',
    apiMethod: 'run',
    reportId: 'fifo_stock_valuation',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'average-cost-stock-valuation': {
    title: 'Average Cost Stock Valuation',
    apiMethod: 'run',
    reportId: 'average_cost_stock_valuation',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'last-purchase-cost-valuation': {
    title: 'Last Purchase Cost Valuation',
    apiMethod: 'run',
    reportId: 'last_purchase_cost_valuation',
    columns: [
      { header: 'Party/Item', field: 'party_item' },
      { header: 'Voucher/Order No.', field: 'voucher_order_no' },
      { header: 'Qty/Count', field: 'qty_count', type: 'number', align: 'center' },
      { header: 'Taxable/Gross', field: 'taxable_gross', type: 'currency', align: 'right' },
      { header: 'Tax/Discount', field: 'tax_discount', type: 'currency', align: 'right' },
      { header: 'Net Amount', field: 'net_amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'standard-cost-valuation': {
    title: 'Standard Cost Valuation',
    apiMethod: 'run',
    reportId: 'standard_cost_valuation',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'physical-stock-register-inventory': {
    title: 'Physical Stock Register',
    apiMethod: 'run',
    reportId: 'physical_stock_register_inventory',
    columns: [
      { header: 'Date', field: 'date', type: 'date' },
      { header: 'Particulars', field: 'particulars' },
      { header: 'Type/Section', field: 'type_section' },
      { header: 'Ref/Vch No.', field: 'ref_vch_no' },
      { header: 'Amount', field: 'amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'physical-stock-variance': {
    title: 'Physical Stock Variance',
    apiMethod: 'run',
    reportId: 'physical_stock_variance',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-journal-register-inventory': {
    title: 'Stock Journal Register',
    apiMethod: 'run',
    reportId: 'stock_journal_register_inventory',
    columns: [
      { header: 'Date', field: 'date', type: 'date' },
      { header: 'Particulars', field: 'particulars' },
      { header: 'Type/Section', field: 'type_section' },
      { header: 'Ref/Vch No.', field: 'ref_vch_no' },
      { header: 'Amount', field: 'amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'stock-transfer-register': {
    title: 'Stock Transfer Register',
    apiMethod: 'run',
    reportId: 'stock_transfer_register',
    columns: [
      { header: 'Date', field: 'date', type: 'date' },
      { header: 'Particulars', field: 'particulars' },
      { header: 'Type/Section', field: 'type_section' },
      { header: 'Ref/Vch No.', field: 'ref_vch_no' },
      { header: 'Amount', field: 'amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'inter-godown-transfer-report': {
    title: 'Inter-Godown Transfer Report',
    apiMethod: 'run',
    reportId: 'inter_godown_transfer_report',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'material-in-report': {
    title: 'Material In Report',
    apiMethod: 'run',
    reportId: 'material_in_report',
    columns: [
      { header: 'Particulars', field: 'particulars' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Transactions', field: 'transactions' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'material-out-report': {
    title: 'Material Out Report',
    apiMethod: 'run',
    reportId: 'material_out_report',
    columns: [
      { header: 'Particulars', field: 'particulars' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Transactions', field: 'transactions' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'rejection-in-report': {
    title: 'Rejection In Report',
    apiMethod: 'run',
    reportId: 'rejection_in_report',
    columns: [
      { header: 'Particulars', field: 'particulars' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Transactions', field: 'transactions' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'rejection-out-report': {
    title: 'Rejection Out Report',
    apiMethod: 'run',
    reportId: 'rejection_out_report',
    columns: [
      { header: 'Particulars', field: 'particulars' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Transactions', field: 'transactions' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'delivery-note-register-inventory': {
    title: 'Delivery Note Register',
    apiMethod: 'run',
    reportId: 'delivery_note_register_inventory',
    columns: [
      { header: 'Date', field: 'date', type: 'date' },
      { header: 'Particulars', field: 'particulars' },
      { header: 'Type/Section', field: 'type_section' },
      { header: 'Ref/Vch No.', field: 'ref_vch_no' },
      { header: 'Amount', field: 'amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'receipt-note-register-inventory': {
    title: 'Receipt Note Register',
    apiMethod: 'run',
    reportId: 'receipt_note_register_inventory',
    columns: [
      { header: 'Date', field: 'date', type: 'date' },
      { header: 'Particulars', field: 'particulars' },
      { header: 'Type/Section', field: 'type_section' },
      { header: 'Ref/Vch No.', field: 'ref_vch_no' },
      { header: 'Amount', field: 'amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'inventory-voucher-register': {
    title: 'Inventory Voucher Register',
    apiMethod: 'run',
    reportId: 'inventory_voucher_register',
    columns: [
      { header: 'Date', field: 'date', type: 'date' },
      { header: 'Particulars', field: 'particulars' },
      { header: 'Type/Section', field: 'type_section' },
      { header: 'Ref/Vch No.', field: 'ref_vch_no' },
      { header: 'Amount', field: 'amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'stock-item-profitability': {
    title: 'Stock Item Profitability',
    apiMethod: 'run',
    reportId: 'stock_item_profitability',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-category-summary': {
    title: 'Stock Category Summary',
    apiMethod: 'stockCategorySummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-category-movement': {
    title: 'Stock Category Movement',
    apiMethod: 'run',
    reportId: 'stock_category_movement',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-group-profitability': {
    title: 'Stock Group Profitability',
    apiMethod: 'run',
    reportId: 'stock_group_profitability',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-item-cost-analysis': {
    title: 'Stock Item Cost Analysis',
    apiMethod: 'run',
    reportId: 'stock_item_cost_analysis',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-item-sales-trend': {
    title: 'Stock Item Sales Trend',
    apiMethod: 'run',
    reportId: 'stock_item_sales_trend',
    columns: [
      { header: 'Party/Item', field: 'party_item' },
      { header: 'Voucher/Order No.', field: 'voucher_order_no' },
      { header: 'Qty/Count', field: 'qty_count', type: 'number', align: 'center' },
      { header: 'Taxable/Gross', field: 'taxable_gross', type: 'currency', align: 'right' },
      { header: 'Tax/Discount', field: 'tax_discount', type: 'currency', align: 'right' },
      { header: 'Net Amount', field: 'net_amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'stock-item-purchase-trend': {
    title: 'Stock Item Purchase Trend',
    apiMethod: 'run',
    reportId: 'stock_item_purchase_trend',
    columns: [
      { header: 'Party/Item', field: 'party_item' },
      { header: 'Voucher/Order No.', field: 'voucher_order_no' },
      { header: 'Qty/Count', field: 'qty_count', type: 'number', align: 'center' },
      { header: 'Taxable/Gross', field: 'taxable_gross', type: 'currency', align: 'right' },
      { header: 'Tax/Discount', field: 'tax_discount', type: 'currency', align: 'right' },
      { header: 'Net Amount', field: 'net_amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'inventory-exception-report': {
    title: 'Inventory Exception Report',
    apiMethod: 'run',
    reportId: 'inventory_exception_report',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'bill-of-materials-report': {
    title: 'Bill of Materials Report',
    apiMethod: 'run',
    reportId: 'bill_of_materials_report',
    columns: [
      { header: 'Particulars', field: 'particulars' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Transactions', field: 'transactions' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'bom-component-summary': {
    title: 'BOM Component Summary',
    apiMethod: 'run',
    reportId: 'bom_component_summary',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'bom-cost-report': {
    title: 'BOM Cost Report',
    apiMethod: 'run',
    reportId: 'bom_cost_report',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'manufacturing-journal-register-manufacturing': {
    title: 'Manufacturing Journal Register',
    apiMethod: 'run',
    reportId: 'manufacturing_journal_register_manufacturing',
    columns: [
      { header: 'Date', field: 'date', type: 'date' },
      { header: 'Particulars', field: 'particulars' },
      { header: 'Type/Section', field: 'type_section' },
      { header: 'Ref/Vch No.', field: 'ref_vch_no' },
      { header: 'Amount', field: 'amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'production-summary': {
    title: 'Production Summary',
    apiMethod: 'run',
    reportId: 'production_summary',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'production-voucher-register': {
    title: 'Production Voucher Register',
    apiMethod: 'run',
    reportId: 'production_voucher_register',
    columns: [
      { header: 'Date', field: 'date', type: 'date' },
      { header: 'Particulars', field: 'particulars' },
      { header: 'Type/Section', field: 'type_section' },
      { header: 'Ref/Vch No.', field: 'ref_vch_no' },
      { header: 'Amount', field: 'amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'finished-goods-production-report': {
    title: 'Finished Goods Production Report',
    apiMethod: 'run',
    reportId: 'finished_goods_production_report',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'raw-material-consumption-report': {
    title: 'Raw Material Consumption Report',
    apiMethod: 'run',
    reportId: 'raw_material_consumption_report',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'wastage-report': {
    title: 'Wastage Report',
    apiMethod: 'run',
    reportId: 'wastage_report',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'scrap-report': {
    title: 'Scrap Report',
    apiMethod: 'run',
    reportId: 'scrap_report',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'yield-analysis': {
    title: 'Yield Analysis',
    apiMethod: 'run',
    reportId: 'yield_analysis',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'standard-vs-actual-consumption': {
    title: 'Standard vs Actual Consumption',
    apiMethod: 'run',
    reportId: 'standard_vs_actual_consumption',
    columns: [
      { header: 'Particulars', field: 'particulars' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Transactions', field: 'transactions' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'production-cost-sheet': {
    title: 'Production Cost Sheet',
    apiMethod: 'run',
    reportId: 'production_cost_sheet',
    columns: [
      { header: 'Order/Vch No.', field: 'order_vch_no' },
      { header: 'Finished/Job Item', field: 'finished_job_item' },
      { header: 'Input/Component', field: 'input_component' },
      { header: 'Qty', field: 'qty', type: 'number', align: 'center' },
      { header: 'Cost', field: 'cost', type: 'currency', align: 'right' },
      { header: 'Variance', field: 'variance', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
};
