import type { ReportConfig } from './types';

// Inventory report definitions, part 1 (stock summaries, godown/batch views,
// movement analysis, ageing) — split from inventory.ts; the combined
// INVENTORY_DEFINITIONS map re-exported there is unchanged.
export const INVENTORY_DEFINITIONS_PART1: Record<string, ReportConfig> = {
  'stock-summary': {
    title: 'Stock Summary',
    apiMethod: 'stockSummary',
    columns: [
      { header: 'Stock Item', field: 'item_name' },
      { header: 'Group', field: 'group_name' },
      { header: 'Opening Qty', field: 'opening_qty', type: 'number', align: 'center' },
      { header: 'Opening Value', field: 'opening_value', type: 'currency', align: 'right' },
      { header: 'Inward Qty', field: 'inwards_qty', type: 'number', align: 'center' },
      { header: 'Inward Value', field: 'inwards_value', type: 'currency', align: 'right' },
      { header: 'Outward Qty', field: 'outwards_qty', type: 'number', align: 'center' },
      { header: 'Outward Value', field: 'outwards_value', type: 'currency', align: 'right' },
      { header: 'Closing Qty', field: 'closing_qty', type: 'number', align: 'center' },
      { header: 'Closing Value', field: 'closing_value', type: 'currency', align: 'right' },
    ],
  },
  'stock-summary-group-wise': {
    title: 'Stock Summary Group-wise',
    apiMethod: 'stockSummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-summary-item-wise': {
    title: 'Stock Summary Item-wise',
    apiMethod: 'stockSummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-summary-godown-wise': {
    title: 'Stock Summary Godown-wise',
    apiMethod: 'stockSummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-summary-batch-wise': {
    title: 'Stock Summary Batch-wise',
    apiMethod: 'stockSummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-summary-category-wise': {
    title: 'Stock Summary Category-wise',
    apiMethod: 'stockSummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-summary-with-rates': {
    title: 'Stock Summary with Rates',
    apiMethod: 'stockSummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-summary-with-values': {
    title: 'Stock Summary with Values',
    apiMethod: 'stockSummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-item-ledger': {
    title: 'Stock Item Ledger',
    apiMethod: 'run',
    reportId: 'stock_item_ledger',
    columns: [
      { header: 'Date/Particulars', field: 'date_particulars', type: 'date' },
      { header: 'Vch Type', field: 'vch_type' },
      { header: 'Vch No.', field: 'vch_no' },
      { header: 'Debit', field: 'debit', type: 'currency', align: 'right' },
      { header: 'Credit', field: 'credit', type: 'currency', align: 'right' },
      { header: 'Balance', field: 'balance', type: 'currency', align: 'right' },
    ],
  },
  'stock-group-ledger': {
    title: 'Stock Group Ledger',
    apiMethod: 'run',
    reportId: 'stock_group_ledger',
    columns: [
      { header: 'Date/Particulars', field: 'date_particulars', type: 'date' },
      { header: 'Vch Type', field: 'vch_type' },
      { header: 'Vch No.', field: 'vch_no' },
      { header: 'Debit', field: 'debit', type: 'currency', align: 'right' },
      { header: 'Credit', field: 'credit', type: 'currency', align: 'right' },
      { header: 'Balance', field: 'balance', type: 'currency', align: 'right' },
    ],
  },
  'godown-summary': {
    title: 'Godown Summary',
    apiMethod: 'godownSummary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'godown-item-summary': {
    title: 'Godown Item Summary',
    apiMethod: 'run',
    reportId: 'godown_item_summary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'godown-batch-summary': {
    title: 'Godown Batch Summary',
    apiMethod: 'run',
    reportId: 'godown_batch_summary',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-query': {
    title: 'Stock Query',
    apiMethod: 'run',
    reportId: 'stock_query',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-query-godown-wise': {
    title: 'Stock Query Godown-wise',
    apiMethod: 'run',
    reportId: 'stock_query_godown_wise',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-query-batch-wise': {
    title: 'Stock Query Batch-wise',
    apiMethod: 'run',
    reportId: 'stock_query_batch_wise',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-query-order-wise': {
    title: 'Stock Query Order-wise',
    apiMethod: 'run',
    reportId: 'stock_query_order_wise',
    columns: [
      { header: 'Party/Item', field: 'party_item' },
      { header: 'Voucher/Order No.', field: 'voucher_order_no' },
      { header: 'Qty/Count', field: 'qty_count', type: 'number', align: 'center' },
      { header: 'Taxable/Gross', field: 'taxable_gross', type: 'currency', align: 'right' },
      { header: 'Tax/Discount', field: 'tax_discount', type: 'currency', align: 'right' },
      { header: 'Net Amount', field: 'net_amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'movement-analysis': {
    title: 'Movement Analysis',
    apiMethod: 'movementAnalysis',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'movement-analysis-stock-item-wise': {
    title: 'Movement Analysis Stock Item-wise',
    apiMethod: 'movementAnalysis',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'movement-analysis-stock-group-wise': {
    title: 'Movement Analysis Stock Group-wise',
    apiMethod: 'movementAnalysis',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'movement-analysis-party-wise': {
    title: 'Movement Analysis Party-wise',
    apiMethod: 'movementAnalysis',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'movement-analysis-supplier-wise': {
    title: 'Movement Analysis Supplier-wise',
    apiMethod: 'movementAnalysis',
    columns: [
      { header: 'Party/Item', field: 'party_item' },
      { header: 'Voucher/Order No.', field: 'voucher_order_no' },
      { header: 'Qty/Count', field: 'qty_count', type: 'number', align: 'center' },
      { header: 'Taxable/Gross', field: 'taxable_gross', type: 'currency', align: 'right' },
      { header: 'Tax/Discount', field: 'tax_discount', type: 'currency', align: 'right' },
      { header: 'Net Amount', field: 'net_amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'movement-analysis-buyer-wise': {
    title: 'Movement Analysis Buyer-wise',
    apiMethod: 'movementAnalysis',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'movement-analysis-consumption-wise': {
    title: 'Movement Analysis Consumption-wise',
    apiMethod: 'movementAnalysis',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-ageing-analysis': {
    title: 'Stock Ageing Analysis',
    apiMethod: 'stockAgeing',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-ageing-by-purchase-date': {
    title: 'Stock Ageing by Purchase Date',
    apiMethod: 'stockAgeing',
    columns: [
      { header: 'Party/Item', field: 'party_item' },
      { header: 'Voucher/Order No.', field: 'voucher_order_no' },
      { header: 'Qty/Count', field: 'qty_count', type: 'number', align: 'center' },
      { header: 'Taxable/Gross', field: 'taxable_gross', type: 'currency', align: 'right' },
      { header: 'Tax/Discount', field: 'tax_discount', type: 'currency', align: 'right' },
      { header: 'Net Amount', field: 'net_amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'stock-ageing-by-manufacturing-date': {
    title: 'Stock Ageing by Manufacturing Date',
    apiMethod: 'stockAgeing',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'stock-ageing-by-expiry-date': {
    title: 'Stock Ageing by Expiry Date',
    apiMethod: 'stockAgeing',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'to-be-expired-stock-report': {
    title: 'To-be-Expired Stock Report',
    apiMethod: 'run',
    reportId: 'to_be_expired_stock_report',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'expired-stock-report': {
    title: 'Expired Stock Report',
    apiMethod: 'run',
    reportId: 'expired_stock_report',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'batch-wise-stock-report': {
    title: 'Batch-wise Stock Report',
    apiMethod: 'run',
    reportId: 'batch_wise_stock_report',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'mrp-wise-stock-report': {
    title: 'MRP-wise Stock Report',
    apiMethod: 'run',
    reportId: 'mrp_wise_stock_report',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'reorder-status': {
    title: 'Reorder Status',
    apiMethod: 'reorderStatus',
    columns: [
      { header: 'Name of Item', field: 'item_name' },
      { header: 'Closing Stock', field: 'closing', align: 'right' },
      { header: 'Purchase Orders Pending', field: 'po_pending', align: 'right' },
      { header: 'Total Stock Available', field: 'total_available', align: 'right' },
      { header: 'Reorder Level', field: 'level', align: 'right' },
      { header: 'Shortfall', field: 'shortage', align: 'right' },
      { header: 'Order to be Placed', field: 'to_order', align: 'right' },
    ],
  },
  'reorder-quantity-report': {
    title: 'Reorder Quantity Report',
    apiMethod: 'run',
    reportId: 'reorder_quantity_report',
    columns: [
      { header: 'Party/Item', field: 'party_item' },
      { header: 'Voucher/Order No.', field: 'voucher_order_no' },
      { header: 'Qty/Count', field: 'qty_count', type: 'number', align: 'center' },
      { header: 'Taxable/Gross', field: 'taxable_gross', type: 'currency', align: 'right' },
      { header: 'Tax/Discount', field: 'tax_discount', type: 'currency', align: 'right' },
      { header: 'Net Amount', field: 'net_amount', type: 'currency', align: 'right' },
      { header: 'Status', field: 'status' },
    ],
  },
  'negative-stock-report': {
    title: 'List of Negative Stock Items',
    apiMethod: 'run',
    reportId: 'negative_stock_report',
    columns: [
      { header: 'Particulars', field: 'item_name', align: 'left' },
      { header: 'Closing Quantity', field: 'closing_qty', type: 'number', align: 'right' },
      { header: 'Rate', field: 'closing_rate', type: 'currency', align: 'right' },
      { header: 'Closing Value', field: 'closing_value', type: 'currency', align: 'right' },
    ],
  },
  'zero-stock-report': {
    title: 'Zero Stock Report',
    apiMethod: 'run',
    reportId: 'zero_stock_report',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'low-stock-report': {
    title: 'Low Stock Report',
    apiMethod: 'run',
    reportId: 'low_stock_report',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
  'fast-moving-items': {
    title: 'Fast Moving Items',
    apiMethod: 'run',
    reportId: 'fast_moving_items',
    columns: [
      { header: 'Item/Group', field: 'item_group' },
      { header: 'Godown/Batch', field: 'godown_batch' },
      { header: 'Opening', field: 'opening', type: 'currency', align: 'right' },
      { header: 'Inward', field: 'inward' },
      { header: 'Outward', field: 'outward' },
      { header: 'Closing', field: 'closing', type: 'currency', align: 'right' },
      { header: 'Value/Status', field: 'value_status' },
    ],
  },
};
