import type { ReportConfig } from "./types";

export const MANUFACTURING_DEFINITIONS: Record<string, ReportConfig> = {
  "job-work-in-register": {
    title: "Job Work In Register",
    apiMethod: "run",
    reportId: "job_work_in_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "job-work-out-register": {
    title: "Job Work Out Register",
    apiMethod: "run",
    reportId: "job_work_out_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "material-sent-to-job-worker": {
    title: "Material Sent to Job Worker",
    apiMethod: "run",
    reportId: "material_sent_to_job_worker",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "material-received-from-job-worker": {
    title: "Material Received from Job Worker",
    apiMethod: "run",
    reportId: "material_received_from_job_worker",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pending-job-work-material": {
    title: "Pending Job Work Material",
    apiMethod: "run",
    reportId: "pending_job_work_material",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "job-worker-wise-stock": {
    title: "Job Worker-wise Stock",
    apiMethod: "run",
    reportId: "job_worker_wise_stock",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "principal-manufacturer-wise-stock": {
    title: "Principal Manufacturer-wise Stock",
    apiMethod: "run",
    reportId: "principal_manufacturer_wise_stock",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "cost-centre-summary": {
    title: "Cost Centre Summary",
    apiMethod: "costCentreReport",
    columns: [
      { header: "Cost Centre", field: "cost_centre" },
      { header: "Expense/Debit", field: "expense", type: "currency", align: "right" },
      { header: "Income/Credit", field: "income", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
    ],
  },
  "cost-category-summary": {
    title: "Cost Category Summary",
    apiMethod: "costCategorySummary",
    columns: [
      { header: "Category Name", field: "category_name" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
    ],
  },
  "cost-centre-break-up": {
    title: "Cost Centre Break-up",
    apiMethod: "costCentreReport",
    columns: [
      { header: "Cost Centre", field: "cost_centre" },
      { header: "Expense/Debit", field: "expense", type: "currency", align: "right" },
      { header: "Income/Credit", field: "income", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
    ],
  },
  "cost-centre-ledger": {
    title: "Cost Centre Ledger",
    apiMethod: "run",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "ledger_name" },
      { header: "Vch Type", field: "voucher_type" },
      { header: "Vch No.", field: "voucher_number" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "cost-centre-wise-p-and-l": {
    title: "Cost Centre-wise P&L",
    apiMethod: "run",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Expense/Debit", field: "expense_debit", type: "currency", align: "right" },
      { header: "Income/Credit", field: "income_credit", type: "currency", align: "right" },
      { header: "Current Amount", field: "current_amount", type: "currency", align: "right" },
    ],
  },
  "project-cost-report": {
    title: "Project Cost Report",
    apiMethod: "run",
    reportId: "project_cost_report",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "project-profitability": {
    title: "Project Profitability",
    apiMethod: "run",
    reportId: "project_profitability",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "department-cost-report": {
    title: "Department Cost Report",
    apiMethod: "run",
    reportId: "department_cost_report",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "batch-costing-report": {
    title: "Batch Costing Report",
    apiMethod: "run",
    reportId: "batch_costing_report",
    columns: [
      { header: "Item/Group", field: "item_group" },
      { header: "Godown/Batch", field: "godown_batch" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Inward", field: "inward" },
      { header: "Outward", field: "outward" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Value/Status", field: "value_status" },
    ],
  },
  "order-costing-report": {
    title: "Order Costing Report",
    apiMethod: "run",
    reportId: "order_costing_report",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
};
