import type { ReportConfig } from "./types";

export const PAYROLL_DEFINITIONS: Record<string, ReportConfig> = {
  "salary-register": {
    title: "Salary Register",
    apiMethod: "salaryRegister",
    columns: [
      { header: "Period", field: "month" },
      { header: "Employees", field: "employees_count", type: "number", align: "right" },
      { header: "Total Payout", field: "total_payout", type: "currency", align: "right" },
    ],
  },
  "attendance-register": {
    title: "Attendance Register",
    apiMethod: "attendanceReport",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "Present", field: "present", type: "number", align: "right" },
      { header: "Absent", field: "absent", type: "number", align: "right" },
      { header: "Leave", field: "leave", type: "number", align: "right" },
    ],
  },
  "attendance-sheet": {
    title: "Attendance Sheet",
    apiMethod: "attendanceSheet",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Present", field: "present", type: "number", align: "right" },
      { header: "Absent", field: "absent", type: "number", align: "right" },
      { header: "Leave", field: "leave", type: "number", align: "right" },
      { header: "Total Days", field: "total_days", type: "number", align: "right" },
    ],
  },
  "payment-advice": {
    title: "Payment Advice",
    apiMethod: "paymentAdvice",
    columns: [
      { header: "Sl No.", field: "id", type: "number", align: "right" },
      { header: "Name of the Employee", field: "emp_name" },
      { header: "Account No.", field: "account_number" },
      { header: "Bank Name", field: "bank_name" },
      { header: "IFSC Code", field: "ifsc_code" },
      { header: "Amount", field: "net_pay", type: "currency", align: "right" },
    ],
  },
  "employees-without-email": {
    title: "Employees Without E-mail IDs",
    apiMethod: "employeesWithoutEmail",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "Code", field: "emp_code" },
      { header: "Designation", field: "designation" },
      { header: "Department", field: "department" },
    ],
  },
  "payroll-statement": {
    title: "Payroll Statement",
    apiMethod: "payrollStatement",
    columns: [
      { header: "Pay Head", field: "pay_head_name" },
      { header: "Type", field: "pay_type" },
      { header: "Total Amount", field: "total_amount", type: "currency", align: "right" },
    ],
  },
  "employee-pay-head-breakup": {
    title: "Employee Pay Head Breakup",
    apiMethod: "employeePayHeadBreakup",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "Pay Head", field: "pay_head_name" },
      { header: "Type", field: "pay_type" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "pay-head-employee-breakup": {
    title: "Pay Head Employee Breakup",
    apiMethod: "payHeadEmployeeBreakup",
    columns: [
      { header: "Pay Head", field: "pay_head_name" },
      { header: "Type", field: "pay_type" },
      { header: "Employee", field: "emp_name" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "employee-profile": {
    title: "Employee Profile",
    apiMethod: "employeeProfile",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "Code", field: "emp_code" },
      { header: "Designation", field: "designation" },
      { header: "Department", field: "department" },
      { header: "Date of Joining", field: "date_of_joining" },
      { header: "Mobile", field: "mobile" },
      { header: "E-mail", field: "email" },
      { header: "PAN", field: "pan" },
      { header: "UAN", field: "uan" },
    ],
  },
  "employee-head-count": {
    title: "Employee Head Count",
    apiMethod: "employeeHeadCount",
    columns: [
      { header: "Employee Group", field: "group_name" },
      { header: "Head Count", field: "head_count", type: "number", align: "right" },
    ],
  },
  "overtime-register": {
    title: "Overtime Register",
    apiMethod: "run",
    reportId: "overtime_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "leave-register": {
    title: "Leave Register",
    apiMethod: "run",
    reportId: "leave_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "leave-encashment-report": {
    title: "Leave Encashment Report",
    apiMethod: "run",
    reportId: "leave_encashment_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "gratuity-report": {
    title: "Gratuity Report",
    apiMethod: "gratuity",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "Years of Service", field: "years", align: "right" },
      { header: "Gratuity Payable", field: "gratuity", type: "currency", align: "right" },
    ],
  },
  "employee-loan-or-advance-report": {
    title: "Employee Loan/Advance Report",
    apiMethod: "run",
    reportId: "employee_loan_or_advance_report",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Bank/Cash Ledger", field: "bank_cash_ledger" },
      { header: "Party/Reference", field: "party_reference" },
      { header: "Deposit/Receipt", field: "deposit_receipt" },
      { header: "Withdrawal/Payment", field: "withdrawal_payment" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "payroll-voucher-register-payroll": {
    title: "Payroll Voucher Register",
    apiMethod: "run",
    reportId: "payroll_voucher_register_payroll",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "payroll-cost-centre-report": {
    title: "Payroll Cost Centre Report",
    apiMethod: "costCentreReport",
    columns: [
      { header: "Order/Vch No.", field: "order_vch_no" },
      { header: "Finished/Job Item", field: "finished_job_item" },
      { header: "Input/Component", field: "input_component" },
      { header: "Qty", field: "qty", type: "number", align: "center" },
      { header: "Cost", field: "cost", type: "currency", align: "right" },
      { header: "Variance", field: "variance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "department-wise-payroll": {
    title: "Department-wise Payroll",
    apiMethod: "run",
    reportId: "department_wise_payroll",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "employee-group-wise-payroll": {
    title: "Employee Group-wise Payroll",
    apiMethod: "run",
    reportId: "employee_group_wise_payroll",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pay-head-summary": {
    title: "Pay Head Summary",
    apiMethod: "payHeadBreakup",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "Pay Head", field: "pay_head" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "pay-head-employee-wise": {
    title: "Pay Head Employee-wise",
    apiMethod: "payHeadBreakup",
    columns: [
      { header: "Pay Head", field: "pay_head" },
      { header: "Employee", field: "emp_name" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "earnings-summary": {
    title: "Earnings Summary",
    apiMethod: "run",
    reportId: "earnings_summary",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "deductions-summary": {
    title: "Deductions Summary",
    apiMethod: "run",
    reportId: "deductions_summary",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "employer-contribution-summary": {
    title: "Employer Contribution Summary",
    apiMethod: "run",
    reportId: "employer_contribution_summary",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "payroll-statutory-summary": {
    title: "Payroll Statutory Summary",
    apiMethod: "run",
    reportId: "payroll_statutory_summary",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "payroll-statutory-pay-head-details": {
    title: "Payroll Statutory Pay Head Details",
    apiMethod: "payHeadBreakup",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "Pay Head", field: "pay_head" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "provident-fund-summary": {
    title: "Provident Fund Summary",
    apiMethod: "pfReport",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "PF Account No.", field: "pf_no" },
      { header: "Employee Contribution", field: "emp_contrib", type: "currency", align: "right" },
      { header: "Employer Contribution", field: "employer_contrib", type: "currency", align: "right" },
    ],
  },
  "pf-form-5": {
    title: "PF Form 5",
    apiMethod: "run",
    reportId: "pf_form_5",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pf-form-10": {
    title: "PF Form 10",
    apiMethod: "run",
    reportId: "pf_form_10",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pf-form-12a": {
    title: "PF Form 12A",
    apiMethod: "run",
    reportId: "pf_form_12a",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pf-monthly-statement": {
    title: "PF Monthly Statement",
    apiMethod: "run",
    reportId: "pf_monthly_statement",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pf-e-challan-cum-return": {
    title: "PF E-Challan-cum-Return",
    apiMethod: "run",
    reportId: "pf_e_challan_cum_return",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pf-form-3a": {
    title: "PF Form 3A",
    apiMethod: "run",
    reportId: "pf_form_3a",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pf-form-6a": {
    title: "PF Form 6A",
    apiMethod: "run",
    reportId: "pf_form_6a",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pf-e-return": {
    title: "PF E-Return",
    apiMethod: "run",
    reportId: "pf_e_return",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "employee-state-insurance-summary": {
    title: "Employee State Insurance Summary",
    apiMethod: "esiReport",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "ESI No.", field: "esi_no" },
      { header: "Employee Contribution", field: "emp_contrib", type: "currency", align: "right" },
      { header: "Employer Contribution", field: "employer_contrib", type: "currency", align: "right" },
    ],
  },
  "esi-monthly-contribution": {
    title: "ESI Monthly Contribution",
    apiMethod: "run",
    reportId: "esi_monthly_contribution",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "esi-employee-wise-contribution": {
    title: "ESI Employee-wise Contribution",
    apiMethod: "run",
    reportId: "esi_employee_wise_contribution",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "esi-employer-contribution": {
    title: "ESI Employer Contribution",
    apiMethod: "run",
    reportId: "esi_employer_contribution",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "professional-tax-summary": {
    title: "Professional Tax Summary",
    apiMethod: "professionalTax",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "PT Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "professional-tax-employee-wise": {
    title: "Professional Tax Employee-wise",
    apiMethod: "professionalTax",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "PT Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "professional-tax-state-wise": {
    title: "Professional Tax State-wise",
    apiMethod: "professionalTax",
    columns: [
      { header: "Employee", field: "emp_name" },
      { header: "PT Amount", field: "amount", type: "currency", align: "right" },
    ],
  },
  "national-pension-scheme-summary": {
    title: "National Pension Scheme Summary",
    apiMethod: "run",
    reportId: "national_pension_scheme_summary",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "nps-employee-contribution": {
    title: "NPS Employee Contribution",
    apiMethod: "run",
    reportId: "nps_employee_contribution",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "nps-employer-contribution": {
    title: "NPS Employer Contribution",
    apiMethod: "run",
    reportId: "nps_employer_contribution",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "income-tax-summary": {
    title: "Income Tax Summary",
    apiMethod: "run",
    reportId: "income_tax_summary",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "form-16": {
    title: "Form 16",
    apiMethod: "run",
    reportId: "form_16",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "form-12ba": {
    title: "Form 12BA",
    apiMethod: "run",
    reportId: "form_12ba",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "annexure-i": {
    title: "Annexure I",
    apiMethod: "run",
    reportId: "annexure_i",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "annexure-ii": {
    title: "Annexure II",
    apiMethod: "run",
    reportId: "annexure_ii",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "form-24q-payroll": {
    title: "Form 24Q Payroll",
    apiMethod: "run",
    reportId: "form_24q_payroll",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "e-24q-return": {
    title: "E-24Q Return",
    apiMethod: "run",
    reportId: "e_24q_return",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "tds-variance-payroll": {
    title: "TDS Variance Payroll",
    apiMethod: "run",
    reportId: "tds_variance_payroll",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "income-tax-projection": {
    title: "Income Tax Projection",
    apiMethod: "run",
    reportId: "income_tax_projection",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "tax-regime-comparison": {
    title: "Tax Regime Comparison",
    apiMethod: "run",
    reportId: "tax_regime_comparison",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "employee-investment-declaration": {
    title: "Employee Investment Declaration",
    apiMethod: "run",
    reportId: "employee_investment_declaration",
    columns: [
      { header: "Metric", field: "metric" },
      { header: "Formula/Source", field: "formula_source" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Previous Value", field: "previous_value", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "employee-tax-computation": {
    title: "Employee Tax Computation",
    apiMethod: "run",
    reportId: "employee_tax_computation",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
};
