import type { ReportConfig } from "./types";

export const RECEIVABLES_DEFINITIONS: Record<string, ReportConfig> = {
  "bills-receivable": {
    title: "Bills Receivable",
    apiMethod: "billsReceivable",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Ref No", field: "ref_no" },
      { header: "Party Name", field: "party_name" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Due Date", field: "due_date", type: "date" },
      { header: "Overdue Days", field: "overdue_days", type: "number", align: "center" },
    ],
  },
  "bills-payable": {
    title: "Bills Payable",
    apiMethod: "billsPayable",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Ref No", field: "ref_no" },
      { header: "Party Name", field: "party_name" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Due Date", field: "due_date", type: "date" },
      { header: "Overdue Days", field: "overdue_days", type: "number", align: "center" },
    ],
  },
  "ledger-outstandings": {
    title: "Ledger Outstandings",
    apiMethod: "run",
    reportId: "ledger_outstandings",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "group-outstandings": {
    title: "Group Outstandings",
    apiMethod: "run",
    reportId: "group_outstandings",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "receivables-ageing": {
    title: "Receivables Ageing",
    apiMethod: "run",
    reportId: "receivables_ageing",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "payables-ageing": {
    title: "Payables Ageing",
    apiMethod: "run",
    reportId: "payables_ageing",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "bill-wise-receivables": {
    title: "Bill-wise Receivables",
    apiMethod: "run",
    reportId: "bill_wise_receivables",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "bill-wise-payables": {
    title: "Bill-wise Payables",
    apiMethod: "run",
    reportId: "bill_wise_payables",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "customer-wise-outstanding": {
    title: "Customer-wise Outstanding",
    apiMethod: "run",
    reportId: "customer_wise_outstanding",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "supplier-wise-outstanding": {
    title: "Supplier-wise Outstanding",
    apiMethod: "run",
    reportId: "supplier_wise_outstanding",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "salesperson-wise-outstanding": {
    title: "Salesperson-wise Outstanding",
    apiMethod: "run",
    reportId: "salesperson_wise_outstanding",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "area-wise-outstanding": {
    title: "Area-wise Outstanding",
    apiMethod: "run",
    reportId: "area_wise_outstanding",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "due-today-receivables": {
    title: "Due Today Receivables",
    apiMethod: "run",
    reportId: "due_today_receivables",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "due-today-payables": {
    title: "Due Today Payables",
    apiMethod: "run",
    reportId: "due_today_payables",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "overdue-receivables": {
    title: "Overdue Receivables",
    apiMethod: "billsReceivable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "overdue-payables": {
    title: "Overdue Payables",
    apiMethod: "billsPayable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "credit-limit-exception": {
    title: "Credit Limit Exception",
    apiMethod: "run",
    reportId: "credit_limit_exception",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "credit-period-exception": {
    title: "Credit Period Exception",
    apiMethod: "run",
    reportId: "credit_period_exception",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "interest-receivable": {
    title: "Interest Receivable",
    apiMethod: "run",
    reportId: "interest_receivable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "interest-payable": {
    title: "Interest Payable",
    apiMethod: "run",
    reportId: "interest_payable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "interest-calculation-ledger-wise": {
    title: "Interest Calculation Ledger-wise",
    apiMethod: "run",
    reportId: "interest_calculation_ledger_wise",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
  "interest-calculation-bill-wise": {
    title: "Interest Calculation Bill-wise",
    apiMethod: "run",
    reportId: "interest_calculation_bill_wise",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "collection-follow-up": {
    title: "Collection Follow-up",
    apiMethod: "run",
    reportId: "collection_follow_up",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "payment-follow-up": {
    title: "Payment Follow-up",
    apiMethod: "run",
    reportId: "payment_follow_up",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "promise-to-pay-report": {
    title: "Promise-to-Pay Report",
    apiMethod: "run",
    reportId: "promise_to_pay_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "broken-promise-report": {
    title: "Broken Promise Report",
    apiMethod: "run",
    reportId: "broken_promise_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "disputed-bills-report": {
    title: "Disputed Bills Report",
    apiMethod: "run",
    reportId: "disputed_bills_report",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "unadjusted-receipts": {
    title: "Unadjusted Receipts",
    apiMethod: "run",
    reportId: "unadjusted_receipts",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "unadjusted-payments": {
    title: "Unadjusted Payments",
    apiMethod: "run",
    reportId: "unadjusted_payments",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "advance-from-customers": {
    title: "Advance from Customers",
    apiMethod: "run",
    reportId: "advance_from_customers",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "advance-to-suppliers": {
    title: "Advance to Suppliers",
    apiMethod: "run",
    reportId: "advance_to_suppliers",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "pending-bill-allocations": {
    title: "Pending Bill Allocations",
    apiMethod: "run",
    reportId: "pending_bill_allocations",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Opening", field: "opening", type: "currency", align: "right" },
      { header: "Transactions", field: "transactions" },
      { header: "Closing", field: "closing", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "bill-settlement-register": {
    title: "Bill Settlement Register",
    apiMethod: "run",
    reportId: "bill_settlement_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "party-statement": {
    title: "Party Statement",
    apiMethod: "run",
    reportId: "party_statement",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "ledger-confirmation-report": {
    title: "Ledger Confirmation Report",
    apiMethod: "run",
    reportId: "ledger_confirmation_report",
    columns: [
      { header: "Date/Particulars", field: "date_particulars", type: "date" },
      { header: "Vch Type", field: "vch_type" },
      { header: "Vch No.", field: "vch_no" },
      { header: "Debit", field: "debit", type: "currency", align: "right" },
      { header: "Credit", field: "credit", type: "currency", align: "right" },
      { header: "Balance", field: "balance", type: "currency", align: "right" },
    ],
  },
};
