import type { ReportConfig } from "./types";

export const STATUTORY_DEFINITIONS: Record<string, ReportConfig> = {
  "vat-reports-menu": {
    title: "VAT Reports Menu",
    apiMethod: "run",
    reportId: "vat_reports_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "vat-computation": {
    title: "VAT Computation",
    apiMethod: "run",
    reportId: "vat_computation",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "vat-return-summary": {
    title: "VAT Return Summary",
    apiMethod: "run",
    reportId: "vat_return_summary",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "vat-sales-annexure": {
    title: "VAT Sales Annexure",
    apiMethod: "run",
    reportId: "vat_sales_annexure",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "vat-purchase-annexure": {
    title: "VAT Purchase Annexure",
    apiMethod: "run",
    reportId: "vat_purchase_annexure",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "vat-commodity-wise-report": {
    title: "VAT Commodity-wise Report",
    apiMethod: "run",
    reportId: "vat_commodity_wise_report",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "vat-party-wise-report": {
    title: "VAT Party-wise Report",
    apiMethod: "run",
    reportId: "vat_party_wise_report",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "vat-form-rt-iii": {
    title: "VAT Form RT-III",
    apiMethod: "run",
    reportId: "vat_form_rt_iii",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "vat-payment-details": {
    title: "VAT Payment Details",
    apiMethod: "run",
    reportId: "vat_payment_details",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "vat-exception-report": {
    title: "VAT Exception Report",
    apiMethod: "run",
    reportId: "vat_exception_report",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "central-excise-reports-menu": {
    title: "Central Excise Reports Menu",
    apiMethod: "run",
    reportId: "central_excise_reports_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "excise-computation": {
    title: "Excise Computation",
    apiMethod: "run",
    reportId: "excise_computation",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "excise-duty-payable": {
    title: "Excise Duty Payable",
    apiMethod: "run",
    reportId: "excise_duty_payable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "excise-sales-register": {
    title: "Excise Sales Register",
    apiMethod: "run",
    reportId: "excise_sales_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "excise-purchase-register": {
    title: "Excise Purchase Register",
    apiMethod: "run",
    reportId: "excise_purchase_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "excise-stock-register": {
    title: "Excise Stock Register",
    apiMethod: "run",
    reportId: "excise_stock_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "excise-invoice-register": {
    title: "Excise Invoice Register",
    apiMethod: "run",
    reportId: "excise_invoice_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "excise-payment-register": {
    title: "Excise Payment Register",
    apiMethod: "run",
    reportId: "excise_payment_register",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "excise-exception-report": {
    title: "Excise Exception Report",
    apiMethod: "run",
    reportId: "excise_exception_report",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "service-tax-reports-menu": {
    title: "Service Tax Reports Menu",
    apiMethod: "run",
    reportId: "service_tax_reports_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "service-tax-computation": {
    title: "Service Tax Computation",
    apiMethod: "run",
    reportId: "service_tax_computation",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "form-st-3": {
    title: "Form ST-3",
    apiMethod: "run",
    reportId: "form_st_3",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "service-tax-payable": {
    title: "Service Tax Payable",
    apiMethod: "run",
    reportId: "service_tax_payable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "service-tax-input-credit": {
    title: "Service Tax Input Credit",
    apiMethod: "run",
    reportId: "service_tax_input_credit",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "service-tax-payment-details": {
    title: "Service Tax Payment Details",
    apiMethod: "run",
    reportId: "service_tax_payment_details",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "service-tax-exception-report": {
    title: "Service Tax Exception Report",
    apiMethod: "run",
    reportId: "service_tax_exception_report",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "msme-reports-menu": {
    title: "MSME Reports Menu",
    apiMethod: "run",
    reportId: "msme_reports_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "msme-form-1": {
    title: "MSME Form 1",
    apiMethod: "run",
    reportId: "msme_form_1",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "msme-outstanding-to-micro-or-small-enterprises": {
    title: "MSME Outstanding to Micro/Small Enterprises",
    apiMethod: "run",
    reportId: "msme_outstanding_to_micro_or_small_enterprises",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "msme-supplier-ageing": {
    title: "MSME Supplier Ageing",
    apiMethod: "run",
    reportId: "msme_supplier_ageing",
    columns: [
      { header: "Party/Item", field: "party_item" },
      { header: "Voucher/Order No.", field: "voucher_order_no" },
      { header: "Qty/Count", field: "qty_count", type: "number", align: "center" },
      { header: "Taxable/Gross", field: "taxable_gross", type: "currency", align: "right" },
      { header: "Tax/Discount", field: "tax_discount", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "msme-interest-payable": {
    title: "MSME Interest Payable",
    apiMethod: "run",
    reportId: "msme_interest_payable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "msme-pending-acceptance-report": {
    title: "MSME Pending Acceptance Report",
    apiMethod: "run",
    reportId: "msme_pending_acceptance_report",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "msme-party-classification-exception": {
    title: "MSME Party Classification Exception",
    apiMethod: "run",
    reportId: "msme_party_classification_exception",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "msme-payment-delay-report": {
    title: "MSME Payment Delay Report",
    apiMethod: "run",
    reportId: "msme_payment_delay_report",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "msme-compliance-summary": {
    title: "MSME Compliance Summary",
    apiMethod: "run",
    reportId: "msme_compliance_summary",
    columns: [
      { header: "Return/Tax Head", field: "return_tax_head" },
      { header: "Party/Commodity", field: "party_commodity" },
      { header: "Taxable Value", field: "taxable_value", type: "currency", align: "right" },
      { header: "Tax/Credit", field: "tax_credit", type: "currency", align: "right" },
      { header: "Paid", field: "paid" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
};
