import type { ReportConfig } from "./types";

export const TCS_DEFINITIONS: Record<string, ReportConfig> = {
  "tcs-reports-menu": {
    title: "TCS Reports Menu",
    apiMethod: "run",
    reportId: "tcs_reports_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "tcs-challan-reconciliation": {
    title: "TCS Challan Reconciliation",
    apiMethod: "run",
    reportId: "tcs_challan_reconciliation",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-challan-details": {
    title: "TCS Challan Details",
    apiMethod: "run",
    reportId: "tcs_challan_details",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "form-27eq": {
    title: "Form 27EQ",
    apiMethod: "run",
    reportId: "form_27eq",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-return-transaction-book": {
    title: "TCS Return Transaction Book",
    apiMethod: "run",
    reportId: "tcs_return_transaction_book",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "tcs-outstandings": {
    title: "TCS Outstandings",
    apiMethod: "run",
    reportId: "tcs_outstandings",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "tcs-outstandings-nature-of-goods-wise": {
    title: "TCS Outstandings Nature of Goods-wise",
    apiMethod: "run",
    reportId: "tcs_outstandings_nature_of_goods_wise",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "tcs-outstandings-party-wise": {
    title: "TCS Outstandings Party-wise",
    apiMethod: "run",
    reportId: "tcs_outstandings_party_wise",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "ledgers-without-pan-collectees": {
    title: "Ledgers Without PAN - Collectees",
    apiMethod: "run",
    reportId: "ledgers_without_pan_collectees",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "buyer-ledger-without-pan": {
    title: "Buyer Ledger Without PAN",
    apiMethod: "run",
    reportId: "buyer_ledger_without_pan",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-collection-details": {
    title: "TCS Collection Details",
    apiMethod: "run",
    reportId: "tcs_collection_details",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-collection-at-normal-rate": {
    title: "TCS Collection at Normal Rate",
    apiMethod: "run",
    reportId: "tcs_collection_at_normal_rate",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-collection-at-higher-rate": {
    title: "TCS Collection at Higher Rate",
    apiMethod: "run",
    reportId: "tcs_collection_at_higher_rate",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-zero-or-lower-rate-collection": {
    title: "TCS Zero/Lower Rate Collection",
    apiMethod: "run",
    reportId: "tcs_zero_or_lower_rate_collection",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-exemption-limit-report": {
    title: "TCS Exemption Limit Report",
    apiMethod: "run",
    reportId: "tcs_exemption_limit_report",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-payment-details": {
    title: "TCS Payment Details",
    apiMethod: "run",
    reportId: "tcs_payment_details",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-balance-payable": {
    title: "TCS Balance Payable",
    apiMethod: "run",
    reportId: "tcs_balance_payable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "tcs-recompute-return": {
    title: "TCS Recompute Return",
    apiMethod: "run",
    reportId: "tcs_recompute_return",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-revised-return": {
    title: "TCS Revised Return",
    apiMethod: "run",
    reportId: "tcs_revised_return",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-save-return": {
    title: "TCS Save Return",
    apiMethod: "run",
    reportId: "tcs_save_return",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-remarks-report": {
    title: "TCS Remarks Report",
    apiMethod: "run",
    reportId: "tcs_remarks_report",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-exception-report": {
    title: "TCS Exception Report",
    apiMethod: "run",
    reportId: "tcs_exception_report",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-challan-details-of-buyer": {
    title: "TCS Challan Details of Buyer",
    apiMethod: "run",
    reportId: "tcs_challan_details_of_buyer",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-validation-report": {
    title: "TCS Validation Report",
    apiMethod: "run",
    reportId: "tcs_validation_report",
    columns: [
      { header: "Nature/Goods", field: "nature_goods" },
      { header: "Buyer/Collectee", field: "buyer_collectee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TCS Collectible", field: "tcs_collectible", type: "currency", align: "right" },
      { header: "Collected/Paid", field: "collected_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tcs-return-export-report": {
    title: "TCS Return Export Report",
    apiMethod: "run",
    reportId: "tcs_return_export_report",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
  "payroll-reports-menu": {
    title: "Payroll Reports Menu",
    apiMethod: "run",
    reportId: "payroll_reports_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "payroll-summary": {
    title: "Payroll Summary",
    apiMethod: "run",
    reportId: "payroll_summary",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "employee-summary": {
    title: "Employee Summary",
    apiMethod: "run",
    reportId: "employee_summary",
    columns: [
      { header: "Employee/Pay Head", field: "employee_pay_head" },
      { header: "Department/Group", field: "department_group" },
      { header: "Earnings/Payable", field: "earnings_payable", type: "currency", align: "right" },
      { header: "Deductions/Paid", field: "deductions_paid", type: "currency", align: "right" },
      { header: "Net/Balance", field: "net_balance", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "employee-pay-slip": {
    title: "Pay Slip",
    apiMethod: "paySlip",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Employee Number", field: "emp_number" },
      { header: "Account No.", field: "account_no" },
      { header: "Bank Name", field: "bank_name" },
      { header: "Branch", field: "branch" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "E-Mail ID", field: "email_id" },
    ],
  },
  "pay-slip": {
    title: "Pay Slip",
    apiMethod: "paySlip",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Employee Number", field: "emp_number" },
      { header: "Account No.", field: "account_no" },
      { header: "Bank Name", field: "bank_name" },
      { header: "Branch", field: "branch" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "E-Mail ID", field: "email_id" },
    ],
  },
  "pay-sheet": {
    title: "Pay Sheet",
    apiMethod: "paySheet",
    columns: [
      { header: "Particulars", field: "particulars" },
      { header: "Total Earnings", field: "total_earnings", type: "currency", align: "right" },
      { header: "Total Deductions", field: "total_deductions", type: "currency", align: "right" },
      { header: "Net Amount", field: "net_amount", type: "currency", align: "right" },
    ],
  },
};
