import type { ReportConfig } from "./types";

export const TDS_DEFINITIONS: Record<string, ReportConfig> = {
  "tds-reports-menu": {
    title: "TDS Reports Menu",
    apiMethod: "run",
    reportId: "tds_reports_menu",
    columns: [
      { header: "Report Group", field: "report_group" },
      { header: "Report Name", field: "report_name" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Status", field: "status" },
      { header: "Last Used", field: "last_used" },
    ],
  },
  "tds-challan-reconciliation": {
    title: "TDS Challan Reconciliation",
    apiMethod: "run",
    reportId: "tds_challan_reconciliation",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-challan-details": {
    title: "TDS Challan Details",
    apiMethod: "run",
    reportId: "tds_challan_details",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-challan-status": {
    title: "TDS Challan Status",
    apiMethod: "run",
    reportId: "tds_challan_status",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "form-26q": {
    title: "Form 26Q",
    apiMethod: "run",
    reportId: "form_26q",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "form-27q": {
    title: "Form 27Q",
    apiMethod: "run",
    reportId: "form_27q",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "form-24q": {
    title: "Form 24Q",
    apiMethod: "run",
    reportId: "form_24q",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-return-transaction-book": {
    title: "TDS Return Transaction Book",
    apiMethod: "run",
    reportId: "tds_return_transaction_book",
    columns: [
      { header: "Date", field: "date", type: "date" },
      { header: "Particulars", field: "particulars" },
      { header: "Type/Section", field: "type_section" },
      { header: "Ref/Vch No.", field: "ref_vch_no" },
      { header: "Amount", field: "amount", type: "currency", align: "right" },
      { header: "Status", field: "status" },
    ],
  },
  "tds-outstandings": {
    title: "TDS Outstandings",
    apiMethod: "run",
    reportId: "tds_outstandings",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "tds-outstandings-nature-of-payment-wise": {
    title: "TDS Outstandings Nature of Payment-wise",
    apiMethod: "run",
    reportId: "tds_outstandings_nature_of_payment_wise",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "tds-outstandings-party-wise": {
    title: "TDS Outstandings Party-wise",
    apiMethod: "run",
    reportId: "tds_outstandings_party_wise",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "ledgers-without-pan-deductees": {
    title: "Ledgers Without PAN - Deductees",
    apiMethod: "run",
    reportId: "ledgers_without_pan_deductees",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "deductee-pan-exception": {
    title: "Deductee PAN Exception",
    apiMethod: "run",
    reportId: "deductee_pan_exception",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "deductee-type-exception": {
    title: "Deductee Type Exception",
    apiMethod: "run",
    reportId: "deductee_type_exception",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "resident-type-exception": {
    title: "Resident Type Exception",
    apiMethod: "run",
    reportId: "resident_type_exception",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "section-number-exception": {
    title: "Section Number Exception",
    apiMethod: "run",
    reportId: "section_number_exception",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-deduction-details": {
    title: "TDS Deduction Details",
    apiMethod: "run",
    reportId: "tds_deduction_details",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-deducted-at-normal-rate": {
    title: "TDS Deducted at Normal Rate",
    apiMethod: "run",
    reportId: "tds_deducted_at_normal_rate",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-deducted-at-higher-rate": {
    title: "TDS Deducted at Higher Rate",
    apiMethod: "run",
    reportId: "tds_deducted_at_higher_rate",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-zero-or-lower-rate-deduction": {
    title: "TDS Zero/Lower Rate Deduction",
    apiMethod: "run",
    reportId: "tds_zero_or_lower_rate_deduction",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-exemption-limit-report": {
    title: "TDS Exemption Limit Report",
    apiMethod: "run",
    reportId: "tds_exemption_limit_report",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-payment-details": {
    title: "TDS Payment Details",
    apiMethod: "run",
    reportId: "tds_payment_details",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-balance-payable": {
    title: "TDS Balance Payable",
    apiMethod: "run",
    reportId: "tds_balance_payable",
    columns: [
      { header: "Party/Ledger", field: "party_ledger" },
      { header: "Bill Ref", field: "bill_ref" },
      { header: "Bill/Due Date", field: "bill_due_date", type: "date" },
      { header: "0-30", field: "0_30", type: "currency", align: "right" },
      { header: "31-60", field: "31_60", type: "currency", align: "right" },
      { header: "60+", field: "60", type: "currency", align: "right" },
      { header: "Total Pending", field: "total_pending", type: "currency", align: "right" },
    ],
  },
  "tds-recompute-return": {
    title: "TDS Recompute Return",
    apiMethod: "run",
    reportId: "tds_recompute_return",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-revised-return": {
    title: "TDS Revised Return",
    apiMethod: "run",
    reportId: "tds_revised_return",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-save-return": {
    title: "TDS Save Return",
    apiMethod: "run",
    reportId: "tds_save_return",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-remarks-report": {
    title: "TDS Remarks Report",
    apiMethod: "run",
    reportId: "tds_remarks_report",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-exception-report": {
    title: "TDS Exception Report",
    apiMethod: "run",
    reportId: "tds_exception_report",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-validation-or-fvu-report": {
    title: "TDS Validation/FVU Report",
    apiMethod: "run",
    reportId: "tds_validation_or_fvu_report",
    columns: [
      { header: "Nature/Section", field: "nature_section" },
      { header: "Deductee", field: "deductee" },
      { header: "Assessable Value", field: "assessable_value", type: "currency", align: "right" },
      { header: "TDS Deductible", field: "tds_deductible", type: "currency", align: "right" },
      { header: "Deducted/Paid", field: "deducted_paid", type: "currency", align: "right" },
      { header: "Balance/Status", field: "balance_status" },
    ],
  },
  "tds-return-export-report": {
    title: "TDS Return Export Report",
    apiMethod: "run",
    reportId: "tds_return_export_report",
    columns: [
      { header: "Option", field: "option" },
      { header: "Current Value", field: "current_value", type: "currency", align: "right" },
      { header: "Allowed Values", field: "allowed_values" },
      { header: "Shortcut", field: "shortcut" },
      { header: "Apply", field: "apply" },
    ],
  },
};
