import type { Op } from './OpsPanel';

// NIC e-Way Bill API operation specs. Each op maps a small form to the NIC-shaped call the
// backend already speaks (writes POST a `body`; the service passes it straight to NIC, so field
// names here must be the NIC camelCase names). Shared with OpsPanel — no per-op JSX.

const eway = () => window.api.ewayBill as typeof window.api.ewayBill & Record<string, any>;

// Drop empty/undefined keys so optional fields never clobber NIC defaults.
const clean = (o: Record<string, unknown>) =>
  Object.fromEntries(
    Object.entries(o).filter(([, v]) => v != null && v !== '' && !Number.isNaN(v)),
  );

const num = (s: string | undefined) => {
  const n = Number(s);
  return s == null || s === '' || Number.isNaN(n) ? undefined : n;
};

const TRANS_MODE = {
  key: 'transMode',
  label: 'Transport mode',
  type: 'select' as const,
  options: [
    { value: '1', label: 'Road' },
    { value: '2', label: 'Rail' },
    { value: '3', label: 'Air' },
    { value: '4', label: 'Ship' },
  ],
};

// ---- Read lookups (client-cred, no OTP) -------------------------------------
export const EWAY_LOOKUP_OPS: Op[] = [
  {
    value: 'get',
    label: 'e-Way Bill by EWB No',
    submitLabel: 'Fetch',
    fields: [{ key: 'ewbNo', label: 'EWB No' }],
    run: (v) => eway().get(v.ewbNo.trim()),
  },
  {
    value: 'byDate',
    label: 'e-Way Bills by Date',
    submitLabel: 'Fetch',
    fields: [{ key: 'date', label: 'Date (dd/mm/yyyy)' }],
    run: (v) => eway().byDate(v.date.trim()),
  },
  {
    value: 'forTransporterByDate',
    label: 'For transporter — by assigned date',
    submitLabel: 'Fetch',
    fields: [{ key: 'date', label: 'Date (dd/mm/yyyy)' }],
    run: (v) => eway().forTransporterByDate(v.date.trim()),
  },
  {
    value: 'forTransporterByState',
    label: 'For transporter — by state',
    submitLabel: 'Fetch',
    fields: [
      { key: 'state_code', label: 'State code' },
      { key: 'date', label: 'Date (dd/mm/yyyy)' },
    ],
    run: (v) => eway().forTransporterByState(v.state_code.trim(), v.date.trim()),
  },
  {
    value: 'forTransporterByGstin',
    label: 'For transporter — by generator GSTIN',
    submitLabel: 'Fetch',
    fields: [
      { key: 'gen_gstin', label: 'Generator GSTIN', width: 'w-52' },
      { key: 'date', label: 'Date (dd/mm/yyyy)' },
    ],
    run: (v) => eway().forTransporterByGstin(v.gen_gstin.trim(), v.date.trim()),
  },
  {
    value: 'reportByTransporterAssignedDate',
    label: 'Report by transporter-assigned date',
    submitLabel: 'Fetch',
    fields: [
      { key: 'date', label: 'Date (dd/mm/yyyy)' },
      { key: 'state_code', label: 'State code', optional: true },
    ],
    run: (v) => eway().reportByTransporterAssignedDate(v.date.trim(), (v.state_code || '').trim()),
  },
  {
    value: 'byDateGenerated',
    label: 'Generated by me — by date',
    submitLabel: 'Fetch',
    fields: [{ key: 'date', label: 'Date (dd/mm/yyyy)' }],
    run: (v) => eway().byDate(v.date.trim()),
  },
  {
    value: 'rejectedByOthers',
    label: 'Rejected by others — by date',
    submitLabel: 'Fetch',
    fields: [{ key: 'date', label: 'Date (dd/mm/yyyy)' }],
    run: (v) => eway().rejectedByOthers(v.date.trim()),
  },
  {
    value: 'ofOtherParty',
    label: 'Of other party — by date',
    submitLabel: 'Fetch',
    fields: [{ key: 'date', label: 'Date (dd/mm/yyyy)' }],
    run: (v) => eway().ofOtherParty(v.date.trim()),
  },
  {
    value: 'getConsolidated',
    label: 'Consolidated e-Way Bill',
    submitLabel: 'Fetch',
    fields: [{ key: 'trip_sheet_no', label: 'Trip sheet (consolidated) no.' }],
    run: (v) => eway().getConsolidated(v.trip_sheet_no.trim()),
  },
  {
    value: 'byConsigner',
    label: 'By consigner (doc type + no.)',
    submitLabel: 'Fetch',
    fields: [
      {
        key: 'doc_type',
        label: 'Doc type',
        type: 'select',
        options: [
          { value: 'INV', label: 'Tax Invoice (INV)' },
          { value: 'BIL', label: 'Bill of Supply (BIL)' },
          { value: 'BOE', label: 'Bill of Entry (BOE)' },
          { value: 'CHL', label: 'Delivery Challan (CHL)' },
          { value: 'OTH', label: 'Others (OTH)' },
        ],
      },
      { key: 'doc_no', label: 'Document no.' },
    ],
    run: (v) => eway().byConsigner(v.doc_type || 'INV', v.doc_no.trim()),
  },
  {
    value: 'getGstinDetails',
    label: 'GSTIN details',
    submitLabel: 'Fetch',
    fields: [{ key: 'gstin', label: 'GSTIN', width: 'w-52' }],
    run: (v) => eway().getGstinDetails(v.gstin.trim()),
  },
  {
    value: 'getTransporterDetails',
    label: 'Transporter details',
    submitLabel: 'Fetch',
    fields: [{ key: 'trn_no', label: 'Transporter ID (TRN)', width: 'w-52' }],
    run: (v) => eway().getTransporterDetails(v.trn_no.trim()),
  },
  {
    value: 'getHsnDetails',
    label: 'HSN details',
    submitLabel: 'Fetch',
    fields: [{ key: 'hsncode', label: 'HSN code' }],
    run: (v) => eway().getHsnDetails(v.hsncode.trim()),
  },
  {
    value: 'getErrorList',
    label: 'NIC error-code list',
    submitLabel: 'Fetch',
    run: () => eway().getErrorList(),
  },
];

// ---- Write actions ----------------------------------------------------------
export const EWAY_ACTION_OPS: Op[] = [
  {
    value: 'cancel',
    label: 'Cancel e-Way Bill',
    submitLabel: 'Cancel',
    fields: [
      { key: 'ewbNo', label: 'EWB No' },
      {
        key: 'cancelRsnCode',
        label: 'Reason',
        type: 'select',
        width: 'w-48',
        options: [
          { value: '1', label: '1 — Duplicate' },
          { value: '2', label: '2 — Order cancelled' },
          { value: '3', label: '3 — Data entry mistake' },
          { value: '4', label: '4 — Others' },
        ],
      },
      { key: 'cancelRmrk', label: 'Remarks', width: 'w-56' },
    ],
    confirm: (v) =>
      `Cancel e-Way Bill ${v.ewbNo}? Allowed within 24h of generation; cannot be undone.`,
    run: (v) =>
      eway().cancel({
        ewb_no: v.ewbNo.trim(),
        cancel_reason: num(v.cancelRsnCode) ?? 2,
        cancel_remarks: v.cancelRmrk || 'Cancelled',
      }),
    note: 'Cancellation is permitted only within 24 hours of generation and if the EWB has not been verified in transit.',
  },
  {
    value: 'updatePartB',
    label: 'Update Part-B / vehicle no.',
    submitLabel: 'Update Part-B',
    fields: [
      { key: 'ewbNo', label: 'EWB No' },
      { key: 'vehicleNo', label: 'Vehicle no.', placeholder: 'MH01AB1234' },
      { key: 'fromPlace', label: 'From place' },
      { key: 'fromState', label: 'From state code' },
      TRANS_MODE,
      {
        key: 'reasonCode',
        label: 'Reason',
        type: 'select',
        width: 'w-52',
        options: [
          { value: '1', label: '1 — Due to break down' },
          { value: '2', label: '2 — Due to transhipment' },
          { value: '3', label: '3 — Others' },
          { value: '4', label: '4 — First time' },
        ],
      },
      { key: 'reasonRem', label: 'Reason remark', optional: true, width: 'w-52' },
      { key: 'transDocNo', label: 'Transport doc no.', optional: true },
      {
        key: 'transDocDate',
        label: 'Transport doc date',
        optional: true,
        placeholder: 'dd/mm/yyyy',
      },
    ],
    run: (v) =>
      eway().updatePartB(
        clean({
          ewbNo: num(v.ewbNo),
          vehicleNo: v.vehicleNo,
          fromPlace: v.fromPlace,
          fromState: num(v.fromState),
          transMode: v.transMode || '1',
          reasonCode: num(v.reasonCode) ?? 3,
          reasonRem: v.reasonRem,
          transDocNo: v.transDocNo,
          transDocDate: v.transDocDate,
        }),
      ),
  },
  {
    value: 'updateTransporter',
    label: 'Update transporter',
    submitLabel: 'Update transporter',
    fields: [
      { key: 'ewbNo', label: 'EWB No' },
      { key: 'transporterId', label: 'Transporter ID (GSTIN/TRN)', width: 'w-56' },
    ],
    run: (v) =>
      eway().updateTransporter(
        clean({ ewbNo: num(v.ewbNo), transporterId: v.transporterId.trim() }),
      ),
  },
  {
    value: 'extendValidity',
    label: 'Extend validity',
    submitLabel: 'Extend validity',
    fields: [
      { key: 'ewbNo', label: 'EWB No' },
      { key: 'vehicleNo', label: 'Vehicle no.', placeholder: 'MH01AB1234' },
      { key: 'fromPlace', label: 'Current place' },
      { key: 'fromState', label: 'Current state code' },
      { key: 'remainingDistance', label: 'Remaining distance (km)', type: 'number' },
      TRANS_MODE,
      {
        key: 'consignmentStatus',
        label: 'Consignment status',
        type: 'select',
        width: 'w-48',
        options: [
          { value: 'M', label: 'In movement (M)' },
          { value: 'T', label: 'In transit (T)' },
        ],
      },
      {
        key: 'extnRsnCode',
        label: 'Reason',
        type: 'select',
        width: 'w-52',
        options: [
          { value: '1', label: '1 — Natural calamity' },
          { value: '2', label: '2 — Law & order' },
          { value: '3', label: '3 — Transhipment' },
          { value: '4', label: '4 — Accident' },
          { value: '99', label: '99 — Others' },
        ],
      },
      { key: 'extnRemarks', label: 'Remarks', width: 'w-52' },
    ],
    run: (v) =>
      eway().extendValidity(
        clean({
          ewbNo: num(v.ewbNo),
          vehicleNo: v.vehicleNo,
          fromPlace: v.fromPlace,
          fromState: num(v.fromState),
          remainingDistance: num(v.remainingDistance) ?? 0,
          transMode: v.transMode || '1',
          consignmentStatus: v.consignmentStatus || 'M',
          extnRsnCode: num(v.extnRsnCode) ?? 99,
          extnRemarks: v.extnRemarks,
        }),
      ),
    note: 'Extend within 8 hours before or after the current validity expiry.',
  },
  {
    value: 'reject',
    label: 'Reject e-Way Bill',
    submitLabel: 'Reject',
    fields: [{ key: 'ewbNo', label: 'EWB No' }],
    confirm: (v) => `Reject e-Way Bill ${v.ewbNo}? Allowed within 72h of generation.`,
    run: (v) => eway().reject(clean({ ewbNo: num(v.ewbNo) })),
  },
  {
    value: 'generateConsolidated',
    label: 'Generate consolidated e-Way Bill',
    submitLabel: 'Generate CEWB',
    fields: [
      { key: 'fromPlace', label: 'From place' },
      { key: 'fromState', label: 'From state code' },
      { key: 'vehicleNo', label: 'Vehicle no.', placeholder: 'MH01AB1234' },
      TRANS_MODE,
      { key: 'ewbNos', label: 'EWB nos (comma-separated)', width: 'w-72' },
      { key: 'transDocNo', label: 'Transport doc no.', optional: true },
      {
        key: 'transDocDate',
        label: 'Transport doc date',
        optional: true,
        placeholder: 'dd/mm/yyyy',
      },
    ],
    run: (v) =>
      eway().generateConsolidated(
        clean({
          fromPlace: v.fromPlace,
          fromState: num(v.fromState),
          vehicleNo: v.vehicleNo,
          transMode: v.transMode || '1',
          transDocNo: v.transDocNo,
          transDocDate: v.transDocDate,
          tripSheetEwbBills: (v.ewbNos || '')
            .split(',')
            .map((s) => s.trim())
            .filter(Boolean)
            .map((n) => ({ ewbNo: Number(n) })),
        }),
      ),
  },
  {
    value: 'regenerateConsolidated',
    label: 'Regenerate consolidated e-Way Bill',
    submitLabel: 'Regenerate CEWB',
    fields: [
      { key: 'cEwbNo', label: 'Consolidated EWB no.' },
      { key: 'vehicleNo', label: 'Vehicle no.', placeholder: 'MH01AB1234' },
      { key: 'fromPlace', label: 'From place' },
      { key: 'fromState', label: 'From state code' },
      TRANS_MODE,
      { key: 'transDocNo', label: 'Transport doc no.', optional: true },
      {
        key: 'transDocDate',
        label: 'Transport doc date',
        optional: true,
        placeholder: 'dd/mm/yyyy',
      },
    ],
    run: (v) =>
      eway().regenerateConsolidated(
        clean({
          cEwbNo: num(v.cEwbNo),
          vehicleNo: v.vehicleNo,
          fromPlace: v.fromPlace,
          fromState: num(v.fromState),
          transMode: v.transMode || '1',
          transDocNo: v.transDocNo,
          transDocDate: v.transDocDate,
        }),
      ),
  },
  {
    value: 'initMultiVehicle',
    label: 'Multi-vehicle — initiate movement',
    submitLabel: 'Initiate',
    fields: [
      { key: 'ewbNo', label: 'EWB No' },
      { key: 'fromPlace', label: 'From place' },
      { key: 'fromState', label: 'From state code' },
      { key: 'toPlace', label: 'To place' },
      { key: 'toState', label: 'To state code' },
      { key: 'totalQuantity', label: 'Total quantity', type: 'number' },
      { key: 'unitCode', label: 'Unit code', placeholder: 'NOS / KGS' },
      TRANS_MODE,
      {
        key: 'reasonCode',
        label: 'Reason',
        type: 'select',
        width: 'w-52',
        options: [
          { value: '1', label: '1 — Due to transhipment' },
          { value: '2', label: '2 — Due to break down' },
          { value: '3', label: '3 — Others' },
        ],
      },
      { key: 'reasonRem', label: 'Reason remark', optional: true, width: 'w-52' },
    ],
    run: (v) =>
      eway().initMultiVehicle(
        clean({
          ewbNo: num(v.ewbNo),
          fromPlace: v.fromPlace,
          fromState: num(v.fromState),
          toPlace: v.toPlace,
          toState: num(v.toState),
          totalQuantity: num(v.totalQuantity),
          unitCode: v.unitCode,
          transMode: v.transMode || '1',
          reasonCode: num(v.reasonCode) ?? 3,
          reasonRem: v.reasonRem,
        }),
      ),
  },
  {
    value: 'addMultiVehicle',
    label: 'Multi-vehicle — add vehicle',
    submitLabel: 'Add vehicle',
    fields: [
      { key: 'ewbNo', label: 'EWB No' },
      { key: 'fromPlace', label: 'From place' },
      { key: 'fromState', label: 'From state code' },
      { key: 'toPlace', label: 'To place' },
      { key: 'toState', label: 'To state code' },
      { key: 'vehicleNo', label: 'Vehicle no.', placeholder: 'MH01AB1234' },
      { key: 'groupNo', label: 'Group no.', type: 'number' },
      { key: 'quantity', label: 'Quantity', type: 'number' },
      TRANS_MODE,
      { key: 'transDocNo', label: 'Transport doc no.', optional: true },
      {
        key: 'transDocDate',
        label: 'Transport doc date',
        optional: true,
        placeholder: 'dd/mm/yyyy',
      },
    ],
    run: (v) =>
      eway().addMultiVehicle(
        clean({
          ewbNo: num(v.ewbNo),
          fromPlace: v.fromPlace,
          fromState: num(v.fromState),
          toPlace: v.toPlace,
          toState: num(v.toState),
          vehicleNo: v.vehicleNo,
          groupNo: num(v.groupNo),
          quantity: num(v.quantity),
          transMode: v.transMode || '1',
          transDocNo: v.transDocNo,
          transDocDate: v.transDocDate,
        }),
      ),
  },
  {
    value: 'changeMultiVehicle',
    label: 'Multi-vehicle — change vehicle',
    submitLabel: 'Change vehicle',
    fields: [
      { key: 'ewbNo', label: 'EWB No' },
      { key: 'fromPlace', label: 'From place' },
      { key: 'fromState', label: 'From state code' },
      { key: 'toPlace', label: 'To place' },
      { key: 'toState', label: 'To state code' },
      { key: 'vehicleNo', label: 'Vehicle no.', placeholder: 'MH01AB1234' },
      { key: 'groupNo', label: 'Group no.', type: 'number' },
      { key: 'quantity', label: 'Quantity', type: 'number' },
      TRANS_MODE,
    ],
    run: (v) =>
      eway().changeMultiVehicle(
        clean({
          ewbNo: num(v.ewbNo),
          fromPlace: v.fromPlace,
          fromState: num(v.fromState),
          toPlace: v.toPlace,
          toState: num(v.toState),
          vehicleNo: v.vehicleNo,
          groupNo: num(v.groupNo),
          quantity: num(v.quantity),
          transMode: v.transMode || '1',
        }),
      ),
  },
];
