-- ============================================================================
-- POSTGRES SCHEMA — GENERATED FROM DRIZZLE  (server/db/schema/pg/*.js)
-- ----------------------------------------------------------------------------
-- Single source of truth: the pgTable definitions under server/db/schema/pg.
-- Regenerate with:  npm run docs:db
-- DO NOT HAND-EDIT. Edit the Drizzle schema files instead, then re-run docs:db.
--
-- Section 1 — CREATE TABLE (no inline foreign keys).
-- Section 2 — Foreign keys as ALTER TABLE ... ADD CONSTRAINT.
-- ============================================================================

-- ############################################################################
-- SECTION 1 :: CREATE TABLE
-- ############################################################################

CREATE TABLE IF NOT EXISTS attendance_types (
  attendance_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  type TEXT NOT NULL DEFAULT 'Attendance / Leave with Pay',
  unit_id BIGINT,
  period TEXT NOT NULL DEFAULT 'Per Day',
  carry_forward BOOLEAN NOT NULL DEFAULT FALSE,
  encashment BOOLEAN NOT NULL DEFAULT FALSE,
  max_days NUMERIC(18,4) NOT NULL DEFAULT '0',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance_voucher_entries (
  entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_voucher_id BIGINT NOT NULL,
  employee_id BIGINT,
  attendance_type_id BIGINT,
  value NUMERIC(18,4) DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS attendance_vouchers (
  attendance_voucher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  voucher_number TEXT,
  date DATE NOT NULL,
  narration TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS balance_sheet_reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  report_name TEXT DEFAULT 'Balance Sheet',
  report_date DATE,
  comparison_period_start DATE,
  comparison_period_end DATE,
  format_type TEXT DEFAULT 'Vertical',
  method_of_showing TEXT DEFAULT 'Net Balance',
  show_vertical_balance_sheet BOOLEAN NOT NULL DEFAULT TRUE,
  show_working_capital_figures BOOLEAN NOT NULL DEFAULT FALSE,
  profit_or_loss_as_liability BOOLEAN NOT NULL DEFAULT TRUE,
  show_detail_view BOOLEAN NOT NULL DEFAULT FALSE,
  show_condensed_view BOOLEAN NOT NULL DEFAULT FALSE,
  show_schedule_vi BOOLEAN NOT NULL DEFAULT FALSE,
  include_closing_stock BOOLEAN NOT NULL DEFAULT TRUE,
  compare_quarterly BOOLEAN NOT NULL DEFAULT FALSE,
  basis_of_values TEXT DEFAULT 'Default',
  change_view TEXT,
  exception_reports_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  filter_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  saved_view_name TEXT,
  filter_details TEXT,
  show_profit BOOLEAN NOT NULL DEFAULT TRUE,
  show_columnar BOOLEAN NOT NULL DEFAULT FALSE,
  show_optional BOOLEAN NOT NULL DEFAULT FALSE,
  show_post_dated BOOLEAN NOT NULL DEFAULT FALSE,
  show_stat_adjustment BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS balance_sheet_views (
  view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  company_id BIGINT NOT NULL,
  report_date DATE,
  group_name TEXT,
  parent_group_name TEXT,
  opening_balance NUMERIC(18,2) NOT NULL DEFAULT '0',
  side TEXT NOT NULL DEFAULT 'Assets',
  current_period_debit NUMERIC(18,2) NOT NULL DEFAULT '0',
  current_period_credit NUMERIC(18,2) NOT NULL DEFAULT '0',
  closing_balance NUMERIC(18,2) NOT NULL DEFAULT '0',
  display_order INTEGER NOT NULL DEFAULT 0,
  is_total_row BOOLEAN NOT NULL DEFAULT FALSE,
  is_drill_down_available BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS companies (
  company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  mailing_name TEXT,
  address1 TEXT,
  address2 TEXT,
  state TEXT,
  country TEXT,
  pincode TEXT,
  telephone TEXT,
  mobile TEXT,
  fax TEXT,
  email TEXT,
  website TEXT,
  base_currency_symbol TEXT,
  formal_name TEXT,
  financial_year_beginning_from TEXT,
  books_beginning_from TEXT,
  password TEXT,
  access_control TEXT,
  edit_log TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_creation_success (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  created_successfully BOOLEAN NOT NULL DEFAULT TRUE,
  success_screen_shown BOOLEAN NOT NULL DEFAULT FALSE,
  show_more_features BOOLEAN NOT NULL DEFAULT FALSE,
  show_all_features BOOLEAN NOT NULL DEFAULT FALSE,
  default_features_loaded BOOLEAN NOT NULL DEFAULT TRUE,
  feature_setup_completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_feature_values (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  feature_item_id BIGINT NOT NULL,
  value_boolean BOOLEAN NOT NULL DEFAULT FALSE,
  value_text TEXT,
  value_number DOUBLE PRECISION,
  value_date DATE,
  is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_gst_details (
  company_id BIGINT PRIMARY KEY,
  hsn_sac_type TEXT DEFAULT 'Not Defined',
  hsn_sac_code TEXT,
  description TEXT,
  taxability_type TEXT DEFAULT 'Not Defined',
  gst_rate NUMERIC(18,4) DEFAULT '0',
  interstate_threshold_limit NUMERIC(18,2) DEFAULT '50000',
  intrastate_threshold_limit NUMERIC(18,2) DEFAULT '50000',
  threshold_limit_includes TEXT DEFAULT 'Value of Invoice',
  create_hsn_summary_for TEXT DEFAULT 'All Sections',
  minimum_hsn_length INTEGER DEFAULT 4,
  show_gst_advances BOOLEAN DEFAULT FALSE,
  update_gst_status BOOLEAN DEFAULT FALSE,
  gst_returns_configured BOOLEAN DEFAULT FALSE,
  effective_date TEXT DEFAULT '1-Apr-26',
  download_gst_registration TEXT,
  download_return_type TEXT DEFAULT 'All Returns',
  set_state_wise_threshold_limit BOOLEAN DEFAULT FALSE,
  state_wise_limits JSONB,
  gst_advances_applicable_from TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_pan_cin_details (
  company_id BIGINT PRIMARY KEY,
  pan TEXT,
  cin TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_tcs_details (
  company_id BIGINT PRIMARY KEY,
  tan_reg_number TEXT,
  tan TEXT,
  collector_type TEXT DEFAULT 'Company',
  collector_branch TEXT,
  set_alter_person_responsible BOOLEAN NOT NULL DEFAULT FALSE,
  person_responsible_name TEXT,
  person_responsible_son_daughter_of TEXT,
  person_responsible_designation TEXT,
  person_responsible_pan TEXT,
  person_responsible_flat_no TEXT,
  person_responsible_premises TEXT,
  person_responsible_road TEXT,
  person_responsible_area TEXT,
  person_responsible_city TEXT,
  person_responsible_state TEXT,
  person_responsible_pincode TEXT,
  person_responsible_phone TEXT,
  person_responsible_std_code TEXT,
  person_responsible_telephone TEXT,
  person_responsible_email TEXT,
  ignore_it_exemption BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_tds_details (
  company_id BIGINT PRIMARY KEY,
  tan_reg_number TEXT,
  tan TEXT,
  deductor_type TEXT NOT NULL DEFAULT 'Company',
  deductor_branch TEXT,
  set_alter_person_responsible BOOLEAN NOT NULL DEFAULT FALSE,
  person_responsible_name TEXT,
  person_responsible_designation TEXT,
  person_responsible_pan TEXT,
  person_responsible_phone TEXT,
  person_responsible_email TEXT,
  ignore_it_exemption BOOLEAN NOT NULL DEFAULT TRUE,
  activate_tds_for_items BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cost_centres (
  cc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  parent_id BIGINT,
  category TEXT NOT NULL DEFAULT 'Primary',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS currencies (
  currency_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  formal_name TEXT,
  iso_code TEXT NOT NULL,
  symbol TEXT,
  decimal_places INTEGER NOT NULL DEFAULT 2,
  decimal_symbol TEXT NOT NULL DEFAULT '.',
  decimal_places_in_words TEXT,
  suffix_symbol_to_amount BOOLEAN NOT NULL DEFAULT FALSE,
  show_amount_in_millions BOOLEAN NOT NULL DEFAULT FALSE,
  word_representing_amount_after_decimal TEXT,
  add_space_between_amount_and_symbol BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS day_book_entries (
  entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  company_id BIGINT NOT NULL,
  voucher_id BIGINT,
  voucher_date DATE,
  particulars TEXT,
  voucher_type TEXT,
  voucher_number TEXT,
  debit_amount NUMERIC(18,2) NOT NULL DEFAULT '0',
  credit_amount NUMERIC(18,2) NOT NULL DEFAULT '0',
  narration TEXT,
  party_ledger_name TEXT,
  show_profit BOOLEAN NOT NULL DEFAULT FALSE,
  is_optional BOOLEAN NOT NULL DEFAULT FALSE,
  is_post_dated BOOLEAN NOT NULL DEFAULT FALSE,
  is_stat_adjustment BOOLEAN NOT NULL DEFAULT FALSE,
  gross_profit NUMERIC(18,2) NOT NULL DEFAULT '0',
  cost NUMERIC(18,2) NOT NULL DEFAULT '0',
  display_order INTEGER NOT NULL DEFAULT 0,
  is_drillable BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS day_book_entry_lines (
  line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id BIGINT NOT NULL,
  ledger_id BIGINT,
  particulars TEXT,
  debit_amount NUMERIC(18,2) NOT NULL DEFAULT '0',
  credit_amount NUMERIC(18,2) NOT NULL DEFAULT '0',
  line_order INTEGER NOT NULL DEFAULT 0,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS day_book_reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  report_name TEXT DEFAULT 'Day Book',
  date_from DATE,
  date_to DATE,
  selected_company_id BIGINT,
  basis_of_values TEXT DEFAULT 'Default',
  change_view TEXT,
  exception_reports_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  saved_view_name TEXT,
  filter_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  filter_details TEXT,
  show_profit BOOLEAN NOT NULL DEFAULT FALSE,
  show_columnar BOOLEAN NOT NULL DEFAULT FALSE,
  show_optional BOOLEAN NOT NULL DEFAULT FALSE,
  show_post_dated BOOLEAN NOT NULL DEFAULT FALSE,
  show_stat_adjustment BOOLEAN NOT NULL DEFAULT FALSE,
  show_details BOOLEAN NOT NULL DEFAULT TRUE,
  show_related_reports BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS einvoice_credentials (
  cred_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  client_id TEXT NOT NULL,
  client_secret TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  app_key TEXT NOT NULL,
  is_sandbox BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS einvoice_records (
  irn_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  voucher_id BIGINT,
  invoice_number TEXT NOT NULL,
  invoice_date TEXT NOT NULL,
  buyer_gstin TEXT,
  irn TEXT,
  ack_no TEXT,
  ack_dt TEXT,
  signed_invoice TEXT,
  signed_qr_code TEXT,
  ewb_no TEXT,
  ewb_dt TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING',
  cancel_reason INTEGER,
  cancel_remarks TEXT,
  cancelled_at TIMESTAMPTZ,
  raw_response TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS employee_categories (
  employee_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  allocate_revenue BOOLEAN NOT NULL DEFAULT FALSE,
  allocate_non_revenue BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS employee_groups (
  employee_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  employee_category_id BIGINT,
  name TEXT NOT NULL,
  alias TEXT,
  parent_group_id BIGINT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS employees (
  employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  employee_category_id BIGINT,
  employee_group_id BIGINT,
  name TEXT NOT NULL,
  alias TEXT,
  employee_code TEXT,
  designation TEXT,
  department TEXT,
  function TEXT,
  location TEXT,
  date_of_joining DATE,
  date_of_leaving DATE,
  date_of_birth DATE,
  gender TEXT,
  blood_group TEXT,
  father_name TEXT,
  mother_name TEXT,
  spouse_name TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  pincode TEXT,
  mobile TEXT,
  phone TEXT,
  email TEXT,
  define_salary_details BOOLEAN NOT NULL DEFAULT FALSE,
  bank_account_number TEXT,
  bank_name TEXT,
  bank_branch TEXT,
  ifsc_code TEXT,
  applicable_tax_regime TEXT,
  pan TEXT,
  aadhaar TEXT,
  uan TEXT,
  pf_account_number TEXT,
  eps_account_number TEXT,
  date_of_joining_pf DATE,
  pran TEXT,
  esi_number TEXT,
  esi_dispensary_name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS feature_groups (
  feature_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_key TEXT NOT NULL,
  group_name TEXT NOT NULL,
  online_access BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS feature_items (
  feature_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_group_id BIGINT NOT NULL,
  feature_key TEXT NOT NULL,
  feature_name TEXT NOT NULL,
  description TEXT,
  control_type TEXT NOT NULL DEFAULT 'boolean',
  default_value_boolean BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_mandatory BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS financial_years (
  fy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  is_closed BOOLEAN NOT NULL DEFAULT FALSE,
  closing_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS godowns (
  godown_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  parent_godown_id BIGINT,
  address TEXT,
  city TEXT,
  state TEXT,
  pincode TEXT,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  is_main_location BOOLEAN NOT NULL DEFAULT FALSE,
  allow_storage_of_materials BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS groups (
  group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  parent_group_id BIGINT,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  nature TEXT,
  set_alter_tds_details BOOLEAN NOT NULL DEFAULT FALSE,
  set_alter_tcs_details BOOLEAN NOT NULL DEFAULT FALSE,
  set_alter_other_statutory_details BOOLEAN NOT NULL DEFAULT FALSE,
  hsn_sac_source TEXT,
  hsn_sac_description TEXT,
  gst_rate_source TEXT,
  taxability_type TEXT,
  behaves_like_subledger BOOLEAN NOT NULL DEFAULT FALSE,
  show_net_debit_credit BOOLEAN NOT NULL DEFAULT FALSE,
  used_for_calculation BOOLEAN NOT NULL DEFAULT FALSE,
  allocation_method TEXT NOT NULL DEFAULT 'Average Cost',
  gst_rate NUMERIC(18,4),
  cgst_rate NUMERIC(18,4),
  sgst_rate NUMERIC(18,4),
  igst_rate NUMERIC(18,4),
  hsn_sac_code TEXT,
  statutory_details TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  group_type TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gst_classifications (
  gc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  hsn_sac_code TEXT,
  is_non_gst_goods BOOLEAN NOT NULL DEFAULT FALSE,
  nature_of_transaction TEXT NOT NULL DEFAULT 'Not Applicable',
  taxability TEXT NOT NULL DEFAULT 'Unknown',
  is_reverse_charge BOOLEAN NOT NULL DEFAULT FALSE,
  is_ineligible_for_itc BOOLEAN NOT NULL DEFAULT FALSE,
  rate_type TEXT NOT NULL DEFAULT 'Fixed Rate',
  igst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  igst_valuation_type TEXT NOT NULL DEFAULT 'Based on Value',
  cgst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  cgst_valuation_type TEXT NOT NULL DEFAULT 'Based on Value',
  sgst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  sgst_valuation_type TEXT NOT NULL DEFAULT 'Based on Value',
  cess_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  cess_valuation_type TEXT NOT NULL DEFAULT 'Based on Value',
  gst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  gst_rate_details TEXT,
  valuation_type TEXT NOT NULL DEFAULT 'Based on Value',
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gst_hsn_rates (
  rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  hsn_code TEXT NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE,
  taxability TEXT NOT NULL DEFAULT 'Taxable',
  gst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  cgst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  sgst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  igst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  cess_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  type_of_supply TEXT NOT NULL DEFAULT 'Goods',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gst_registrations (
  gst_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  registration_type TEXT DEFAULT 'Regular',
  registration_status TEXT DEFAULT 'Active',
  assessee_of_other_territory BOOLEAN NOT NULL DEFAULT FALSE,
  periodicity_of_gstr1 TEXT DEFAULT 'Monthly',
  gstin TEXT,
  gst_username TEXT,
  mode_of_filing TEXT DEFAULT 'Online',
  e_invoice_details TEXT,
  e_invoice_application BOOLEAN NOT NULL DEFAULT FALSE,
  e_way_bill_applicable BOOLEAN NOT NULL DEFAULT FALSE,
  e_way_bill_applicable_from DATE,
  applicable_for_intrastat BOOLEAN NOT NULL DEFAULT FALSE,
  legal_name TEXT,
  trade_name TEXT,
  state_id TEXT,
  registration_date DATE,
  effective_from DATE,
  address_type TEXT DEFAULT 'Primary',
  goods_dispatched_from TEXT DEFAULT 'Primary',
  e_invoice_applicable_from DATE,
  e_invoice_bill_from_place TEXT,
  composition_tax_rate NUMERIC(18,4),
  composition_tax_calc_basis TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gst_voucher_tax_lines (
  tax_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  entry_id BIGINT,
  hsn_code TEXT,
  description TEXT,
  quantity NUMERIC(18,4) NOT NULL DEFAULT '0',
  unit TEXT,
  assessable_value NUMERIC(18,2) NOT NULL DEFAULT '0',
  tax_type TEXT,
  rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  amount NUMERIC(18,2) NOT NULL DEFAULT '0',
  is_inter_state BOOLEAN NOT NULL DEFAULT FALSE,
  party_gstin TEXT,
  party_state TEXT,
  gst_classification_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gstr1_exports (
  export_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  fy_id BIGINT NOT NULL,
  return_period TEXT NOT NULL,
  filed_date DATE,
  status TEXT NOT NULL DEFAULT 'Draft',
  b2b_json TEXT,
  b2cl_json TEXT,
  b2cs_json TEXT,
  cdnr_json TEXT,
  hsn_json TEXT,
  errors_json TEXT,
  full_payload_json TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ledger_bank_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  account_holder_name TEXT,
  account_number TEXT,
  ifsc_code TEXT,
  swift_code TEXT,
  bank_name TEXT,
  branch_name TEXT,
  bank_configuration TEXT,
  cheque_book_start_no TEXT,
  cheque_book_end_no TEXT,
  enable_cheque_printing BOOLEAN DEFAULT FALSE,
  cheque_printing_configuration TEXT,
  od_limit NUMERIC(18,2) DEFAULT '0',
  transaction_type TEXT,
  cross_using TEXT DEFAULT 'A/c Payee',
  company_bank TEXT
);

CREATE TABLE IF NOT EXISTS ledger_statutory_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  gst_applicability TEXT DEFAULT 'Not Applicable',
  hsn_sac_code TEXT,
  hsn_sac_description TEXT,
  gst_rate NUMERIC(18,4) DEFAULT '0',
  cgst_rate NUMERIC(18,4) DEFAULT '0',
  sgst_rate NUMERIC(18,4) DEFAULT '0',
  igst_rate NUMERIC(18,4) DEFAULT '0',
  type_of_duty_tax TEXT,
  percentage_of_calculation NUMERIC(18,4) DEFAULT '0',
  statutory_details TEXT,
  include_in_assessable_value_calculation TEXT DEFAULT 'Not Applicable',
  appropriate_to TEXT DEFAULT 'Goods',
  method_of_calculation TEXT DEFAULT 'Based on Quantity'
);

CREATE TABLE IF NOT EXISTS ledgers (
  ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  group_id BIGINT,
  name TEXT NOT NULL,
  alias TEXT,
  ledger_type TEXT DEFAULT 'General',
  nature TEXT,
  opening_balance NUMERIC(18,2) DEFAULT '0',
  closing_balance NUMERIC(18,2) DEFAULT '0',
  is_bill_wise BOOLEAN DEFAULT FALSE,
  maintain_inventory_values BOOLEAN DEFAULT FALSE,
  mailing_name TEXT,
  address1 TEXT,
  address2 TEXT,
  city TEXT,
  state TEXT,
  country TEXT,
  pincode TEXT,
  phone TEXT,
  email TEXT,
  gstin TEXT,
  pan TEXT,
  registration_type TEXT DEFAULT 'Unregistered',
  allow_cost_centres BOOLEAN DEFAULT FALSE,
  default_credit_period INTEGER DEFAULT 0,
  check_credit_days INTEGER DEFAULT 0,
  invoice_rounding BOOLEAN DEFAULT FALSE,
  rounding_method TEXT,
  rounding_limit NUMERIC(18,4) DEFAULT '0',
  additional_gst_details BOOLEAN DEFAULT FALSE,
  service_tax_details BOOLEAN DEFAULT FALSE,
  include_assessable_value TEXT DEFAULT 'Not Applicable',
  method_of_calculation TEXT DEFAULT 'Based on Value',
  other_statutory_details BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  is_predefined BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pay_head_formula_lines (
  formula_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pay_head_id BIGINT NOT NULL,
  sequence INTEGER DEFAULT 0,
  function TEXT,
  pay_head_id_ref BIGINT,
  operator TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pay_head_slab_lines (
  slab_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pay_head_id BIGINT NOT NULL,
  effective_from DATE,
  amount_gt NUMERIC(18,4) DEFAULT '0',
  amount_up_to NUMERIC(18,4) DEFAULT '0',
  slab_type TEXT,
  value NUMERIC(18,4) DEFAULT '0',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pay_heads (
  pay_head_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  pay_head_type TEXT DEFAULT 'Earnings for Employees',
  income_type TEXT DEFAULT 'Fixed',
  under_group TEXT,
  affects_net_salary BOOLEAN DEFAULT TRUE,
  payslip_display_name TEXT,
  use_for_gratuity BOOLEAN DEFAULT FALSE,
  set_alter_income_tax BOOLEAN DEFAULT FALSE,
  calculation_type TEXT DEFAULT 'As User Defined Value',
  calculation_period TEXT DEFAULT 'Months',
  rounding_method TEXT DEFAULT 'Not Applicable',
  rounding_limit NUMERIC(18,4) DEFAULT '0',
  statutory_component TEXT,
  percentage_or_amount NUMERIC(18,4) DEFAULT '0',
  is_active BOOLEAN DEFAULT TRUE,
  is_predefined BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payroll_units (
  payroll_unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  symbol TEXT,
  formal_name TEXT,
  unit_type TEXT NOT NULL DEFAULT 'Simple',
  decimal_places INTEGER NOT NULL DEFAULT 0,
  first_unit TEXT,
  conversion NUMERIC(18,4),
  second_unit TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS physical_stock_entries (
  physical_stock_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  voucher_no TEXT,
  voucher_date DATE NOT NULL,
  reference_no TEXT,
  narration TEXT,
  is_optional BOOLEAN NOT NULL DEFAULT FALSE,
  is_post_dated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS physical_stock_entry_lines (
  line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  physical_stock_entry_id BIGINT NOT NULL,
  stock_item_id BIGINT,
  godown_id BIGINT,
  batch_no TEXT,
  lot_no TEXT,
  manufacturing_date DATE,
  expiry_date DATE,
  quantity NUMERIC(18,4) NOT NULL DEFAULT '0',
  rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  amount NUMERIC(18,2) NOT NULL DEFAULT '0',
  line_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS price_levels (
  price_level_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  level_index INTEGER NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS price_list_lines (
  line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price_list_id BIGINT NOT NULL,
  item_id BIGINT,
  particulars TEXT NOT NULL,
  qty_from NUMERIC(18,4) NOT NULL DEFAULT '0',
  qty_less_than NUMERIC(18,4) NOT NULL DEFAULT '0',
  rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  disc_percent NUMERIC(18,4) NOT NULL DEFAULT '0',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS price_lists (
  price_list_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  stock_group TEXT NOT NULL DEFAULT 'All Items',
  price_level TEXT NOT NULL,
  applicable_from DATE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS profit_loss_reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  report_name TEXT DEFAULT 'Profit & Loss A/c',
  report_date DATE,
  period_start DATE,
  period_end DATE,
  format_type TEXT DEFAULT 'Vertical',
  compare_with_previous_period BOOLEAN NOT NULL DEFAULT FALSE,
  comparison_period_start DATE,
  comparison_period_end DATE,
  basis_of_values TEXT DEFAULT 'Default',
  change_view TEXT,
  exception_report_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  saved_view_name TEXT,
  filter_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  filter_details TEXT,
  show_detail_view BOOLEAN NOT NULL DEFAULT FALSE,
  show_condensed_view BOOLEAN NOT NULL DEFAULT FALSE,
  show_percentage_of_sales BOOLEAN NOT NULL DEFAULT FALSE,
  show_auto_column BOOLEAN NOT NULL DEFAULT FALSE,
  show_profit BOOLEAN NOT NULL DEFAULT TRUE,
  show_optional BOOLEAN NOT NULL DEFAULT FALSE,
  show_post_dated BOOLEAN NOT NULL DEFAULT FALSE,
  show_stat_adjustment BOOLEAN NOT NULL DEFAULT FALSE,
  show_schedule_vi BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS profit_loss_views (
  view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  company_id BIGINT NOT NULL,
  report_date DATE,
  section TEXT DEFAULT 'Income',
  group_name TEXT,
  parent_group_name TEXT,
  opening_balance NUMERIC(18,2) NOT NULL DEFAULT '0',
  current_period_amount NUMERIC(18,2) NOT NULL DEFAULT '0',
  closing_balance NUMERIC(18,2) NOT NULL DEFAULT '0',
  display_order INTEGER NOT NULL DEFAULT 0,
  is_total_row BOOLEAN NOT NULL DEFAULT FALSE,
  is_gross_profit_row BOOLEAN NOT NULL DEFAULT FALSE,
  is_drill_down_available BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reconciliations (
  reconciliation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id BIGINT NOT NULL,
  voucher_id BIGINT NOT NULL,
  ledger_id BIGINT NOT NULL,
  reconciled_date DATE,
  bank_date DATE,
  bank_reference TEXT,
  reconciled_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS salary_structures (
  structure_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  employee_id BIGINT NOT NULL,
  effective_from DATE NOT NULL,
  pay_head_id BIGINT NOT NULL,
  amount NUMERIC(18,2) NOT NULL DEFAULT '0',
  calculation_mode TEXT NOT NULL DEFAULT 'Flat Rate',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stock_categories (
  sc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  description TEXT,
  parent_category_id BIGINT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stock_groups (
  sg_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  parent_group_id BIGINT,
  should_quantities_be_added BOOLEAN NOT NULL DEFAULT FALSE,
  hsn_sac_code TEXT,
  hsn_sac_description TEXT,
  gst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  cgst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  sgst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  taxability_type TEXT,
  statutory_details TEXT,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stock_item_opening_allocations (
  allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL,
  godown_id BIGINT,
  batch_number TEXT,
  mfg_date DATE,
  expiry_date DATE,
  quantity NUMERIC(18,4) NOT NULL DEFAULT '0',
  rate NUMERIC(18,2) NOT NULL DEFAULT '0',
  amount NUMERIC(18,2) NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS stock_items (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  group_id BIGINT,
  category_id BIGINT,
  unit_id BIGINT,
  gst_applicable TEXT NOT NULL DEFAULT 'Not Applicable',
  hsn_sac TEXT,
  source_of_details TEXT NOT NULL DEFAULT 'As per Company/Stock Group',
  hsn_sac_description TEXT,
  hsn_code TEXT,
  sac_code TEXT,
  gst_rate_details TEXT,
  source_of_gst_rate TEXT NOT NULL DEFAULT 'As per Company/Stock Group',
  taxability_type TEXT,
  gst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  cgst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  sgst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  igst_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  type_of_supply TEXT NOT NULL DEFAULT 'Goods',
  rate_of_duty NUMERIC(18,4) NOT NULL DEFAULT '0',
  statutory_details TEXT,
  opening_quantity NUMERIC(18,4) NOT NULL DEFAULT '0',
  opening_rate NUMERIC(18,2) NOT NULL DEFAULT '0',
  opening_value NUMERIC(18,2) NOT NULL DEFAULT '0',
  reorder_level NUMERIC(18,4) NOT NULL DEFAULT '0',
  reorder_quantity NUMERIC(18,4) NOT NULL DEFAULT '0',
  track_batches BOOLEAN NOT NULL DEFAULT FALSE,
  track_expiry BOOLEAN NOT NULL DEFAULT FALSE,
  track_date_of_manufacturing BOOLEAN NOT NULL DEFAULT FALSE,
  enable_cost_tracking BOOLEAN NOT NULL DEFAULT FALSE,
  has_bom BOOLEAN NOT NULL DEFAULT FALSE,
  bom_name TEXT,
  excise_applicable TEXT NOT NULL DEFAULT 'Not Applicable',
  excise_details TEXT,
  excise_tariff_name TEXT,
  excise_tariff_hsn_code TEXT,
  excise_tariff_uom TEXT NOT NULL DEFAULT 'Undefined',
  excise_tariff_valuation_type TEXT NOT NULL DEFAULT 'Undefined',
  excise_tariff_rate NUMERIC(18,4) NOT NULL DEFAULT '0',
  excise_tariff_rate_per_unit NUMERIC(18,2) NOT NULL DEFAULT '0',
  vat_applicable TEXT NOT NULL DEFAULT 'Applicable',
  vat_details TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tally_features (
  tally_feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  maintain_accounts BOOLEAN NOT NULL DEFAULT TRUE,
  enable_bill_wise_entry BOOLEAN NOT NULL DEFAULT FALSE,
  enable_cost_centres BOOLEAN NOT NULL DEFAULT FALSE,
  maintain_inventory BOOLEAN NOT NULL DEFAULT TRUE,
  integrate_accounts_with_inventory BOOLEAN NOT NULL DEFAULT TRUE,
  enable_multiple_price_levels BOOLEAN NOT NULL DEFAULT FALSE,
  enable_batches BOOLEAN NOT NULL DEFAULT FALSE,
  maintain_expiry_date_for_batches BOOLEAN NOT NULL DEFAULT FALSE,
  use_discount_column_in_invoices BOOLEAN NOT NULL DEFAULT FALSE,
  use_separate_actual_billed_qty BOOLEAN NOT NULL DEFAULT FALSE,
  enable_gst BOOLEAN NOT NULL DEFAULT FALSE,
  set_alter_company_gst_details BOOLEAN NOT NULL DEFAULT FALSE,
  enable_tds BOOLEAN NOT NULL DEFAULT FALSE,
  enable_tcs BOOLEAN NOT NULL DEFAULT FALSE,
  enable_browser_access_for_reports BOOLEAN NOT NULL DEFAULT FALSE,
  enable_tally_net_services BOOLEAN NOT NULL DEFAULT FALSE,
  enable_payment_request_qr BOOLEAN NOT NULL DEFAULT FALSE,
  enable_multiple_addresses BOOLEAN NOT NULL DEFAULT FALSE,
  mark_modified_vouchers BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tax_units (
  tax_unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  alias TEXT,
  address_line1 TEXT,
  address_line2 TEXT,
  address_line3 TEXT,
  address_line4 TEXT,
  state TEXT,
  pincode TEXT,
  telephone TEXT,
  registered_for TEXT NOT NULL DEFAULT 'Excise',
  set_alter_excise_details BOOLEAN NOT NULL DEFAULT FALSE,
  registration_type TEXT NOT NULL DEFAULT 'Importer',
  ecc_number TEXT,
  set_alter_excise_tariff BOOLEAN NOT NULL DEFAULT FALSE,
  set_alter_rule11_book BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tcs_nature_of_goods (
  tcs_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  section TEXT,
  payment_code TEXT,
  rate_individual_with_pan NUMERIC(18,4) NOT NULL DEFAULT '0',
  rate_individual_without_pan NUMERIC(18,4) NOT NULL DEFAULT '0',
  rate_other_with_pan NUMERIC(18,4) NOT NULL DEFAULT '0',
  rate_other_without_pan NUMERIC(18,4) NOT NULL DEFAULT '0',
  is_own_status BOOLEAN NOT NULL DEFAULT FALSE,
  tax_on_receipt_or_realization TEXT NOT NULL DEFAULT 'Tax Calculated on Receipt',
  threshold_level NUMERIC(18,2) NOT NULL DEFAULT '0',
  is_zero_rated BOOLEAN NOT NULL DEFAULT FALSE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tds_nature_of_payment (
  tds_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  section TEXT,
  payment_code TEXT,
  remittance_code TEXT,
  rate_individual_with_pan NUMERIC(18,4) NOT NULL DEFAULT '0',
  rate_other_with_pan NUMERIC(18,4) NOT NULL DEFAULT '0',
  is_zero_rated BOOLEAN NOT NULL DEFAULT FALSE,
  threshold_limit NUMERIC(18,2) NOT NULL DEFAULT '0',
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trial_balance_reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  company_name TEXT,
  report_date DATE,
  period_start DATE,
  period_end DATE,
  show_closing_balance BOOLEAN NOT NULL DEFAULT TRUE,
  show_debit_credit BOOLEAN NOT NULL DEFAULT TRUE,
  show_groups BOOLEAN NOT NULL DEFAULT TRUE,
  show_grand_total BOOLEAN NOT NULL DEFAULT TRUE,
  detailed_mode BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trial_balance_rows (
  row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  parent_row_id BIGINT,
  row_type TEXT NOT NULL DEFAULT 'Ledger',
  particulars TEXT,
  group_id BIGINT,
  ledger_id BIGINT,
  display_order INTEGER NOT NULL DEFAULT 0,
  opening_debit NUMERIC(18,2) NOT NULL DEFAULT '0',
  opening_credit NUMERIC(18,2) NOT NULL DEFAULT '0',
  period_debit NUMERIC(18,2) NOT NULL DEFAULT '0',
  period_credit NUMERIC(18,2) NOT NULL DEFAULT '0',
  closing_debit NUMERIC(18,2) NOT NULL DEFAULT '0',
  closing_credit NUMERIC(18,2) NOT NULL DEFAULT '0',
  is_drillable BOOLEAN NOT NULL DEFAULT TRUE,
  is_grand_total BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS units (
  unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  symbol TEXT NOT NULL,
  formal_name TEXT,
  decimal_places INTEGER NOT NULL DEFAULT 0,
  unit_quantity_code TEXT,
  unit_type TEXT NOT NULL DEFAULT 'Simple',
  is_simple BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  first_unit_id BIGINT,
  second_unit_id BIGINT,
  conversion_factor NUMERIC(18,4) DEFAULT '1',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS voucher_bank_details (
  bank_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  ledger_id BIGINT,
  transaction_type TEXT DEFAULT 'Cheque',
  cheque_range TEXT,
  instrument_number TEXT,
  instrument_date DATE,
  bank_name TEXT,
  branch TEXT,
  amount NUMERIC(18,2) DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS voucher_batches (
  batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  stock_entry_id BIGINT NOT NULL,
  batch_number TEXT,
  expiry_date DATE,
  quantity NUMERIC(18,4) DEFAULT '0',
  rate NUMERIC(18,4) DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS voucher_bill_references (
  bill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  ledger_id BIGINT,
  bill_name TEXT,
  bill_type TEXT,
  amount NUMERIC(18,2) DEFAULT '0',
  credit_period TEXT,
  due_date DATE
);

CREATE TABLE IF NOT EXISTS voucher_cash_denominations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  ledger_id BIGINT,
  denomination TEXT,
  quantity INTEGER DEFAULT 0,
  amount NUMERIC(18,2) DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS voucher_cost_centres (
  cc_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  entry_id BIGINT,
  cost_centre_id BIGINT,
  amount NUMERIC(18,2) DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS voucher_credit_note_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  tracking_no TEXT,
  dispatch_doc_no TEXT,
  dispatched_through TEXT,
  destination TEXT,
  carrier_name TEXT,
  bill_of_lading_no TEXT,
  bill_of_lading_date DATE,
  motor_vehicle_no TEXT,
  original_invoice_no TEXT,
  original_invoice_date DATE
);

CREATE TABLE IF NOT EXISTS voucher_debit_note_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  tracking_no TEXT,
  dispatch_doc_no TEXT,
  dispatched_through TEXT,
  destination TEXT,
  carrier_name TEXT,
  bill_of_lading_no TEXT,
  bill_of_lading_date DATE,
  motor_vehicle_no TEXT,
  original_invoice_no TEXT,
  original_invoice_date DATE
);

CREATE TABLE IF NOT EXISTS voucher_dispatch_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  delivery_note_nos TEXT,
  dispatch_doc_no TEXT,
  dispatched_through TEXT,
  destination TEXT,
  carrier_name TEXT,
  bill_of_lading_no TEXT,
  bill_of_lading_date DATE,
  motor_vehicle_no TEXT
);

CREATE TABLE IF NOT EXISTS voucher_entries (
  entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  ledger_id BIGINT,
  ledger_name TEXT,
  type TEXT NOT NULL,
  amount NUMERIC(18,2) DEFAULT '0',
  amount_forex NUMERIC(18,2) DEFAULT '0',
  currency TEXT DEFAULT 'INR',
  narration TEXT
);

CREATE TABLE IF NOT EXISTS voucher_entry_actions (
  action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  voucher_id BIGINT,
  action_type TEXT NOT NULL,
  action_data JSONB,
  autofill_ledger_id BIGINT,
  autofill_amount NUMERIC(18,2),
  autofill_narration TEXT,
  previous_mode TEXT,
  new_mode TEXT,
  additional_details JSONB,
  related_report_type TEXT,
  related_report_id BIGINT,
  is_optional BOOLEAN NOT NULL DEFAULT FALSE,
  optional_reason TEXT,
  performed_by TEXT,
  performed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS voucher_party_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  supplier_name TEXT,
  mailing_name TEXT,
  address TEXT,
  state TEXT,
  country TEXT
);

CREATE TABLE IF NOT EXISTS voucher_payroll_entries (
  payroll_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  employee_id BIGINT,
  pay_head_id BIGINT,
  amount NUMERIC(18,2) DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS voucher_receipt_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  receipt_note_no TEXT,
  receipt_doc_no TEXT,
  dispatched_through TEXT,
  destination TEXT,
  carrier_name TEXT,
  bill_of_lading_no TEXT,
  bill_of_lading_date DATE,
  motor_vehicle_no TEXT
);

CREATE TABLE IF NOT EXISTS voucher_stock_entries (
  stock_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  stock_item_id BIGINT,
  item_name TEXT,
  godown_id BIGINT,
  unit_id BIGINT,
  quantity NUMERIC(18,4) DEFAULT '0',
  rate NUMERIC(18,4) DEFAULT '0',
  amount NUMERIC(18,2) DEFAULT '0',
  additional_amount NUMERIC(18,2) DEFAULT '0',
  discount_amount NUMERIC(18,2) DEFAULT '0',
  hsn_code TEXT,
  gst_rate NUMERIC(18,4) DEFAULT '0',
  cgst_amount NUMERIC(18,2) DEFAULT '0',
  sgst_amount NUMERIC(18,2) DEFAULT '0',
  igst_amount NUMERIC(18,2) DEFAULT '0',
  is_source BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS voucher_type_configs (
  config_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_type_id BIGINT NOT NULL,
  use_effective_dates BOOLEAN NOT NULL DEFAULT FALSE,
  allow_zero_value_transactions BOOLEAN NOT NULL DEFAULT FALSE,
  make_voucher_optional BOOLEAN NOT NULL DEFAULT FALSE,
  allow_narration BOOLEAN NOT NULL DEFAULT TRUE,
  allow_narration_per_ledger BOOLEAN NOT NULL DEFAULT FALSE,
  print_after_save BOOLEAN NOT NULL DEFAULT FALSE,
  whatsapp_after_save BOOLEAN NOT NULL DEFAULT FALSE,
  enable_default_accounting_allocation BOOLEAN NOT NULL DEFAULT FALSE,
  track_additional_cost_for_purchase BOOLEAN NOT NULL DEFAULT FALSE,
  default_title_to_print TEXT,
  use_for_pos_invoicing BOOLEAN NOT NULL DEFAULT FALSE,
  default_bank_id BIGINT,
  declaration TEXT,
  set_alter_declaration BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS voucher_types (
  vt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  short_name TEXT,
  category TEXT,
  default_voucher_class TEXT,
  affects_inventory BOOLEAN NOT NULL DEFAULT FALSE,
  affects_accounting BOOLEAN NOT NULL DEFAULT TRUE,
  affects_gst BOOLEAN NOT NULL DEFAULT FALSE,
  numbering_method TEXT NOT NULL DEFAULT 'Automatic',
  numbering_prefix TEXT NOT NULL DEFAULT '',
  numbering_suffix TEXT NOT NULL DEFAULT '',
  starts_with INTEGER NOT NULL DEFAULT 1,
  is_predefined BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  parent_vt_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vouchers (
  voucher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  fy_id BIGINT NOT NULL,
  voucher_type TEXT NOT NULL,
  voucher_number TEXT,
  date DATE NOT NULL,
  status TEXT DEFAULT 'Regular',
  supplier_invoice_no TEXT,
  supplier_invoice_date DATE,
  reference_number TEXT,
  reference_date DATE,
  narration TEXT,
  party_ledger_id BIGINT,
  party_name TEXT,
  place_of_supply TEXT,
  is_invoice BOOLEAN DEFAULT FALSE,
  is_accounting_voucher BOOLEAN DEFAULT TRUE,
  is_inventory_voucher BOOLEAN DEFAULT FALSE,
  is_order_voucher BOOLEAN DEFAULT FALSE,
  is_cancelled BOOLEAN DEFAULT FALSE,
  is_optional BOOLEAN DEFAULT FALSE,
  is_post_dated BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS whatsapp_config (
  config_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  phone_number_id TEXT NOT NULL,
  waba_id TEXT NOT NULL,
  access_token TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS whatsapp_logs (
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  voucher_id BIGINT,
  to_number TEXT NOT NULL,
  message_type TEXT NOT NULL,
  template_name TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING',
  wamid TEXT,
  error TEXT,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS whatsapp_templates (
  template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'en',
  category TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ############################################################################
-- SECTION 2 :: FOREIGN KEYS
-- ############################################################################

ALTER TABLE attendance_voucher_entries ADD CONSTRAINT fk_attendance_voucher_entries_attendance_voucher_id FOREIGN KEY (attendance_voucher_id) REFERENCES attendance_vouchers (attendance_voucher_id) ON DELETE CASCADE;
ALTER TABLE balance_sheet_views ADD CONSTRAINT fk_balance_sheet_views_report_id FOREIGN KEY (report_id) REFERENCES balance_sheet_reports (report_id) ON DELETE CASCADE;
ALTER TABLE company_creation_success ADD CONSTRAINT fk_company_creation_success_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE company_gst_details ADD CONSTRAINT fk_company_gst_details_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE company_pan_cin_details ADD CONSTRAINT fk_company_pan_cin_details_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE company_tcs_details ADD CONSTRAINT fk_company_tcs_details_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE company_tds_details ADD CONSTRAINT fk_company_tds_details_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE cost_centres ADD CONSTRAINT fk_cost_centres_parent_id FOREIGN KEY (parent_id) REFERENCES cost_centres (cc_id);
ALTER TABLE day_book_entries ADD CONSTRAINT fk_day_book_entries_report_id FOREIGN KEY (report_id) REFERENCES day_book_reports (report_id) ON DELETE CASCADE;
ALTER TABLE day_book_entry_lines ADD CONSTRAINT fk_day_book_entry_lines_entry_id FOREIGN KEY (entry_id) REFERENCES day_book_entries (entry_id) ON DELETE CASCADE;
ALTER TABLE employee_groups ADD CONSTRAINT fk_employee_groups_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE employee_groups ADD CONSTRAINT fk_employee_groups_employee_category_id FOREIGN KEY (employee_category_id) REFERENCES employee_categories (employee_category_id);
ALTER TABLE employee_groups ADD CONSTRAINT fk_employee_groups_parent_group_id FOREIGN KEY (parent_group_id) REFERENCES employee_groups (employee_group_id);
ALTER TABLE feature_items ADD CONSTRAINT fk_feature_items_feature_group_id FOREIGN KEY (feature_group_id) REFERENCES feature_groups (feature_group_id) ON DELETE CASCADE;
ALTER TABLE godowns ADD CONSTRAINT fk_godowns_parent_godown_id FOREIGN KEY (parent_godown_id) REFERENCES godowns (godown_id);
ALTER TABLE groups ADD CONSTRAINT fk_groups_parent_group_id FOREIGN KEY (parent_group_id) REFERENCES groups (group_id);
ALTER TABLE gst_classifications ADD CONSTRAINT fk_gst_classifications_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE gst_registrations ADD CONSTRAINT fk_gst_registrations_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE ledger_bank_details ADD CONSTRAINT fk_ledger_bank_details_ledger_id FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id) ON DELETE CASCADE;
ALTER TABLE ledger_statutory_details ADD CONSTRAINT fk_ledger_statutory_details_ledger_id FOREIGN KEY (ledger_id) REFERENCES ledgers (ledger_id) ON DELETE CASCADE;
ALTER TABLE pay_head_formula_lines ADD CONSTRAINT fk_pay_head_formula_lines_pay_head_id FOREIGN KEY (pay_head_id) REFERENCES pay_heads (pay_head_id) ON DELETE CASCADE;
ALTER TABLE pay_head_formula_lines ADD CONSTRAINT fk_pay_head_formula_lines_pay_head_id_ref FOREIGN KEY (pay_head_id_ref) REFERENCES pay_heads (pay_head_id) ON DELETE SET NULL;
ALTER TABLE pay_head_slab_lines ADD CONSTRAINT fk_pay_head_slab_lines_pay_head_id FOREIGN KEY (pay_head_id) REFERENCES pay_heads (pay_head_id) ON DELETE CASCADE;
ALTER TABLE physical_stock_entry_lines ADD CONSTRAINT fk_physical_stock_entry_lines_physical_stock_entry_id FOREIGN KEY (physical_stock_entry_id) REFERENCES physical_stock_entries (physical_stock_entry_id) ON DELETE CASCADE;
ALTER TABLE price_levels ADD CONSTRAINT fk_price_levels_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE price_list_lines ADD CONSTRAINT fk_price_list_lines_price_list_id FOREIGN KEY (price_list_id) REFERENCES price_lists (price_list_id) ON DELETE CASCADE;
ALTER TABLE profit_loss_views ADD CONSTRAINT fk_profit_loss_views_report_id FOREIGN KEY (report_id) REFERENCES profit_loss_reports (report_id) ON DELETE CASCADE;
ALTER TABLE stock_categories ADD CONSTRAINT fk_stock_categories_parent_category_id FOREIGN KEY (parent_category_id) REFERENCES stock_categories (sc_id);
ALTER TABLE stock_groups ADD CONSTRAINT fk_stock_groups_parent_group_id FOREIGN KEY (parent_group_id) REFERENCES stock_groups (sg_id);
ALTER TABLE stock_item_opening_allocations ADD CONSTRAINT fk_stock_item_opening_allocations_item_id FOREIGN KEY (item_id) REFERENCES stock_items (item_id) ON DELETE CASCADE;
ALTER TABLE tally_features ADD CONSTRAINT fk_tally_features_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE tax_units ADD CONSTRAINT fk_tax_units_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE tcs_nature_of_goods ADD CONSTRAINT fk_tcs_nature_of_goods_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE tds_nature_of_payment ADD CONSTRAINT fk_tds_nature_of_payment_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE trial_balance_rows ADD CONSTRAINT fk_trial_balance_rows_report_id FOREIGN KEY (report_id) REFERENCES trial_balance_reports (report_id) ON DELETE CASCADE;
ALTER TABLE units ADD CONSTRAINT fk_units_first_unit_id FOREIGN KEY (first_unit_id) REFERENCES units (unit_id);
ALTER TABLE units ADD CONSTRAINT fk_units_second_unit_id FOREIGN KEY (second_unit_id) REFERENCES units (unit_id);
ALTER TABLE voucher_bank_details ADD CONSTRAINT fk_voucher_bank_details_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_batches ADD CONSTRAINT fk_voucher_batches_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_batches ADD CONSTRAINT fk_voucher_batches_stock_entry_id FOREIGN KEY (stock_entry_id) REFERENCES voucher_stock_entries (stock_entry_id) ON DELETE CASCADE;
ALTER TABLE voucher_bill_references ADD CONSTRAINT fk_voucher_bill_references_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_cash_denominations ADD CONSTRAINT fk_voucher_cash_denominations_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_cost_centres ADD CONSTRAINT fk_voucher_cost_centres_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_cost_centres ADD CONSTRAINT fk_voucher_cost_centres_entry_id FOREIGN KEY (entry_id) REFERENCES voucher_entries (entry_id);
ALTER TABLE voucher_credit_note_details ADD CONSTRAINT fk_voucher_credit_note_details_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_debit_note_details ADD CONSTRAINT fk_voucher_debit_note_details_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_dispatch_details ADD CONSTRAINT fk_voucher_dispatch_details_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_entries ADD CONSTRAINT fk_voucher_entries_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_party_details ADD CONSTRAINT fk_voucher_party_details_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_payroll_entries ADD CONSTRAINT fk_voucher_payroll_entries_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_receipt_details ADD CONSTRAINT fk_voucher_receipt_details_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_stock_entries ADD CONSTRAINT fk_voucher_stock_entries_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE;
ALTER TABLE voucher_type_configs ADD CONSTRAINT fk_voucher_type_configs_voucher_type_id FOREIGN KEY (voucher_type_id) REFERENCES voucher_types (vt_id);
ALTER TABLE voucher_types ADD CONSTRAINT fk_voucher_types_parent_vt_id FOREIGN KEY (parent_vt_id) REFERENCES voucher_types (vt_id);
ALTER TABLE whatsapp_config ADD CONSTRAINT fk_whatsapp_config_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE whatsapp_logs ADD CONSTRAINT fk_whatsapp_logs_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;
ALTER TABLE whatsapp_templates ADD CONSTRAINT fk_whatsapp_templates_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE;

